### ISSUE TITLE
`Argument list too long` errors when running 4.0.0-rc.2 on ios

### ISSUE THREAD

**Issue by scottarivale** [invertase/react-native-firebase#917] opened 2018-03-28 00:21 UTC
### Issue
Builds fails with the following error:
```
Argument list too long: recursive header expansion failed at /project/path/to/node_modules/react-native-firebase/ios/../../../ios/Pods/React/node_modules/fsevents/node_modules/process-nextick-args.
```
I've followed the setup steps for 4.0.0-rc.2, and deleted/reinstalled the pods and node_modules folders, as well as unlinking and relinking 'react-native-firebase', all to no avail.
### Environment

iOS, both when building it in XCode (v9.2) and using `react-native run-ios`

1. Application Target Platform:

iOS 9+

2. Development Operating System:

Xcode 9.2, macOS High Sierra 10.13.3

3. Build Tools:

4. React Native version:

0.54.2

5. RNFirebase Version:

4.0.0-rc.2

**Comment by chrisbianca** [comment] 2018-03-28 14:19
@scottarivale Can I see your podfile?

**Comment by scottarivale** [comment] 2018-03-28 17:12
@chrisbianca sure!

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coachconnect' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  pod 'Mixpanel'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'


  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  target 'coachconnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'coachconnect-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coachconnect-tvOS

  target 'coachconnect-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by superguineapig** [comment] 2018-03-29 04:49
Hello,

I ran into the same issue today. Same exact Environment specs as @scottarivale But with a much simpler Podfile.

Had been building fine for several days with only

`pod 'Firebase/Core'`
`pod 'Firebase/Auth'`

in my Podfile

The issue presented itself  immediately after including

`pod 'Firebase/Firestore'`

ran the usual pod install to pull the deps and tried to run a clean and a build in XCode. Failed with the 

> "Argument list too long..." error.

From what I can tell so far, it looks like there is a conflict between the `Firebase/Firestore` pod's `React`  dependency, (as it pulls in its own `node_modules`), and the `node_modules` pulled from the *react-native cli* (npm/yarn)

Experimentally, removing the `Pods/React/` dir entirely, gets rid of the errors we're seeing (although leads to new errors when building the Firestore native code, which is expected)

**Current Hypothesis**
Perhaps it isn't an actual conflict between the two 'node_modules' dirs, but something in the XCode settings like a *build path, or a relative path, or path symbol* being unintentionally overwritten/overloaded as a result of the pod install process when installing a rnfb pod that has React as a dep.

I am really not that familiar with all the XCode settings, or cocoapods for that matter, but based on the errors, it seems like a place to start.

Especially since the Android install of 'Firebase/Firestore', on the same react-native project had no issues, and compiles/builds/simulates just fine; only the ios/XCode stuff is having a problem (which makes me think it's not actually the node_modules themselves)

Hope this will help others who are more familiar with how this works under-the-hood to find a solution.

I'll keep digging myself, but I sure could use some other eyes on the issue.

**Comment by chrisbianca** [comment] 2018-03-29 10:38
@scottarivale @superguineapig If either of you are able to push a copy of the project that exhibits this issue, it would really help me try and track down what's going on?

Unfortunately, without a reproducible example, it's very difficult to figure out which header might be causing the issue.

**Comment by superguineapig** [comment] 2018-03-29 19:29
@chrisbianca take a look at this repo (https://github.com/superguineapig/rnfb-test-project)

I created 4 branches, each adding something along the way.

the readme has all the details, but in short, the order was:

1. *master* - new react-native project
2. *rnfb-core* - add the react native firebase core pod
3. *rnfb-firestore* - add the firestore pod
4. *rn-vector-icons* - add another dep that modifies the Podfile

1 through 3 all build just fine.

number 4 is where the fun begins. This build fails. Although I chose the react-native-vector-icons package because it was common between my production Podfile and @scottarivale 's, I'm not convinced that it is the problem by itself. A project without react-native-firebase and only the react-native-vector-icons builds fine.

I suspect the issue has something to do with having certain react-native-firebase pods specified (in my case it was after adding the Firestore pod) along with any other pods that use this pattern:

`pod 'FOOBAR', :path => '../node_modules/foo-bar'`

Specifically the 'path' part with a relative 'node_modules' dir.

Once the 'React' pod is added via pod install/update, things go south.

Hope this helps.

**Comment by chrisbianca** [comment] 2018-03-30 14:54
@superguineapig I've just checked out your repo and using the `rn-vector-icons` branch I encountered the following error:

```
react-native-vector-icons/RNVectorIconsManager/RNVectorIconsManager.m:95:37: error: too many arguments to block call, expected 1, have 3
        reject(@"font_load_failed", @"Font failed to load", error);
        ~~~~~~                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This error is caused by the fact that because RNVectorIcons has `React` as a Pod dependency, by default it resolves the React Native v11 pod (the last version that RN published to Cocoapods...).

I resolved this by adding the following to the Podfile:

```
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'RCTNetwork'
  ]
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
```

This cleared the error and allowed the app to start.  Interestingly, at no point am I seeing the `"Argument list too long..."` error which is annoying and a little confusing.

This implies that there must be something different about the build environment.

What version of cocoapods are you using? You can run `pod --version` to find out...

**Comment by superguineapig** [comment] 2018-03-30 16:48
@chrisbianca hmm, interesting.

here's some additional env info:
* cocoapods 1.3.1
* react-native cli 2.0.1
* react 16.3.0-rc.0 (default installed by react-native init)
* react-native-firebase 3.3.1 (default)
* yarn 1.5.1
* node 8.10.0 (via NVM)
* nvm 0.33.6

side note: I was also able to get the argument list error with other libs, not just the RNVectorIcons

**Comment by chrisbianca** [comment] 2018-03-30 20:37
Could you try updating your cocoa pods to v1.4.0? That’s the only thing that’s standing out as being significantly different from my setup.

**Comment by superguineapig** [comment] 2018-03-31 00:13
### short version
cocoapods update didn't have any effect.

In addition, the Podfile modifications listed in [this comment](https://github.com/invertase/react-native-firebase/issues/917#issuecomment-377541455) do not remove the argument list errors on my machine.

For reference, that pesky *'argument list...'* error is present in the Xcode IDE only, not on cli builds; at least in my case. (product->clean will also produce this) Still present after starting from scratch with cocoapods 1.4.0:
```
Argument list too long: recursive header expansion failed at /Users/superguineapig/rnative/RNFBTestProject/node_modules/react-native-firebase/ios/../../../ios/Pods/React/node_modules/uglify-js/node_modules/optimist/test/_.
```
### more thoughts
I appreciate you looking into this @chrisbianca 

I'm pretty convinced that what we're seeing is not related to RNFB directly, but the react-native ecosystem/tools + cocoapods.

At this point I've run several tests locally, and it all points to **the order** in which the following tools are used during the course of a development project: 

* `react-native link`
* `pod install` or `pod update`
* pods which have 'React' as a dep in their podspec

See this [comment](https://github.com/invertase/react-native-firebase/issues/917#issuecomment-377381343) for more on that theory.

Although I'm still wary of the differences in dev environment playing a role in this somehow.

Luckily, I've had success manually linking stuff (like vector icons) to my Xcode workspace *without* the use of 'react-native link' and its additions to the Podfile. (with all of the RNFB stuff in the Podfile behaving just fine, btw.)
### going forward
My go-forward strategy is to avoid `react-native link` as it makes unknown changes to the Podfile and  native project workspaces. Several of the *'react-native-foo'* javascript packages with native libs seem to have manual/non-cocoapods install instructions. (for both iOS and Android)

Again, thanks @chrisbianca for taking time to look at this. If you happen across any additional insights or discoveries, I'd be glad to hear them.

@scottarivale Any of this stuff work for you? Did you ever find a solution on your end?

**Comment by chrisbianca** [comment] 2018-03-31 16:19
@superguineapig Thank you for your continued input on this - I'm determined to get this reproduced locally, but you're right in your analysis that the ordering and combination of Pods and `react-native link` does play havoc in react native.

For reference, the root cause for these issues comes down to this PR: https://github.com/facebook/react-native/pull/15460

As you can see from the history, I objected at the time as it broke our library when the change made it through to the next RN release.  As a result of the PR, our Podspec was picked up and used by default rather than just linking the library as had happened prior to that RN release.  The PR provided no way to opt out of or customise this behaviour.  Instead we had to move our Podspec out of the main directory to ensure it wasn't picked up automatically as part of `react-native link`.

Unfortunately, this hasn't necessarily been picked up by other libraries, so now, libraries that previously had a Podspec as an optional method of installation are having this installed by default.

This wouldn't (and doesn't) cause an issue if React is set up to be installed as a Pod and is also removed from being linked within XCode.  However, this isn't the default set up for a new React Native project, and is fraught with other issues and difficult to explain.

Ultimately:

1) The RN ecosystem is incredibly fragmented in how libraries can be setup and installed
2) There is very little consideration paid to library maintainers (outside of Expo) and the challenges they face as a result of this
3) Changes like the PR linked are made and then issues that come out of the back of it are ignored
4) We as library maintainers have to face an uphill battle to try and keep up / fix the resultant issues

Sorry, this has turned into a bit of a rant (it's been one of those days!!) which wasn't the plan.  As stated above, we will get this issue reproduced and get it resolved somehow, it just might be a bit of a slog :D  Thank you again for all your help!

**Comment by chrisbianca** [comment] 2018-04-03 14:48
@superguineapig would you be able to try the following version and see if it fixes the issues you're seeing?

`npm install --save https://github.com/invertase/react-native-firebase#framework-headers`

**Comment by superguineapig** [comment] 2018-04-03 19:03
@chrisbianca installing the new version has removed the *argument list...* error!

### more details
After updating the *react-native-firebase* libs, building off of the 'rn-vector-icons' test branch will choke on the RNVectorIcons build, instead of the 'Argument list' thing.

Adding
```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'RCTNetwork'
]
pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
```
to the Podfile will clear **ALL Xcode** build errors.

However, the Metro Bundler will puke with **dozens** of `Duplicate module name: foo` errors, preventing a successful bundle and app launch.

So, it looks like the RNFB change clears up its own conflicts with the duplicate **'React'** dependency pulled in by cocoapods, but the `react-native` tools can't cope with having `.../ios/Pods/React/...` hanging around.

**Comment by chrisbianca** [comment] 2018-04-03 21:14
@superguineapig from a purely selfish point of view, I’m glad that the fix has stopped the issues within react-native-firebase. That’s some progress at least...

There’s two ways to resolve the problem you’re now seeing:

1) Link react-native-vector-icons manually rather than as a pod
2) Leave as is, keep React specified as a pod, but remove the manually linked React library from within Xcode.

By removing the linked library you _should_ get rid of the duplicates you’re seeing in the Metro Builder. You may however have to add some more subspecs to the React pod to make up for the missing parts that are included within the manually linked library.

There may also be other issues with libs that you come across, but largely this approach will stand you in better stead and is one I follow in my own apps.

**Comment by superguineapig** [comment] 2018-04-03 21:30
@chrisbianca agreed. I've opted for option 1 in my real-world production project. The interaction between cocoapods and react-native link is just too unpredictable for comfort.

Thanks again for your support on this even though it's mostly an ecosystem thing.

react-native-firebase works like a charm. Keep up the great work over there!

**Comment by chrisbianca** [comment] 2018-04-04 07:12
@superguineapig I generally think that Cocoapods is a more reliable package manager and it would be good if react native embraced it, given its prevalence in the native iOS world.

In the meantime, I think you're right and that `react-native link` is just unpredictable where library owners haven't paid heed to the the fairly hidden changes in it's functionality.  It's definitely wise to just manually install libraries either by adding the pod yourself, or by linking within XCode.

Glad you're now up and running now.  I'm going to close this as the fix will be brought into the full release of v4 which we'll do in the next day or so.

**Closed by chrisbianca** 2018-04-04 07:12 UTC
