### ISSUE TITLE
FIS_AUTH_ERROR - when trying to getToken()

### ISSUE THREAD

**Issue by MaxEmbregts** [invertase/react-native-firebase#5522] opened 2021-07-16 07:10 UTC
Hi,

So the problem im having is that when i do the getToken() call on android i get this error in my google developer tools:

[messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR

and this error in android studio logcat:

E/FirebaseMessaging: Failed to get FIS auth token
    java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.

The steps i have taken to setup my android project in firebase:
- Added the sha-1 key to the android app in firebase console.
- In the Google Cloud Platform console I have my android api key without restrictions and added the sha-1 key.
- The google-services.json is in my android/app folder.
- Added apply plugin: 'com.google.gms.google-services' to android/app/build.gradle.
- Added classpath 'com.google.gms:google-services:4.3.8' to android/build.gradle

I have tried with and without the SHA-1 key, no difference. 
I have tried with and without restrictions, no difference. With restrictions i added these api's:

Cloud Messaging
FCM Registration API
Firebase Cloud Messaging API
Firebase Installations API

Im using the current google-services.json that firebase console gives me when i download it.

I also tried to do a curl command. The curl command gave PERMISSION_DENIED back when i had restrictions on (only those 4 mentioned api's above). The curl command gave this response without restrictions:

```
curl -H "content-type: application/json" -d "{appId: 'appId', sdkVersion: 't:1'}" https://firebaseinstallations.googleapis.com/v1/projects/project-name/installations/?key=key
{
  "name": "projects/id/installations/dQ8fVUnRxVhSnBNoDs2jLw",
  "fid": "dQ8fVUnRxVhSnBNoDs2jLw",
  "refreshToken": "2_wkBefPcXZ3J32ot1tb8GW1Jl5iCMnaJ4Tuae7-F1eT_8vAyY3cFXwZ-wgWvzUW44",
  "authToken": {
    "token": "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjE6OTYwMzcxMDQxNzc5OmFuZHJvaWQ6MTYxM2FhOWQyZGY1M2Q0MmJkZGU4NiIsImV4cCI6MTYyNjk2NzE0NCwiZmlkIjoiZFE4ZlZVblJ4VmhTbkJOb0RzMmpMdyIsInByb2plY3ROdW1iZXIiOjk2MDM3MTA0MTc3OX0.AB2LPV8wRAIgc_DF2HThEiUZCjEm9eUWz1kcqzj0OU3cCM7akX3JElsCIDDqndwo8r7FU8Vrs1g_QoXowwcisoh2LAKB0GYY7DwQ",
    "expiresIn": "604800s"
  }
}
```

package.json:
```
 "@react-native-firebase/app": "^12.1.0",
 "@react-native-firebase/messaging": "^12.1.0",
 "react": "17.0.1",
 "react-native": "0.64.2"
```
On iOS everything is working fine. I have setup numerous projects with firebase messaging and never had this happen so im quite confused about this whole situation.

If anybody knows whats going on, please let me know.

Greetings,
Max Embregts

**Comment by snkhan120** [comment] 2021-07-16 10:04
I got the same issue;

package.json versions:
```
"@react-native-firebase/app": "^12.1.0",
"@react-native-firebase/messaging": "^12.1.0",
"react": "17.0.1",
"react-native": "0.64.2",
"react-native-push-notification": "^7.4.0"
```
Code I tried in App.js

```
 useEffect(() => {
    (async function () {
      try {
        const token = await messaging().getToken();
        console.log('we have a token and should do something with it: ' + token);

        let tokenRefreshListenerUnsubscriber = messaging().onTokenRefresh(token => {
          console.log('we have a refreshed token and should do something with it: ' + token);
        });
      } catch (e) {
        console.error('token registration failed?', e);
      }
    })();
  }, []);
```

Log Snapshot:

![image](https://user-images.githubusercontent.com/285439/125930327-b0c76844-2666-4be8-8be8-d9d96a248c88.png)

**Comment by snkhan120** [comment] 2021-07-16 13:23
Problem has been solved, step need to do,

First check the react-native-push-notification is configured correctly
Second create new firebase project and add android app, download the google-json from newly created project app.

then run the code with
./gradlew clean
yarn android 

works perfect and get the token 

index.js 


```
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

import PushNotification from "react-native-push-notification";

PushNotification.configure({
  onNotification: function (notification) {
      console.log("NOTIFICATION:", notification);
  },
  requestPermissions: Platform.OS === 'ios'
});

AppRegistry.registerComponent(appName, () => App);
```

App.js

```
import React, {useEffect} from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';

import {
  Colors,
} from 'react-native/Libraries/NewAppScreen';
import messaging from '@react-native-firebase/messaging';
import PushNotification, {Importance} from 'react-native-push-notification';


const App = () => {

  const createDefaultChannels = () => {
    PushNotification.createChannel(
      {
        channelId: "default-channel-id", // (required)
        channelName: `Default channel`, // (required)
        channelDescription: "A default channel", // (optional) default: undefined.
        soundName: "default", // (optional) See `soundName` parameter of `localNotification` function
        importance: Importance.HIGH, // (optional) default: Importance.HIGH. Int value of the Android notification importance
        vibrate: true, // (optional) default: true. Creates the default vibration pattern if true.
      },
      (created) => console.log(`createChannel 'default-channel-id' returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
    );
    PushNotification.createChannel(
      {
        channelId: "sound-channel-id", // (required)
        channelName: `Sound channel`, // (required)
        channelDescription: "A sound channel", // (optional) default: undefined.
        soundName: "sample.mp3", // (optional) See `soundName` parameter of `localNotification` function
        importance: Importance.HIGH, // (optional) default: Importance.HIGH. Int value of the Android notification importance
        vibrate: true, // (optional) default: true. Creates the default vibration pattern if true.
      },
      (created) => console.log(`createChannel 'sound-channel-id' returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
    );

    PushNotification.localNotification({
      /* Android Only Properties */
      channelId: "sound-channel-id", // (required) channelId, if the channel doesn't exist, notification will not trigger.
    
      actions: ["Yes", "No"], // (Android only) See the doc for notification actions to know more
      invokeApp: true, // (optional) This enable click on actions to bring back the application to foreground or stay in background, default: true
    
      title: "My Notification Title", // (optional)
      message: "My Notification Message", // (required)
    });

  }

  

  const checkToken = async () => {
    const fcmToken = await messaging().getToken();
    if (fcmToken) {
       console.log(fcmToken);
    } 
   }
   
  //  checkToken();

  async function requestUserPermission() {
    const authStatus = await messaging().requestPermission();
    const enabled =
      authStatus === messaging.AuthorizationStatus.AUTHORIZED ||
      authStatus === messaging.AuthorizationStatus.PROVISIONAL;
  
    if (enabled) {
      console.log('Authorization status:', authStatus);
    }
  }

  useEffect(() => {
    // createDefaultChannels();
   checkToken();

  }, []);

  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}>
          <Text>Hello, world!</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default App;
```


Best, 
Ahsan Khan

**Comment by MaxEmbregts** [comment] 2021-07-16 13:37
I don't use react-native-push-notification. I created a new firebase project, added android app, downloaded google-services.json. Still same error.

```
export const checkPermission = () => {
  messaging().hasPermission().then((enabled) => {
    if (enabled) {
      getToken();
    } else {
      requestPermission();
    }
  }).catch((error) => {
    console.log('Error checking permissions ' + error);
  });
};

const requestPermission = () => {
  messaging().requestPermission().then(() => {
    getToken();
  }).catch((error) => {
    console.log('Permission rejected ' + error);
  });
};

const getToken = () => {
  messaging().getToken().then((token) => {
    console.log(token);
  }).catch((error) => {
    console.log('Error getting push token ' + error);
  });
};
```

**Comment by mikehardy** [comment] 2021-07-16 16:48
Not sure what is going on, but it is definitely centered around your API key. Something is not what it appears to be with regard to the key actually in use by the app, and how it is configured.

This seemed like a reasonable explanation of the above to consult https://stackoverflow.com/questions/61453640/android-error-when-communicating-with-the-firebase-installations-server-api/61529757#61529757 - you indicate you've set up a few apps before so it's likely unexpected and you've been through this, yet still there is something wrong in exactly this API key area around Firebase Installations

**Comment by MaxEmbregts** [comment] 2021-07-18 18:15
@mikehardy I did what that post did. I also tried to make a new firebase project with a new android app. I tried to delete the whole app from device and remove all the build folders. Nothing is working, I just don't get it :(

**Comment by MaxEmbregts** [comment] 2021-07-21 07:36
Anybody else any other ideas about what could be the problem. I have checked my API key some many times already. The API key in the google-services.json is the same as in the google cloud platform.

**Comment by timothyerwin** [comment] 2021-07-21 17:46
I'm getting the same problem...not sure what is up

**Comment by timothyerwin** [comment] 2021-07-21 18:25
It looks like I fixed it by downgrading the minor version...not sure what they changed.

```json
    "@react-native-firebase/app": "^12.0.0",
    "@react-native-firebase/messaging": "^12.0.0",
```

**Comment by mikehardy** [comment] 2021-07-21 18:46
That's really unexpected. I wonder if this would be resolved by downloading a new set of google-services json/plist files?

**Comment by MaxEmbregts** [comment] 2021-07-22 07:00
Downgraded versions to 12.0.0 and redownloaded config, same problem.

**Comment by timothyerwin** [comment] 2021-07-22 07:11
Did you make sure you reinstalled version via npm and it is in fact 12.0.0?

**Comment by MaxEmbregts** [comment] 2021-07-22 07:13
Yes, its reinstalled with npm. Version 12.0.0 for both.

**Comment by MaxEmbregts** [comment] 2021-07-22 14:31
After days of trying to find a solution and frustration, I finally found a solution to my problem. In my app im using ssl pinning and apparently that was causing the issue. I found this post on stackoverflow:

https://stackoverflow.com/questions/60698622/java-io-ioexception-fis-auth-error-in-android-firebase

In this post if you scroll down enough you will find this:

"Hope this helps someone:

In my situation, I used self-signed ca. So I need to use network-security-config.xml

After huge try and error, finally I add system directory in trust-anchors like below, FIS_AUTH_ERROR is gone and Firebase worked."

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config>
        <trust-anchors>
            <certificates src="system" />  <!-- for Firebase -->
            <certificates src="user" /> <!-- for tooling.   Ex:Charles --> 
            <certificates src="@raw/ca_1"/> <!-- my self-signed ca-->
        </trust-anchors>
    </base-config>
</network-security-config>
```
This file is found in: android/app/src/main/res/xml/network-security-config.xml

This basically fixed my problem. Finally. 

Thanks for all the other reponses and help though.

**Comment by timothyerwin** [comment] 2021-07-22 17:41
@mikehardy well I just created a new firebase project with the latest downloads so maybe check against that.

**Comment by mikehardy** [comment] 2021-07-22 17:53
@timothyerwin I'm not sure how that is relevant. I'm not having this issue, just 3 hours ago someone reported success (after unrestricting security chain a bit...) with current versions.

To me that means: react-native-firebase + firebase is working. Your project and/or API key and/or SSL config is not working. That's not an issue I here I don't think?

**Comment by timothyerwin** [comment] 2021-07-22 18:11
@mikehardy I'm just responding to your earlier comment:

> That's really unexpected. I wonder if this would be resolved by downloading a new set of google-services json/plist files?

I'm not sure why you want to paint this as a me problem when I'm clearly not the only one having this. If I downgrade a minor version and things suddenly work how is it a me problem now? lol...yes, other people have solved this after tinkering around with things and mentioning "days of frustration"...but I guess everyone else is the issue... :)

**Comment by mikehardy** [comment] 2021-07-23 04:00
There are lots of reasons it can happen, for every person that has had it, it is a "me" problem yes. Based on the fact it is *possible* for it to work, it is not a module problem. As a maintainer, with apologies, that is my vital interest --> I must fix bugs in the module. With whatever time I have left over I can try to offer help, but if it's not a module bug it's project issue, it's a bit binary in that way

**Comment by timothyerwin** [comment] 2021-07-25 05:06
@mikehardy I guess I took it personally...but reading the thread again...I see you just do that with other people too. You just tell everyone its their problem and that comes off as a bit of an asshat :)

We aren't playing a blame game here. Everyone is just looking to fix random problems...we aren't blaming you for it :) This is par for the course...

**Comment by mikehardy** [comment] 2021-07-25 13:48
I do not tell everyone it's their problem. I ask for reproducible examples an  provide tools and info to provide same. I fix bugs and publish. Releases. Never a game

**Closed** 2021-07-25 13:59 UTC
Labels: Help: Needs Triage, Impact: Bug

**Comment by timothyerwin** [comment] 2021-07-25 17:03
> I do not tell everyone it's their problem. 

Yes. You do, and I'll take you to task on this.

> Not sure what is going on, but it is definitely centered around your API key.

You don't know what's going on, but you definitely know what's going on. It's something with them.

> I'm not sure how that is relevant....To me that means: react-native-firebase + firebase is working. Your project and/or API key and/or SSL config is not working.

It's relevant because I'm responding to your earlier suggestion and now you try to say how this project is perfect and it's a me problem, which it's not.

> for every person that has had it, it is a "me" problem yes.

No, it's not. You're being an asshat and I'm telling you why, but I don't think you care about logic. 

In the future, if I have an issue please don't respond unless you are actually going to be helpful. On this thread you didn't help anyone and everyone had to figure it out themselves while being told it was their api key, ssl setting, etc from the same guy who admitted he doesn't know what's going on.

**Comment by mikehardy** [comment] 2021-07-26 19:17
Hey @timothyerwin I mean this sincerely: I would welcome any documentation PR that sums up whatever specific project-specific items may need attention based on whatever evidence is posted here. We have a tips and tricks section for this purpose, and there's an edit button on the top right https://rnfirebase.io/faqs-and-tips - the project's not perfect and the documentation is largely improved by users, in this specific area the project is working though. Yet users are still having issues for what appears to be a wide variety of reasons. Any help untangling that could save future devs a lot of time, and that would be a plus

**Comment by mashish584** [comment] 2022-03-10 10:38
I'm switching from v5 to v14 in an App & caught this issue while generating token.

What I've missed to add while migrating is

`implementation platform('com.google.firebase:firebase-bom:xx.x.x')`


Token is generate successfully after adding this line.

**Comment by mikehardy** [comment] 2022-03-10 14:40
@mashish584 something is wrong - that should not be necessary, we do that for you right here:

https://github.com/invertase/react-native-firebase/blob/1fe6ac7bbba5f544fd51454e47f163152e68334e/packages/app/android/build.gradle#L94

**Comment by mashish584** [comment] 2022-03-10 16:15
@mikehardy Bit strange for me as well because in other projects it's working fine without adding  "firebase-bom". I'll try to inspect it on my end once I got some time.

**Comment by taylorkline** [comment] 2022-04-26 20:44
@MaxEmbregts thank you SO much. Ran into this same issue because of SSL pinning. You saved me hours (more) of digging.

**Comment by mzupek** [comment] 2023-01-06 20:57
> I also had this issue, I solved this by manually removing the **current_key** under **api_key** object on google-services.json.
> 
> Apparently Google put other Firebase app API key as well and those keys are restricted (while my test project key is not).
> 
> Hope this helps future devs some time

This solution worked for me, not sure how the API key got replaced

**Comment by spsaucier** [comment] 2023-04-04 14:56
The fix for me was to update the API key to include these two permissions:
```
 LOG  NotificationHandler:onRegister {"os": "android", "token": "eoikJetIRMWxfv8eFLfQmZ:APA91bGtM42SrIy9NoHhXR5G5leCVxpBVvFnggd-ykszJUOxjFbHd22dv7sdL3qjbQkNCUT1kRTsq0l0Oy72HBIyAHYLLEPKPFhVPtfDSsDBDKs8aPeUbAJjfwywvGAlaB0x6mSKY-_A"}
```

**Comment by Orest1996** [comment] 2024-02-22 14:49
in my case problem was wrong google-services.json file (was copied from other prjoect before) after I changed it by correct one from firebase console, everything started working

**Comment by chanphiromsok** [comment] 2024-08-09 02:10
> in my case problem was wrong google-services.json file (was copied from other prjoect before) after I changed it by correct one from firebase console, everything started working

after solved my issue and I found your it's correct 
- google-service.json is changed so just download goggle-service.json and rebuild your app it is work for me

**Comment by mzanini** [comment] 2024-11-23 05:25
> > I also had this issue, I solved this by manually removing the **current_key** under **api_key** object on google-services.json.
> > Apparently Google put other Firebase app API key as well and those keys are restricted (while my test project key is not).
> > Hope this helps future devs some time
> 
> This solution worked for me, not sure how the API key got replaced

Aren't you getting the error:
```
Missing api_key/current_key object
```
?

**Comment by ajprince21** [comment] 2025-04-18 21:02
@all 
https://medium.com/@ajprince0607/resolving-firebase-messaging-error-in-react-native-fis-auth-error-9b5bfba5649a

**Comment by benedusi** [comment] 2026-04-13 21:50
I started experiencing this issue on an app update, it's a new codebase, but using the proper key and google-services file, and, the reports are coming only from android 16 on a few Samsung and Pixel devices.
FIS_AUTH_ERROR messaging/unknown
