### ISSUE TITLE
Unable to identify which action button is clicked when two buttons are added for Android push notification

### ISSUE THREAD

**Issue by alnsantosh** [invertase/react-native-firebase#1396] opened 2018-08-13 23:07 UTC
### Issue
I am unable to identify which action button is clicked when there are multiple action buttons present in the push notification.
Also on clicking the button when the app is in the background, NotificationOpen.action is android.intent.action.VIEW instead of the value which I set when creating an action for the button.

### Environment

1. Application Target Platform:
Android

2. Development Operating System:
macOS Sierra

3. Build Tools:
Android Studio 3.1.3

4. `React Native` version:
0.53.0

5. `React Native Firebase` Version:
4.3.8

6. `Firebase` Module:
Notifications

7. Are you using `typescript`?
no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by alnsantosh** [comment] 2018-08-17 17:32
@Salakar , Please help me with this issue. It is not letting me to use action buttons for the android push notification.

**Comment by Salakar** [comment] 2018-08-17 21:00
Duplicate of https://github.com/invertase/react-native-firebase/issues/1330.

**Closed by Salakar** 2018-08-17 21:00 UTC
Labels: notifications

**Comment by trimitrtechnologies** [comment] 2019-03-06 08:54
If still facing problem to render Action button, make sure you've imported

`import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;`

In MainApplication.java

and added 
`new RNFirebaseNotificationsPackage()` line inside `getPackages()`


it will looks like below: 
` @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNFirebasePackage(),
            new RNFirebaseMessagingPackage(),
            new RNFirebaseNotificationsPackage()
      );
    }`
