### ISSUE TITLE
🔥'GoogleUtilities/GULAppDelegateSwizzler.h' file not found

### ISSUE THREAD

**Issue by dakkafex** [invertase/react-native-firebase#4132] opened 2020-08-25 13:10 UTC
## Issue

'GoogleUtilities/GULAppDelegateSwizzler.h' file not found

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "^8.3.1",
    "@react-native-firebase/dynamic-links": "^7.4.3",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'PakzeApp' do
  # Pods for PakzeApp
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


  target 'PakzeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'PakzeApp-tvOS' do
  # Pods for PakzeApp-tvOS

  target 'PakzeApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#if RCT_DEV
#import <React/RCTDevLoadingView.h>
#endif
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  #if RCT_DEV
    [bridge moduleForClass:[RCTDevLoadingView class]];
  #endif
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"PakzeApp"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *, id> *) options {
  return [self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:url];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
    Memory: 131.46 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ X] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `whatever the latest version is`
- **`Firebase` module(s) you're using that has the issue:**
  - `Dynamic links`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2020-08-25 13:32
You skipped most of the template, and guessing the reasons without the data we request is an inefficient use of time

Run this and compare the output with your project, https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh - the answer will be in the difference.

**Comment by dakkafex** [comment] 2020-08-25 13:39
skipped most of the template? i filled in all the relevant info what did i skip?

**Comment by mikehardy** [comment] 2020-08-25 13:48
You chose which parts to post and which parts not to. The template does not say "two lines from package.json", that's important

Regardless, my statement (your project likely has a problem, compare a throwaway generated by that script which works with your project) is still the fastest path to resolution

**Comment by mikehardy** [comment] 2020-08-25 14:15
also potentially `npx react-native-clean-project`

**Comment by dakkafex** [comment] 2020-08-25 14:25
I used clean project and that did nothing

Also the scrip you linked just hangs up at
`
[Process completed
`

**Comment by mikehardy** [comment] 2020-08-25 14:27
Can you post the full output, I haven't run it in the last few days but I run that thing *all the time* as it's my primary way of generating full working projects for people with integration issues.

**Comment by mikehardy** [comment] 2020-08-25 15:01
Yeah, I can't reproduce. It's still building for android (and I did a couple changes related to patches there which I've integrated upstream in the main repo) but ios went off without a hitch.

![Screenshot from 2020-08-25 09-59-05](https://user-images.githubusercontent.com/782704/91190981-d2e85080-e6b9-11ea-8b79-12a3ced462f7.png)

The patches were android related so wouldn't affect it, the other change was a bump to firebase-ios-sdk 6.30.0 (current as of this typing) as I use the demo to prove out the new releases as well https://github.com/mikehardy/rnfbdemo/commits/master

Can't reproduce

**Comment by dakkafex** [comment] 2020-08-25 15:48
it says it cant find the firebase .plist file, but i put it in with the script, where else does it have to go?

**Comment by mikehardy** [comment] 2020-08-25 16:21
the two config files (ios is the plist, android is the json - downloaded from the web console) go in the root directory of the repo - the script makes a new example app in a sub-directory, and will copy them in (if it can find them) at the appropriate time

Stated another way, they should be in the same directory as `make-demo.sh`

**Comment by dakkafex** [comment] 2020-08-25 16:47
alright i got it working and its not throwing and build failures.

but i dont know about the diferences between RN 61.5 and 63

**Comment by mikehardy** [comment] 2020-08-25 17:39
https://react-native-community.github.io/upgrade-helper/

**Comment by dakkafex** [comment] 2020-08-25 17:43
but is RN 63 a requirement for the library?

**Comment by dakkafex** [comment] 2020-08-25 19:34
ive tried completely removing the library and installing it back again and only when i add the dynamic links one, i get the not found error

**Comment by mikehardy** [comment] 2020-08-25 19:59
RN63 is not required, you can see the test app which compiles successfully and runs our e2e tests on every push to master (multiple times a day) is still on older version - RN62 https://github.com/invertase/react-native-firebase/blob/b3e6ffc3c81aea6c7b9eee3d23e6297236b078a5/tests/package.json#L29

**Comment by dakkafex** [comment] 2020-08-25 20:41
so i also installed the analytics package, and now it builds fine, but i dont think its mentioned as dependency

**Comment by mikehardy** [comment] 2020-08-25 20:46
I just specifically altered my demo package to build *without* analytics in order to verify the solution for an app targeting the child demographic on app store and it worked fine

get current version and `./make-demo.sh --no-idfa` and it proves that out, analytics isn't needed https://github.com/mikehardy/rnfbdemo/commit/4a716e9fff91ebb9fcca5b095c8278d9ada21427#diff-c8e33fe90e78d567b713e8dab48e5d87L79

**Comment by dakkafex** [comment] 2020-08-25 20:48
but did you also try running it with only the app and dynamic links package?

**Comment by mikehardy** [comment] 2020-08-25 20:55
I did not, if you modify the script to do only that and it reproduces the failure, then we'll have something to work with

**Comment by dakkafex** [comment] 2020-08-26 02:49
i couldnt reproduce it with your script, but when i make a fresh RN project, install the app package first, test it, then install the dynamic link package, test it, i get a build failure with `'GoogleUtilities/GULAppDelegateSwizzler.h' file not found`

**Comment by mikehardy** [comment] 2020-08-26 02:59
That is terrible :-) ! Very strange, especially given that my script is...making a fresh RN project, and just installing things and building.

I'll give it a whirl next time I give it a chance - I haven't been able to reproduce it yet but it should be easy to strip my script down to just app + dynamic-links then we'll see what happens. Perhaps messaging is bringing in the swizzler so it happens to work with dynamic links but dynamic links needs it's own dependency just in case messaging isn't there...

**Comment by dakkafex** [comment] 2020-08-26 03:17
I probably didnt fully understand your script when i was pulling it apart and maybe left something in

**Comment by mikehardy** [comment] 2020-08-26 04:08
Got it - by [stripping the script down to just dynamic links + app](https://github.com/mikehardy/rnfbdemo/blob/dynamic-links-only/make-demo.sh) I was able to reproduce the failure

Inspection of the Podfile.lock shows that the other react-native-firebase modules that use the AppDelegateSwizzler depend directly on firebase-ios-sdk modules that bring it in transitively, so no problem.

FIrebase/DynamicLinks does not bring in the AppDelegateSwizzler package though, so we either need to get lucky (use one of the other modules that uses it - Auth, Analytics, Messaging) or we need to depend on it directly.

Apparently luck has worked for a year but better to be certain and have it just work every time, no?

Here's [the patch](https://github.com/mikehardy/rnfbdemo/blob/master/patches/%40react-native-firebase%2Bdynamic-links%2B7.4.3.patch) in [patch-package](https://github.com/ds300/patch-package) format that gets the build working for you immediately, and I'll release a new version of dynamic-links as soon as E2E is done testing the pull request (30mins or so?)

I definitely didn't have a reproduction case until now so I was resistant yes - but thank you for being persistent, you were definitely on to something here, this won't matter except in the rare app that only wants links, but it is definitely necessary for those

**Comment by mikehardy** [comment] 2020-08-26 04:12
I need to wait on a review approval as well so it might be a day before the release is out - patch-package should get you moving until then, it's a trivial change and patch-package works fantastically - very highly recommended - it will warn you kindly when the release is out and it's time to remove the patch.

**Closed** 2020-08-26 17:51 UTC
Labels: Impact:  Build Error, Platform: iOS, Resolution: No Template, Service: Links

**Comment by mikehardy** [comment] 2020-08-26 18:02
Just released, update and it should work:

```
 - @react-native-firebase/admob@7.6.1
 - @react-native-firebase/analytics@7.5.1
 - @react-native-firebase/auth@9.1.1
 - @react-native-firebase/crashlytics@8.4.1
 - @react-native-firebase/database@7.5.1
 - @react-native-firebase/dynamic-links@7.5.1
 - @react-native-firebase/firestore@7.6.1
 - @react-native-firebase/functions@7.4.1
 - @react-native-firebase/iid@7.4.1
 - @react-native-firebase/in-app-messaging@7.4.1
 - @react-native-firebase/messaging@7.8.1
 - @react-native-firebase/ml-natural-language@7.4.1
 - @react-native-firebase/ml-vision@7.4.1
 - @react-native-firebase/perf@7.4.1
 - @react-native-firebase/remote-config@8.2.1
 - @react-native-firebase/storage@7.4.1
 - react-native-firebase-tests@8.4.1
```
