### ISSUE TITLE
Typescript not working on `firebase.` unless used as `firebase.app().`

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#774] opened 2018-01-23 09:20 UTC
### Issue

I was using `firebase.app().auth` previously until discovering that `app()` bit is no longer needed. Switching to `firebase.auth` causes typescript error below (not only for auth, but in general)

![example](https://camo.githubusercontent.com/577365d1cd23694bf237e375fb204d732d2ba394/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f3236674e3076447050653653624d6c33322f67697068792e676966)

> 
> [ts] Property 'auth' does not exist on type 'typeof FireBase'.
> any

### Environment

1. Application Target Platform: iOS, Android

2. Development Operating System: macOS High Sierra

3. Build Tools: 

4. React Native version: 0.52

5. RNFirebase Version: 3.2.1

6. Firebase Module:

**Comment by Ehesp** [comment] 2018-01-23 11:18
@IljaDaderko does this happen on the other modules as well?

**Comment by IljaDaderko** [comment] 2018-01-23 11:21
@Ehesp indeed it does, judging by typescript suggestions a lot is missing, see screenshots for both `firebase.` and `firebase.app().` below (everything seems to be typed correctly for app())

![firebase](https://i.imgur.com/z6zKfFn.png)

![firebase.app()](https://i.imgur.com/6v15Brj.png)

**Comment by Ehesp** [comment] 2018-01-24 08:54
@pheromonez can you see what's going on here?

**Comment by pheromonez** [comment] 2018-01-24 13:03
@Ehesp No problem, I'll submit a PR once I've got something ready

**Comment by Ehesp** [comment] 2018-01-24 14:55
Awesome thanks very much!

**Comment by danielw93** [comment] 2018-01-26 12:16
What works for me is to first instantiate a firebase object (for example in an injection container like TSDI) `const firebase = new FireBase()`. 
And then use the modules on that instance like `firebase.auth()`, `firebase.links()`, etc.
I always assumed that was intended behavior 😅

**Comment by IljaDaderko** [comment] 2018-01-26 12:44
@danielw93 That did the trick for me, but docs show implementation that is more concise with web sdk: https://rnfirebase.io/docs/v3.2.x/installation/javascript in my opinion this is more friendly to web devs coming into react-native-firebase.

**Comment by meyer** [comment] 2018-01-27 20:10
`firestore` also seems to be missing from type defs. I tried the `new Firebase` approach that @danielw93 suggested but got errors saying that `Firebase` is not a constructor. I’ve resorted to commonjs imports to skip type checking, which is definitely less than ideal:

```jsx
import firebase from 'react-native-firebase';
const firebase2 = require('react-native-firebase');

// ...

firebase.app().auth().signInAnonymously().then(user => {
  const docRef = firebase2.default.firestore().collection('users').doc(user.uid);
  // ...
});
```

@pheromonez let me know if there’s anything I can do to help with fixing type definitions.

I dug around a bit to see if I could find a flow to `.d.ts` generator, but didn’t have a lot of luck. Seems like this should be an automated thing.

**Comment by Ehesp** [comment] 2018-01-28 17:33
@meyer there's currently a PR for Firestore

**Comment by pheromonez** [comment] 2018-01-29 05:46
@Ehesp I've submitted a PR to improve the TS definitions. While going through the JS code I noticed that there's a `utils` package which is undocumented on https://rnfirebase.io/. Is this package intended for internal use only?

@meyer Thanks for the offer to help. This fix was fairly small, so I've been able to complete it, but there are a couple of modules that currently don't have any TS definitions (admob, config, perf) and could certainly use some attention.

**Comment by Ehesp** [comment] 2018-01-29 09:38
@pheromonez yeah the `utils` directory is used for things like internal event emitters, common helpers and the like and isn't designed for public consumption.

**Comment by Ehesp** [comment] 2018-01-30 07:29
Closing in favour of https://github.com/invertase/react-native-firebase/pull/788

**Closed by Ehesp** 2018-01-30 07:29 UTC
Labels: typings

**Comment by eazeye** [comment] 2019-03-20 17:42
This may not be the right place, but I'm wondering what the rationale for returning multiple values was? 
For example, calling firestore.data() will return the following:

![Screen Shot 2019-03-20 at 12 42 30 PM](https://user-images.githubusercontent.com/32505014/54706758-a962e700-4b0d-11e9-8593-96a258cdb058.png)

For Javascript it doesn't seem to matter, but for Typescript I've had to structure my code differently in comparison to if I was just using that standard Firebase.firestore SDK.
