### ISSUE TITLE
🔥 RNFBMessaging build failed for iOS in Mac m1 chip

### ISSUE THREAD

**Issue by theartificialguy** [invertase/react-native-firebase#6792] opened 2022-12-18 07:26 UTC
## Issue

Describe your issue here

My project was working fine in my previous Mac , but as I shifted to the new m1 chip, this started happening, my build failed due to rnfirebase messaging package throwing the following error stack:- (I use -> `npx react-native run-ios --simulator "iPhone 14"`)
```
1 error generated.
In file included from /Users/username/Desktop/myapp/node_modules/@react-native-firebase/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.m:18:
In file included from /Users/username/Desktop/myapp/node_modules/@react-native-firebase/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.h:18:
/Users/username/Desktop/myapp/ios/Pods/Headers/Public/Firebase/Firebase.h:50:13: fatal error: could not build module 'FirebaseFirestore'
    #import <FirebaseFirestore/FirebaseFirestore.h>
     ~~~~~~~^
While building module 'React' imported from /Users/username/Desktop/myapp/node_modules/@react-native-firebase/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.h:20:
In file included from <module-includes>:1:
In file included from /Users/username/Desktop/myapp/ios/Pods/Target Support Files/React-Core/React-Core-umbrella.h:14:
In file included from /Users/username/Desktop/myapp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager+Internal.h:8:
In file included from /Users/username/Desktop/myapp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.h:10:
In file included from /Users/username/Desktop/myapp/node_modules/react-native/React/Base/RCTBridge.h:11:
/Users/username/Desktop/myapp/node_modules/react-native/React/Base/RCTBridgeModule.h:182:1: error: property with 'retain (or strong)' attribute must be of object type
@property (nonatomic, strong, readonly) dispatch_queue_t methodQueue;
^
While building module 'React' imported from /Users/username/Desktop/myapp/node_modules/@react-native-firebase/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.h:20:
In file included from <module-includes>:1:
In file included from /Users/username/Desktop/myapp/ios/Pods/Target Support Files/React-Core/React-Core-umbrella.h:19:
/Users/username/Desktop/myapp/node_modules/react-native/React/CoreModules/RCTAppearance.h:15:60: warning: this function declaration is not a prototype [-Wstrict-prototypes]
RCT_EXTERN NSString *RCTCurrentOverrideAppearancePreference();
                                                           ^
                                                            void
While building module 'React' imported from /Users/username/Desktop/myapp/node_modules/@react-native-firebase/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.h:20:
In file included from <module-includes>:1:
In file included from /Users/username/Desktop/myapp/ios/Pods/Target Support Files/React-Core/React-Core-umbrella.h:27:
In file included from /Users/username/Desktop/myapp/node_modules/react-native/React/CoreModules/RCTDevSplitBundleLoader.h:9:
/Users/username/Desktop/myapp/node_modules/react-native/React/Base/RCTJSScriptLoaderModule.h:16:67: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
@property (nonatomic, copy, nonnull) void (^loadScript)(RCTSource *source);
                                                                  ^
/Users/username/Desktop/myapp/node_modules/react-native/React/Base/RCTJSScriptLoaderModule.h:16:67: note: insert '_Nullable' if the pointer may be null
@property (nonatomic, copy, nonnull) void (^loadScript)(RCTSource *source);
                                                                  ^
                                                                    _Nullable
/Users/username/Desktop/myapp/node_modules/react-native/React/Base/RCTJSScriptLoaderModule.h:16:67: note: insert '_Nonnull' if the pointer should never be null
@property (nonatomic, copy, nonnull) void (^loadScript)(RCTSource *source);
                                                                  ^
                                                                    _Nonnull
While building module 'React' imported from /Users/username/Desktop/myapp/node_modules/@react-native-firebase/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.h:20:
In file included from <module-includes>:1:
...
6 warnings and 3 errors generated.
6 warnings and 5 errors generated.

CompileC /Users/username/Library/Developer/Xcode/DerivedData/myapp-bqzfnxmekpsgkmfaztyrfllaudqg/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFBMessaging.build/Objects-normal/arm64/RNFBMessagingModule.o /Users/username/Desktop/myapp/node_modules/@react-native-firebase/messaging/ios/RNFBMessaging/RNFBMessagingModule.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNFBMessaging' from project 'Pods')
...
1 error generated.
In file included from /Users/username/Desktop/myapp/node_modules/@react-native-firebase/messaging/ios/RNFBMessaging/RNFBMessagingModule.m:18:
/Users/username/Desktop/myapp/ios/Pods/Headers/Public/Firebase/Firebase.h:50:13: fatal error: could not build module 'FirebaseFirestore'
    #import <FirebaseFirestore/FirebaseFirestore.h>
     ~~~~~~~^
...
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/username/Library/Developer/Xcode/DerivedData/myapp-bqzfnxmekpsgkmfaztyrfllaudqg/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFBMessaging.build/Objects-normal/arm64/RNFBMessagingSerializer.o /Users/username/Desktop/myapp/node_modules/@react-native-firebase/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNFBMessaging' from project 'Pods')
(1 failure)
```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "myapp",
  "version": "1.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.7",
    "@react-native-community/datetimepicker": "6.2.0",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-firebase/app": "~15.4.0",
    "@react-native-firebase/auth": "^15.4.0",
    "@react-native-firebase/firestore": "^15.4.0",
    "@react-native-firebase/messaging": "^15.4.0",
    "@react-native-google-signin/google-signin": "^8.0.0",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/elements": "^1.3.6",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "@shopify/flash-list": "1.1.0",
    "axios": "^0.27.2",
    "expo": "^46.0.0",
    "expo-linear-gradient": "~11.4.0",
    "expo-updates": "~0.14.6",
    "react": "18.0.0",
    "react-content-loader": "^6.2.0",
    "react-hook-form": "^7.38.0",
    "react-native": "0.69.6",
    "react-native-element-dropdown": "^2.2.0",
    "react-native-exit-app": "1.1.0",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^13.1.2",
    "react-native-push-notification": "^8.1.1",
    "react-native-reanimated": "2.12.0",
    "react-native-rename": "^2.9.0",
    "react-native-root-siblings": "^4.1.1",
    "react-native-root-toast": "^3.4.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.15.0",
    "react-native-size-matters": "^0.4.0",
    "react-native-svg": "12.3.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-version": "^4.0.0",
    "react-native-version-info": "^1.1.1",
    "react-native-webview": "11.23.0",
    "react-query": "^4.0.0",
    "zustand": "^4.0.0-rc.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.69.3",
    "@types/react-native-push-notification": "^8.1.1",
    "@types/react-native-vector-icons": "^6.4.11",
    "@types/react-query": "^1.2.9",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.29.0",
    "@typescript-eslint/parser": "^5.29.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.72.1",
    "react-test-renderer": "18.1.0",
    "typescript": "^4.4.4"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'myapp' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!
  config = use_frameworks!
  # use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
#    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'myappTests' do
    inherit! :complete
    # Pods for testing
  end
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"
#import <Firebase.h>
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <React/RCTAppSetupUtils.h>

#if RCT_NEW_ARCH_ENABLED
#import <React/CoreModulesPlugins.h>
#import <React/RCTCxxBridgeDelegate.h>
#import <React/RCTFabricSurfaceHostingProxyRootView.h>
#import <React/RCTSurfacePresenter.h>
#import <React/RCTSurfacePresenterBridgeAdapter.h>
#import <ReactCommon/RCTTurboModuleManager.h>

#import <react/config/ReactNativeConfig.h>

static NSString *const kRNConcurrentRoot = @"concurrentRoot";

@interface AppDelegate () <RCTCxxBridgeDelegate, RCTTurboModuleManagerDelegate> {
  RCTTurboModuleManager *_turboModuleManager;
  RCTSurfacePresenterBridgeAdapter *_bridgeAdapter;
  std::shared_ptr<const facebook::react::ReactNativeConfig> _reactNativeConfig;
  facebook::react::ContextContainer::Shared _contextContainer;
}
@end
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  RCTAppSetupPrepareApp(application);

  RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];

#if RCT_NEW_ARCH_ENABLED
  _contextContainer = std::make_shared<facebook::react::ContextContainer const>();
  _reactNativeConfig = std::make_shared<facebook::react::EmptyReactNativeConfig const>();
  _contextContainer->insert("ReactNativeConfig", _reactNativeConfig);
  _bridgeAdapter = [[RCTSurfacePresenterBridgeAdapter alloc] initWithBridge:bridge contextContainer:_contextContainer];
  bridge.surfacePresenter = _bridgeAdapter.surfacePresenter;
#endif

  NSDictionary *initProps = [self prepareInitialProps];
  UIView *rootView = [self.reactDelegate createRootViewWithBridge:bridge moduleName:@"algoguru" initialProperties:initProps];

  if (@available(iOS 13.0, *)) {
    rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
    rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [self.reactDelegate createRootViewController];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [super application:application didFinishLaunchingWithOptions:launchOptions];
  return YES;
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feture is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  // Switch this bool to turn on and off the concurrent root
  return true;
}

- (NSDictionary *)prepareInitialProps
{
  NSMutableDictionary *initProps = [NSMutableDictionary new];

#ifdef RCT_NEW_ARCH_ENABLED
  initProps[kRNConcurrentRoot] = @([self concurrentRootEnabled]);
#endif

  return initProps;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

#if RCT_NEW_ARCH_ENABLED

#pragma mark - RCTCxxBridgeDelegate

- (std::unique_ptr<facebook::react::JSExecutorFactory>)jsExecutorFactoryForBridge:(RCTBridge *)bridge
{
  _turboModuleManager = [[RCTTurboModuleManager alloc] initWithBridge:bridge
                                                             delegate:self
                                                            jsInvoker:bridge.jsCallInvoker];
  return RCTAppSetupDefaultJsExecutorFactory(bridge, _turboModuleManager);
}

#pragma mark RCTTurboModuleManagerDelegate

- (Class)getModuleClassFromName:(const char *)name
{
  return RCTCoreModulesClassProvider(name);
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                      jsInvoker:(std::shared_ptr<facebook::react::CallInvoker>)jsInvoker
{
  return nullptr;
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                     initParams:
                                                         (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return nullptr;
}

- (id<RCTTurboModule>)getModuleInstanceFromClass:(Class)moduleClass
{
  return RCTAppSetupDefaultModuleFromClass(moduleClass);
}

#endif

@end
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 242.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `"@react-native-firebase/app": "~15.4.0",`
- **`Firebase` module(s) you're using that has the issue:**
  - `"@react-native-firebase/messaging": "^15.4.0",`
- **Are you using `TypeScript`?**
  - `Y` & `^4.4.4`

</p>
</details>

This build error only exists for iOS, android build is working fine with no problems, I need help!
---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2022-12-18 20:43
https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+build+retain

This normally happens to people mixing up react-native-firebase versions or on incorrect Xcode versions.

Your react-native-firebase versions appear to be inline with one another though they are out of date. Your Podfile does not seem to have an override to the firebase-ios-sdk. Your Xcode appears to be up to date.

So I'm a bit stumped, but this has shown up a lot and it has always been one of those things so I'd triple check it.

I can tell you without hesitation it builds fine on an M1 mac though, I test it on one frequently and have certainly tested react-native-firebase 15.4.0 with it. Meaning: this *will* be a local problem of some sort. Just confusing what it will be...

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh is a from-scratch demo that shows a project build + compile and I run it on M1s with fine results, as a reproducible example

**Comment by theartificialguy** [comment] 2022-12-19 14:15
> https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+build+retain
> 
> This normally happens to people mixing up react-native-firebase versions or on incorrect Xcode versions.
> 
> Your react-native-firebase versions appear to be inline with one another though they are out of date. Your Podfile does not seem to have an override to the firebase-ios-sdk. Your Xcode appears to be up to date.
> 
> So I'm a bit stumped, but this has shown up a lot and it has always been one of those things so I'd triple check it.
> 
> I can tell you without hesitation it builds fine on an M1 mac though, I test it on one frequently and have certainly tested react-native-firebase 15.4.0 with it. Meaning: this *will* be a local problem of some sort. Just confusing what it will be...
> 
> https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh is a from-scratch demo that shows a project build + compile and I run it on M1s with fine results, as a reproducible example

So are you suggesting me to build your reproducible example and find out what's missing/wrong?

**Comment by mikehardy** [comment] 2022-12-20 14:08
You can just comment out whatever python thing is not working, that's only used to make the macCatalyst build test work and I assume you don't really care about that

What I'm asking you to do is to forget your project for a moment, and try a clean project. Because react-native 0.70.6 and react-native-firebase v16.current work just fine on an M1. If you try a clean project, it should prove that's the case (as I prove to myself frequently, as do thousands of others using it without problem).

Once you've satisfied yourself that it works *in general* then you know where to focus your effort *which is inside your project* to find the problem. That's my assumption anyway. That will result in this issue being closed as inactionable which is not the best outcome for you but I do think it's helpful because often simply knowing where to focus leads to the solution, and if you're focused on "the module has an issue, I'll go ask there..." it's time spent in the wrong spot.

**Comment by theartificialguy** [comment] 2022-12-20 14:32
> You can just comment out whatever python thing is not working, that's only used to make the macCatalyst build test work and I assume you don't really care about that
> 
> What I'm asking you to do is to forget your project for a moment, and try a clean project. Because react-native 0.70.6 and react-native-firebase v16.current work just fine on an M1. If you try a clean project, it should prove that's the case (as I prove to myself frequently, as do thousands of others using it without problem).
> 
> Once you've satisfied yourself that it works _in general_ then you know where to focus your effort _which is inside your project_ to find the problem. That's my assumption anyway. That will result in this issue being closed as inactionable which is not the best outcome for you but I do think it's helpful because often simply knowing where to focus leads to the solution, and if you're focused on "the module has an issue, I'll go ask there..." it's time spent in the wrong spot.

hey, so I was able to run your reproducible example, and it is running completely fine! So now, would you suggest me to upgrade all react-native-firebase/* packages? or copy paste the Podfile...?

**Comment by mikehardy** [comment] 2022-12-20 18:49
I learned long ago that I can *maybe* guess and offer suggestions but there are an infinite variety of ways people creatively mis-integrate react-native and react-native-firebase and I can never predict all the failure modes, that's what my script is for - it approaches the problem from the opposite direction. If I can't guess what way some specific project is failing, I can at least prove that there is one clean + reproducible way to prove it *can* work.

The rest I unfortunately I have to leave up to creators+fixers on their individual projects or I will lose my entire life on the infinite variety of problems.

I do in general suggest people upgrade all their software to current stable *first* and only then open issues anywhere in open source repositories, so yes, try that. Beyond that? Whatever seems right to do, do it. That sounds vague and is on purpose, as I don't know why your project is failing unfortunately

**Comment by mikehardy** [comment] 2022-12-20 18:50
Given this is provably working on an M1 script with a reproduction of success I have to close this as unactionable as it will not result in any changes here

**Closed by mikehardy** 2022-12-20 18:50 UTC
Labels: Impact: Bug, Help: Needs Triage

**Comment by crosskpixel** [comment] 2023-06-13 14:32
Same problem here, i am looking to https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh and solving lines in my code, but at end line in got

<img width="445" alt="image" src="https://github.com/invertase/react-native-firebase/assets/30272464/f51daa3c-7f6f-4986-bd72-9bc3eee23738">

![image](https://github.com/invertase/react-native-firebase/assets/30272464/ebc52a61-7b32-4022-8078-9795c3554481)

I applied Excluded Arch  arm64 for Project and Pods, for got this position. before that i received CoreFoundation issues. 
I think that is a good evolution, i just need to solve that build to RNFBMessaging, has if anyone with solution for that ?

**Comment by crosskpixel** [comment] 2023-06-13 14:37
Maybe is the version of RNFB in package.json, but i hope is compatible because i tried to follow documentation.
In other project a little bit older, i used messaging in android and for curiosity for execution on iOS i needed to uninstall to compile project. Not is the first time i got it, but i hope be some mistake in my code. If i will get new asnwer i will post here.
