### ISSUE TITLE
[Android] Java exception in NativeMules java.lang.IllegalArgumentException: Given String is empty or null when start app

### ISSUE THREAD

**Issue by PanarinU** [invertase/react-native-firebase#1098] opened 2018-05-17 09:20 UTC
### Issue
When I Build react-native android
I get error 

Java exception in NativeMules in Android

java.lang.IllegalArgumentException: Given String is empty or null 

when start app

![screen shot 2561-05-17 at 15 56 29](https://user-images.githubusercontent.com/36912395/40167667-cd7e8f72-59eb-11e8-93eb-08b6778d9c0a.png)

my `android/build.gradle `

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

def googlePlayServicesVersion = "11.8.0"

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        configurations.all {
            resolutionStrategy {
                force "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"
                // react-native-admob
                force "com.google.android.gms:play-services-ads:$googlePlayServicesVersion"
                // // react-native-maps
                force "com.google.android.gms:play-services-base:$googlePlayServicesVersion"
                force "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
                // // react-native-onesignal
                force "com.google.android.gms:play-services-analytics:$googlePlayServicesVersion"
                force "com.google.android.gms:play-services-location:$googlePlayServicesVersion"
                // // react-native-google-sign-in
                force "com.google.android.gms:play-services-auth:$googlePlayServicesVersion"
                // // google place
                force "com.google.android.gms:play-services-places:$googlePlayServicesVersion"
                
            }
        }

        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'https://maven.google.com' }
    }
}
```

my `android/app/build.gradle`

```
apply plugin: "com.android.application"

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        // The Fabric Gradle plugin uses an open ended version to react
        // quickly to Android tooling updates
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'io.fabric'
repositories {
    maven { url 'https://maven.fabric.io/public' }
}

import com.android.build.OutputFile

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

project.ext.envConfigFiles = [
    dev: ".env.dev",
    staging: ".env",
    production: ".env.production",
]

apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
project.ext.envConfigFiles = [
    staging: ".env",
    production: ".env.production"
]

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId project.env.get("APP_ID_ANDROID")
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 93
        versionName "4.0.3"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        manifestPlaceholders = [manifestApplicationId          : "${applicationId}",
                                onesignal_app_id               : "${app_id}",
                                onesignal_google_project_number: "${google_number}"]
        resValue "string", "build_config_package", "${package}"
        multiDexEnabled true
    }
    signingConfigs {
        release {
            storeFile file("")
            storePassword ""
            keyAlias ""
            keyPassword ""
        }
    }
    dexOptions {
        jumboMode = true
        javaMaxHeapSize "4g"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    productFlavors {
        dev {
        
        }
        staging {

        }
        production {

        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile "com.google.firebase:firebase-auth:11.8.0"
    compile project(':react-native-i18n')
    compile project(':react-native-android-permissions')
    compile project(':bugsnag-react-native')
    compile project(':react-native-google-places')
    compile project(':react-native-image-resizer')
    compile project(':react-native-image-picker')
    compile project(':react-native-vector-icons')
    compile project(':react-native-fabric')
    compile project(':react-native-fbsdk')
    compile project(':react-native-device-info')
    compile project(':react-native-mixpanel')
    compile project(':react-native-google-analytics-bridge')
    compile project(':react-native-onesignal')
    compile project(':react-native-config')
    compile project(':react-native-code-push')
    // Crashlytics Kit
    compile('com.crashlytics.sdk.android:crashlytics:2.6.7@aar') {
        transitive = true;
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    // From node_modules
    compile 'com.google.firebase:firebase-messaging:11.8.0'
    compile 'com.facebook.android:notifications:1.+'
    compile 'com.android.support:appcompat-v7:26+'
    compile 'com.facebook.react:react-native:+'
    compile 'com.android.support:multidex:1.0.1'
    compile "com.google.firebase:firebase-analytics:11.8.0"
    compile project(':react-native-video')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'

```

### Environment

1. Application Target Platform:
Android

2. Development Operating System:
SDK 26

3. Build Tools:
26.0.2

4. React Native version:
0.53.3

5. RNFirebase Version:
3.2.6

**Comment by LRNZ09** [comment] 2018-05-17 16:01
I'm having this issue too with the latest version `4.1.0`.
It seems it crash when calling `getConstants` at the app boot.

**Comment by LRNZ09** [comment] 2018-05-17 16:28
Tried to replace with the new downloaded `google-services.json` from the firebase console but there is no difference in the file content and the package name match up.

**Comment by PanarinU** [comment] 2018-05-18 05:15
@Salakar @LRNZ09 
right now i can solved by fix in
 `android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java` line `1616`
From 
`FirebaseAuth firebaseAuth = FirebaseAuth.getInstance(instance);`
To
`FirebaseAuth firebaseAuth = FirebaseAuth.getInstance();`

That work for me 

Thank you

**Comment by lunarraid** [comment] 2018-05-18 20:26
I am running into this issue as well. It may have something to do with react-native-onesignal, since running some debugging shows that the app name changes from `[DEFAULT]` when this method is called to `ONESIGNAL_SDK_FCM_APP_NAME`, which is probably the point it is failing at.

**Comment by lunarraid** [comment] 2018-05-18 20:53
On further digging, this may be related: https://github.com/OneSignal/OneSignal-Android-SDK/commit/81dfa79b11bc65c7785c69e400844495b7ea6a94

**Comment by lunarraid** [comment] 2018-05-19 15:03
@chrisbianca Since it looks like OneSignal already fixed the issue in the next version of their SDK (just waiting on an official release), this is a configuration issue on their end that `react-native-firebase` shouldn't need to account for.

**Comment by LRNZ09** [comment] 2018-05-19 19:18
I can confirm it's a `react-native-onesignal` issue, updated it to the latest version and it seems the issue has been resolved!

**Comment by adirzoari** [comment] 2018-05-20 19:42
@lunarraid  same here. after I install react-native onesignal i'm facing this issue. @LRNZ09  how did you solve it?

**Comment by adirzoari** [comment] 2018-05-21 19:15
@lunarraid  can you please explain how can I put my fork in package.json? when I put my fork https://github.com/adirzoari/react-native-firebase  in package.json in 'react-native-firebase' it install unnecessary things.

**Comment by lunarraid** [comment] 2018-05-21 19:26
@adirzoari My project is private commercial software, so I can't publish my
project. When you npm install `react-native-firebase` straight from the
fork, it runs a bunch of publish actions. I just took the end result of
those actions and pushed that to my branch.

**Comment by adirzoari** [comment] 2018-05-21 19:27
you mean to run `npm install https://github.com/adirzoari/react-native-firebase `??

**Comment by LRNZ09** [comment] 2018-05-22 13:16
@adirzoari I'm using these versions:
`"react-native-firebase": "^4.2.0"`
`"react-native-onesignal": "^3.2.3"`
Remember to `yarn` or whatever is your package manager and then `react-native link` to make sure you have linked native libraries.

**Comment by adirzoari** [comment] 2018-05-22 13:18
@LRNZ09  push notification in android works good for you? you get notifications

**Comment by chrisbianca** [comment] 2018-05-22 15:42
Closing as this is not a react-native-firebase issue and will be addressed in a future react-native-onesignal release.

**Closed by chrisbianca** 2018-05-22 15:42 UTC
Labels: android, installation, third-party-issue
