### ISSUE TITLE
Installation for iOS?

### ISSUE THREAD

**Issue by alxvallejo** [invertase/react-native-firebase#5599] opened 2021-08-15 17:46 UTC
The directions for this repo seem inadequate. 

error:  NativeFirebaseError: [auth/internal-error] An internal error has occurred, please try again.
    at FirebaseAuthModule.createUserWithEmailAndPassword (VM4 index.bundle:107536)

I'm seeing this logged in XCode:

[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.

whereas this repo's documentation calls for initialization via [FIRApp configure];

Why the discrepency? 

The firebase documentation (https://firebase.google.com/docs/ios/setup#swift) doesn't make that much sense either, which tells you to import Firebase in UIApplicationDelegate. That function is in AppDelegate.h, not AppDelegate.m.

Can anyone straighten this out for me?

**Comment by mikehardy** [comment] 2021-08-15 17:56
Hi there!
No discrepancy in Objective-C, not sure if you are using swift, but that would perhaps explain it.
Are you using Swift?

Here's a demo from scratch to fully working: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by alxvallejo** [comment] 2021-08-15 18:00
I'm not a C/Swift developer, but isn't Swift just the preferred standard now? 

This is a vanilla react native build, so whatever is in AppDelegate.m is what I'm using.

I thought you could put 

  if ([FIRApp defaultApp] == nil) {
      [FIRApp configure];
    }

but it looks like this is wrong. So is there a Swift appropriate way? I don't see why I need to bootstrap an entire demo application to answer this.

**Comment by mikehardy** [comment] 2021-08-15 18:10
How did it go when you examine the script I linked, read the comments and did exactly what it does? 

https://github.com/mikehardy/rnfbdemo/blob/37dbe674474425dd49a651798411318d999fd88e/make-demo.sh#L15-L20

They follow the documentation exactly.

if you have an AppDelegate.m file, you are using Objective-C. If you are not a C or Swift developer, the current preferred standard is unimportant, but you may know that react-native is still mostly an Objective-C ecosystem due to inertia for the most part. A fresh app will give you Objective-C files, e.g., `AppDelegate.m`

This is not going to result in any sort of change to the module - the module itself, nor it's basic integration instructions have an issue, so I'm going to close this.

I believe the documents are complete and correct and for the avoidance of doubt the my script will walk you through all the steps or is executable and will provide a working app.

**Closed by mikehardy** 2021-08-15 18:10 UTC

**Comment by alxvallejo** [comment] 2021-08-15 18:17
You should update your script to use 8.5, not 8.4, but more importantly running your scripts doesn't exactly help me diagnose what went wrong during my installation. For example, i'm not interested in running the android configurations so those are moot. 
You're also doing some type of workaround which I doubt i would need to do:
 # Workaround needed for static framework build only, regular build is fine.
  # https://github.com/facebook/react-native/issues/31149#issuecomment-800841668

Using someone else's working example should be separate from diagnosing vanilla installs.

**Comment by mikehardy** [comment] 2021-08-15 18:27
I think you mean firebase-ios-sdk 8.5.0 (there is no '8.5', if you're being really really specific about instructions not being perfect, please realize precision is important, yes?)

That's immaterial though, you likely do not want a version override, they should only be used in specific situations which you won't have on a default project, and we've already updated to 8.5.0 here, so you're set #5572

I don't think you're here to complain about unneeded versions in the helper script I provide for confused integrators though, and I don't think it's important that I've helpfully provided an example for static frameworks which you may not need, or for android problems which you may not have

If you don't want that help, don't take it.

if all you want is the vanilla install for iOS, use **the exact** lines that I linked the second time. 15-20.

You will need to do some work here.

**Comment by mikehardy** [comment] 2021-08-15 18:30
Most pointedly though:

> but more importantly running your scripts doesn't exactly help me diagnose what went wrong during my installation.

This assertion is incorrect.

Running the script produces a working project, whereas incorrect integrations can have infinite variations - that's an intractable problem for us, from a support perspective.

So I provide that script and it is your job to compare it's output with whatever variation of incorrect variation you have

That exact activity will provide the diagnosis for what went wrong in your project

**Comment by alxvallejo** [comment] 2021-08-15 18:32
Thanks for pointing out the relevant lines in the code. The rest is just noise.

So you're using `@import Firebase;` but this repo says to use `#import <Firebase.h>`, the latter is consistent with the rest of the AppDelegate.m file. Can you explain why i'd use one over the other? That is the only difference i see in steps here.

**Comment by mikehardy** [comment] 2021-08-15 18:40
That's an interesting question and the last time I looked deeply on stackoverflow.com the results were educational, you might search it.

How did it go when you tried each of the two to see?

In my testing there were compatibility issues a long time ago but it should make no difference now.

**Comment by alxvallejo** [comment] 2021-08-16 15:01
I'm still getting this:

The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.

Why would it tell me to explicitly use this method if i'm not using Swift?

**Comment by mikehardy** [comment] 2021-08-16 15:09
I followed your link

For Objective-C they recommend what we recommend https://firebase.google.com/docs/ios/setup#initialize-firebase (on Objective-C tab)

I suppose their error message has just gone swift first. 

Did you know that firebase-ios-sdk is also open source?
You can see the very error message you are getting here:

https://github.com/firebase/firebase-ios-sdk/blob/125a6fee8a079486770e93d7d1f463f38c2f371e/FirebaseCore/Sources/FIRApp.m#L247-L259

```objective-c
+ (FIRApp *)defaultApp {
  if (sDefaultApp) {
    return sDefaultApp;
  }
  FIRLogError(kFIRLoggerCore, @"I-COR000003",
              @"The default Firebase app has not yet been "
              @"configured. Add `FirebaseApp.configure()` to your "
              @"application initialization. This can be done in "
              @"in the App Delegate's application(_:didFinishLaunchingWithOptions:)` "
              @"(or the `@main` struct's initializer in SwiftUI). "
              @"Read more: https://goo.gl/ctyzm8.");
  return nil;
}
```

When you run my script do you get a working project?

**Comment by mikehardy** [comment] 2021-08-16 15:10
In fact it did, git blame on those lines shows an appropriately labelled pull request: https://github.com/firebase/firebase-ios-sdk/pull/8295 ("Swift first exception messages")

**Comment by mikehardy** [comment] 2021-08-16 15:11
I won't have time to respond more until I hear results from execution of the script to make sure that something/anything works in your environment. Going back on forth about error messages is inefficient

**Comment by alxvallejo** [comment] 2021-09-06 15:20
@mikehardy Sorry, but custom installation scripts don't address the heart of the issue.

For me, what ended up working was simply removing the conditional in AppDelegate.m

if ([FIRApp defaultApp] == nil) {
[FIRApp configure];
}

to 

[FIRApp configure];

Make sure to clean the build directory before compiling. Finally got it to work. Phew.

**Comment by mikehardy** [comment] 2021-09-06 19:07
Installation scripts (they are all custom?) do address the heart of the issue.
You have (had! thankfully) a build issue that only you reproduce.
The script reproduces a successful build.
Somewhere between the two, you could perhaps come up with a reproduction of the issue so far only you reproduce, and if it were scripted (even with a sorry but custom installation script) then we could learn from it

That's the whole point of (custom) installation scripts --> reproductions that may be shared and confirmed.

Shame you never ran it to confirm results, as at this point we've spent a fair bit of time communicating but there are no reproducible results we can learn from to advance our knowledge

Perhaps another time
