### ISSUE TITLE
react-native-firebase-starter : issue with ios pod install

### ISSUE THREAD

**Issue by bhakta0007** [invertase/react-native-firebase#884] opened 2018-03-15 08:12 UTC
### Issue

https://github.com/invertase/react-native-firebase-starter

IOS setup seems broken, I get an error during pod install. I have filed https://github.com/invertase/react-native-firebase-starter/issues/19.

posting it here for a quicker response

### Environment

iOS

1. Application Target Platform:

iOS on macOS high sierra

2. Development Operating System:

3. Build Tools:

N/a

4. React Native version:
5. RNFirebase Version:
6. Firebase Module:

    "fbjs": "^0.8.16",
    "react": "^16.2.0",
    "react-native": "^0.53.0",
    "react-native-firebase": "^3.2.7"

**Comment by Salakar** [comment] 2018-03-15 09:38
Duplicate of invertase/react-native-firebase-starter#19. Please don't duplicate issues trying to get a quicker response, it doesn't help and only slows things down more.

**Closed by Salakar** 2018-03-15 09:38 UTC
