### ISSUE TITLE
[🐛] MinifyEnabled breaks app after React Native 0.72.4 upgrade

### ISSUE THREAD

**Issue by UnderTheMoonspell** [invertase/react-native-firebase#7345] opened 2023-09-12 12:10 UTC
## Issue

Came here from the react native github issues section.

Hey all!

We just upgraded to React Native 0.72.4 following the upgrade helper website. All was good in our QA pipeline, we tested a lot on top of the new version.

Problems arose when we were in our deployment phase and we noticed that a release version would not start in Android (only). After some investigation the issue seems to be the minifyEnabled in build.gradle. As we were able to startup the app in release mode if its not enabled.

The obfuscated stacktrace is also not very helpful anyone have any idea?

![image](https://github.com/invertase/react-native-firebase/assets/10156878/58c53250-2ef7-4079-aab1-d580cce5c993)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
OS: macOS 13.3.1
CPU: (10) arm64 Apple M1 Pro
Memory: 260.80 MB / 16.00 GB
Shell:
version: "5.9"
path: /bin/zsh
Binaries:
Node:
version: 18.14.0
path: ~/.nvm/versions/node/v18.14.0/bin/node
Yarn:
version: 1.22.18
path: /opt/homebrew/bin/yarn
npm:
version: 9.3.1
path: ~/.nvm/versions/node/v18.14.0/bin/npm
Watchman:
version: 2022.10.24.00
path: /opt/homebrew/bin/watchman
Managers:
CocoaPods:
version: 1.12.1
path: /Users//.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
iOS SDK:
Platforms:
- DriverKit 22.4
- iOS 16.4
- macOS 13.3
- tvOS 16.4
- watchOS 9.4
Android SDK: Not Found
IDEs:
Android Studio: 2022.2 AI-222.4459.24.2221.9971841
Xcode:
version: 14.3.1/14E300c
path: /usr/bin/xcodebuild
Languages:
Java:
version: 11.0.11
path: /usr/bin/javac
Ruby:
version: 2.7.6
path: /Users//.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
"@react-native-community/cli": Not Found
react:
installed: 18.2.0
wanted: 18.2.0
react-native:
installed: 0.72.4
wanted: 0.72.4
react-native-macos: Not Found
npmGlobalPackages:
"react-native": Not Found
Android:
hermesEnabled: true
newArchEnabled: false
iOS:
hermesEnabled: true
newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.12.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Nehal-Zeller** [comment] 2023-09-20 06:30
+1

**Comment by Nehal-Zeller** [comment] 2023-09-20 10:09
@mikehardy 

Getting error logs:

```
> Task :app:minifyStagingFirebaseReleaseWithR8 FAILED

ERROR:R8: java.lang.NullPointerException

FAILURE: Build failed with an exception.

What went wrong:

Execution failed for task ':app:minifyStagingFirebaseReleaseWithR8'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable

   > Compilation failed to complete
```
package.json:
     "react-native": "0.72.4",
    "@react-native-firebase/app": "^14.12.0",
    "@react-native-firebase/app-check": "^14.12.0",
    "@react-native-firebase/messaging": "^14.12.0",
    "@react-native-firebase/remote-config": "^14.12.0",
    
           
android/build.gradle:
....
      buildToolsVersion = "33.0.2"
        minSdkVersion = 26
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.9.0"
        ndkVersion = "23.1.7779620"
  ....
        classpath("com.android.tools.build:gradle")


    
    proguard is enabled

**Comment by mikehardy** [comment] 2023-09-20 11:34
I think I'm caught up enough to give it a look but it won't be for a few hours. Has anyone run my rnfbdemo/make-demo.sh script to check? That's my first step. It contains a release build test with minification so should surface the issue in a reproducible way...

**Comment by mikehardy** [comment] 2023-09-20 11:40
Oh, just noticed the versions. You need to use current versions of react-native-firebase, and retest, for this to receive attention. I'll rerun my demo script to prove current versions work but I'll assume this is from old versions of the crashlytics Gradle plugin

**Comment by Nehal-Zeller** [comment] 2023-09-20 14:05
@mikehardy  I got the crash with the latest versions too. Moreover, I'm not using crashlytics in my project. Packages I'm using are: 
     "@react-native-firebase/app"
    "@react-native-firebase/app-check"
    "@react-native-firebase/messaging"
    "@react-native-firebase/remote-config"

**Comment by mikehardy** [comment] 2023-10-20 16:56
My reproduction script works for me as positive confirmation that minify can work with current versions.
I'll need a full reproduction that shows the error in order to pursue this, until then closing as there is a valid reproduction of success and nothing to the contrary at the moment that I can execute + see

**Closed by mikehardy** 2023-10-20 16:56 UTC
Labels: Impact: Bug, Help: Needs Triage
