### ISSUE TITLE
[🐛] Execution failed for task ':react-native-firebase_crashlytics:generateReleaseRFile'.

### ISSUE THREAD

**Issue by allexwentworthok** [invertase/react-native-firebase#6653] opened 2022-11-02 18:41 UTC
## Issue

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-firebase_crashlytics:generateReleaseRFile'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > /Users/vagrant/git/node_modules/@react-native-firebase/app/android/build/intermediates/symbol_list_with_package_name/release/package-aware-r.txt
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 5m 8s
569 actionable tasks: 569 executed

Describe your issue here

Since yesterday I'm having an error in bitrise, when I try to export my app

"@react-native-firebase/crashlytics": "14.7.0"

**Comment by mikehardy** [comment] 2022-11-02 19:17
Hi there! You skipped our issue template, which means we do not have the information to help, I will close this.

Your versions of this module at least are out of date though, and since there is a warning that your file will not be compatible with gradle 7, but gradle 7 is already out and in use in current react-native releases what I guess happened is:

- react-native-firebase is out of date, and your crashlytics plugins is likely out of date (check docs for current version on install page)
- react-native is out of date so your gradle + gradle plugin are out of date in android build files
- you may or may not be using JDK11 but you should upgrade to that.

If everything were up to date, this would build fine and we demonstrate the same with a https://stackoverflow.com/help/minimal-reproducible-example here which you may run yourself to verify https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh so I'm certain there is not a problem with this module when used as documented on current versions

**Closed by mikehardy** 2022-11-02 19:17 UTC
Labels: Impact: Bug, Help: Needs Triage
