### ISSUE TITLE
Crash: TypeError Object.defineProperty() argument is not an object 

### ISSUE THREAD

**Issue by sivakumar-cf** [invertase/react-native-firebase#3598] opened 2020-05-03 14:08 UTC
## Issue

**Crashing on messaging module.**
Stacktrace has given here
```
TypeError Object.defineProperty() argument is not an object 
    native defineProperty
    node_modules/@react-native-firebase/messaging/lib/index.js:204:13 anonymous
    native apply
    node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:32 value
```
---

### Javascript
`Messaging/index.js:` 
<details><summary>Click To Expand</summary>
  
```
onTokenRefresh(listener) {
    if (!isFunction(listener)) {
      throw new Error("firebase.messaging().onTokenRefresh(*) 'listener' expected a function.");
    }
    const subscription = this.emitter.addListener('messaging_token_refresh', event => {
      // TODO remove after v7.0.0, see: https://github.com/invertase/react-native-firebase/issues/2889
      const { token } = event;
      const tokenStringWithTokenAccessor = String(token);
      Object.defineProperty(tokenStringWithTokenAccessor, 'token', {
        enumerable: false,
        get() {
          // eslint-disable-next-line no-console
          console.warn(
            'firebase.messaging().onTokenRefresh(event => event.token) is deprecated, use onTokenRefresh(token => token) or call getToken() instead',
          );
          return token;
        },
      });
      listener(tokenStringWithTokenAccessor);
    });
    return () => subscription.remove();
  }
```

<p>

**Usage:**
```
const unsubscribe = messaging().onTokenRefresh(token => {
      typeof onTokenRefresh === "function" && onTokenRefresh(token);
  });
```

#### `package.json`:
    "@react-native-firebase/messaging": "6.7.1",

#### `firebase.json` for react-native-firebase v6:
`{
  "react-native": {
    "messaging_android_notification_channel_id": "curefit_notification_id",
    "messaging_ios_auto_register_for_remote_messages": false
  }
}`
```json
# N/A
```

</details>

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.44 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.0, 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-startup-time: 1.2.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.7.1`
- **Are you using `TypeScript`?**
  - `Y/N` & `Y`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by tbrent** [comment] 2020-05-04 20:27
Facing this issue as well. Downgrading from `@react-native-firebase/messaging` 6.7.1 to 6.7.0 is a possible workaround for now.

**Comment by Ehesp** [comment] 2020-05-04 20:37
I think there may be a PR out for this, on my phone though and can't find it.

**Comment by SaeedZhiany** [comment] 2020-05-05 10:25
@Ehesp 

I'm facing with this crash only on application first install.

**Comment by SaeedZhiany** [comment] 2020-05-05 10:27
@Ehesp 

I'm facing with this crash only on application first install. it causes Force close on Android at the first lunch of the app in release mode too.

**Comment by SaeedZhiany** [comment] 2020-05-05 10:43
> Facing this issue as well. Downgrading from @react-native-firebase/messaging 6.7.1 to 6.7.0 is a possible workaround for now.

@tbrent 
I tried this but the result is the same.

**Comment by SaeedZhiany** [comment] 2020-05-05 10:45
@Ehesp 

I'm facing with this crash only on application **first install and first lunch**. it causes a force close in release mode too.

> Facing this issue as well. Downgrading from @react-native-firebase/messaging 6.7.1 to 6.7.0 is a possible workaround for now.

@tbrent 
I tried this but the result is the same.

**Comment by SaeedZhiany** [comment] 2020-05-05 11:00
@Ehesp 

I'm facing with this crash only on application **first install and first lunch**. it causes a force close in release mode too.

**Comment by Salakar** [comment] 2020-05-06 07:53
PR #3552 has been merged which should fix this, will be published later today.

**Closed by Salakar** 2020-05-06 07:53 UTC

**Comment by SaeedZhiany** [comment] 2020-05-08 19:17
> PR #3552 has been merged which should fix this, will be published later today.

@Salakar 
please publish the new version, we are still waiting. Thanks

**Comment by SaeedZhiany** [comment] 2020-05-11 04:32
> PR #3552 has been merged which should fix this, will be published later today.

@Salakar 
please publish the new version, we are still waiting. Thanks

**Comment by SaeedZhiany** [comment] 2020-05-11 04:34
> Facing this issue as well. Downgrading from `@react-native-firebase/messaging` 6.7.1 to 6.7.0 is a possible workaround for now.

I downgraded to many versions including 6.7.0, even version 6.4.0 suffers from this issue.

**Comment by dansiemens** [comment] 2020-05-11 15:57
@SaeedZhiany are you sure? I downgraded to 6.7.0 and it seemed to resolve the issue. Make sure you clear the gradle cache when downgrading.

**Comment by SaeedZhiany** [comment] 2020-05-11 16:05
Yeah, as I said before the error happened only on first install and lunching the application. After the first lunch even v6.7.1 doesn't cause force close. at least it's what I'm experiencing with my project.

**Comment by dansiemens** [comment] 2020-05-11 16:57
Actually I just uninstalled/reinstalled and it did crash again for me on `6.7.0`. Any word on when this release will be available @Salakar?

**Comment by SaeedZhiany** [comment] 2020-05-15 09:03
RNFB v7.0.1 is out.

**Comment by SaeedZhiany** [comment] 2020-05-15 09:05
[RNFB v7.01 is out](https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/CHANGELOG.md#bug-fixes)

I'm going to check whether the problem is gone. I'll report back here.
