### ISSUE TITLE
FirebaseStorage/FirebaseStorage-Swift.h file not found

### ISSUE THREAD

**Issue by salihgun** [invertase/react-native-firebase#6335] opened 2022-06-24 16:27 UTC
Hi i create a new project with 0.69 version of react native and the install firebase but i got "FirebaseStorage/FirebaseStorage-Swift.h file not found" error all the time. Here is my pod file
`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'Hotshot' do
  config = use_native_modules!

  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'HotshotTests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
`
![Screen Shot 2022-06-24 at 19 25 05](https://user-images.githubusercontent.com/47421572/175579020-d9d0adf1-b3c9-4b8f-98a9-0ff522e667eb.png)

**Comment by mikehardy** [comment] 2022-06-24 16:59
Hi there! You'll want to examine my completely scripted reproducible demo app creator to see exactly how to create a successful react-native project with 0.69 and react-native-firebase v15

It is full of comments explaining each step it takes before it runs a command to automatically do the step

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

I've run it just a few hours ago and it works, so I know it's working

Pay special attention to the fact that react-native-firebase v15 will not work with 0.69.0 as noted in our documentation, without a patch, linked in our documentation. You've ignored our template so I can't say if this is your problem or not. https://rnfirebase.io/#altering-cocoapods-to-use-frameworks

Also note that react-native 0.69 does not work with iOS11. It requires iOS12.4 https://reactnative.dev/blog/2022/06/21/version-069#highlights-of-069

As I have a reproducible demonstration with comments showing how to do it and proving it works, I am reasonably confident this issue will not cause a change to anything in this repository which implies the issue is not actionable so I will close it.

If you can demonstrate to the contrary with a a reproducible example https://stackoverflow.com/help/mcve we can reopen

**Closed by mikehardy** 2022-06-24 16:59 UTC
Labels: Impact: Bug, Help: Needs Triage

**Comment by the900app** [comment] 2022-06-25 20:05
Same issue: 
Pod File; 

`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'the900app' do
  config = use_native_modules!
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseStorage', :modular_headers => true
  pod 'FirebaseStorageInternal', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true

  
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'the900appTests' do
    inherit! :complete
    # Pods for testing
  end


  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end`

**Comment by mikehardy** [comment] 2022-06-25 20:26
Hey there -

I edited your comment so it was readable, that is I put it in triple-backticks with the ruby language specifier

You are missing the static frameworks that I explained in my comment

You have done this, which is not necessary as far as I know, I would remove all of it:
```ruby
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseStorage', :modular_headers => true
  pod 'FirebaseStorageInternal', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true

```

You must include `use_frameworks!` as documented
You must include `$RNFirebaseAsStaticFramework = true` as documented

https://rnfirebase.io/#altering-cocoapods-to-use-frameworks
