### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by Yogiyadavmca** [invertase/react-native-firebase#2947] opened 2019-11-30 15:20 UTC
Build is getting failed with below error:

info: Exec Fabric Run from Pods
/Users/username/Library/Developer/Xcode/DerivedData/proj-aborwdibjxfidpatdmfgwuvpgiia/Build/Intermediates.noindex/proj.build/Debug-iphonesimulator/proj.build/Script-5B12EC83BDE80469ED942876.sh: line 22: /Users/username/Documents/Projects/ReactNative/Project/19: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

Version Details are as follow:
Pod Version - 1.8.4
Xcode Version - 11.1
npm version - 6.9.0
node version - v10.16.1
react-native-cli: 2.0.1
react-native: 0.60.3

Package.json:
    "@react-native-firebase/app": "^6.1.0",
    "@react-native-firebase/crashlytics": "^6.1.0",

[RNFB] Crashlytics Configuration:
set -e

if [[ ${PODS_ROOT} ]]; then
  echo "info: Exec Fabric Run from Pods"
  ${PODS_ROOT}/Fabric/run
else
  echo "info: Exec Fabric Run from framework"
  ${PROJECT_DIR}/Fabric.framework/run
fi

**Comment by mikehardy** [comment] 2019-11-30 16:45
So why doesn't that directory exist? What does the shell script look like? I demonstrate here that crashlytics integration does work https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L54 and the build succeeded for me. Thoughts: maybe some case-sensitive filesystem issue? That pops up on macOS sometimes since case-sensitive filesystems are rare and don't get as much testing. Spaces in the path name? Maybe not handled correctly, unknown.

**Comment by Yogiyadavmca** [comment] 2019-12-01 16:30
If I changed the [RNFB] Crashlytics Configuration then it works fine(See the double quotes) however on next 'pod install' it remove the double quotes around command and it is getting failed again.

updated configuration:

if [[ ${PODS_ROOT} ]]; then
echo "info: Exec Fabric Run from Pods"
**"${PODS_ROOT}/Fabric/run"**
else
echo "info: Exec Fabric Run from framework"
**"${PROJECT_DIR}/Fabric.framework/run"**
fi

**Comment by mikehardy** [comment] 2019-12-01 16:40
That makes me think you have a space in your project name, or some other special character that needs escaping. You didn't fill out the template so I have no idea. Perhaps you could propose a PR here? https://github.com/invertase/react-native-firebase/blob/master/packages/crashlytics/ios_config.sh#L21

**Comment by Yogiyadavmca** [comment] 2019-12-01 16:44
> That makes me think you have a space in your project name, or some other special character that needs escaping. You didn't fill out the template so I have no idea. Perhaps you could propose a PR here? https://github.com/invertase/react-native-firebase/blob/master/packages/crashlytics/ios_config.sh#L21

Project name doesn't have space in it. I am not aware about any template. If you need any file or information please let me know.

**Comment by mikehardy** [comment] 2019-12-01 16:45
The template presented to you when  you first opened the issue. It has all the information needed to actually find problems https://github.com/invertase/react-native-firebase/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

That said, if you've got a fix for your problem, make a PR and you're set - and in the meantime (before the PR is merged and released) you may use the excellent "[patch-package](https://github.com/ds300/patch-package)" module to make your edit and save it in your project so it applies for all colleagues / CI etc

**Closed** 2019-12-07 23:07 UTC

**Comment by bakhtarov** [comment] 2020-05-21 18:31
I had this issue because of that lines:
`
$FirebaseSDKVersion = '6.8.1'
$FabricSDKVersion = '1.6.0'
$CrashlyticsSDKVersion = '3.1.0'
`
https://rnfirebase.io/#ios

**Comment by yoshifumi4423** [comment] 2020-06-11 03:18
@mikehardy 
Thank you. It works!

**Comment by mikehardy** [comment] 2020-06-11 12:32
@yoshifumi4423 glad to hear it! There is one shortcoming in that now you won't be uploading symbols for local builds which means that if you do a local crash test (a reasonable thing to test...) the symbols won't be there. But if you do a release build TestFlight crash test and use fastlane to sync the dSYMs from TestFlight to Crashlytics as I mention in that stackoverflow post, then it works. I have a debug screen that lets me do things like that, and that screen is only allowed for certain users or certain environments (so I can test prod as well...) so in practice this isn't a problem for me but it is a limitation, worth mentioning. Good luck in your project

**Comment by yoshifumi4423** [comment] 2020-06-11 14:51
@mikehardy 
I see. I will use Manual download like you mentioned in StackOverFlow.
> Manual download / upload
The current recommended solutions from the 3rd party crash reporters (both NewRelic and Crashlytics documentation at least) is to either go to the App Store Connect page for the build and download dSYMs then upload, or using XCode's Organizer for the archive hit the "Download Debug Symbols" button, then upload them.


I have another problem that Firebase Crashlytics Console doesn't show any reports, although my app of TestFlight sends error by using `crashlytics().recordError(error);` and 
 `crashlytics().log('test');`

<img width="1162" alt="2020-06-11 23 38 56" src="https://user-images.githubusercontent.com/8575750/84400333-daf92e00-ac3c-11ea-89cb-de853e098ccd.png">

I use newest versions of RNF.
`
    "@react-native-firebase/admob": "7.1.4",
    "@react-native-firebase/analytics": "^7.1.4",
    "@react-native-firebase/app": "^7.2.0",
    "@react-native-firebase/crashlytics": "^7.1.5",
    "@react-native-firebase/firestore": "^7.1.7",
`

If you have any idea, could you give me advice?

Also, I think this is relevant to [this issue's 1st problem](https://github.com/invertase/react-native-firebase/issues/3520#issue-604949760).

**Comment by yoshifumi4423** [comment] 2020-06-13 14:04
I solved [this problem](https://github.com/invertase/react-native-firebase/issues/2947#issuecomment-642710582).

It caused by wrong bundle identifier of Firebase settings, and changing the id correct fixed the bug.

**Comment by ghasemikasra39** [comment] 2020-09-12 14:00
I had the same issue on these versions:
```
    "@react-native-firebase/analytics": "^7.6.2",
    "@react-native-firebase/app": "^8.4.2",
    "@react-native-firebase/auth": "^9.2.2",
    "@react-native-firebase/crashlytics": "^8.4.4",
    "@react-native-firebase/firestore": "^7.8.1",
    "@react-native-firebase/messaging": "^7.8.6",
```

I deleted the run script and the issue is solved. However, when I open the app, it crashes right away without any error in console

**Comment by mikehardy** [comment] 2020-09-12 14:03
@ghasemikasra39 this is a closed issue. Please open a new issue following the issue template, if you can reproduce.
Note that any mention of "crash" should be accompanied by the relevant stack trace (from adb logcat or Xcode console after launching the app from Xcode on a real device). No one else is experiencing this so it will probably need a reproduction posted as a github repo we can clone and run in order to diagnose, since it is likely project specific. You may find constructing a throwaway project to see how it works is instructive, you may base it on https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by amitailanciano** [comment] 2020-10-29 19:45
In my case the Fabric folder in the run script got dropped in favor of FirebaseCrashlytics, [renaming the folder Fabric in the run script to FirebaseCrashlytics](https://firebase.google.com/docs/crashlytics/get-started#initialize-crashlytics)
