### ISSUE TITLE
Firebase does not return value nor throw error using real time db

### ISSUE THREAD

**Issue by abburi03** [invertase/react-native-firebase#1570] opened 2018-10-06 05:19 UTC
Hello, 

I am facing an issue when i reload the app in android simulator. Below code works fine if i open the app/close and open the app. But if i reload (CMD+ M => Reload) in simulator . Below code does not return any thing , it does not even return an error. I am having difficulty because when i change some code its really hard to again compile the app. 

FYI, I am facing this only in android simulator. I have no issue in IOS Simulator.

const query = database().ref('categories/');

    query.once('value', (snapshot) => {
        console.log(snapshot);
        resolve(snapshot.val());
    })
    .catch(error => {
      console.log(error);
      reject(error);
    });

### Environment

1. Application Target Platform:
Android

2. Development Operating System:
macOS Sierra,

3. Build Tools:

4. `React Native` version:
React native version (able to reproduce in both 0.55.2 and 0.56.0

5. `React Native Firebase` Version:
5.0.0

6. `Firebase` Module:
database

7. Are you using `typescript`?
no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Salakar** [comment] 2018-10-07 02:55
Duplicate of #1498

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Closed by Salakar** 2018-10-07 02:55 UTC
