### ISSUE TITLE
setBadge using react-native-firebase 6+

### ISSUE THREAD

**Issue by jcharbo** [invertase/react-native-firebase#3444] opened 2020-04-11 04:25 UTC
Hi, I'm using react-native-firebase 6.4.0 with RN 62.0. When using v5 I was able to call setBadge but I cannot find this method in v6.4.0. Has it been removed?

**Comment by Ehesp** [comment] 2020-04-11 09:34
Duplicate of https://github.com/invertase/react-native-firebase/issues/3419

**Closed by Ehesp** 2020-04-11 09:34 UTC
