### ISSUE TITLE
[🐛][Android] Could not find method firebaseCrashlytics()

### ISSUE THREAD

**Issue by aprilmintacpineda** [invertase/react-native-firebase#4314] opened 2020-09-27 13:18 UTC
## Issue

Describe your issue here

I was setting up react-native-firebase on a bare react-native app and I followed the optional step here https://rnfirebase.io/crashlytics/android-setup#4-optional-enable-crashlytics-ndk-reporting but I got this error when I do `react-native android`

```
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method firebaseCrashlytics() for arguments [build_eb1e26l7v1ub3obnwzg5vs7s$_run_closure1$_closure8$_closure14$_closure15@48eabe2f] on BuildType_Decorated{name=release, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={react_native_dev_server_port=com.android.builder.internal.ClassFieldImpl@99240943, react_native_inspector_proxy_port=com.android.builder.internal.ClassFieldImpl@44d408ec}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2020-09-27 13:22
You're missing all the requested information from the templates. Can you try building a reproducible example starting from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh and posting it?

**Comment by FadiAboMsalam** [comment] 2020-10-08 17:57
I am also facing this issue any fix for this @mikehardy  @aprilmintacpineda

**Comment by mikehardy** [comment] 2020-10-08 18:30
@FadiAboMsalam no, because the original reporter provided insufficient information.

**Closed by mikehardy** 2020-10-08 18:30 UTC
Labels: Help: Needs Triage, Impact: Bug, Resolution: No Template

**Comment by usama-asfar** [comment] 2020-10-20 17:51
skipping [4th setp](https://rnfirebase.io/crashlytics/android-setup#4-optional-enable-crashlytics-ndk-reporting) solves the issue.

**Comment by aprilmintacpineda** [comment] 2020-10-21 06:30
I will try to provide a repo for repro, sorry for being unable to do that, my time is all consumed by work-related tasks :(

**Comment by mikehardy** [comment] 2020-10-21 11:44
@aprilmintacpineda I think there is actually another issue in the list that is a little farther along where someone really wants to get the NDK reporting working and is trying to do a build of react-native locally in order to play with the settings for stripped / unstripped directories. That would really advance the state of the art here. That you will get this error just by configuring NDK crash reporting but not providing the directories is a known thing and is correct behavior, simply reproducing it won't move it forward

**Comment by zhangjianshuai** [comment] 2020-11-29 13:38
@mikehardy i am also facing this issuse, used unity 2017.4.31f1, build with il2cpp and mainTemplate, firebase sdk for unity6.16.1;    
 cannot build success when using  :
` implementation 'com.google.firebase:firebase-crashlytics-ndk:17.2.2'`

`
signingConfigs {
        release {
......
	        // Add this extension
	          firebaseCrashlytics {
	              nativeSymbolUploadEnabled true
	          }
.....
        }
    }`


, could you help me ,and the building errorlog : 
`
* Where:
Build file '/Users/jens/Documents/AMS/DevBranch/Client/Game/Temp/gradleOut/build.gradle' line: 187

* What went wrong:
A problem occurred evaluating root project 'gradleOut'.
> Could not find method firebaseCrashlytics() for arguments
`
or 

`* What went wrong:
A problem occurred evaluating root project 'gradleOut'.
> Failed to apply plugin [id 'com.google.firebase.crashlytics']
   > Could not create plugin of type 'CrashlyticsPlugin'.
      > org/gradle/api/tasks/TaskProvider`

Waiting for your reply, thanking you;;;

**Comment by mikehardy** [comment] 2020-11-29 13:48
There is no way I will be able to help without a minimal reproduction posted on a github URL
My best advice is to *stop* using the native symbol upload feature though

**Comment by dmitryzaytsev** [comment] 2021-01-21 15:11
Same here. Just went through the tutorial and when trying to add NDK it will fail:
    buildTypes {
        release {
           // .... does not work
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
            }
        }
    }
  
  Versions:
  
```
        classpath('com.android.tools.build:gradle:3.6.3')
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
```
```
    "@react-native-firebase/app": "^10.5.0",
    "@react-native-firebase/crashlytics": "^10.5.1",
    "@react-native-firebase/messaging": "^10.5.1",
```

**Comment by bpander** [comment] 2021-03-24 20:56
@aprilmintacpineda @dmitryzaytsev @FadiAboMsalam @zhangjianshuai Not sure if it'll help, but I also ran into this error when I tried enabling NDK reporting. My `apply` lines were at the bottom of my `android/app/build.gradle` file. I moved them to the top of the file and the error went away.

**Comment by leni8ec** [comment] 2021-04-06 22:47
Update gradle wrapper to v5.6.4 (from 5.4.1) - is solved my problem with this issue.

file: **gradle-wrapper.properties**
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip`

My Android Build Gradle tools is **3.5.4**
`com.android.tools.build:gradle:3.5.4`

**Comment by molimat** [comment] 2021-05-10 18:57
> @aprilmintacpineda @dmitryzaytsev @FadiAboMsalam @zhangjianshuai Not sure if it'll help, but I also ran into this error when I tried enabling NDK reporting. My `apply` lines were at the bottom of my `android/app/build.gradle` file. I moved them to the top of the file and the error went away.

this does work.

**Comment by fontesrp** [comment] 2021-11-08 21:20
@bpander 's [answer](https://github.com/invertase/react-native-firebase/issues/4314#issuecomment-806181174) worked for me as well. Thanks!

**Comment by mikehardy** [comment] 2021-11-09 00:05
This had me worried so I just double-checked:

https://rnfirebase.io/crashlytics/android-setup#3-apply-the-firebase-crashlytics-plugin-to-your-app

> Apply the com.google.firebase.crashlytics plugin by adding the following to the top of your android/app/build.gradle file:

This is as documented, so if having it at the top works (and it sounds like it does, the success reports are nice), excellent :-)
