### ISSUE TITLE
firebase.database().ref("path").once("value") don't call callback

### ISSUE THREAD

**Issue by HemrajLodha** [invertase/react-native-firebase#1609] opened 2018-10-17 12:48 UTC
**Issue**
```
const ref = firebase.database().ref('users').child(uid);
            ref.update(user).then(function () {
                Alert.alert("success");
            }).catch(function (error) {
                Alert.alert("error", error);
            });
```
It's updating data in database but not calling callback.

### Environment

1. Application Target Platform:

targetSdkVersion = 26

2. Development Operating System:

Windows 7

3. Build Tools:

Android Studio

4. `React Native` version:

react-native": "^0.57.1"

5. `React Native Firebase` Version:

"react-native-firebase": "^5.0.0"

6. `Firebase` Module:

database

7. Are you using `typescript`?

No

**Comment by Salakar** [comment] 2018-10-18 13:39
Duplicate of https://github.com/invertase/react-native-firebase/issues/1498

**Closed by Salakar** 2018-10-18 13:39 UTC
