### ISSUE TITLE
[🐛] [Auth] Error codes differentiation for language of environment

### ISSUE THREAD

**Issue by oguzhanali** [invertase/react-native-firebase#5164] opened 2021-04-13 15:12 UTC
## Issue

After change android emulator system language to the Turkish for testing, I figure out that auth errors code strings return different according to system language settings in Android. 

For example:
[auth/email-already-in-use] code string in English, 
[auth/emaıl-already-ın-use] code string in Turkish.  

So it creates unstable error handling situation. I checked history and found an already stated issue [#3917](https://github.com/invertase/react-native-firebase/issues/3917), it turns out closed without solution, but problem is active.

I didn't check yet if its a problem for production or for real devices too. If it is, much more annoying situation becomes.

@mikehardy added that Auth module is not open source yet in 'firebase-android-sdk'. Not sure what can be done right now but it needs to be open, especially for who works in and develops for non-English languages. 

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 auth()
      .signInWithEmailAndPassword(email, password)
      .catch((e) => {
        switch (e.code) {
          case "auth/email-already-in-use":
         //This error code returns in English
           console.log(e.code);
            break;
          case "auth/emaıl-already-ın-use":
          //This error code returns in Turkish
           console.log(e.code);
            break;
        }
      });
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `11.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Auth`
- **Are you using `TypeScript`?**
  - `Y` & `4.0.0`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2021-04-14 19:54
This *is* duplicate of #3917, having another issue open does not add value. That issue has all the relevant discussion, it needs to be pursued with firebase-android-sdk

**Closed by mikehardy** 2021-04-14 19:54 UTC
Labels: Help: Needs Triage, Impact: Bug
