### ISSUE TITLE
[🐛] NPM package '@react-native-firebase/messaging' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3

### ISSUE THREAD

**Issue by lorenc-tomasz** [invertase/react-native-firebase#4283] opened 2020-09-19 17:49 UTC
NPM package '@react-native-firebase/messaging' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3

**Comment by mikehardy** [comment] 2020-09-19 23:27
Yes! Sorry about that. Something isn't quite right with the publish from #4275 - I'm not sure what happened.

Please know that it shouldn't be a problem *this time* but yes it should be fixed, that's on me, I'll sort it out when I get a moment but it will likely be a day or three

**Comment by lorenc-tomasz** [comment] 2020-09-20 07:54
@mikehardy Thank you for answer :)) And sorry for that short description.

**Comment by mikehardy** [comment] 2020-09-20 16:21
haha it was nevertheless complete. Still hoping to get this early next week, launching other stuff today

**Comment by sangameshrently** [comment] 2020-09-22 14:21
@mikehardy : is that just warning ? for me ios app is getting crashed on launch.

**Comment by mikehardy** [comment] 2020-09-22 14:39
@sangameshrently This is just a warning. Your crash will be unrelated.

**Comment by cristiankmb** [comment] 2020-09-22 17:42
I have the same problem. When i run **npx react-native run-android** the app run without problems en real device, but when i run **npx react-native run-android --variant=release** to build an android release return build filed with

**Task :app:packageRelease FAILED**
**ReactNativeFirebase WARNING: NPM package '@react-native-firebase/storage' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.**

**Comment by ArrudaWillyan** [comment] 2020-09-22 18:23
> I have the same problem. When i execute **npx react-native run-android** the app run without problems en real device, but when i execute **npx react-native run-android --variant=release** to build an android release return build filed with
> 
> **Task :app:packageRelease FAILED**
> **ReactNativeFirebase WARNING: NPM package '@react-native-firebase/storage' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.**
> 
> @mikehardy Can this apply to the same issue or should be another section?

I have the same problem, does anyone have any solutions?

**Comment by mikehardy** [comment] 2020-09-22 18:33
THIS IS A WARNING. It is not the source of your problem.
If app:packageRelease FAILED you are looking for a FAILURE, an ERROR, not a WARNING

I am SHOUTING because if you are attributing your problems to this you are wasting your previous time while you have a real problem somewhere else, and I know that for me at least when I am troubleshooting - especially a build failure! - I have no time to waste.

Look in other areas for your problem. The peer dependency warning here is not your problem.

**Comment by ArrudaWillyan** [comment] 2020-09-22 18:42
@mikehardy 
I'm not getting a compilation error, I apologize for the mistake. However, my release version is always closed when running the generated apk on a device. During debugging the application runs smoothly, however after following the documentation to generate a signed apk I am unable to run it on devices. The only north I have is this warning that I always receive at the terminal after running gradlew clean or npx react-native run-android --variant = release

**Comment by mikehardy** [comment] 2020-09-22 18:48
@ArrudaWillyan you have a separate problem. It is not related to this thread - you should look through the issues and post a new one if needed

**Comment by lorenc-tomasz** [comment] 2020-09-22 18:59
@ArrudaWillyan @cristiankmb I'm using those versions without issues. Only annoying warning ;) If I were I would lower the packages versions and check what will happen. And then I start looking forward into the issue. Maybe you use custom firebase library versions, etc.

**Comment by mikehardy** [comment] 2020-09-22 19:06
@lorenc-tomasz that's okay - it's got the goal of saving people time (by focusing on the real problem vs this) which is valuable - that was the point of my SHOUTING above as well - I sincerely want people to fix their problems, and one of the important steps in doing so is discarding incorrect ideas. I hope to fix this actual issue soon but it should be apparent by my not having done so yet that it is not a high priority matter

**Comment by daniyal-ahmed-khan** [comment] 2020-09-25 10:40
Did anyone figured out the solution for this ??

**Comment by codecog** [comment] 2020-09-25 12:04
@daniyal-ahmed-khan There's no need for a solution here. It's not an error, as @mikehardy just a misstep in the publishing. You can ignore the warning for now until the next patch release is out.

**Comment by Odinwan** [comment] 2020-09-26 06:34
guys i cant build apk because of this error

**Comment by quyetthang122** [comment] 2020-09-26 13:07
Hi @Odinwan, you can apply this patch - link: [https://github.com/invertase/react-native-firebase/actions/runs/259924803](url), either run update the package, I think they already fix the issue.

**Comment by daniyal-ahmed-khan** [comment] 2020-09-27 06:23
![image](https://user-images.githubusercontent.com/56723631/94357577-765ec380-00b3-11eb-87c4-d06397cad158.png)

Cant build either it just terminates

**Comment by mikehardy** [comment] 2020-09-27 12:37
I will repeat myself for @daniyal-ahmed-khan @quyetthang122 and @Odinwan who are not reading the comments and misdiagnosing their problems:

> THIS IS A WARNING. It is not the source of your problem.
> If app:packageRelease FAILED you are looking for a FAILURE, an ERROR, not a WARNING
> 
> I am SHOUTING because if you are attributing your problems to this you are wasting your precious time while you have a real problem somewhere else, and I know that for me at least when I am troubleshooting - especially a build failure! - I have no time to waste.
> 
> Look in other areas for your problem. The peer dependency warning here is not your problem.

**Comment by cxrod** [comment] 2020-09-28 18:14
@mikehardy The last version on NPM of @react-native-firebase/messaging es 7.8.6, but in GitHub the last release es 7.8.8. The last GitHub version fix the warning? Do you know why is not published on NPM yet?

**Comment by mikehardy** [comment] 2020-09-28 18:48
There was a publishing failure in the last release
The last github version will likely fix the warning

> Do you know why is not published on NPM yet?

Because it's just me keeping the lights on here at the moment and I had a major work feature to deliver in the app I develop for money, hadn't gotten around to diagnosing what the publish failure was yet and didn't want to do a new release until I knew the root cause

Hoping to get to it in the next day or so, as well as reviewing the stack of PRs queued https://github.com/invertase/react-native-firebase/pulls?q=is%3Apr+is%3Aopen+label%3A%22Workflow%3A+Needs+Review%22 and do a release.

And I need to figure out why the patch-package task is failing https://github.com/invertase/react-native-firebase/pull/4306#issuecomment-698998034

Any contribution of effort that distributes the load here would be welcome if you want to review and test PRs etc

I'm not complaining - I enjoy working on the module, just answering your question. Help is always welcome though, sincerely

**Comment by mikehardy** [comment] 2020-09-30 18:07
I believe I've diagnosed the root cause of the publish failure as an inclusion of workflow auto-cancel-of-prior-jobs which is normally a feature you want, but is specifically bad for our publish setup because it runs two workflows and the second was cancelling the first before it finished.

>  lerna http fetch PUT 200 http://registry.npmjs.org/@react-native-firebase%2ffirestore 5016ms
>  Error: The operation was canceled.

The good news? I've got a PR up for that in #4330 and as soon as it's approved I can merge it and release a correctly cross-dependent set of modules.

**Closed** 2020-09-30 18:10 UTC
Labels: Help: Needs Triage, Impact: Bug, Workflow: Needs Review

**Comment by Nehal-29** [comment] 2020-11-09 08:50
@mikehardy facing the same warnings in updated version as well.
I've both dynamic links & messaging added into my project

 NPM package '@react-native-firebase/dynamic-links' depends on '@react-native-firebase/app' v8.4.6 but found v8.4.7, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/messaging' depends on '@react-native-firebase/app' v8.4.7 but found v8.4.6, this might cause build issues or runtime crashes.

which version to keep?

**Comment by mikehardy** [comment] 2020-11-09 14:39
@Nehal-29 I don't reproduce dependency warnings with https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh using current stable versions of all releases. So the "version to keep" should be the highest version of all packages

**Comment by waleedshkt** [comment] 2021-01-30 21:51
Ran into similar versions non-compatibility issue too.
This is simply caused by different versions installed at different points in time. And during that period, newer (DEFAULT) versions got released. 

Solution:  re-install the packages of correct versions

**Comment by MalikNaser** [comment] 2021-05-14 07:46
> Ran into similar versions non-compatibility issue too.
> This is simply caused by different versions installed at different points in time. And during that period, newer (DEFAULT) versions got released.
> 
> **Solution**: re-install the packages with (correct) matching versions

this answer should be on top

**Comment by mikehardy** [comment] 2021-05-14 13:07
https://invertase.io/blog/react-native-firebase-versioning @MalikNaser
