### ISSUE TITLE
Using firestore emulator?

### ISSUE THREAD

**Issue by gilbert** [invertase/react-native-firebase#2953] opened 2019-12-01 15:08 UTC
Is there a way to point firestore to a local emulator in the same way as `functions().useFunctionsEmulator('...')` ?

**Comment by mikehardy** [comment] 2019-12-01 16:08
Unsure. What version you using (you didn't follow template, so no idea)?
What did you see when you checked the relevant doc site for the react-native-firebase version in use? Or the init code (it's trivial to trace through and can show you if there is room to pass in emulator config)

Here's the upstream docs to get a handle on it https://firebase.google.com/docs/emulator-suite/connect_and_prototype

**Comment by gilbert** [comment] 2019-12-01 16:41
Ah sorry, none of the templates were related to a question. I'm using 6.x

I have the emulators running locally. I originally tried looking for a function similar to `useFunctionsEmulator` in the react-native-firebase docs.

This is basically my setup:

```ts
import firestore from '@react-native-firebase/firestore'
const db = firestore()
```

Calling `db.settings` throws an error:

```
Exception 'FIRESTORE INTERNAL ASSERTION FAILED: Firestore instance has already been started and its settings can no longer be changed. you can only set settings before calling any other methods on a Firestore instance.'
```

Your link looks helpful, but I'm not sure where to put the swift code:

```swift
let settings = Firestore.firestore().settings
settings.host = "localhost:8080"
settings.isPersistenceEnabled = false 
settings.isSSLEnabled = false
Firestore.firestore().settings = settings
```

I appreciate your help. I'm new to react native, and I'm sure others will have this question in the future. Thanks.

**Comment by mikehardy** [comment] 2019-12-01 16:57
The template is related to every problem, because it shows what versions are in use and how they are setup. Never ignore a template in a github repo. It also indicates what platform the problem is on. You don't indicate android or ios but if you mention swift, I'll try ios.

This module uses Objective-C not swift, so you'd want to use that version if you're hacking in the native code. But that shouldn't be necessary?

If you are on v6 then it appears the settings are available, have you tried them: https://invertase.io/oss/react-native-firebase/v6/firestore/reference/settings#host or is that what is throwing the error? 

Appears to be wired up: 
https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/lib/index.js#L168
https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/ios/RNFBFirestore/RNFBFirestoreModule.m#L88
https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.m#L74

Maybe you just need to do that setting prior to doing any other thing? Or maybe there is a startup configuration order-of-operations issue in the module where it "starts" firestore before you get control so you can't set it as things are now and the order of operations needs to change

**Comment by gilbert** [comment] 2019-12-01 17:37
> The template is related to every problem, because it shows what versions are in use and how they are setup. Never ignore a template in a github repo.

There is not one template, but [four](https://user-images.githubusercontent.com/17013/69917361-c4feeb00-1419-11ea-8a47-30eeae1a2a21.png). I don't see one for a question. "Documentation Feedback" seemed like the most relevant, since I was asking a question, so I clicked that one. But the template does not ask for that information. Just my feedback in case you want to improve it.

> If you are on v6 then it appears the settings are available, have you tried them:

Right, that is what was throwing the error.

Here is my code:

```ts
import firestore from '@react-native-firebase/firestore'
firestore().settings({
  host: 'https://59f59951.ngrok.io',
  ssl: true,
})
```

(I'm using ngrok to avoid localhost).

I moved this code to the top of the main `index.js` entry file, which stopped the error from happening. However, now it's not hitting the network, and firestore is working offline instead. Rebuilding the app does not help.

If I remove the above code, the app uses production firestore and works fine.

----

On [this page](https://invertase.io/oss/react-native-firebase/v6/app/client#client-initialization) it states:

> The default firebase app instance can not be initialized via JS. After following the iOS & Android installation guides and correctly setting up your google services plist/json files, the default app is automatically initialized and available for use in react-native-firebase.

which sounds like I shouldn't be trying to use `firestore().settings()` at all? This is why I originally asked my question.

**Comment by mikehardy** [comment] 2019-12-01 17:59
Hmm - I should see about adding version information and platform and a link to the documentation under discussion in the template for documentation then, because if you were going to examine documentation feedback, how could you do it without pinning those things down? I'm not sure how, anyway

Interesting that you did see an effect moving it to top of index.js (even if that's pretty brutal) but a shame it did not fully work. Just to get moving I think for iOS you'd want to plop Objective-C config code right here https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.m#L33

@Salakar / @Ehesp this seems like maybe a candidate for firebase.json config mechanism, though that all seems to be static, or some delay on firestore setup such that a settings call first thing would be valid as indicated in underlying SDK https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore.html#setFirestoreSettings(com.google.firebase.firestore.FirebaseFirestoreSettings)

**Comment by Salakar** [comment] 2019-12-30 13:50
> Right, that is what was throwing the error.
> 
> Here is my code:
> 
> ```ts
> import firestore from '@react-native-firebase/firestore'
> firestore().settings({
>   host: 'https://59f59951.ngrok.io',
>   ssl: true,
> })
> ```
> 
> (I'm using ngrok to avoid localhost).
> 
> I moved this code to the top of the main `index.js` entry file, which stopped the error from happening. However, now it's not hitting the network, and firestore is working offline instead. Rebuilding the app does not help.
> 
> If I remove the above code, the app uses production firestore and works fine.

I believe you should be passing the host only, not the fully qualified url, so your host should be like the following (without `https://`):

```ts
import firestore from '@react-native-firebase/firestore'
firestore().settings({
  host: '59f59951.ngrok.io',
  ssl: true,
})
```

Also shouldn't there be a port, e.g. `59f59951.ngrok.io:8080`? Not sure what `ngrok` is/does but the emulator on localhost starts with a port.

----

Also on Android Emulators you can use `10.0.2.2:8080` as the `host` to connect to `localhost` on your emulator host machine, if it's still not working with the above then I'd suggest trying the `10.0.2.2` as the host with ssl as `false` - to confirm its not `ngrok` causing the issue.

**Comment by andresilveirah** [comment] 2019-12-31 17:00
Hi there, I'm facing (I believe) the same issue.
```javascript
//index.js
import firestore from '@react-native-firebase/firestore'
firestore().settings({ host: 'http://localhost:8080', ssl: false })
const { docs } = await firestore().collection('products').get()
console.log(docs)
```
I'm getting results from the remote firestore instead of the emulator. I have tried setting `host` to `localhost:8080` (removing the protocol from it), but no success. 

Am I missing something?

**Comment by Lucas-Geitner** [comment] 2020-01-17 19:42
+1 here ! 

I think Firestore/Firebase - emulator is a big deal and it's really important to handle it !

Thanks a lots if someone find a way to do it or fix it !

**Comment by tad3j** [comment] 2020-01-21 21:42
I'm also having the same problem, using v6.2.0, I can't override firebase host with `firebase.firestore().settings({ host: 'localhost:8080', ssl: true })`.

This is actually all of my code for initializing firebase modules:
```
import firebase from '@react-native-firebase/app';
import firestore from '@react-native-firebase/firestore';

//TODO: why is this not working off of local host?
firebase.firestore().settings({
  host: 'localhost:8080',
  ssl: false,
});

// exports
export default firebase;
export const db = firestore();
```

I've used the debugger to track what's actually going on and `settings()` method of firebase module is called by the code that I've added and I was able to confirm with the debuger that correct settings are returned from line 225: https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/lib/index.js#L225

However, the next line of code debugger hit after line 225 was the line after my setting override (`export default firebase;`)...could it be that settings are just returned there without being applied?

**Comment by mikehardy** [comment] 2020-01-21 21:47
Great information - thanks for posting that @tad3j - perhaps time to ping @Salakar again (sorry man :-) ) - there is something strange going on with the emulator, at least on iOS. I haven't tried firestore emulator but the functions emulator worked for me on Android but not iOS on device (not simulator) during investigation yesterday in #3114 - I was pretty careful to actually start the emulator listening on 0.0.0.0 and there was no firewall and the IP was right as near as I can tell. I was stumped.

**Comment by tad3j** [comment] 2020-01-21 21:53
Forgot to mention that I'm using Android and this works perfect on my WEB app, just having problems with mobile one. 

There my init looks like this:
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/firestore';
import 'firebase/functions';
import config from '../../config/firebaseConfig';

//firebase app init
firebase.initializeApp(config);

// exports
export default firebase;
export const db = firebase.firestore();

//DEV ENV OVERRIDES
if (window.location.hostname === 'localhost') {
    //FUNCTIONS emulator
    firebase.functions().useFunctionsEmulator('http://localhost:5001');

    //FIRESTORE emulator
    db.settings({
        host: "localhost:8080",
        ssl: false
    });
}

**Comment by gilbert** [comment] 2020-01-29 18:45
I got it working. The problem with [my original code](https://github.com/invertase/react-native-firebase/issues/2953#issuecomment-560135227) was the url – **do not** include the `https://` part in your host string!

Also, if you're running on device, localhost is not going to work. Instead, you can use [ngrok](https://ngrok.com) to forward multiple ports by first creating a `~/.ngrok2/ngrok.yml` file like the this:

```yaml
authtoken: xxx
tunnels:
  firestore:
    addr: 8080
    proto: http
    bind-tls: true
  functions:
    addr: 5001
    proto: http
    bind-tls: true
```

and then running `ngrok start --all`

**Comment by mikehardy** [comment] 2020-01-29 18:51
🤦‍♂ so for the emulator, no protocol !?!, but obviously we want it in other cases? I'll try this again myself when I get a chance. Thanks a bunch for circling back

**Comment by gilbert** [comment] 2020-01-29 22:59
Yup. And, for the record, if you use the firebase functions emulator, you **do** put the protocol:

```js
functions().useFunctionsEmulator('https://abc123.ngrok.io') // localhost:5001
```

**Comment by Salakar** [comment] 2020-02-03 12:12
Would be good to have some docs on these if anyone is willing to send a PR?

**Comment by tad3j** [comment] 2020-03-02 22:29
I still can't get RNF to connect to firestore running on localhost....it just ignores [host setting](https://invertase.io/oss/react-native-firebase/v6/firestore/reference/settings#host) (code snippet posted above).

I've also tried to use `FIRESTORE_EMULATOR_HOST` env variable, but looks like this project is not using it (couldn't find mention on repo). Kind of running out of ideas what else to check.

Could anyone confirm this is a bug? Also, I guess this should work without changing native code or adding redirects?

**Comment by mikehardy** [comment] 2020-03-02 23:17
for now I am ignoring it by only using the emulator when I test things on Android, making the bold assumption that if I get the functions right with that dev cycle then iOS is not going to change the result largely

**Comment by tad3j** [comment] 2020-03-02 23:32
> 
> 
> for now I am ignoring it by only using the emulator when I test things on Android, making the bold assumption that if I get the functions right with that dev cycle then iOS is not going to change the result largely

I was referring to firestore DB emulator not functions one...does that work for you on Android? I haven't tried functions yet (need to first get firestore working so I can test), but I would assume that it shouldn't be problematic.

**Comment by mikehardy** [comment] 2020-03-02 23:47
Oh I'm sorry @tad3j - I haven't tested the DB emulator, only functions. For me, on android, the functions emulator is working, if that helps.

**Comment by tad3j** [comment] 2020-03-03 07:48
Would be better if we get both working. :)

I was debugging further today and I've noticed that `firebase.app()` returns an object who's `databaseURL` is the same as from my configuration setting...so I can confirm that setting are not overridden (looks like something is off in [native firebase module](https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreModule.java#L60)).

To test further I've tried to call `firebase.initializeApp()` to override settings, but RNF won't let me since it has been initialized by native module.

I've then started looking into native code (unfortunately don't know how to debug that), but I came across a [suspicions line in the code](https://github.com/invertase/react-native-firebase/blob/8a147b0789d95a79b17b13b46add0ec75c351718/packages/app/android/src/main/java/io/invertase/firebase/common/UniversalFirebasePreferences.java#L80). The if statement checks for `null equality with preferences`, but the preferences variable is never set it seems...it's only initialized with `private SharedPreferences preferences;`. Could this be the issue?

**Comment by Ehesp** [comment] 2020-03-03 08:24
Adding note for documenatation: https://github.com/invertase/react-native-firebase/issues/3217

**Comment by okcompewter** [comment] 2020-03-06 06:55
I think that line of code is causing the same issue for me when trying to override the '**persistence**' setting in my app. I just can't turn it off, no matter what I try:

```
import firestore from '@react-native-firebase/firestore';
// TODO - doesn't seem to be disabling offline persistence
firestore().settings({ persistence: false })

**Comment by mikehardy** [comment] 2020-03-06 11:44
@okcompewter does it work when you alter that line via an edit in node_modules?

**Comment by okcompewter** [comment] 2020-03-07 01:25
I'm not sure how to go about editing it, honestly (I'm quite unfamiliar with java).

**Comment by mikehardy** [comment] 2020-03-07 16:36
literally just go in to that file and hack at it, java syntax is not remarkably different than javascript. You can just convert 

```java
if (whateverTheThingIs == null) {
```
 to 

``` java
if (true) { // (whateverTheThingIs == null) {
```
... to hack out the logic check, then re run your android build - easy-peasy

**Comment by okcompewter** [comment] 2020-03-08 05:47
I think to test out if the app's provided persistence settings are being thrown out for some default settings (what I believe @tad3j said is happening), I had to make this line false, but that gives an error in the app:

```
  private SharedPreferences getPreferences() {
    if (preferences == null && false) {
      preferences = ReactNativeFirebaseApp
        .getApplicationContext()
        .getSharedPreferences(PREFERENCES_FILE, Context.MODE_PRIVATE);
    }
    return preferences;
  }
```

![screenshot](https://user-images.githubusercontent.com/7925720/76157378-f9d7a980-60bc-11ea-94f3-4a8e3b0a5f73.jpg)

If this is a bug, I'm not sure how to remove the default settings smashing any app settings while still providing valid app settings.

**Comment by tad3j** [comment] 2020-03-11 15:40
I've tested today if `settings` task inside [UniversalFirebaseFirestoreModule](https://github.com/invertase/react-native-firebase/blob/10a2cbf306923cfb0f8e2b97247b20ea637ea0f8/packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreModule.java#L47) gets executed by hardcoding `localhost:8080` [here](https://github.com/invertase/react-native-firebase/blob/10a2cbf306923cfb0f8e2b97247b20ea637ea0f8/packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreModule.java#L63) (I've also tried to remove if statement and result is the same).

Even with that `firebase.app()` returns `databaseURL` from my file and not the hardcoded value. This makes me think that task is never executed and [@ReactMethod `settings` ](https://github.com/invertase/react-native-firebase/blob/f55c86931a85afdf38609d8c94ab152a6b1f0d08/packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreModule.java#L71)is never called from js files.

Any idea why react wouldn't call native settings method?

**Comment by egoossens** [comment] 2020-04-03 10:39
Haven't investigated a lot but another approach to testing with the emulators would be to use the apps from the @firebase/testing package through the initializeTestApp method which provides a firebase.app.App. 

The problem is that there is type incompatibility between RNFirebase's FirebaseApp and firebase.app.App. So if I have an API that wraps an RNFirebase app and want to substitute it with a fireabse.app.App for testing, TypeScript complains. A workaround is to type it as ```any```, but that means losing all the benefits of typing.

**Comment by tad3j** [comment] 2020-04-11 20:00
I'm still experiencing this in 6.4.0. 

I was able to get Android Studio debugger working and breakpoint is never hit inside `settings()` method of `ReactNativeFirebaseFirestoreModule.java`, although this module is loaded inside `ReactNativeFirebaseFirestorePackage.java`...breakpoint in constructor is hit (`module = new UniversalFirebaseFirestoreModule(reactContext, SERVICE_NAME);` gets executed).

Beside that, Android Studio is showing that there are no usages, could it be it's just not implemented?
![image](https://user-images.githubusercontent.com/4150904/79053725-a6b6c080-7c3f-11ea-9062-09f1f3f7c1a5.png)

**Comment by tad3j** [comment] 2020-04-12 01:06
I was able to set up Android Studio debugger today and I think I found the cause for this issue. 

It seems like that settings are always locked and therefore they are never overridden inside `UniversalFirebaseFirestoreCommon`. More specifically, the problem is that `settingsLock` always contains key for app `[DEFAULT]`, that's why `setFirestoreSettings()` method always returns on [this line](https://github.com/invertase/react-native-firebase/blob/10a2cbf306923cfb0f8e2b97247b20ea637ea0f8/packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreCommon.java#L45) and `firebaseFirestore.setFirestoreSettings()` at the bottom is never called.

SOLUTION: If I remove this check (`if (settingsLock.containsKey(appName)) return;`), app loads data from my emulated firestore instead of server one (with downside being that settings are set multiple times).

@Ehesp, @Salakar, I've noticed that you two were involved in [this commit](https://github.com/invertase/react-native-firebase/commit/10a2cbf306923cfb0f8e2b97247b20ea637ea0f8)...any idea why `settingsLock` would be populated before `setFirestoreSettings()` is called?

**Comment by tad3j** [comment] 2020-04-28 18:25
I've looked into the new documentation and realized that settings actually returns a **promise** (for the difference, official `firebase-js-sdk` returns **void**), so one has execute that async way (btw, documentation has a syntax problem [here](https://rnfirebase.io/firestore/usage#offline-capabilities), function should be async).

So with that, I've added this code to my index.js file (firebase service where I want to configure it):

```
export const db = firebase.firestore()
;(async () => {
    try {
      await db.settings({
        host: '10.0.2.2:8080',
        ssl: false,
        // persistence: false, // disable offline persistence
      })
      console.log('databaseURL', db.app.options.databaseURL)
    } catch (e) {
      console.log('e', e)
      // Deal with the fact the chain failed
    }
  })()
```

Still with that, `databaseURL` logged to console remains unchanged, so it seems like calling settings() has no effect (data is still loaded from live firestore instead of emulator).

Would there be any chance to remove async requirement for settings() method and keep the API sync with  `firebase-js-sdk` API?

**Comment by gruzinskis** [comment] 2020-06-04 11:09
Hello, I've been trying to setup firestore + cloud function emulator locally to work with a react-native app with react-native-firebase and react-redux-firebase. The cloud functions worked out of the box when using useFunctionsEmulator setter. But with firestore, I had the same problems as you, until today accidentally I made it work. 

Double checked multiple times - what happens is run firestore().settings({...), it never works, **UNTIL you recompile and relaunch the app!** (I ran react-native run-android, but I'm sure Android Studio run would also work). If I put the wrong firestore host in the settings, and refresh the react-native app - it still works with the emulated firestore instance. It starts using the address you set only after a recompile, either way, at this point I don't care why, because I was about to give up the 3rd time!

**Comment by Ehesp** [comment] 2020-06-04 12:20
> Was wondering, would there be any chance to remove async requirement for settings() method and keep the API sync with firebase-js-sdk API?

Unfortunately not, since we have to send the options to native, this needs to be async.

> PS, I also noticed that the settings method returns a promise, but with the steps i just described, it also works without awaiting.

The promise will still be called, just you wont know when it completes.

> it never works, UNTIL you recompile and relaunch the app!

So the way it works is by storing your settings in "local storage", and then when you use Firestore for the first time, it applies those settings. If you have already used Firebase, it will only work when the app is relaunched.  This is because you can only set settings before usage, otherwise an error is thrown.

**Comment by gruzinskis** [comment] 2020-06-04 12:25
> This is because you can only set settings before usage, otherwise an error is thrown.

Shouldn't the firestore().settings() throw the error then? It resolves to null for me.

**Comment by Ehesp** [comment] 2020-06-04 12:29
Yeah it will always resolve - as mentioned above, it will use the settings when the next usage of a clean Firestore instance is created.

**Comment by mikehardy** [comment] 2020-06-04 15:42
That one sounds like a really rough DX - maybe an info or warning message or at least docs indicating app restart is required for last-set settings to be in use

**Comment by sabinayakc** [comment] 2020-06-04 22:59
I have been unable to use the emulator for FireStore in v7.0. I tried setting the host to localhost 8080 in my index.js and also App.tsx of react-native. Any help would be highly appreciated.

**Comment by mikehardy** [comment] 2020-06-04 23:18
@sabinayakc you might like the result of #3690

**Comment by sabinayakc** [comment] 2020-06-05 01:50
In React Native App, where should we initialize the emulator db.settings()? In other words which file?

**Comment by tad3j** [comment] 2020-06-05 15:06
Amazing, this really seem to work. :) Thank you @gruzinskis! 

@Ehesp , thanks for further explanation. I've asked about async since I though we should be calling with await, but works ok without it.

@mikehardy , I think it would be a good idea to add that as a note to docs to save time on user and support side.

@sabinayakc , I think for now on android you should be using `10.0.2.2` instead of `localhost`. I store it in a firebase.js file from where I import different services:
```
import firebase from '@react-native-firebase/app'
import '@react-native-firebase/firestore'
import '@react-native-firebase/auth'
import '@react-native-firebase/messaging'
import '@react-native-firebase/functions'

// exports
export default firebase
export const db = firebase.firestore()
export const auth = firebase.auth()
export const messaging = firebase.messaging()
export const functions = firebase.functions()

//in DEV env use emulators
//TODO: https://github.com/invertase/react-native-firebase/pull/3690/files (only android redirects 10.0.2.2 to localhost)
if (__DEV__) {
  functions.useFunctionsEmulator('http://10.0.2.2:5001')
  db.settings({
    host: '10.0.2.2:8080',
  })
}
```

Thank you very much all!

**Comment by gruzinskis** [comment] 2020-06-05 15:23
@tadj3 

>   I think for now on android you should be using 10.0.2.2

You can always do that, as the emulator uses that to access the host machine network. With #3690 though, you can *also* use localhost. Which means you could skip a platform check as the iOS emulator accesses the host machine with localhost.

**Comment by tad3j** [comment] 2020-06-05 15:35
@gruzinskis, I understand right, but seems like that PR was not released yet, that's why I left a TODO inside the code pointing to it. :) Thanks for heads up!

**Comment by mikehardy** [comment] 2020-06-05 15:42
> @mikehardy , I think it would be a good idea to add that as a note to docs to save time on user and support side.

There's a PR link at the top right of every docs page I think :-)

**Comment by tad3j** [comment] 2020-06-05 15:57
@mikehardy, right, will try to get the wording right once I understand it. :)

However, I think I'm still experiencing an issue that might be related to async settings for firestore...it seems like my first write to DB is timing out. Could it be that with my code async setting request didn't finish yet? If so, any suggestion how to get around?

**Comment by gruzinskis** [comment] 2020-06-05 16:07
@tad3j put the request in the .then() block of settings method, or keep a variable that you set to true in the then() method, so you can start doing the requests when the variable is finally set true

**Comment by tad3j** [comment] 2020-06-05 16:25
@gruzinskis , I hoped I'll be able to keep my firestore settings in the same fashion as I have it in my web project, but since it seems that's not and won't be the case, but I guess the only way for me is to dispatch a new action to my redux store (something like 'initFirebase') and wait for it to complete before dispatching any firestore related actions. 

I'm wondering though if there may be a better way...since this should be only used in debug builds, code to implement emulation seems to be a bit too verbose. If I understand correctly the issue is that firestore is initialized in native code, and JS code loads after that so once can't just set initial settings, one needs to request the change. I wonder if configuring that on gradle level would make more sense (for debug build only)...

**Comment by sabinayakc** [comment] 2020-06-05 22:05
@tad3j I am unable to hit the firestore. I tried your solution but it still doesn't work :/ 
My cloud functions are able to hit the emulator tho. Just not the firestore. I have created docs via UI in firestore emulator and am trying to retrieve it from React Native App.

**Comment by tad3j** [comment] 2020-06-05 22:26
@sabinayakc , make sure you re-compile and re-open your app as @gruzinskis mentions [in this comment](https://github.com/invertase/react-native-firebase/issues/2953#issuecomment-638782065)...JS code works for sure in `"@react-native-firebase/firestore": "^7.1.2",`.

**Comment by Matgsan** [comment] 2020-06-06 15:47
@tad3j where you using typescript or javascript? Because in typescript they ask for other keys on the settings object. 

I am using the latest version and I am unable to use firestore emulator. Following @tad3j example.

**Comment by tad3j** [comment] 2020-06-06 19:33
@Matgsan , I use JavaScript.
That's strange, I never seen that. Is your firestore emulator running on port 8080? Also make sure you re-compile and clear app data after you've changed the setting.

**Comment by gruzinskis** [comment] 2020-06-09 13:32
@Matgsan If you are running on a physical device with a usb cable (not bundler through network) then any localhost's used for connection need to be reverse proxied with ```adb reverse tcp:8080 tcp:8080``` Or whatever port you want to read. If running the android emulator, use 10.0.2.2 to reach local workstation

**Comment by voold** [comment] 2020-06-12 21:21
I have tried putting 10.0.2.2:8080 for the android emulator

```
import functions from '@react-native-firebase/functions';

firestore().settings({
  host: '10.0.0.2:8080',
});

<RoundedButton
              text={t('begin')}
              textColor={GlobalStyle.colors.primary}
              handleOnPress={async () => {
                // setIsLoading(true);

                console.log('set');
               const res = await firestore()
                  .collection('users')
                  .doc('epvPnwg9o72pOv4828oGu')
                  .get();

                console.log(res.data());
              }}
            />
```
And I get the following error: 
```
Error: [firestore/unknown] An unknown error occurred
NativeFirebaseError: [firestore/unknown] An unknown error occurred
```

If I try to add an item `firestore().collection('users').doc('epvPnwg9o72pOv4828oGu').set();` it just blocks and does nothing...

Can someone help?

**Comment by Ehesp** [comment] 2020-06-12 21:32
Try setting the ssl flag to false?

**Comment by voold** [comment] 2020-06-13 10:39
Thanks for your help. No it does the same thing...

**Comment by voold** [comment] 2020-06-15 12:53
Ok I made it work by doing the following:

`firebase emulators:start`
`adb uninstall "[PROJECT]"` (important)
`react-native start`
`react-native run-android`
`firestore().settings({
  persistence: false,
  host: '10.0.2.2:8080',
  ssl: false,
});`

Works on the android emulator

**Comment by voold** [comment] 2020-06-15 13:57
I'm trying with android device but it does not work for me.

I did the same as above, tried with ngrok

`firestore().settings({
  persistence: false,
  host: '6ad3074a9b12.ngrok.io',
  ssl: false,
});`

But I have:

`Error: [firestore/unknown] An unknown error occurred
NativeFirebaseError: [firestore/unknown] An unknown error occurred`

Any suggestions?

**Comment by voold** [comment] 2020-06-15 20:34
Ok if it might interest, my workaround, by using the firestore emulator to the android device by usb cable, was by doing as followed:

firebase.json
`{
  ...
  "emulators": {
    "firestore": {
      "port": 8080,
      "host": "192.168.0.*" (this should be the ip address of your local machine, or you could simply enter: 0.0.0.0)
    }
  }
}
`
Then I did: 

`firestore().settings({
  persistence: false,
 // same ip as in firebase.json
  host: '192.168.0.*:8080',
  ssl: false,
});`

I then did'nt have to do `adb reverse ...` or use `ngrok`

Hope it might help

src: https://stackoverflow.com/questions/58260877/access-firebase-emulator-from-local-network

**Comment by karlmarxlopez** [comment] 2020-07-02 08:49
> Hello, I've been trying to setup firestore + cloud function emulator locally to work with a react-native app with react-native-firebase and react-redux-firebase. The cloud functions worked out of the box when using useFunctionsEmulator setter. But with firestore, I had the same problems as you, until today accidentally I made it work.
> 
> Double checked multiple times - what happens is run firestore().settings({...), it never works, **UNTIL you recompile and relaunch the app!** (I ran react-native run-android, but I'm sure Android Studio run would also work). If I put the wrong firestore host in the settings, and refresh the react-native app - it still works with the emulated firestore instance. It starts using the address you set only after a recompile, either way, at this point I don't care why, because I was about to give up the 3rd time!
> 
> PS, I also noticed that the settings method returns a promise, but with the steps i just described, it also works without awaiting.

I followed this but, my app crashes after adding a document. 

I using the latest react-native-firebase and I am also using `react-redux-firebase`. When I remove the setting(reset it to default), all my sample documents are saved into the production database (Firestore).

**Comment by NanduKkd** [comment] 2020-07-04 12:08
Hi
I am also unable to connect my android app to the local emulator.

Minimal index.js I used to reproduce this:
```
/**
 * @format
 */

import React from 'react';
import {AppRegistry, View, Text, Button} from 'react-native';
import '@react-native-firebase/app';
import firestore from '@react-native-firebase/firestore';

import {name as appName} from './app.json';

const db = firestore();
db.settings({host: 'localhost:8080'}).then(() => {
	console.log('done setting');
});

AppRegistry.registerComponent(appName, () => {
	return function App(){
		return (
			<View style={{flex:1, backgroundColor:'#aaa'}}>
				<Button onPress={async() => {
					console.log(db.app.options.databaseURL);
					const doc = await db.collection('users').doc('some_id').get()
					console.log(doc.data());
				}} title='Hello' />
			</View>
		)
	}
});
```
My device is connected through usb cable. I started firebase emulator, ran `adb reverse tcp:8080 tcp:8080`, uninstalled the app, then ran `react-native run-android`.

I noticed this in adb logcat when I first pressed the button:
```
Firestore: (21.4.3) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: Status{code=UNAVAILABLE, description=null, cause=javax.net.ssl.SSLHandshakeException: Handshake failed
```

I use:
react-native: 0.62.2
react: 16.11.0
@react-native-firebase/app: 7.1.0
@react-native-firebase/firestore: 7.1.0
@react-native-firebase/storage: 7.1.0
@react-native-firebase/messaging: 7.1.0

**Comment by NanduKkd** [comment] 2020-07-05 08:16
@mikehardy

**Comment by NanduKkd** [comment] 2020-07-08 02:38
Somebody please..!

**Comment by Ehesp** [comment] 2020-07-08 06:56
> My device is connected through usb cable.

Try using the IP of your computer instead of localhost?

**Comment by NanduKkd** [comment] 2020-07-08 08:26
> Try using the IP of your computer instead of localhost?
To connect using the IP address the device and the computer should be connected to the same network right?
I tried using IP address in both ways. It failed with errors `host unreachable` when not connected in the same network  and ECONNREFUSED when in the same network.

Then I tried the IP 0.0.0.0 as host address of the emulator instead of localhost. Now when both are connected in the same network, it shows the same old error(`javax.net.ssl.SSLHandshakeException: Handshake failed`).

Anyways, thanks for replying!

**Comment by Ehesp** [comment] 2020-07-08 12:02
Honestly it depends on your network setup - usually localhost works but sometimes it may need an IP which is forwarded. Also, make sure `ssl` is false when using a local host.

**Comment by NanduKkd** [comment] 2020-07-08 12:47
I connected the device and the computer to the same network, used `db.settings({ssl: false, host: '192.168.*.*:8080'})` and set firestore host to `0.0.0.0` in firebase.json. Now it is working! Thank you!

**Comment by dackers86** [comment] 2020-07-13 09:43
Closing as working example has been found.

Please re-open if this does not solve the issue.

**Closed by dackers86** 2020-07-13 09:43 UTC
Labels: Service: Firestore, Type: Docs, Type: Question, Version: >= 6

**Comment by cbdeveloper** [comment] 2024-06-05 05:06
Any newer solution to this in 2024?

What combination of host in `firebase.json` + `db.settings` or `firestore().useEmulator('localhost')` should we use today?
