### ISSUE TITLE
DynamicLinks: After stores, getInitialLink is undefined

### ISSUE THREAD

**Issue by gaultierq** [invertase/react-native-firebase#1311] opened 2018-07-17 16:27 UTC
### Issue
Quick description of my problem :
- click on a short / long dynamic link 
     ✔ redirected to the Appstore / Playstore
- install the app (from xcode / android studio) 
- open the app, and call `getInitialLink`
     ✕ returns `undefined` on ios and android

Additional information :
- `performDiagnosticsWithCompletion` returns no error
- adding `&d=1`to the dynamic link returns no error
- navigating to `/apple-app-site-association` returns all my apps (staging, preprod, prod)
- clicking on the dynamic link when the app is closed open the app or in background and `getInitialLink` returns the correct value

### Environment

1. Application Target Platform: 

Both

2. Development Operating System:

macOS Sierra

3. Build Tools:

xcode 9.2

4. `React Native` version:

0.55.2

5. `React Native Firebase` Version:

4.0.5

6. `Firebase` Module:

Firebase/Messaging
Firebase/DynamicLinks

7. Are you using `typescript`? 

no

---
Loving `react-native-firebase`? Please consider supporting them with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Salakar** [comment] 2018-09-02 02:30
Duplicate of: https://github.com/invertase/react-native-firebase/issues/1084

**Comment by Appkidd** [comment] 2019-10-10 11:21
How is it a duplicate? This is affecting iOS not Android and is absolutely broken. The obvious workaround is to wrap a timeout around onLink as this is called for the initial URL but this is far from ideal.

**Comment by minuhariharan** [comment] 2020-02-15 12:42
We are also facing the same issue : undefined is not a function when we try to invoke dynamicLinks.getInitialLink

**Comment by mikehardy** [comment] 2020-02-15 13:18
@minuhariharan that is not the same issue

This issue is about the dynamic link itself being undefined
You mention a function undefined.
If the first time you attempt to use a function from the native modules on react-native-firebase results in the function being undefined you have not integrated react-native-firebase correctly (so it can't find the native modules...). Totally different problem and you likely need to investigate your integration

**Comment by minuhariharan** [comment] 2020-02-16 06:01
For us also getInitialLink is undefined, this is the error we get when we try to invoke  dynamicLinks()
      .getInitialLink().then(...): undefined is not a function (near '...pLinkUrl(t))}).error(function(t){return...')

**Comment by mikehardy** [comment] 2020-02-16 12:51
@minuhariharan so you have not integrated react-native-firebase properly at all. The native module is not there.

**Comment by minuhariharan** [comment] 2020-02-16 13:57
Thanks @mikehardy will look into it, however the strange thing is this works fine for Development environment and Staging environment and throws this error just for production

**Comment by minuhariharan** [comment] 2020-02-16 15:06
Turns out that the issue was we did not provide a team id and app store id via the Firebase console for the iOS project, once we added that then things started working.

**Comment by minuhariharan** [comment] 2020-02-16 15:28
Turns out we did not have the team id and apple store id specified for the firebase project for the iOS version of the app on the Firebase console, once we added that the undefined error was not reported again.

**Comment by Salakar** [comment] 2020-02-16 18:21
Given this issue has been resurrected from almost 2 years ago, I'm going to go ahead and close it, if this issue is still a problem in the latest React Native Firebase then please open a new issue, v6 is substantially different to when this issue was made.

**Closed by Salakar** 2020-02-16 18:21 UTC
Labels: Resolution: Duplicate, Service: Links, Version: 5.x.x
