### ISSUE TITLE
Uploading Build to App Store Rejected

### ISSUE THREAD

**Issue by hend-elsahli** [invertase/react-native-firebase#7702] opened 2024-03-25 07:34 UTC
Trying to upload a new build to App Store results in the following error:

> Unexpected CFBundleExecutable Key. The bundle at 'Payload/[APP_NAME].app/AccessibilityResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue. (ID: c392cb0f-9cc4-4751-85d5-53ed7c65234b)

I believe it's because of `GoogleService-Info.plist` shouldn't be added to `Copy Bundle Resources`

https://forums.developer.apple.com/forums/thread/80534

**Comment by haozhutw** [comment] 2024-03-27 03:32
According to the link you attached, the root cause is that the target's plist file is added to `Copy Bundle Resources`, not the `GoogleService-Info.plist`, the plist file is named like `YourAppName-Info.plist`.

**Comment by hend-elsahli** [comment] 2024-03-27 10:04
> According to the link you attached, the root cause is that the target's plist file is added to `Copy Bundle Resources`, not the `GoogleService-Info.plist`, the plist file is named like `YourAppName-Info.plist`.

Here's how my `Copy  Bundle Resources` look like:

<img width="406" alt="image" src="https://github.com/invertase/react-native-firebase/assets/32862214/6cb16978-75f5-48f7-8b77-3ef438823012">


- Build in development succeeds without any issues.
- Generating an an ipa (product > archive) also works.
- Trying to upload the generated build to App Store fails with the mentioned error.

I also tried to remove firebase-setup and the issue I mentioned went away and I wan able to upload my build

**Comment by mikehardy** [comment] 2024-04-03 03:25
You have ignored the issue template so I don't have any information to go on, with apologies I'm going to close this

https://stackoverflow.com/help/how-to-ask

...and ideally https://stackoverflow.com/help/minimal-reproducible-example

Deleting templates + not providing sufficient information means no help is possible

**Closed by mikehardy** 2024-04-03 03:25 UTC
Labels: Impact: Bug, Help: Needs Triage

**Comment by GeeGYMR** [comment] 2024-05-13 00:23
Can we re-open this back. This defintly needs a solution as i am also experiencing the same issue

**Comment by Sermanbilotil** [comment] 2024-05-30 10:46
Same issue

**Comment by fransiskasiburian** [comment] 2024-09-26 07:26
same isssue with Xcode 16

**Comment by mikehardy** [comment] 2024-09-26 16:59
I have been working on the Xcode 16 fixes here in react-native-firebase and as a test of my work pre-release I uploaded a build of one of my work apps to App Store without problem

**Comment by nbonatsakis** [comment] 2024-12-27 19:52
Was a fix ever determined for this? Currently running into it on Xcode 16.2.

**Comment by mikehardy** [comment] 2024-12-27 22:34
No reproduction - and Xcode 16.2 has been out long enough I'm certain hundreds of react-native-firebase users have used it to upload new builds. I can't say what's wrong or what to change but I'm not aware of any widescale problem with just the one report and no details about the exact problem or how to reproduce it

**Comment by nbonatsakis** [comment] 2024-12-28 02:07
OK, I can't say for sure yet what might be triggering it in my project, but I will try to narrow it down.

**Comment by amalajeeth** [comment] 2025-03-06 05:34
same issue here
any possible solution

**Comment by mikehardy** [comment] 2025-03-06 12:11
@amalajeeth without a reproduction of the issue, no, there is no solution for you - ignoring comments requesting reproductions and asking for status does not advance an issue

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by hend-elsahli** [comment] 2025-03-07 09:18
I did the following workaround and it worked for me...

(I had to have two  different setups for dev, and production)

1. Remove GoogleService-Info.plist file from `copy bundle resources`, and keep it in the file system.
2. Create custom step in `build phases`, to copy `GoogleService-Info.plist` programatically to `copied bundle resources` ... right before `Copy Bundle Resources` step.

Just a guideline ... I'd create detailed answer with a link to it later on.

**Comment by mikehardy** [comment] 2025-03-07 12:07
What is strange to me, is that there are 500,000 downloads of react-native-firebase *per week*
And that thread linked in the original post was from...2017?
And I myself have personally uploaded my app to Apple App Store with success.

All of which adds up to a huge volume of objective evidence that for years and years most people have no problem with uploads of apps built with react-native-firebase (and GoogleService-Info.plist). Most people upload fine.

Okay, some can't but that doesn't mean that a blanket statement like "you need to change the main way all of this is done, and do it this way" is necessarily correct. There is something more subtle going on here that is only affecting a really small number of users. Something about those user's projects is having a problem.

The question to answer before you can construct a solid guide and suggest things is to figure out why most people have no problem and only some have a problem. What's the difference. Providing guidance based on that understanding of the difference is the thing to do

In the meantime, no one has provided a minimal reproducible example that has this problem. Just statements of "I have this problem" which unfortunately doesn't do any good to understand and solve things
