### ISSUE TITLE
react-native-firebase/messaging - Remote notifications on iOS do not trigger setBackgroundMessageHandler

### ISSUE THREAD

**Issue by harmit001** [invertase/react-native-firebase#6129] opened 2022-03-15 06:46 UTC
- register using var apnsToken: string | null = await messaging().getAPNSToken()
- Exit / Close the app
-send a notification using apnsToken
- Notification is recieved on the ios device
- Remote notifications on iOS do not trigger setBackgroundMessageHandler or onBackgroundEvent

    "@react-native-firebase/app": "^12.0.0",
    "@react-native-firebase/messaging": "^12.1.0",

    messaging()
      .getInitialNotification()
      .then(async (remoteMessage) => {
        console.log("ON Notification ClOSED APP");
      })

also try -> 
messaging().setBackgroundMessageHandler()

not get any background event in app background or quit state.

[https://i.stack.imgur.com/zq7qc.png](url)

**Comment by mikehardy** [comment] 2022-03-15 13:17
Hi there! You deleted our template, so I will close this as not actionable since it does not have the data required to troubleshoot - https://stackoverflow.com/help/how-to-ask

Please use current versions, not old versions (14.5.1+), there is actually an ios token registration bug fix you are missing since you are using old versions

```
"@react-native-firebase/app": "^12.0.0",
"@react-native-firebase/messaging": "^12.1.0",
```

You have not provided actual code (an index.js + App.js) that reproduces the problem (https://stackoverflow.com/help/minimal-reproducible-example) so I can't be sure but carefully notice from the example https://rnfirebase.io/messaging/usage#background--quit-state-messages that you setBackgroundMessageHandler in `index.js`, before you make calls to AppRegistry for your App.js, and it is an async function

**Closed by mikehardy** 2022-03-15 13:17 UTC
Labels: Impact: Bug, Help: Needs Triage
