### ISSUE TITLE
Notification received but onNotificationOpened and getInitialNotification not fired in release mode when notification clicked in notification tray. Android

### ISSUE THREAD

**Issue by Zain995** [invertase/react-native-firebase#1331] opened 2018-07-23 13:51 UTC
Hi everyone,
I am able to receive notification in IOS and android and in IOS  onNotificationOpened and getInitialNotification is triggered when i receive notification from server but on android onNotificationOpened and getInitialNotification is not triggered so i am not able to redirect to another page based on data received in notification. I have searched a lot and looked every issue related to Notifications in react-native-firebase issues but no help.

This is android/app .gradle file dependencies 
dependencies {
    implementation(project(':react-native-firebase')) {
        transitive = false
    }
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
        transitive = true
    }
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-database:16.0.1"
    implementation "com.google.firebase:firebase-analytics:15.0.2"
    implementation "com.google.firebase:firebase-functions:15.0.0"
    implementation "com.google.firebase:firebase-messaging:15.0.2"
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:23.0.1"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-navigation')
}

This is the code i am using to get data from server which is working perfectly on IOS but not on android.

	async componentDidMount(){
	         this.notificationOpenedListener = 
                 firebase.notifications().onNotificationOpened((notificationOpen: NotificationOpen) => {
			// Get the action triggered by the notification being opened
			const action = notificationOpen.action;
			// Get information about the notification that was opened
			const notification: Notification = notificationOpen.notification;
                         console.log(notification);
		});

		const notificationOpen: NotificationOpen = await 
                 firebase.notifications().getInitialNotification();
		if (notificationOpen) {
			// App was opened by a notification
			// Get the action triggered by the notification being opened
			const action = notificationOpen.action;
		        // Get information about the notification that was opened
		       const notification: Notification = notificationOpen.notification;
                        console.log(notification);
		}
	}

1. Application Target Platform:
Android

2. Development Operating System:
macOS Sierra

3. Build Tools:
    compileSdkVersion 25
    buildToolsVersion "25.0.1"
    targetSdkVersion 22

4. `React Native` version:
0.55.4

5. `React Native Firebase` Version:
4.2.0

6. `Firebase` Module:
 Messaging (firebase-messaging:15.0.2)

7. Are you using `typescript`?
No
---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by gbenga504** [comment] 2018-08-08 04:28
+1

**Comment by rheng001** [comment] 2018-08-14 16:34
Same issue here.

**Comment by rheng001** [comment] 2018-08-15 00:54
@esprehn 

Tried adding that, still facing the same issue unfortunately. getInitialNotification returns null

**Comment by stonecold123** [comment] 2018-08-18 08:26
There are a lot of people getting problems with the notification click events. The `onNotificationOpened` is broken on my phone. That suggestion about adding `onNewIntent` method doesn't work.

https://github.com/invertase/react-native-firebase/issues/1230

**Comment by matdehaast** [comment] 2018-08-25 12:57
Having the same issue where on android

**Comment by AkilLis** [comment] 2018-08-27 08:04
@Zain995 just let me know do you append `new RNFirebaseNotificationsPackage()` on MainApplication.java ?

**Comment by cx5168** [comment] 2018-09-07 06:37
same issue, any ideas? @everyboy

**Comment by aaalive** [comment] 2018-09-09 12:13
same issue ((

**Comment by GodWar101** [comment] 2018-09-14 06:37
Same issue on android.

**Comment by Ehesp** [comment] 2018-09-14 07:18
If anyone could help take a look into this one on the native side we'd be more than grateful!

**Comment by krystofbe** [comment] 2018-09-21 07:59
I'd like to help on this issue. How can I help?

**Comment by gbenga504** [comment] 2018-10-09 13:45
You might need to send data only messages from firebase to make this work. You cannot do this with the firebase console. Write a custom api request from post man that sends only data only messages to the android devices

**Comment by diego-caceres** [comment] 2018-10-12 14:59
I'm also experiencing this in Android, but it is rare, because sometimes the `getInitialNotification` return null (when opening the app from a push notification), and other it returns the notification correctly, for the same type of notification. 

Has anyone found a workaround ?

**Comment by guitar9** [comment] 2018-10-14 22:17
Somebody has a solution?

**Comment by Salakar** [comment] 2018-10-23 12:13
Duplicate of #1149 and many others, lets track all `onNotificationOpened` issues in one place please (same platform or not please discuss on #1149).

Thanks

**Closed by Salakar** 2018-10-23 12:13 UTC
Labels: Hacktoberfest, await-maintainer-feedback, help-wanted, notifications, 👉 await-user-feedback

**Comment by thandunaresh** [comment] 2018-11-06 16:11
@Salakar  seems like #1149 is specific to iOS?

**Comment by karlmarxlopez** [comment] 2018-11-07 05:53
> I'm also experiencing this in Android, but it is rare, because sometimes the `getInitialNotification` return null (when opening the app from a push notification), and other it returns the notification correctly, for the same type of notification.
> 

I'm also experiencing the exact issue by @diego-caceres

**Comment by sangupandi** [comment] 2018-11-08 12:43
Any updates on this?

**Comment by ozanmanav** [comment] 2019-01-08 20:09
same, any update ?

**Comment by roadev** [comment] 2019-02-11 16:13
same here :(

**Comment by Edison4mobile** [comment] 2019-02-14 20:28
same here.

**Comment by MBAustin** [comment] 2019-03-01 02:17
Also having this issue -- looks like no one's figured it out? It works fine on iOS

**Comment by ramon90** [comment] 2019-04-11 17:14
Same here :((((((((

**Comment by Kriknu** [comment] 2019-05-07 08:42
Be careful if you're sending "a lot" of data with the notification. I removed images (in base64) from the notifications and the issue of being able to open the app by clicking the notification was solved.

**Comment by MrEdinLaw** [comment] 2019-06-12 14:57
> ```java
>     @Override
>     public void onNewIntent(Intent intent) {
>         setIntent(intent);
>         super.onNewIntent(intent);
>     }
> ```

Gives me an error when building
`MainActivity.java:16: error: cannot find symbol
    public void onNewIntent(Intent intent) {
                            ^
  symbol:   class Intent
  location: class MainActivity
1 error`

**Comment by sellomkantjwa** [comment] 2019-06-14 18:47
@MrEdinLaw Add this at the top of your MainActivity.java
```import android.content.Intent;```

**Comment by uchar** [comment] 2019-06-18 16:59
Same here ...

**Comment by mikehardy** [comment] 2019-06-18 17:12
Closed issue for maybe 6 months, just saying "same" is not useful in the open source world @uchar - either open a new issue with full details in the issue template or look harder at the solutions and related issues

Note that if you are integrating react-native-splash-screen or anything that uses multiple Activities this will happen. For splash-screen specifically I posted code up that fixes it: https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454

If that doesn't fit your case -> new issue, follow template please

**Comment by uchar** [comment] 2019-06-18 18:07
It seems that there was a problem with my AndroidManifest.xml or MainApplication.java .
I copied their contents from this [link ](https://medium.com/@yangnana11/how-to-set-up-firebase-notification-in-react-native-app-android-only-4920eb875eae)and now it's working fine.
