### ISSUE TITLE
onNotification, onMessage and onNotificationOpened does not work in background

### ISSUE THREAD

**Issue by guitar9** [invertase/react-native-firebase#1602] opened 2018-10-15 20:31 UTC
### Issue

I created a repo with my code.
https://github.com/guitar9/RNFirebaseTest/
I only removed google-services.json because of privacy.

I did these steps:
https://rnfirebase.io/docs/v5.x.x/messaging/receiving-messages
https://rnfirebase.io/docs/v5.x.x/messaging/android

When my App is in Background onNotification, onMessage in App.js does not fire. 
When i click on the Notification onNoticationOpened does not fire.
For test i create a Toast when the event is fired.
I send the message through firebase console. 
Can somebody help me?

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

Linux

4. `React Native` version:

0.57.1

5. `React Native Firebase` Version:

5.0.0

6. `Firebase` Module:

messaging, notfication

7. Are you using `typescript`?
no

**Comment by guitar9** [comment] 2018-10-16 12:34
Somebody can help me?

**Comment by guitar9** [comment] 2018-10-18 18:09
Nobody here who can help me?

**Comment by guitar9** [comment] 2018-10-19 08:36
thank you this works. But this is still a bug which should be solved.

**Comment by Salakar** [comment] 2018-10-23 12:12
Duplicate of #1149 and many others, lets track all `onNotificationOpened` opened issues in one place please (same platform or not please discuss on #1149).

Thanks

**Closed by Salakar** 2018-10-23 12:12 UTC
Labels: notifications

**Comment by kevinEsherick** [comment] 2018-12-15 21:35
@guitar9 @nik-amir when you guys say this fixes this, are you saying that onNotification is called when your app is in the background, even if the user does not interact with the notification? This is the functionality I've been looking for, but as far as I can tell, it's not possible given the way notifications are handled in Apple's system. They say in the following link that they do not provide a handler for when a notification is simply delivered in the background and every google/SO search indicates the same thing: 
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SchedulingandHandlingLocalNotifications.html 

If you have evidence to the contrary, please let me know!
