### ISSUE TITLE
Firebase Auth: current user object doesn't have proper 'providerId' with facebook

### ISSUE THREAD

**Issue by Colmea** [invertase/react-native-firebase#99] opened 2017-05-09 14:25 UTC
Hi all,

When I signin with a facebook user, I except the user's object to have *providerId* set to *facebook*, but it's always *firebase*. Furthermore, there's no providerData linked to the user.

I'm pretty sure the registration process is correct since Firebase Auth display the user as a Facebook user (see screenshot below).

![image](https://cloud.githubusercontent.com/assets/974918/25855382/55eaaace-34d3-11e7-95e1-9719b2254944.png)

Here is the code I use to signin with Facebook:

```
<FBLogin
  permissions={['public_profile', 'email', 'user_friends', 'user_birthday', 'user_about_me', 'user_hometown']}
  onLogin={data => {
    const token = data.credentials.token;
    const credential = firestack.auth.FacebookAuthProvider.credential(token);

    firestack.auth().signInWithCredential(credential);
      .then((user) => {
        this.props.updateUser(user.uid, {
          locale: data.profile.locale,
          gender: data.profile.gender,
        });
      ]);
  });
/>
```

I can't see something wrong, but maybe you'll see something.

**Comment by Salakar** [comment] 2017-05-10 15:38
@Colmea see the answer from @puf [here](http://stackoverflow.com/questions/39291878/firebase-auth-get-provider-id), specifically: 

> Since a user can sign into their Firebase Authentication account with multiple providers, the top-level provider ID will now (usually) be `firebase`.

So this is as intended it seems, in terms of the second part,

> But the `currentUser` has a `providerData` property that provides information on the specific providers. Looping over FIRAuth.auth().currentUser.providerData will give you the FIRUserInfo.providerID you're looking for.

`providerData` is only of the few things left on auth that hasn't been implemented, will add this to the priority list and get in in the next couple of days. Once this is you should just be able to loop over the providerData array and find the relevant facebook props you need.

**Comment by Colmea** [comment] 2017-05-10 16:11
OK, thanks for your help !

**Comment by Salakar** [comment] 2017-05-13 02:07
@Colmea closing as provider data is now available on both platforms.

**Closed by Salakar** 2017-05-13 02:07 UTC
Labels: android, auth, ios, js
