### ISSUE TITLE
Application crashing on startup after integrating module (Android)

### ISSUE THREAD

**Issue by ChristianTucker** [invertase/react-native-firebase#47] opened 2017-04-11 17:33 UTC
I'm using `react-native-firebase` just fine in some of my projects, however I'm trying to integrate it into an existing project and I'm having an excessive amount of trouble. I've made sure that all of my gradle files are setup properly, and I've also cross-referenced from my other projects that are using react-native-firebase. 

The application immediately crashes on launch, before it even gets a chance to load. I don't get a Redbox from react-native, the application just crashes to home with "app has stopped working"

Here's the log from logcat

```
--------- beginning of main
--------- beginning of system
--------- beginning of crash
```

Most the time when trying to clean the project I get the following error from gradle

```
Execution failed for task ':app:clean'.
> Unable to delete directory: C:\Programming\demo-app\android\app\build\generated\res\google-services\debug
```

I've converted the app into the most simple app that you can run on react-native, nothing but an empty view, but I still can't seem to get anywhere

```
import { React } from 'react'; 
import { AppRegistry, View } from 'react-native';

AppRegistry.registerComponent('demoapp', () => <View />);
```

I've cleared my node_modules and package cache, I've ran gradlew clean several times, I don't know what to do anymore. 

Here's the full application log

```
04-11 12:31:09.662  5209  5232 E UncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
04-11 12:31:09.662  5209  5232 E UncaughtException:     at android.os.AsyncTask$3.done(AsyncTask.java:325)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.lang.Thread.run(Thread.java:761)
04-11 12:31:09.662  5209  5232 E UncaughtException: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:52)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:711)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:218)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:74)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:151)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:148)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:97)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:950)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:880)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:104)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:218)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:197)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-11 12:31:09.662  5209  5232 E UncaughtException:     ... 3 more
04-11 12:31:09.662  5209  5232 E UncaughtException: Caused by: java.lang.ClassNotFoundException: com.google.android.gms.maps.GoogleMapOptions
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.lang.VMClassLoader.findLoadedClass(Native Method)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-11 12:31:09.662  5209  5232 E UncaughtException:     ... 19 more
04-11 12:31:09.662  5209  5232 E UncaughtException: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/AbstractSafeParcelable;
04-11 12:31:09.662  5209  5232 E UncaughtException:     ... 19 more
04-11 12:31:09.662  5209  5232 E UncaughtException: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.demoapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.demoapp-1/lib/x86, /system/fake-libs, /data/app/com.demoapp-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
04-11 12:31:09.662  5209  5232 E UncaughtException:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
04-11 12:31:09.662  5209  5232 E UncaughtException:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-11 12:31:09.662  5209  5232 E UncaughtException:     ... 19 more
04-11 12:31:09.666  5209  5209 D         : HostConnection::get() New Host Connection established 0x9db5f800, tid 5209
04-11 12:31:09.669  5209  5229 I FA      : Tag Manager is not found and thus will not be used
04-11 12:31:09.676  5209  5209 W unknown:React: Caught exception after cancelling react context init
04-11 12:31:09.676  5209  5209 W unknown:React: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.facebook.react.ReactInstanceManager$Result.get()' on a null object reference
04-11 12:31:09.676  5209  5209 W unknown:React:         at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.onCancelled(ReactInstanceManager.java:247)
04-11 12:31:09.676  5209  5209 W unknown:React:         at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.onCancelled(ReactInstanceManager.java:197)
04-11 12:31:09.676  5209  5209 W unknown:React:         at android.os.AsyncTask.finish(AsyncTask.java:665)
04-11 12:31:09.676  5209  5209 W unknown:React:         at android.os.AsyncTask.-wrap1(AsyncTask.java)
04-11 12:31:09.676  5209  5209 W unknown:React:         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
04-11 12:31:09.676  5209  5209 W unknown:React:         at android.os.Handler.dispatchMessage(Handler.java:102)
04-11 12:31:09.676  5209  5209 W unknown:React:         at android.os.Looper.loop(Looper.java:154)
04-11 12:31:09.676  5209  5209 W unknown:React:         at android.app.ActivityThread.main(ActivityThread.java:6119)
04-11 12:31:09.676  5209  5209 W unknown:React:         at java.lang.reflect.Method.invoke(Native Method)
04-11 12:31:09.676  5209  5209 W unknown:React:         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-11 12:31:09.676  5209  5209 W unknown:React:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-11 12:31:09.711  1326  1536 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
04-11 12:31:09.712  5209  5248 D         : HostConnection::get() New Host Connection established 0xab308e40, tid 5248
04-11 12:31:09.713  5209  5248 I OpenGLRenderer: Initialized EGL, version 1.4
04-11 12:31:09.713  5209  5248 D OpenGLRenderer: Swap behavior 1
04-11 12:31:09.714  5209  5248 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
04-11 12:31:09.714  5209  5248 D OpenGLRenderer: Swap behavior 0
04-11 12:31:09.726  1326  1536 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
04-11 12:31:09.761  1326  1536 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
04-11 12:31:09.859  1599  1620 I ActivityManager: Displayed com.demoapp/.MainActivity: +470ms
04-11 12:31:09.890  5209  5232 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
04-11 12:31:09.890  5209  5232 E AndroidRuntime: Process: com.demoapp, PID: 5209
04-11 12:31:09.890  5209  5232 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:325)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
04-11 12:31:09.890  5209  5232 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:52)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:711)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:218)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:74)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:151)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:148)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:97)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:950)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:880)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:104)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:218)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:197)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:305)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        ... 3 more
04-11 12:31:09.890  5209  5232 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.gms.maps.GoogleMapOptions
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.lang.VMClassLoader.findLoadedClass(Native Method)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        ... 19 more
04-11 12:31:09.890  5209  5232 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/AbstractSafeParcelable;
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        ... 19 more
04-11 12:31:09.890  5209  5232 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.demoapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.demoapp-1/lib/x86, /system/fake-libs, /data/app/com.demoapp-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-11 12:31:09.890  5209  5232 E AndroidRuntime:        ... 19 more
04-11 12:31:09.893  1599  1919 W ActivityManager:   Force finishing activity com.demoapp/.MainActivity
```

I also get this error frequently when trying to build, which requires me to run a gradlew clean

```
:app:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Failed to create folder: C:\Programming\demo-app\android\app\build\generated\res\google-services\debug
```

**Comment by ChristianTucker** [comment] 2017-04-11 17:51
Could this be a potential confliction issue with https://github.com/airbnb/react-native-maps

**Comment by Ehesp** [comment] 2017-04-11 17:55
Whats in your `app/build.gradle`?

I think the problem is around both this lib and `react-native-maps` requiring "com.google.android.gms:play-services-base".

Try adding to the build.gradle something like:

```
compile (project(':react-native-maps')) {
  exclude group: "com.google.android.gms"
}
```

**Comment by ChristianTucker** [comment] 2017-04-11 18:13
@Ehesp  This may be unrelated, but I'm getting this now:

```
Loading dependency graph...
React packager ready.

Loading dependency graph, done.
warning: the transform cache was reset.
error: bundling: UnableToResolveError: Unable to resolve module `./providers/Email` from `C:\Programming\demoapp-app\node_modules\react-native-firebase\lib\modules\auth\index.js`: Directory C:\Programming\demoapp-app\node_modules\react-native-firebase\lib\modules\a
uth\providers\Email doesn't exist
    at Promise.resolve.then (C:/Programming/demoapp-app/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:445:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Bundling `index.android.js`  99.3% (859/862), failed.
```

**Comment by Ehesp** [comment] 2017-04-11 20:44
Out of interest do you have access to a Linux based system to try this on? I have a feeling it's something to do with Windows.

**Comment by Salakar** [comment] 2017-04-16 13:12
@ChristianTucker sounds like permission issues on windows, can you check the contents of `node_modules/react-native-firebase` after you npm install - see if that Email.js file is there for example. Also can you make sure you're running version alpha12 or higher?

**Comment by Salakar** [comment] 2017-05-02 14:20
Assume you have now resolved this as you've made another issue about JS code - which requires your app to be building ;p 

Closing.

**Closed by Salakar** 2017-05-02 14:20 UTC
