### ISSUE TITLE
Firebase Database . off() - virtual method on null object reference

### ISSUE THREAD

**Issue by christoshrousis** [invertase/react-native-firebase#527] opened 2017-10-18 06:16 UTC
### Issue
We recently updated RNFirebase versions, potentially below 3.0.0, and we ran into problems with a .off() call.

We have a line of code that looks like this:
firebaseRef.child('example').off()

and it would drop the following error:

`
10-18 17:13:58.174 6420-6544/com.shojieffect.shoji E/unknown:ReactNative: Exception in native call
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'void io.invertase.firebase.database.RNFirebaseDatabaseReference.removeEventListener(java.lang.String)' on a null object reference
                                                                              at io.invertase.firebase.database.RNFirebaseDatabase.off(RNFirebaseDatabase.java:420)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
                                                                              at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                                              at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                              at android.os.Handler.handleCallback(Handler.java:742)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                              at android.os.Looper.loop(Looper.java:157)
                                                                              at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                              at java.lang.Thread.run(Thread.java:818)
`

Here is the code in your codebase: https://github.com/invertase/react-native-firebase/blob/60a9f879ff2ac7c25651a89f6988818d09a4e326/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabase.java#L419

I was able to fix this locally with a simple nullcheck, but how do I know if it's the library's fault or my fault? 

### Environment
1. Application Target Platform: Android
2. Development Operating System: ubuntu 16
3. Build Tools: 
4. React Native version: 0.48.4
5. RNFirebase Version: 3.0.3
6. Firebase Module: database

**Comment by chrisbianca** [comment] 2017-10-18 07:34
@christoshrousis Thanks for flagging this. It sounds like you're calling `off` on a reference that doesn't currently have a listener, but you're right we should be protecting against this rather than letting the application crash.  I'll add a null check which will be included in the next release.

**Closed by chrisbianca** 2017-10-18 07:34 UTC

**Comment by omer88** [comment] 2017-10-18 08:59
Hi @chrisbianca, we've also encountered this problem in some constellations. I'm trying to figure out what is the root cause of this, and how to reproduce it.

**Comment by Ehesp** [comment] 2017-10-18 10:30
Whats the intended outcome of calling off with no event value?

**Comment by christoshrousis** [comment] 2017-10-18 23:34
Thanks team!

**Comment by ethantran** [comment] 2017-10-30 19:06
It happens with the `.on` for me if I have an error callback for the third arg. `query.on('child_added', this.handleAdd, this.onError)`. Removing third arg so it is ``query.on('child_added', this.handleAdd)` fixed it.
