### ISSUE TITLE
SMS auth flow response of confirm verification code is invalid

### ISSUE THREAD

**Issue by jpudysz** [invertase/react-native-firebase#2543] opened 2019-09-05 09:36 UTC
##  Issue
Hello guys, I'm trying to implement signing with SMS provider and I found response mismatch.
If we try to confirm verification code we will get User object (like described in docs: https://rnfirebase.io/docs/v5.x.x/auth/reference/ConfirmationResult#confirm).
In my POV it's not correct, because it's not a added value and you're not passing more needed data like `isNewUser` flag.

As you can see in official Firebase docs this method should return `UserCredentials` (https://firebase.google.com/docs/reference/js/firebase.auth.ConfirmationResult#confirm)

I checked your native code and it's doable because you're passing only user object without `additionalUserInfo` (see the link to ios code: https://github.com/invertase/react-native-firebase/blob/master/packages/auth/ios/RNFBAuth/RNFBAuthModule.m#L728 and android: https://github.com/invertase/react-native-firebase/blob/master/packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java#L956)

Hope it does make sense to you!

**Comment by mikehardy** [comment] 2019-09-05 16:50
is that the response direct or the value you receive in onAuthChanged? I use the listener / onAuthChanged style and I believe I receive everything intended

**Comment by jpudysz** [comment] 2019-09-05 17:21
This is the direct response from `confirm` method. There is no way to detect if user is new

**Comment by mikehardy** [comment] 2019-09-05 17:23
in the onAuthChanged event handler the user is marked as new if new, as mentioned - I receive everything indicated I should using that method, which is also (I believe) the example code style on rnfirebase.io docs site - I recommend you try it, might work for you

**Comment by jpudysz** [comment] 2019-09-06 07:06
@mikehardy unfortunately it won't work. As per documentation `onAuthChanged` callback is returning User object. User won't contain such information as `isNewUser` - please check the documentation (https://rnfirebase.io/docs/v5.x.x/auth/reference/User and https://firebase.google.com/docs/reference/js/firebase.User). We really need to return `AdditionalUserInfo` for `confirm` method because for now, it breaks the flow and its different for other providers.

**Comment by mikehardy** [comment] 2019-09-06 15:00
I've read the docs, have you console.log'd the actual objects you receive in onAuthChanged? I am hand-waving / uncertain a bit because I haven't tested it just now but I *know* I have received objects with isNewUser set and I use this in my code even

**Comment by jpudysz** [comment] 2019-09-18 09:20
@mikehardy sorry for delayed reply. `onAuthChanged` is returning user object without any additional flag (I console logged it). The problem is not related with `onAuthChange` as its working as expected and since v6 is almost ready and you're still migrating `notifications` please consider fixing the issue explained here and in other issue #2541 .

In short words:
- SMS provider flow is not consistent with other providers
- There is a bug - we can't `signIn` with credentials created with SMS provider described here: #2541 - I found a temporary solution but as I said above it's different than other provider flows


What you may consider to fix, before/in v6:
- add `additionalUserInfo` to confirm repsonse (for SMS provider)
- allow the developer to confirm the SMS code (right now it's confirmed somewhere underneath) and `signIn` manually is causing code to be expired

Thanks in advance!

**Comment by mikehardy** [comment] 2019-09-18 13:51
Okay - I think I understand better now, thanks for the added information.

The misunderstanding on my part might be that I'm using the email sign in flow, and it contains isNewUser when I log it out - I had thought it was like that for all auth providers, and *if I understand correctly* you are saying that for SMS things are different?

If that's the case then this does seem like an area to work on.

Do note that v6 is in the final stretch for a 1.0 release and I don't believe auth will get a second pass before the firebase summit, however, development definitely won't just stop then it might just be a bit before items like this are re-shaped for follow-on releases

**Comment by mikehardy** [comment] 2019-09-18 13:52
(I edited the tightly to conform to my new understanding, but it's possible if I didn't get the understanding correct the title is also incorrect - we can of course fix if that's the case)

**Comment by jpudysz** [comment] 2019-09-18 14:09
Yup, you got it right!

The most important part which is not working (**and I'm talking only about SMS provider, others are working as expected**) and differs from official firebase is that
```
confirm(verificationCode)
```
is returning `User` but it should return `UserCredentials` (see my first post in this thread and link to react native firebase docs and official docs).

The second thing is crucial too, but less important:

I can't `confirm` user and `signInWithCredential` afterward because the user is signed in underneath (by React Native Firebase - I checked it with BrowserStack network debugger). It causes `auth/code-expired` described here: #2541  - and it's not consistent with other providers flow.

If you will have any additional questions, please let me know!
Thanks in advance

**Comment by mikehardy** [comment] 2019-09-18 14:11
Excellent - thanks for confirming that. I'm surprised the different providers behave differently which is why it took me a bit to get over that and get to the understanding :-)

Maybe @Salakar or @Ehesp have context on why the SMS provider is different than the others - they would be the ones that could then move this forward by either providing that context or directing the change so that it conforms.

**Comment by mikehardy** [comment] 2019-11-22 08:18
I don't think this was resolved

**Comment by gwenoleR** [comment] 2020-05-14 09:17
Hi guys, 
Sorry to reopen this issue, but it seems in the current version (v7.0.1) the `confirm(verificationCode)` method still returning a User and not a UserCredentials like the others providers, do you know if something is planned for this issue ?

Thanks in advance ! 🙂

**Comment by chengsokdara** [comment] 2020-05-20 03:29
I am facing this problem too using SignInWithPhoneNumber using auth v7.0.2. Please either return UserCredential in onAuthStateChange or ComfirmationResult.confirm promise. isNewUser is a needed flag to complete a correct signin flow. Thank you.

**Closed** 2020-05-28 21:52 UTC
Labels: Impact: Web Implementation, Service: Authentication, Version: >= 6

**Comment by vamsiabishek** [comment] 2020-06-03 16:16
@chengsokdara i had a similar issue and this worked for me https://github.com/invertase/react-native-firebase/issues/3058#issuecomment-638148907

**Comment by tunm1228** [comment] 2020-06-11 09:10
Hello, I'm using phone auth, and it works on ios, but dont on android. After confirming code I get the error auth/session-expired - ofc I understand that is it mean, but I don't understand why, and how to fix it. Could you help me?

**Comment by vamsiabishek** [comment] 2020-06-11 09:36
For latest

> Hello, I'm using phone auth, and it works on ios, but dont on android. After confirming code I get the error auth/session-expired - ofc I understand that is it mean, but I don't understand why, and how to fix it. Could you help me?

For latest android version, the verification is auto verified as soon as the message is received in your message box. So if you try to verify it again you will see an error as the verification code is expired.
You can try something like this which checks if Auth state is changed when auto verification happens https://github.com/invertase/react-native-firebase/issues/3058#issuecomment-638148907

**Comment by tunm1228** [comment] 2020-06-11 09:47
> For latest
> 
> > Hello, I'm using phone auth, and it works on ios, but dont on android. After confirming code I get the error auth/session-expired - ofc I understand that is it mean, but I don't understand why, and how to fix it. Could you help me?
> 
> For latest android version, the verification is auto verified as soon as the message is received in your message box. So if you try to verify it again you will see an error as the verification code is expired.
> You can try something like this which checks if Auth state is changed when auto verification happens [#3058 (comment)](https://github.com/invertase/react-native-firebase/issues/3058#issuecomment-638148907)

how can it be assigned to the input box?

**Comment by vamsiabishek** [comment] 2020-06-11 09:56
> > For latest
> > > Hello, I'm using phone auth, and it works on ios, but dont on android. After confirming code I get the error auth/session-expired - ofc I understand that is it mean, but I don't understand why, and how to fix it. Could you help me?
> > 
> > 
> > For latest android version, the verification is auto verified as soon as the message is received in your message box. So if you try to verify it again you will see an error as the verification code is expired.
> > You can try something like this which checks if Auth state is changed when auto verification happens [#3058 (comment)](https://github.com/invertase/react-native-firebase/issues/3058#issuecomment-638148907)
> 
> how can it be assigned to the input box?

Input box for the verification Code can be ignored in this case as you will get the Logged in user object inside authStateChanged method

**Comment by tunm1228** [comment] 2020-06-11 09:59
> > > For latest
> > > > Hello, I'm using phone auth, and it works on ios, but dont on android. After confirming code I get the error auth/session-expired - ofc I understand that is it mean, but I don't understand why, and how to fix it. Could you help me?
> > > 
> > > 
> > > For latest android version, the verification is auto verified as soon as the message is received in your message box. So if you try to verify it again you will see an error as the verification code is expired.
> > > You can try something like this which checks if Auth state is changed when auto verification happens [#3058 (comment)](https://github.com/invertase/react-native-firebase/issues/3058#issuecomment-638148907)
> > 
> > 
> > how can it be assigned to the input box?
> 
> Input box for the verification Code can be ignored in this case as you will get the Logged in user object inside authStateChanged method

Please have an example for this part, I do not understand how to solve the problem, it is completely different from iOS?

**Comment by tunm1228** [comment] 2020-06-11 10:22
> > > For latest
> > > > Hello, I'm using phone auth, and it works on ios, but dont on android. After confirming code I get the error auth/session-expired - ofc I understand that is it mean, but I don't understand why, and how to fix it. Could you help me?
> > > 
> > > 
> > > For latest android version, the verification is auto verified as soon as the message is received in your message box. So if you try to verify it again you will see an error as the verification code is expired.
> > > You can try something like this which checks if Auth state is changed when auto verification happens [#3058 (comment)](https://github.com/invertase/react-native-firebase/issues/3058#issuecomment-638148907)
> > 
> > 
> > how can it be assigned to the input box?
> 
> Input box for the verification Code can be ignored in this case as you will get the Logged in user object inside authStateChanged method

How do I know if it's verified automatically so I can process the code in the interface?

**Comment by mikehardy** [comment] 2020-06-11 12:49
@tunm1228 behold, an example: https://rnfirebase.io/auth/usage#listening-to-authentication-state

**Comment by tunm1228** [comment] 2020-06-12 03:44
> @tunm1228 behold, an example: https://rnfirebase.io/auth/usage#listening-to-authentication-state

how can i get the code from the message to put in TextInput?

**Comment by tunm1228** [comment] 2020-06-12 03:46
> @tunm1228 behold, an example: https://rnfirebase.io/auth/usage#listening-to-authentication-state

The above example is only for listening to whether the user exists on the device or not, it does not guide how to get the code back to the user interface.

**Comment by vamsiabishek** [comment] 2020-06-12 03:57
> > @tunm1228 behold, an example: https://rnfirebase.io/auth/usage#listening-to-authentication-state
> 
> The above example is only for listening to whether the user exists on the device or not, it does not guide how to get the code back to the user interface.

Ok you are getting confused:
- in iOS you need text input to enter the verification code which validates the code and gives you the user object.
- same is the case with older versions of android.
- but for new android version when the user enters the phone number and submits, the verification code is received in the message box but after that you don’t have to enter that verification code in the text input. 

Just like when you click on a button you call a onclick method which gets executed Similarly when a verification code is received in your message box the auto verification of the message code happens(you don’t have to enter the code in text input) and an onAuthStateChanged event is triggered(just like onclick on button) which gives you the user object.

**Comment by tunm1228** [comment] 2020-06-12 04:03
> * same is the case with older versions of android

so now I have to check the old android version and the new android version to authenticate OTP, please tell me the version from how much it doesn't need OTP authentication?
I find this problem quite inconvenient for programmers and confusing for android users

**Comment by mikehardy** [comment] 2020-06-12 04:05
Have you...tried it?
Here's the thing, you set up the listener.
Most of the time that works on Android now. Ignore API checking. Just set the listener up. Most of the time it works! You're done for those people.

For all the rest of the people (your listener simply didn't get called, no big deal), you have a text entry box and they enter the code.

It's that easy

**Comment by tunm1228** [comment] 2020-06-12 04:55
Please tell me which android version requires OTP authentication?

**Comment by mikehardy** [comment] 2020-06-12 05:14
Potentially all of them. What if your user sends the OTP to a phone number on another device? They'd still get the code right? It would still be valid right? Any user at any time *might* validate automagically resulting in your listener being called, or might need the code, resulting in your needing to accept OTP entry.

This is all documented and we've helped quite a bit, I will not be responding anymore

**Comment by wincod75** [comment] 2020-07-08 01:35
I'm not sure the OP was answered, I tinkered with this and went this route...

1. Apparently you can not return isNewUser aside from `await firebase.auth().signInAnonymously();` which is not what I needed. I'm trying to control a signin/signup flow, if an account does not exist, I don't want to create it, I need them to be forced out of the signin flow and over to the signup flow if they are new; otherwise this would create many false accounts and result in a very bad UX for my users not to mention the legal ramifications in this instance.

2. You can however retrieve metadata: `const user = firebase.auth().currentUser; console.log('User metadata: ', user.metadata);`

3. Then... `(creationTime === lastSignInTime)` if true, the user does not exist and the signin flow fails. If they are different, the user does exist and I allow them to continue on through the flow and retrieve their account from my db.

4. The only caveat is if the user does not exist... `const user = await firebase.auth().currentUser.delete().then(function() {}` I delete their record immediately, ridding the user entirely. I do this for legal reasons, among others. You can only delete the user after they have confirmed their code because this is when it's created (this is really the only reason why I had to delete them if they were in fact a new user).

In closing... it seems weird that you can't retrieve isNewUser from `signInWithPhoneNumber ` or that there are no built in error codes when confirming the SMS code, while there are several built into `signInWithEmailAndPassword `. Maybe I missed them, but I couldn't find anything from the Google FB docs either. This solution currently works for me, I hope this helps someone!
