### ISSUE TITLE
[🐛] TypeError: this._firestore.native.documentGet is not a function. (In 'this._firestore.native.documentGet(this.path, options)

### ISSUE THREAD

**Issue by ReijiTBK** [invertase/react-native-firebase#4929] opened 2021-02-19 01:58 UTC
## Issue
I've been trying to get firestore collection and document using @react-native-firebase/firestore however I keep getting a promise rejection
version inside package.json
"@react-native-firebase/firestore": "^10.8.0",

`TypeError: this._firestore.native.documentGet is not a function. (In 'this._firestore.native.documentGet(this.path, options)', 'this._firestore.native.documentGet' is undefined)
`
The code that i used is this
`
import firestore from '@react-native-firebase/firestore';

let fireBaseVersionRecord = await firestore().collection(collection).doc(doc).get();
`
both collection name and doc name are valid 

This is only occurring on iOS, it works well on my android build.
i've verified, during pod install, Firestore has been included.

Really hope to get some help here.
Thank you

**Comment by mikehardy** [comment] 2021-02-19 02:40
I'm going to close this but not with malice! I/we really need you to fill in the issue template as you open a new issue. We need that information to troubleshoot. You can skip the android parts since this is ios-specific but do not skip the whole template, or I'll have to close the new issue as well.

Ideally, you can create an App.js file that does nothing but reproduce this error (you can create the data in the App.js then attempt to access it, showing the failure) so that we can drop it in to a clean project (like from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh) to see what is going on.

Before even doing that I'd triple-check the build though, e.g. `npx react-native-clean-project`. Our firestore APIs do not have any problems that I'm aware of right now so this is going to be some sort of project-specific API usage problem I think

**Closed by mikehardy** 2021-02-19 02:40 UTC
Labels: Help: Needs Triage, Impact: Bug

**Comment by ReijiTBK** [comment] 2021-02-19 03:01
Sorry a bout that... i try to update as much information as possible
