### ISSUE TITLE
[Android] v6 messaging().setBackgroundMessageHandler not working if app gets killed

### ISSUE THREAD

**Issue by federicomiralles** [invertase/react-native-firebase#3244] opened 2020-02-26 21:08 UTC
## Issue

"react": "16.9.0",
"react-native": "0.61.5"
"@react-native-firebase/app": "^6.3.4",
"@react-native-firebase/messaging": "^6.3.4",

In Android if the app gets killed messaging().setBackgroundMessageHandler is not invoked.
So as of v6 notifications functionality is not available anymore I was planning to use react-native-firebase (only the messaging module) to get silent pushes and then using other lib to trigger a local notification to mimic react-native-firebase previous versions behaviour.
Btw I according to the doc messaging().setBackgroundMessageHandler is only available for Android. 
How can I use react-native-firebase for getting notifications on iOS when the app is closed.

Thanks in advance.

Federico

---

### Javascript
```
import messaging from '@react-native-firebase/messaging';

export const firebasePushSetup = async () => {
  await messaging().registerForRemoteNotifications();

  const token = await messaging().getToken();
  console.log('TOKEN =', token);

  const granted = await messaging().requestPermission();
  console.log('GRANTED =', granted);

  messaging().setBackgroundMessageHandler(async remoteMessage => {
    console.log('Message handled in the background!', remoteMessage);
  });

  const unsubscribe = messaging().onMessage(async remoteMessage => {
    console.log('FCM Message Data:', remoteMessage.data);
  });

  return unsubscribe;
};

```
<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Ehesp** [comment] 2020-02-26 21:45
Could you show some code usage please?

**Comment by federicomiralles** [comment] 2020-02-27 02:07
Hi @Ehesp! 
I code added under javascript title.
Btw I call the above code from a useEffect hook after the App module has been mounted.
Both messaging().onMessage() and messaging().setBackgroundMessageHandler() work as expected when the app is in foreground and in background respectively. As soon as I kill the app messaging().setBackgroundMessageHandler() stop responding.
As you can see the code aforementioned is based on the official doc (https://invertase.io/oss/react-native-firebase/v6/messaging/quick-start). 
Am I missing something (like some service in the AndroidManifest.xml, although https://invertase.io/oss/react-native-firebase/v6/messaging/android does not says anything about it).

Cheers,

Federico

**Comment by Ehesp** [comment] 2020-02-27 09:56
The `setBackgroundMessageHandler` handler has to be created outside of your UI code. E.g:

```js
// index.js

messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
});

function App() {
  useEffect(() => {
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      console.log('FCM Message Data:', remoteMessage.data);
    });

    return unsubscribe;
  }, []);

  // etc...
}

export default App;
```

**Comment by federicomiralles** [comment] 2020-02-27 13:05
@Ehesp thanks for your quick answer. Unfortunately I did what you suggested but it does not work either. See the code below:

```
index.js

import messaging from '@react-native-firebase/messaging';
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
});

AppRegistry.registerComponent(appName, () => App);
```
I'm still able to get onMessage() and setBackgroundMessageHandler() when the app is in foreground and in background but no when it's killed.

Cheers,

Federico

**Comment by Salakar** [comment] 2020-02-27 13:27
If you're killing your app via 'force stop' in the android apps UI then this is working as expected, force stopping an app there stops the app and all its running services.

Can you clarify what you mean by 'killed'

**Comment by federicomiralles** [comment] 2020-02-27 13:54
@Salakar indeed that's what I'm doing...
If that's the case then what's the option for the user to receive pushes if the app is closed (neither foreground nor background)?

**Comment by Salakar** [comment] 2020-02-27 15:57
App closed is not the same as app killed - if you swipe away your app from recents that is effectively closing the app - background messages will still continue to work after that. 

Killing the app via force stop is not something the average user does on android to close an app, its a last resort thing.

**Comment by federicomiralles** [comment] 2020-02-27 18:01
@Salakar I'm sorry that I wasn't clear enough... With closing/killing the app I meant swiping the app off in the recent screen as you mentioned...
Once I do that the app stops receiving messages through **messaging().setBackgroundMessageHandler()**.

Cheers,

Federico

**Comment by Ehesp** [comment] 2020-02-27 19:27
What are you doing in the handler? If you're expecting to see a console log in your terminal it won't show there (its an isolated environment when running in the background). It may show in Android Studio Logcat though.

**Comment by federicomiralles** [comment] 2020-02-27 22:26
@Ehesp thanks for your comment! After reading your latest message I checked logcat and I found the cause of the error:
`E/RNFirebaseMsgService: Background messages only work if the message priority is set to 'high'`
So I included the priority set to high along with the data sent to FCM:
**"priority": "high"**
And I got it working!
Thank you very much for your help!
Btw the documentation provided is great but a working example will be highly appreciated by the users. 
If you want I can submit a PR including a sample for them to use as a base for starting implementing the messaging module...

Cheers,

Federico

**Comment by Ehesp** [comment] 2020-03-02 17:35
Awesome, yeah we're working through the docs at the moment (see https://github.com/invertase/react-native-firebase/issues/3217). I'll make sure this gets added :)

**Comment by Kailash23** [comment] 2020-03-13 11:28
@federicomiralles  What do you mean by checking logcat? Is that JS stack trace or the native android stack trace. And How to check logcat, is there any command for that?

**Comment by federicomiralles** [comment] 2020-03-13 11:48
@Kailash23 it's native Android tool for checking native logs.
The command is **adb logcat** provided you have the Android SDK envs set properly.
Check more details at https://developer.android.com/studio/command-line/logcat

**Comment by Ehesp** [comment] 2020-03-13 14:31
@federicomiralles could you confirm where exactly you put the `priority` key? Was it in the `data` property:

```
{
  tokens: [...],
  data: {
    priority: 'high',
  }
}
```

**Comment by Ehesp** [comment] 2020-03-13 14:40
Got it, in the `android` key: https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidConfig#priority

"Notification" messages are sent with a "high" priority by default, whereas data only are sent with "default".

**Comment by federicomiralles** [comment] 2020-03-13 14:47
@Ehesp it worked for me using this endpoint https://fcm.googleapis.com/fcm/send along with the following payload: 
```
{
    "to": "cjUyGxLa3pU...",
    "data": {
        "title": "Some title",
        "body": "Some text"
    },
    "priority": "high"
}
```

**Comment by Ehesp** [comment] 2020-03-13 14:50
Makes sense, thanks. Looks like the different API implementations are setup differently.

**Comment by nastarfan** [comment] 2020-03-15 14:30
Thanks for the posts, everything works except that I got `Invariant Violation: Module AppRegistry is not a registered callable module (calling startHeadlessTask)` error message in my logcat somehow. That happens after I swipe off my app and sending the data. Do I miss anything? I've set the `priority` to high which helps me removing `E/RNFirebaseMsgService: Background messages only work if the message priority is set to 'high'` error message.

**Comment by nastarfan** [comment] 2020-03-16 03:57
I solved my problem, for those who use react native navigation make sure to call `setBackgroundMessageHandler` outside of `Navigation.events().registerAppLaunchedListener`

**Comment by NweThazin** [comment] 2020-03-16 09:12
@nastarfan 
setBackgroundMessageHandler is not triggered even i put outside of Navigation.events().registerAppLaunchedListener. 


messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
});

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setDefaultOptions({ ..... })

**Comment by Ehesp** [comment] 2020-03-16 16:23
FYI I have documented this on the new docs setup, see #3217

**Closed by Ehesp** 2020-03-16 16:23 UTC
Labels: Service: Messaging, Version: >= 6

**Comment by nastarfan** [comment] 2020-03-17 02:55
@NweThazin what errors are you having?
Make sure you send **data only** message since that will not handle notification message with data payload. Also you need to set the `priority` key to `high`.

as of what @Ehesp pointed out, you can find more info on [here](https://rnfb-docs.netlify.com/messaging/usage#foreground-messages) (still WIP)

**Comment by marqroldan** [comment] 2020-03-18 11:14
Hello everyone, I'd like to ask if this is a weird or expected behavior: I'm not seeing my `setBackgroundMessageHandler` handler running but I can see that my app seems to start in Logcat everytime I send a notif.

I'm sending the notification using postman with this body `{
 "to" : "",
 "data" : {
     "body" : "Body of Your Notification in Data",
     "title": "Title of Your Notification in Title",
     "key_1" : "Value for key_1",
     "key_2" : "Value for key_2"
 },
 "priority": "high"
}
`

I closed the app by swiping, and I'm currently idling my phone for 10 minutes just to see if there's any effect.

**Comment by Ehesp** [comment] 2020-03-18 12:45
When you say "I'm not seeing my setBackgroundMessageHandler handler running", how are you checking whether it's running? It executes the code inside of its own task, so it wont act like a conventional log and show in the debugger.

**Comment by marqroldan** [comment] 2020-03-18 14:20
I'm actually just expecting to see the console log message on the Logcat, I didn't check for errors but I noticed that these services for `zo0r/react-native-push-notification` in my Manifest seem to be disrupting the background handler; without them the handler runs:


        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_launcher" />
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                    android:value="Now Serving by SeriousMD"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                    android:value="Now Serving by SeriousMD"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@android:color/white"/>
        <receiver
                android:name="com.google.android.gms.gcm.GcmReceiver"
                android:exported="true"
                android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        <service
                android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
                android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        <service
                android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
                android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

**Comment by marqroldan** [comment] 2020-03-18 14:24
I'm actually just expecting to see the console log message on the Logcat, I didn't check for errors and there don't seem to be any but I noticed that these services for zo0r/react-native-push-notification in my Manifest seem to be disrupting the background handler; without them the handler runs:

I am not knowledgable with native coding so I have no idea how to fix this


        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_launcher" />
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                    android:value=""/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                    android:value=""/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@android:color/white"/>
        <receiver
                android:name="com.google.android.gms.gcm.GcmReceiver"
                android:exported="true"
                android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        <service
                android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
                android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        <service
                android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
                android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

**Comment by thanhtuyenpkk** [comment] 2020-03-30 07:42
@federicomiralles Where you call function firebasePushSetup.
I read document but not know how to call messaging().onMessage

**Comment by Luckygirlllll** [comment] 2020-11-05 11:35
Any updates about this issue? I have the same problem but with IOS, haven't tested Android yet. `setBackgroundMessageHandler` is never triggered, I'm trying to get console.log message in the debugger and it never shows up.

**Comment by mikehardy** [comment] 2020-11-08 17:54
There are no react-native-firebase problems right now with messaging on android or iOS that I know of, that do not either have a known workaround (#4299) or are simply an issue with operating system app lifecycle management making it impossible to open the app, so there are no updates that I know of

**Comment by vimalswaroopj** [comment] 2020-11-21 16:42
> @Ehesp it worked for me using this endpoint https://fcm.googleapis.com/fcm/send along with the following payload:
> 
> ```
> {
>     "to": "cjUyGxLa3pU...",
>     "data": {
>         "title": "Some title",
>         "body": "Some text"
>     },
>     "priority": "high"
> }
> ```

I am getting this error: No task registered for key ReactNativeFirebaseMessagingHeadlessTask

**Comment by vimalswaroopj** [comment] 2020-11-21 16:44
> ## Issue
> "react": "16.9.0",
> "react-native": "0.61.5"
> "@react-native-firebase/app": "^6.3.4",
> "@react-native-firebase/messaging": "^6.3.4",
> 
> In Android if the app gets killed messaging().setBackgroundMessageHandler is not invoked.
> So as of v6 notifications functionality is not available anymore I was planning to use react-native-firebase (only the messaging module) to get silent pushes and then using other lib to trigger a local notification to mimic react-native-firebase previous versions behaviour.
> Btw I according to the doc messaging().setBackgroundMessageHandler is only available for Android.
> How can I use react-native-firebase for getting notifications on iOS when the app is closed.
> 
> Thanks in advance.
> 
> Federico
> 
> ## Project Files
> ### Javascript
> ```
> import messaging from '@react-native-firebase/messaging';
> 
> export const firebasePushSetup = async () => {
>   await messaging().registerForRemoteNotifications();
> 
>   const token = await messaging().getToken();
>   console.log('TOKEN =', token);
> 
>   const granted = await messaging().requestPermission();
>   console.log('GRANTED =', granted);
> 
>   messaging().setBackgroundMessageHandler(async remoteMessage => {
>     console.log('Message handled in the background!', remoteMessage);
>   });
> 
>   const unsubscribe = messaging().onMessage(async remoteMessage => {
>     console.log('FCM Message Data:', remoteMessage.data);
>   });
> 
>   return unsubscribe;
> };
> ```
> 
> Click To Expand

I am getting this error: No task registered for key ReactNativeFirebaseMessagingHeadlessTask
I used priority too

**Comment by vimalswaroopj** [comment] 2020-11-23 06:15
> > @Ehesp it worked for me using this endpoint https://fcm.googleapis.com/fcm/send along with the following payload:
> > ```
> > {
> >     "to": "cjUyGxLa3pU...",
> >     "data": {
> >         "title": "Some title",
> >         "body": "Some text"
> >     },
> >     "priority": "high"
> > }
> > ```
> 
> I am getting this error: No task registered for key ReactNativeFirebaseMessagingHeadlessTask
> I used priority too

**Comment by vimalswaroopj** [comment] 2020-11-23 06:15
> > ## Issue
> > "react": "16.9.0",
> > "react-native": "0.61.5"
> > "@react-native-firebase/app": "^6.3.4",
> > "@react-native-firebase/messaging": "^6.3.4",
> > In Android if the app gets killed messaging().setBackgroundMessageHandler is not invoked.
> > So as of v6 notifications functionality is not available anymore I was planning to use react-native-firebase (only the messaging module) to get silent pushes and then using other lib to trigger a local notification to mimic react-native-firebase previous versions behaviour.
> > Btw I according to the doc messaging().setBackgroundMessageHandler is only available for Android.
> > How can I use react-native-firebase for getting notifications on iOS when the app is closed.
> > Thanks in advance.
> > Federico
> > ## Project Files
> > ### Javascript
> > ```
> > import messaging from '@react-native-firebase/messaging';
> > 
> > export const firebasePushSetup = async () => {
> >   await messaging().registerForRemoteNotifications();
> > 
> >   const token = await messaging().getToken();
> >   console.log('TOKEN =', token);
> > 
> >   const granted = await messaging().requestPermission();
> >   console.log('GRANTED =', granted);
> > 
> >   messaging().setBackgroundMessageHandler(async remoteMessage => {
> >     console.log('Message handled in the background!', remoteMessage);
> >   });
> > 
> >   const unsubscribe = messaging().onMessage(async remoteMessage => {
> >     console.log('FCM Message Data:', remoteMessage.data);
> >   });
> > 
> >   return unsubscribe;
> > };
> > ```
> > 
> > 
> > Click To Expand
> 
> I am getting this error: No task registered for key ReactNativeFirebaseMessagingHeadlessTask
> I used priority too

Solved!!!
I just added the code :
messaging().setBackgroundMessageHandler() outside the Navigation.events().registerAppLaunchedListener()

**Comment by iocuydi** [comment] 2021-01-03 05:20
My code looks like this, copied from the docs: 

`// index.js
import { AppRegistry } from 'react-native';
import messaging from '@react-native-firebase/messaging';
import App from './App';

// Register background handler
messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
});

AppRegistry.registerComponent('app', () => App);`

I get "Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)" when I add the messaging() call here. The app works fine without the messaging call, but cannot receive notfications when app is killed.  Everything works fine on iOS.

I do use react navigation, but don't use "Navigation.events().registerAppLaunchedListener()" anywhere.

anyone experienced this behavior?

**Comment by ShravanMeena** [comment] 2022-01-10 12:33
> @Ehesp it worked for me using this endpoint https://fcm.googleapis.com/fcm/send along with the following payload:
> 
> ```
> {
>     "to": "cjUyGxLa3pU...",
>     "data": {
>         "title": "Some title",
>         "body": "Some text"
>     },
>     "priority": "high"
> }
> ```

Not Working

**Comment by thapli9A** [comment] 2022-02-24 12:44
> @Ehesp it worked for me using this endpoint https://fcm.googleapis.com/fcm/send along with the following payload:
> 
> ```
> {
>     "to": "cjUyGxLa3pU...",
>     "data": {
>         "title": "Some title",
>         "body": "Some text"
>     },
>     "priority": "high"
> }
> ```

You just saved my life bro

**Comment by nguyensondev** [comment] 2022-04-20 15:33
> here

same here! can anyone help me?

**Comment by Shahzaib114** [comment] 2022-12-22 11:53
> My code looks like this, copied from the docs:
> 
> ```
> import { AppRegistry } from 'react-native';
> import messaging from '@react-native-firebase/messaging';
> import App from './App';
> 
> // Register background handler
> messaging().setBackgroundMessageHandler(async remoteMessage => {
>   console.log('Message handled in the background!', remoteMessage);
> });
> 
> AppRegistry.registerComponent('app', () => App);
> ```
> 
> I get "Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)" when I add the messaging() call here. The app works fine without the messaging call, but cannot receive notfications when app is killed. Everything works fine on iOS.
> 
> I do use react navigation, but don't use "Navigation.events().registerAppLaunchedListener()" anywhere.
> 
> anyone experienced this behavior?



Add this in index.js

const bgMessaging = async (messages) => {
  console.log("BgMessaging", messages);
  return Promise.resolve();
};

AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);

**Comment by hgndgn** [comment] 2023-01-05 11:19
```
import { AppRegistry } from 'react-native';
import messaging from '@react-native-firebase/messaging';
import App from './App';

// Register background handler
messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
});

AppRegistry.registerComponent('app', () => App);
```

This way my code is also working. But how can I start the closed app? 
On iOS it is started "headless", but on Android nothing happens.

**Comment by mikehardy** [comment] 2023-01-05 12:38
@hgndgn your app will be cold-started / booted on receipt of an FCM that the operating system considers important enough to spend the power on. Usually that means setting the FCM options for android to high priority. Note that Android manages power by only allowing a certain number of high priority messages per day and some vendors apply non-standard power settings. `adb logcat` will be your friend while testing, and you should read the Android Developer documentation on power management and messaging.

**Comment by hgndgn** [comment] 2023-01-05 13:04
@mikehardy What do you actually mean with cold-started, because I cannot see any logs in the "useEffect" hook?

**Comment by mikehardy** [comment] 2023-01-05 13:14
@rlemasquerier I mean starting the app for the first time, booting it from being fully exited. I believe it is a relatively standard term though not formally defined https://search.brave.com/search?q=what+is+an+android+cold+start

**Comment by hgndgn** [comment] 2023-01-05 16:12
@mikehardy So as I understand, it is the starting of the app without showing it on the UI, so it is running in the background? But if this is so, then why is my "useEffect" hook not beeing called, where I initialize all the stuff?

**Comment by mikehardy** [comment] 2023-01-05 16:44
No components mount when the app is booted that way. That is, in a traditional react-native app where you have index.js and an App.js (with root App component), things in index.js run when app is cold-started headless, but nothing in App will. If no components mount, no useEffect hook will fire, right?

**Comment by cw-sanjeev** [comment] 2023-04-02 22:28
Hi @mikehardy , just had a query.
For notifications to get delivered or to say, create, we need to set priority "high" in the payload.
But Google has this mechanism wherein it analyses 7 days notification interaction, and if it finds that the app has not received that many interactions as a high priority notification should received for whatever reason, the priority for future notifications will be resulted to back to default.
My concern is that, if this happens, will the users stop receiving notifications?
As currently we have native implementation and we are migrating towards react-native, this is a huge concern for us.
Thanks for your help in advance

**Comment by mikehardy** [comment] 2023-04-02 22:42
In both ecosystems (iOS and Android) your apps users need to interact with the notifications or yes, the system will assume they are low value and perhaps stop delivering them to prevent user irritation

Most users consider this a feature but as a developer it may be frustrating.

**Comment by kaladivo** [comment] 2023-06-06 12:57
Hey,
in app I am coding we have background message that does not display any notification but just performs a background task.

The issue I am facing is that sometimes the background task won't run and just fails with:

```
Background messages only work if the message priority is set to 'high'
android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=[package name]/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) }: app is in background uid UidRecord{b7ce228 u0a150 RCVR bg:+1m48s662ms idle change:uncached procs:0 seq(0,0,0)}
```

I understand one workaround is to set the priority of the notification to `high` but that if there is no notification displayed while processing the message, the notification might get throttled by Google. 

When message fails with the error above, it is never run. Meaning the message is lost. I don't care if the device processes the notification with some delay, but it seems weird to me, that any background notification needs to have priority set to `high` to get processed at all. What is the point of `medium` priority messages than?

I was looking around and found this [thread](https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten). Is it possible that react native firebase is starting the background task wrongly so it gets filtered on more recent android versions?

**Comment by eakarpov** [comment] 2025-08-12 17:06
Is there any news about this [comment](https://github.com/invertase/react-native-firebase/issues/3244#issuecomment-1578718659)?
Handler is receiving every notification event with a non-high priority, but throws an error on that printed in logcat (Background messages only work if the message priority is set to 'high')
