### ISSUE TITLE
[🐛] RNFB build script using firebase.json from different project

### ISSUE THREAD

**Issue by ronaldtb** [invertase/react-native-firebase#5255] opened 2021-05-03 11:03 UTC
## Issue

I have the following directory structure for my React Native apps:

- /Users/[username]/Projects/[project-1]
- /Users/[username]/Projects/[project-2]

The `RNFB build script` uses the firebase.json file from project-1 in project-2.

```
info: -> RNFB build script started
info: 1) Locating firebase.json file:
info:      (1 of 2) Searching in '/Users/[username]/Projects/[project-2]' for a firebase.json file.
info:      (2 of 2) Searching in '/Users/[username]/Projects' for a firebase.json file.
info:      firebase.json found at /Users/[username]/Projects/[project-1]/firebase.json
```

This can be fixed by changing `_SEARCH_RESULT=$(find "$_CURRENT_SEARCH_DIR" -maxdepth 2 -name ${_JSON_FILE_NAME} -print | head -n 1)` to `_SEARCH_RESULT=$(find "$_CURRENT_SEARCH_DIR" -maxdepth 1 -name ${_JSON_FILE_NAME} -print | head -n 1)` or by adding a firebase.json to the current project.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [X] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `11.4.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2021-05-03 13:03
Hi there! This is a duplicate of #3902 

There is discussion there already, and it's an opportunity to contribute if you want - I work with anyone that proposes PRs, to get them in shape for merge+release

**Closed by mikehardy** 2021-05-03 13:03 UTC
Labels: Help: Needs Triage, Impact: Bug
