### ISSUE TITLE
Firestore is causing UI Thread Blocking on Android

### ISSUE THREAD

**Issue by joaom182** [invertase/react-native-firebase#1345] opened 2018-07-26 05:08 UTC
### Issue

I'm trying to simple save my data with firestore, calling `firestore.doc('path_doc').set(docPayload, {merge: false})`, and this process has taking 5 ~ 7 seconds and is freezing the UI thread.
I don't have snapshots collection listener on the project, that may causes the UI freeze.

### Environment

1. Application Target Platform:
Android

2. Development Operating System:
macOS High Sierra

3. Build Tools:
Android Studio

4. `React Native` version:
0.52.0

5. `React Native Firebase` Version:
3.2.0

6. `Firebase` Module:
Firestore

7. Are you using `typescript`?
No

**Comment by Salakar** [comment] 2018-07-26 14:10
Closing as duplicate of https://github.com/invertase/react-native-firebase/issues/1223.

**Closed by Salakar** 2018-07-26 14:10 UTC
Labels: duplicate
