### ISSUE TITLE
Firebase Remote Config

### ISSUE THREAD

**Issue by IvanStack** [invertase/react-native-firebase#3259] opened 2020-03-01 05:57 UTC
After integrate Firebase Remote config (6.3.4), I'm getting Program type already present: io.invertase.firebase.config.BuildConfig.

**Comment by mikehardy** [comment] 2020-03-01 18:39
I tried to reproduce this and can't so I suspect some sort of local caching thing that `npx react-native-clean-project clean-projecct-auto` would take care of

Here is the line I add remote config for RNFBv6: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L66

later you can see I assemble a release version for android and run the debug version, it runs for me no problem on macOS at least. You can clone that repo and run make-demo-v6.sh and see if it runs for you to confirm it's project-specific vs in the module

closing provisionally as you did not provide template details and I can't reproduce

**Closed by mikehardy** 2020-03-01 18:39 UTC
