### ISSUE TITLE
App crash due to banner component ad displayed on 32-bit iOS devices 

### ISSUE THREAD

**Issue by hackable** [invertase/react-native-firebase#437] opened 2017-09-22 17:43 UTC
admob fails on 32-bit ios devices

``
 (void)sendEvent:(NSString *)type payload:(NSDictionary *_Nullable)payload {
    self.onBannerEvent(@{
            @"type": type,
            @"payload": payload != nil ? payload : [NSNull null],
    });
}
``

### Environment

1. Application Target Platform: 
iOS

2. Development Operating System: 
macOS Sierra

3. Build Tools: 
XCode

4. React Native version: 
0.48.2

5. RNFirebase Version: 
2.2.2

6. Firebase Module: 
admob

**Comment by chrisbianca** [comment] 2017-09-23 15:25
@hackable Is there an error at all? I believe that Apple have dropped support for 32 bit completely as of iOS 11

**Comment by hackable** [comment] 2017-09-23 17:04
The app crashes on iphone 5c devices running on ios 10

**Comment by chrisbianca** [comment] 2017-09-24 10:43
@hackable In which case, can you please include the stack trace from the native logs at the point it crashes?  Without this it's very difficult for us to try and diagnose the problem.

**Comment by hackable** [comment] 2017-09-24 10:47
The app crashes on iphone 5c with EXC_BAD_ACCESS ( code=1 address=0xc)  when onSize event is send using sendEvent

**Comment by Ehesp** [comment] 2017-09-24 10:49
@chrisbianca when I first tried to implement it on ios I was getting that error from the event emitter when the implementation didn't use the "Manager".

**Comment by hackable** [comment] 2017-09-24 10:59
Could it be an issue due to how floats are handled in 32-bit and 64-bit systems

**Comment by chrisbianca** [comment] 2017-09-24 11:02
@hackable Yes, that's more than likely. Either @Ehesp or I will pick this up over the next few days and see what we can figure out.  If you're able to diagnose and fix yourself, a PR would be most welcome

**Comment by hackable** [comment] 2017-09-24 11:14
I would definitely love to contribute if i am able to get a fix would push a PR

**Comment by Ehesp** [comment] 2017-09-24 11:16
If the issue is the float conversion, it'll most likely be happening on the stringToAdSize method within the RNFirebaseAdMob.m file

**Comment by hackable** [comment] 2017-09-25 07:50
In 64-bit devices its returning value of height as 0xb000000000000325 where as in 32-bit devices its returning as float (50)

**Comment by ikonduktor** [comment] 2017-10-09 16:13
Have the same issure. On iphone 4s debugger returns EXC_BAD_ACCESS (code=1, address=0xc).
The app is also crashes on iphone 5 ipad 2. All 32 bit devices.

**Comment by GH974** [comment] 2017-11-02 12:13
have you found a solution?

**Comment by chrisbianca** [comment] 2017-11-02 13:11
@GH974 I'm not going to lie, this isn't high on our priority list as 32 bit support has been dropped by Apple themselves, so it's hard for us to prioritise this over other outstanding issues given that there are going to be fewer and fewer devices that suffer from this problem.

To give some context, the last 32 bit iPhone device was the iPhone 5/5c which is now over 5 years old

**Comment by mustivar** [comment] 2017-12-15 08:35
I checked this one a bit to publish a non-crashing app but temporarily found a way to stop processing requestAd if the device is 32bit. I created a patch for myself but it is a quick solution and not something neat.
```
- (void)requestAd {
    #ifndef __LP64__
        return; // prevent crash on 32bit
    #endif
```

Maybe will you add something more clever to the code to prevent crashes?
Thanks.

**Comment by wasedaigo** [comment] 2018-06-29 21:22
@mustivar I sent a PR with your change. It got merged:) thank you.

**Comment by Salakar** [comment] 2018-07-01 12:44
Thanks for reporting this issue. We're aware that AdMob has fallen behind on React Native Firebase and would like to bring it up to speed again. I will close this issue for now and track it as well as other issues collectively over on the `AdMob overhaul proposal` to be addressed in a future release. See #1259

**Closed by Salakar** 2018-07-01 12:44 UTC
Labels: admob
