### ISSUE TITLE
[🐛] get and setToken not working 

### ISSUE THREAD

**Issue by lalit-tsa** [invertase/react-native-firebase#5299] opened 2021-05-12 14:57 UTC
messaging().getToken()
got crashes while running app

**Comment by raaidkh-tsa** [comment] 2021-05-12 15:00
Same issue

**Comment by gonzalormonja** [comment] 2021-05-12 16:45
Same issue, log message ->

2021-05-12 13:43:40.039 22249-22422/com.id_profesional E/AndroidRuntime: FATAL EXCEPTION: pool-13-thread-1
    Process: com.id_profesional, PID: 22249
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
        at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingModule.lambda$getToken$2(ReactNativeFirebaseMessagingModule.java:116)
        at io.invertase.firebase.messaging.-$$Lambda$ReactNativeFirebaseMessagingModule$Vj2oWQrpOl3AM5fw0hvH-cnu3p8.call(Unknown Source:4)
        at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/com.id_profesional-lks4pPe5P6KG0t40reJNAg==/base.apk"],nativeLibraryDirectories=[/data/app/com.id_profesional-lks4pPe5P6KG0t40reJNAg==/lib/x86, /data/app/com.id_profesional-lks4pPe5P6KG0t40reJNAg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingModule.lambda$getToken$2(ReactNativeFirebaseMessagingModule.java:116) 
        at io.invertase.firebase.messaging.-$$Lambda$ReactNativeFirebaseMessagingModule$Vj2oWQrpOl3AM5fw0hvH-cnu3p8.call(Unknown Source:4) 
        at com.google.android.gms.tasks.zzv.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by mikehardy** [comment] 2021-05-12 16:51
same root cause as / duplicate of #5293

**Closed by mikehardy** 2021-05-12 16:51 UTC
Labels: Help: Needs Triage, Impact: Bug

**Comment by mikehardy** [comment] 2021-05-12 16:52
also duped #5296 please please please please please (get the idea?) search repos before opening issues
