### ISSUE TITLE
[TypeError: _firestore is not a function. (In '_firestore()', '_firestore' is undefined)]

### ISSUE THREAD

**Issue by sscots** [invertase/react-native-firebase#6197] opened 2022-04-12 18:51 UTC
My app had been working fine until one day I just ran "npm run android" and this error started showing up whenever it tried to access firestore(). Not sure what had changed to start causing this error.
However, I do not get this error in ios and it seems to work fine.

@react-native-firebase/firestore: ^12.1.0
I even upgraded to 12.9.3 and got same error

```
try {
    const firestore = firestore();
} catch(err) {
    console.log(err);
}
firestore.collection(collection)
.doc(id)
.get()
.then((res)=>{return res.data()});
```
Initially I just had "firestore().collection..." but it was crashing the app without throwing an error so I dug until I added the exception handler and finally got the error that's in this thread title.

**Comment by mikehardy** [comment] 2022-04-12 20:47
Hi there! We're actually on version 14.7.x right now, so you are still not up to date, that said, you basically ignored the template completely which does not help troubleshoot.
I can't say what your problem is but in general since there every individual project finds it's own unique way to break, what I do instead is provide a generic "build it from scratch" script that shows the exact + current integration steps from `npx react-native init....` through having firebase working. Somewhere in the diff between what that script does and how your project is setup will be the problem - https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

If you can take that and make an example that fails (https://stackoverflow.com/help/minimal-reproducible-example) then open a new issue with the details needed to help (https://stackoverflow.com/help/how-to-ask) then we can check it out. In the meantime with apologies I'm going to close this as not actionable

**Closed by mikehardy** 2022-04-12 20:47 UTC
Labels: Impact: Bug, Help: Needs Triage
