### ISSUE TITLE
FAILED_PRECONDITION when using where and orderBy together 

### ISSUE THREAD

**Issue by mackenziemance** [invertase/react-native-firebase#515] opened 2017-10-15 22:11 UTC
When querying a collection with .where().orderBy() I get the FAILED_PRECONDITION error code. I've tried orderBy before where and querying different collections all instances produce this err for me. Both methods work on there own. Can someone reproduce ?

Dev Tools output 

    Error: Firestore: Operation was rejected because the system is not in a state required for the operation`s execution. (firestore/failed-precondition).
    at createErrorFromErrorData (NativeModules.js:117)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:354)
    at MessageQueue.js:129
    at MessageQueue.__guard (MessageQueue.js:269)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:128)
    at debuggerWorker.js:72

Environment

macOS: High Sierra
Xcode: 9.0
react-native: 0.48.4
react-native-firebase: 3.0.3

**Comment by mackenziemance** [comment] 2017-10-16 03:28
Misread the docs, sorry for the non-issue.

**Comment by mackenziemance** [comment] 2017-10-16 03:40
btw I'm using the equality operator and getting the error

<img width="800" alt="screen shot 2017-10-15 at 11 34 04 pm" src="https://user-images.githubusercontent.com/24738013/31594200-8ab1775a-b201-11e7-8115-5cfba2edad39.png">

**Comment by chrisbianca** [comment] 2017-10-16 08:16
@mackenziemance Can you add the snippet of code that you're running?  Please include the `.where` and `.orderBy` conditions,

**Comment by mackenziemance** [comment] 2017-10-16 19:19
initialEvents() {
       firebase.firestore().collection('events').where('ended', '==', false).orderBy('sp', 'desc').get()
       .then(this.getEvents)
       .catch((err)=> console.log(err));
    }

**Comment by chrisbianca** [comment] 2017-10-17 08:11
@mackenziemance Have you tried the same query on Android to see what it does? I think this is a Firestore issue rather than an RNFirebase issue as we're just passing back the error we receive.

**Comment by mackenziemance** [comment] 2017-10-17 08:42
No but I will. I figured that was probably the case, just thought I’d see if anyone else experienced this issue

**Comment by mikesurowiec** [comment] 2017-10-17 15:23
@mackenziemance I was also running into issues with `orderBy()` on iOS; as far as I could tell adding `orderBy('createdAt', 'desc')` to my query prevented the `onSnapshot` handler from being called when new data was present. the `where()` condition didn't seem to affect my particular case

**Comment by urajat** [comment] 2017-10-23 06:33
@mackenziemance I had the same problem on Android. When I did `adb logcat`, it showed that there was an index missing for this particular query - it even gave me the Firestore URL to use to create that index. Might be the same case here too.

**Comment by rtman** [comment] 2017-10-23 11:11
Hey I'm getting the same thing on Android:

```
		this.inventoriesRef = firebase.firestore().collection('inventories');
		this.inventoriesRef
			.where(`tags.${tag}`, '==', true)
			.orderBy('itemNameKey')
			.get()
			.then((querySnapshot) => {
})

Is there any update on this?

**Comment by chrisbianca** [comment] 2017-10-23 11:29
@rtman Have you followed @urajat's suggestion? As explained above, this looks to be an underlying issue with the Firebase SDKs and not an RNFirebase issue as we're merely returning the error that the SDK gives us...

**Comment by rtman** [comment] 2017-10-23 12:07
Oops, didn't try that yet, will do

**Comment by rtman** [comment] 2017-10-24 15:03
@chrisbianca 
I see the url in logcat, it is requesting I make an composite index for this. I can confirm it works after creating the index!

**Comment by chrisbianca** [comment] 2017-10-24 15:58
Ok great. I'm going to close this as it's definitely a firebase SDK issue rather than RNFirebase.

**Closed by chrisbianca** 2017-10-24 15:58 UTC

**Comment by agersoncgps** [comment] 2017-11-26 19:24
I am getting this error in the chrome console for iOS, but it does not print a URL to create the proper index.

**Comment by brunoro** [comment] 2017-12-06 11:24
@agersoncgps the URL won't show up on `react-native log-android`, as it has the `RNFSCollectionReference` tag instead of the `ReactNativeJS` one. Run `adb logcat` and you should get the full error.

The line you're looking for should look like this: `RNFSCollectionReference: com.google.firebase.firestore.FirebaseFirestoreException: FAILED_PRECONDITION: The query requires an index. You can create it here: <url>`

**Comment by ntomallen** [comment] 2018-08-06 21:59
Is there a particular reason that the URL doesn't get passed to the error message on the js side?

**Comment by tiendn** [comment] 2018-10-03 08:47
I have tried the command `adb logcat -s RNFSCollectionReference`, but it didn't work.
<img width="329" alt="screen shot 2018-10-03 at 3 46 54 pm" src="https://user-images.githubusercontent.com/15717476/46400056-a58c0580-c723-11e8-92b7-6c772af056fe.png">

**Comment by cmmartin** [comment] 2019-03-25 19:26
It would be awesome if there was a way to get these errors (which include the index creation url) into the javascript console. Currently, you have to view them in XCode for iOS or using `adb logcat` for Android

**Comment by luco** [comment] 2019-04-26 20:57
@cmmartin Same here

**Comment by ardalahmet** [comment] 2019-05-14 14:05
In Xcode, click Target->Edit Scheme.
Under `Arguments` tab there's `Environment Variables`. Uncheck `OS_ACTIVITY_MODE` entry if there's any. Now you can see all system logs in Xcode logs pane. Search for `The query requires an index`, you will find the error message and the index creation link as well.

**Comment by tkow** [comment] 2019-06-24 13:57
```
this.inventoriesRef = firebase.firestore().collection('inventories');
		this.inventoriesRef
			.where(`tags.${tag}`, '==', true)
			.orderBy('itemNameKey')
			.get()
			.then((querySnapshot) => {
})
```
I found this query needs indexes each tags, but according to https://firebase.google.com/docs/firestore/query-data/index-overview?hl=en#index_limitations, the compound index limit is 200. So, if we have these keys are id, it cannot be used ordered records.Curiously, js-sdk can read with startAfter inputed to last documentReference, but react-native-firebase@5.x.x cannot. Is there any solution for this?

**Comment by leron8** [comment] 2019-08-09 23:48
For android users, you can use this command to view the url to create the composed index, since that's the error being presented when you try to use a where and order by in the same query:

adb logcat | grep -F "`adb shell ps | grep com.yitto.yittocontenidos  | tr -s [:space:] ' ' | cut -d' ' -f2`"

**Comment by technoplato** [comment] 2019-08-29 14:54
@ardalahmet I tried that and still the Firebase Index Creation URL is still not showing in the XCode log. I am currently trying Project Clean + Installing on a different simulator. Will see if there's any luck. 

Any other ideas though? What version of react-native-firebase do you have?

**Comment by leron8** [comment] 2019-08-29 15:00
@technoplato , have you tried adding catch blocks in your query's promise result and debug via react-native debugger? I'm thinking that it should also give you the create index link.

**Comment by technoplato** [comment] 2019-08-29 15:36
@leron8 Good suggestion. I didn't do that, but I did fix the error by creating an Index for my collectionGroup query. This article helped a ton: https://firebase.googleblog.com/2019/06/understanding-collection-group-queries.html

**Comment by phatmann** [comment] 2019-09-11 00:02
@tkow There is a solution for queries that fail when `startAt` is used: instead of passing in a document snapshot to  `startAt`, use a field property instead. Per the docs both should work, but they don't.

**Comment by Ehesp** [comment] 2019-09-11 07:25
@phatmann which version are you using? v6 has loads of fixes for Firestore queries, passing a document ref in was one.

**Comment by phatmann** [comment] 2019-09-11 16:34
@Ehesp I am using v6. This same query worked fine with v5.

**Comment by alyuid** [comment] 2019-09-17 09:35
I reached the auto-index-creator link by react-native log-android and the link was similar to this:
`FAILED_PRECONDITION: The query requires an index. You can create it here: https://console.firebase.google.com/project/YOURAPPID/database/firestore/indexes?create_composite=INDEXID`
I couldn't create an index automatically because the link redirected me to an empty firebase console. My solution was **not to use CTRL + RightClick**, but **copy and paste** the link into my browser.

In addition, if you will create index for map fields create like this:
```
myMap: {//suppose that this is your field
myElement
}
```
create index as: myMap.`myElement` (i mean use ` )

**Comment by yash1511** [comment] 2019-11-08 20:46
> For android users, you can use this command to view the url to create the composed index, since that's the error being presented when you try to use a where and order by in the same query:
> 
> adb logcat | grep -F "`adb shell ps | grep [your.package.name] | tr -s [:space:] ' ' | cut -d' ' -f2`"

What should I replace '[:space:]' with ??

**Comment by mikehardy** [comment] 2019-11-08 20:55
@yash1511 if I am not mistaken that is a 'tr' command expression syntax way of saying literally "a space character", you don't need to replace it http://www.softpanorama.org/Tools/tr.shtml

**Comment by yash1511** [comment] 2019-11-08 20:57
> @yash1511 if I am not mistaken that is a 'tr' command expression syntax way of saying literally "a space character", you don't need to replace it http://www.softpanorama.org/Tools/tr.shtml

Okay, thank you!

**Comment by yash1511** [comment] 2019-11-09 06:05
I am not getting a link in my logs, I ran both ```adb logcat``` and also ```react-native run -android```

**Comment by leron8** [comment] 2019-11-15 16:39
@yash1511  have you tried this?:
[https://github.com/invertase/react-native-firebase/issues/515#issuecomment-526225788](url)

The code would be something like this:
(on the query's object promise)
`.catch((error)=>{
                        reject(error);
                    });`

and also use the query's error callback:
`,(error)=>{
            console.log(error);
            reject(error);
        }`

**Comment by FitFingers** [comment] 2019-11-18 15:00
> @mackenziemance I had the same problem on Android. When I did `adb logcat`, it showed that there was an index missing for this particular query - it even gave me the Firestore URL to use to create that index. Might be the same case here too.

I had the exact same issue and this fixed it. I didn't get any error but I found it in adb logcat. Thanks!

**Comment by yash1511** [comment] 2019-11-18 17:11
> @yash1511 have you tried this?:
> [https://github.com/invertase/react-native-firebase/issues/515#issuecomment-526225788](url)
> 
> The code would be something like this:
> (on the query's object promise)
> `.catch((error)=>{ reject(error); });`
> 
> and also use the query's error callback:
> `,(error)=>{ console.log(error); reject(error); }`

Thanks, I fixed it

**Comment by suhaillilac** [comment] 2021-08-12 07:08
> ReactNativeJS

08-12 12:36:32.040 13843 15800 W Firestore: 

`adb logcat -s Firestore `

worked for me, Thanks
