### ISSUE TITLE
Notifications SDK missing in v6?

### ISSUE THREAD

**Issue by nlively** [invertase/react-native-firebase#3050] opened 2019-12-28 22:33 UTC
## Documentation Feedback

In using the v6 API and setting up messaging, I noticed a link to Notifications that goes to a Not Found page.  In all the searching I've done, both through the docs and on Google, it seems like everything relating to Firebase Notifications is in v5.x.

What's the recommended best practice for incorporating FCM in a react native app using v6 of this project?

Thank you!

**Comment by mikehardy** [comment] 2019-12-29 02:20
First pinned issue in the repo has all the info - #2566, and this is a dupe of #2990 #2984 #3010

**Closed by mikehardy** 2019-12-29 02:20 UTC
