### ISSUE TITLE
[🐛]🔥 Cloud Functions returning Unauthorized when adding App Check

### ISSUE THREAD

**Issue by gabrieltnishimura** [invertase/react-native-firebase#5622] opened 2021-08-19 12:04 UTC
## Issue

After installing  AppCheck `"@react-native-firebase/app-check": "^12.6.1",` our `httpsCallable` stopped working.
Uninstalling it makes it work again. The cloud functions don't have AppCheck enforcement enabled.

```js
import firebase from '@react-native-firebase/app';

const refCallable = firebase.app().functions('us-east1').httpsCallable('helloWorld');
try {
  await refCallable();
} catch (err) {
  // always here
  console.log('Error on cloud functions', err);
}
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "app",
  "version": "1.0.0",
  "scripts": {
    "start-android": "react-native run-android",
    "start-ios": "react-native run-ios",
    "start": "react-native start"
  },
  "dependencies": {
    "@react-native-firebase/analytics": "^12.6.1",
    "@react-native-firebase/app": "^12.6.1",
    "@react-native-firebase/app-check": "^12.6.1",
    "@react-native-firebase/auth": "^12.6.1",
    "@react-native-firebase/crashlytics": "^12.6.1",
    "@react-native-firebase/dynamic-links": "^12.6.1",
    "@react-native-firebase/firestore": "^12.6.1",
    "@react-native-firebase/functions": "^12.6.1",
    "@react-native-firebase/perf": "^12.6.1",
    "@react-native-firebase/storage": "^12.6.1",
    "react": "17.0.1",
    "react-native": "0.64.2"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "crashlytics_debug_enabled": true,
    "crashlytics_auto_collection_enabled": true,
    "crashlytics_is_error_generation_on_js_crash_enabled": true,
    "crashlytics_javascript_exception_handler_chaining_enabled": true
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'app' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  target 'appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({'Flipper' => '0.78.0'})

  post_install do |installer|
    react_native_post_install(installer)
  end

end

```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"
#import <Firebase.h>

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNBootSplash.h"

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [FIRApp configure];
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"app"
                                            initialProperties:nil];

  if (@available(iOS 13.0, *)) {
      rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
      rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 53.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v16.3.0/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Users/gabriel.t.nishimura/.sdkman/candidates/java/8.0.292.j9-adpt/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [X] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `12.6.1`
- **`Firebase` module(s) you're using that has the issue:**
  - `App Check`
- **Are you using `TypeScript`?**
  - `Y` & `4.3.2`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2021-08-19 12:58
Check upstream in firebase-android-sdk or firebase-ios-sdk, thus is unfortunately a known issue and I forget which repo it's logged in, but it's in one of them. When I am back at my desk I'll link it here if you don't beat me to it

I think, if I remember correctly, this is related to the no token case, so could be worked around by having valid debug tokens, and should work in real devices? Our e2e test here still works with callable functions because of this

**Comment by alexandramostap** [comment] 2021-08-19 14:27
Having the same issue

**Comment by mikehardy** [comment] 2021-08-19 14:38
Here it is: https://github.com/FirebaseExtended/flutterfire/issues/6794

This needs a reproduction on one (or the other) of the native APIs I think, probably easiest with firebase-ios-sdk since AppCheck there needs no extra configuration, you just include it and by default you get the DeviceCheck provider (which should trigger the error) - so starting from https://github.com/firebase/quickstart-ios/tree/master/functions and logging a fix is probably the fastest way

**Comment by mikehardy** [comment] 2021-08-19 14:41
Future people: Please do not "me too", "same issue", "+1" in comments. That generates notifications which do not provide any forward progress, they just waste time. Please "vote" by adding a reaction to the issue. Thank you.

Any reproduction as mentioned above, or comments about same would be great though! Anyone that can contribute to move it forward would be fantastic

**Comment by mikehardy** [comment] 2021-08-19 17:04
For people just looking to work around this for now on the devices that can't get valid tokens (that is, your android emulators in CI) **and are willing to accept the risk of tokens leaking - like you have a dev-only firebase backend for testing** you can crudely hack in a CI token like this:

https://github.com/invertase/react-native-firebase/blob/master/tests/android/app/src/androidTest/java/com/invertase/testing/DetoxTest.java#L32-L59

Please, please think long and hard about your token security and the risk you accept by doing something like this, but it's a nice workaround to have functions and appcheck work on otherwise-invalid-token environments so you may adopt appcheck

**Comment by mikehardy** [comment] 2021-09-21 16:50
This *should* be fixed now and released on all platforms, based on updates in the linked FlutterFire issue https://github.com/FirebaseExtended/flutterfire/issues/6794 where the firebase team has been collaborating with the community. I'm going to close this now with the understanding if you use the most up to date SDKs functions *should* be working now even if you have invalid AppCheck tokens.

**Closed by mikehardy** 2021-09-21 16:50 UTC
Labels: Impact: Bug, Help: Needs Triage, Blocked: Firebase SDK, Workflow: Needs Review
