### ISSUE TITLE
Crashing error while startup on Android (io.invertase.firebase.auth.RNFirebaseAuth.init)

### ISSUE THREAD

**Issue by alekseykarpenko** [invertase/react-native-firebase#45] opened 2017-04-10 15:07 UTC
Hi guys! Thanks for your work!

Please put me in the right direction.. Im trying to integrate Firebase, but when i'm done with all initializations, built my app and trying to start it on my device, ive got a crashing error at
  ```io.invertase.firebase.auth.RNFirebaseAuth.init```:
![screen shot 2017-04-10 at 6 05 11 pm](https://cloud.githubusercontent.com/assets/4648983/24868292/44ae067e-1e18-11e7-9100-af7aa263029c.png)

Appreciate if u could help me with this.

RN v0.41.0
react-native-firebase v1.0.0-alpha12

**Comment by Ehesp** [comment] 2017-04-10 15:09
Hi @alekseykarpenko

If you remove all JS firebase references does the app build? Can you also show where you initialise Firebase in your app please.

**Comment by alekseykarpenko** [comment] 2017-04-10 15:11
@Ehesp when i clear all JS related to firebase including ```import``` – the app still crashes.

**Comment by Ehesp** [comment] 2017-04-10 15:11
Are you using `firebase.auth()` anywhere?

**Comment by alekseykarpenko** [comment] 2017-04-10 15:14
@Ehesp Nope, that's the thing 😄  I was going to use only cloud messaging, but even when i remove all [it's setup](https://github.com/invertase/react-native-firebase/blob/master/docs/installation.android.md#3---cloud-messaging-optional), crashlog doesn't change

**Comment by alekseykarpenko** [comment] 2017-04-10 15:15
Auth is used in [RNFireBasePacPackage.java:38](https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/RNFirebasePackage.java#L38), and there is a crash

**Comment by alekseykarpenko** [comment] 2017-04-10 15:31
@Ehesp, **important update:** when i comment that line with calling ```new RNFirebaseAuth()```, the next line with ```new RNFirebaseDatabase()``` crashes with the same error ```java.lang.NoSuchMethodError```. Maybe i need to update RN, Android SDK, or other environment tools?

**Comment by Ehesp** [comment] 2017-04-10 15:34
cc @Salakar didn't we have this issue? 

@alekseykarpenko I'd recommend deleting your node modules and trying again, with a full app reinstall.

**Comment by Salakar** [comment] 2017-04-11 10:05
This normally tends to happen when react isn't correctly requiring its androik sdk correctly from node modules and is instead referencing the jcenter/maven version which was long deprecated (its on version .29 or something)

Make sure you're correctly including react in your gradle files, if you can show them that might be helpful

**Comment by alekseykarpenko** [comment] 2017-04-11 11:34
@Salakar, thx for your feedback! What gradle files do u need to look into? Both ```android/build.gradle``` && ```android/app/build.gradle```?

**Comment by alekseykarpenko** [comment] 2017-04-11 13:40
@Salakar Here is my ```app/build.gradle```:

[app.build.gradle.txt](https://github.com/invertase/react-native-firebase/files/913348/app.build.gradle.txt)

**Comment by Salakar** [comment] 2017-04-16 14:51
@alekseykarpenko looks like you're missing this: https://github.com/invertase/react-native-firebase-tests/blob/master/android/build.gradle#L22

**Comment by v1kku** [comment] 2017-04-26 10:21
This error is most likely caused by a dependency conflict between the dependencies in [android/build.gradle](https://github.com/invertase/react-native-firebase/blob/master/android/build.gradle#L50-L57) and the project using this library or another dependency that has similar dependencies but with conflicting versions.

To reproduce this error in the example app, install `react-native-fcm` then "link" it. Once the app compiles it will crash with the same `RNFirebaseAuth` error. This is because [its dependencies](https://github.com/evollu/react-native-fcm/blob/master/android/build.gradle) will currently no match with this repo's (latest sdk currently is 10.2.1). Removing the version numbers like below fixes the problem.

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.facebook.react:react-native:+'
    compile 'me.leolin:ShortcutBadger:1.1.10@aar'
    compile 'com.google.android.gms:play-services-base:+'
    compile 'com.google.firebase:firebase-core:+'
    compile 'com.google.firebase:firebase-config:+'
    compile 'com.google.firebase:firebase-auth:+'
    compile 'com.google.firebase:firebase-analytics:+'
    compile 'com.google.firebase:firebase-database:+'
    compile 'com.google.firebase:firebase-storage:+'
    compile 'com.google.firebase:firebase-messaging:+'
    compile 'com.google.firebase:firebase-crash:+'
}
```
If one wants to force a certain version of the firebase sdk they can use [ResolutionStrategy](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html)

```
configurations.all{
    resolutionStrategy {
        force 'com.google.android.gms:play-services-base:10.2.1'
        force 'com.google.firebase:firebase-core:10.2.1'
        force 'com.google.firebase:firebase-config:10.2.1'
        force 'com.google.firebase:firebase-auth:10.2.1'
        force 'com.google.firebase:firebase-analytics:10.2.1'
        force 'com.google.firebase:firebase-database:10.2.1'
        force 'com.google.firebase:firebase-messaging:10.2.1'
        force 'com.google.firebase:firebase-storage:10.2.1'
        force 'com.google.firebase:firebase-crash:10.2.1'
    }
}
```

This also means that this library won't have to publish a new release each time a new version of the sdk changes

**Comment by v1kku** [comment] 2017-04-26 10:26
I've added a PR #69

**Comment by Ehesp** [comment] 2017-05-09 09:26
Closing for now. Discussion based around the PR is required.

**Closed by Ehesp** 2017-05-09 09:26 UTC
Labels: awaiting-user-feedback
