### ISSUE TITLE
[Proposal][WIP] Messaging / FCM overhaul

### ISSUE THREAD

**Issue by chrisbianca** [invertase/react-native-firebase#595] opened 2017-11-08 15:09 UTC
Messaging and FCM is an area that has fallen behind the rest of the library in terms of ease of use, documentation and reliability.  We plan on overhauling this completely for the 3.3.0 release and rewriting from scratch to ensure that it provides the core FCM functionality in an easy to use and reliable manner.

This issue is currently a placeholder that will be updated as we agree exactly what we will support and how this will be structured in the API.  It's also here to show that we're aware of the issues that have already been raised and will be addressing them as part of this work.

To help support this development and sustain the library long term, please consider backing us on [Open Collective](https://opencollective.com/react-native-firebase).

**Comment by akshetpandey** [comment] 2017-11-09 23:53
FR: Notification Channels for Android O

**Comment by krystiansliwa** [comment] 2017-11-22 08:50
Hi, when do you plan to release version with those fixes?

**Comment by agonbina** [comment] 2017-11-27 20:38
Can we split this in such a way that we could also contribute? I would be happy to help out because this is one of the core features of firebase which I assume most people use/want to use.

**Comment by tranquan** [comment] 2017-12-02 15:44
Hi, I have an issue with getInitialNotification, it is not working properly if MainActivity is not configure as a Launcher.

On my app, I configure a SplashActivity as a Launcher to display a SplashScreen while app loading. But when I send the notification from firebase when app exit, then tap on the notification to open the app, `getInitialNotification` is not return the payload that I have sent.

Step to reproduce:

1. quit the app
2. send a notification from firebase
3. open app from the notification

Everything working fine if the MainActivity is the Launcher. Here is my configure:


#### Configure:

My AndroidManifest.xml

```
<activity
    android:name=".SplashActivity"
    android:label="@string/app_name"
    android:theme="@style/SplashTheme">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
</activity>

<activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:theme="@style/SplashTheme"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:launchMode="singleTop"
    android:windowSoftInputMode="adjustResize">
</activity>
```

On SplashActivity, I simply start MainActivity
My SplashActivity

```
public class SplashActivity extends AppCompatActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    Intent intent = new Intent(this, MainActivity.class);
    startActivity(intent);
    finish();
  }
}
```

####  Bug

On React Native, I call `getInitialNotification()`, but got a weird payload

```
messaging.getInitialNotification().then((payload) => {
	console.log('getInitialNotification: ', payload);
});
```

This is the log of payload, it's expected to have the information that I've sent, but not.

```
{
	opened_from_tray:true
	fcm: {
		action:null
	}
}
```

My Firebase Notification Payload:

```
{
   "to": "/topics/user-3322",
   "content_available" : false,
   "notification" : {
       "title": "this is title",
       "body": "this is message's body"
   },
   "data": {
   		"type": 1,
	     "extra_data":{
			"title":"this is title",
	    	"body":"this is message's body"
	     }
   }
}
```

**Comment by sapjunior** [comment] 2017-12-03 09:51
@tranquan I also encounter the same situation. Is your project use wix/react-native-navigation?

**Comment by krystiansliwa** [comment] 2017-12-03 12:01
@tranquan @sapjunior I also encounter that problem and I have some workaround for it here https://github.com/invertase/react-native-firebase/issues/151#issuecomment-342807969

**Comment by gaultierq** [comment] 2017-12-13 06:02
Hello, 
Any idea of when we will be able to use this library for messaging ?
Just to know if I should wait or find another solution.
Thanks for your hard work !

**Comment by tranquan** [comment] 2017-12-15 15:59
@krystiansliwa wow, nice solution (y) I've just tried and it worked perfectly, thanks a lot

**Comment by Nitroman605** [comment] 2017-12-27 10:36
Thanks for the amazing works . I just wanted to ask if the issue  #523  got fixed in 3.2.0 ? I see it that is closed , but in the release change log and in the commits I do not see it's mentioned as fixed .

Thanks .

**Comment by chrisbianca** [comment] 2017-12-27 10:38
@Nitroman605 We've bumped this functionality to the v3.3.0 release as it's a significant piece of work, and we wanted to be able to get Crashlytics functionality added sooner than we'd have been able to otherwise.

**Comment by sibelius** [comment] 2017-12-28 17:29
we can get a lot of code from here https://github.com/evollu/react-native-fcm

**Comment by Nitroman605** [comment] 2017-12-28 17:33
@sibelius  I have a big concern with that idea is that That lib is not compatiable with https://github.com/wix/react-native-navigation Which many of people are using it (Even their own push notification lib did not work with their navigation for some people , including me ) . 

invertase firebase messaging is the only lib that worked for me and some other who are using wix navigation .

**Comment by evollu** [comment] 2017-12-28 18:32
@chrisbianca @sibelius  I'm happy to merge our libraries to avoid duplicated work.
However react-native-fcm has grown from simple firebase bridging library into a push notification library so I wonder if it still fits the scope of react-native-firebase.
- it has a lot of code for local notifications which is independent of firebase cloud messaging
- for android it uses `custom_notification` to get around of many limitation on android cloud messaging

**Comment by sibelius** [comment] 2017-12-28 18:46
@evollu maybe we can move local notification logic to another package

**Comment by evollu** [comment] 2017-12-28 18:50
many things are shared between remote and local notif so I'm not sure.
but it is possible

**Comment by acmayberry** [comment] 2018-01-13 20:07
@chrisbianca  I am still experiencing all of the behavior described by @ashour in #559 even though that issue has been marked closed.  I am using v3.2.2.

I still get undefined for getInitialNotification() when activating the app on iOS by clicking on a notification.

I still get caching of getInitialNotification() when starting or activating the app on Android i.e. every time I open or activate the app, getInitialNotification() is still set to the value of the last time the app was opened from a notification.

**Comment by accordionpeas** [comment] 2018-01-15 14:37
Hello, can I ask if #678 will be addressed in the v3.3.0 release? And if there is an estimate on when the release will be ready? Thanks for all your hard work on this.

**Comment by talhamuhammadashraf** [comment] 2018-01-24 13:21
@chrisbianca  i am getting the message twice while its triggering once in the functions logs

**Comment by krystofcelba** [comment] 2018-01-26 13:59
👍 for https://github.com/evollu/react-native-fcm , I don't think that code for local notifications on android is issue as react-native-firebase has implemented them too. I use react-native-fcm in app with react-native-navigation and it works like a charm. @Nitroman605

**Comment by Salakar** [comment] 2018-02-12 12:59
For those want to track the progress of this see [this branch.](https://github.com/invertase/react-native-firebase/tree/fcm-rewrite)

**Comment by Jacse** [comment] 2018-02-19 18:11
@chrisbianca awesome you're tackling this. Looking forward!

**Comment by gaultierq** [comment] 2018-03-03 05:37
oh. so the milestone for this issue is v4.0.0 now ? does i mean that it will be released later on ? I am checking this thread everyday :D

**Comment by chrisbianca** [comment] 2018-03-03 07:56
Don't worry, it is very much in progress, but as it's such a big change we're likely to run it as an alpha for a little while.

We didn't want this to stop us getting Firestore transactions out which will be the main part of v3.3.0.

**Comment by gaultierq** [comment] 2018-03-03 13:31
ok great thx 👍

**Comment by chrisbianca** [comment] 2018-03-20 09:05
Good news, the long awaited alpha of our messaging and notifications overhaul is now available!!

Check out the release notes here: https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-alpha.1

If you have any comments and suggestions or want to report an issue, come find us on [Discord](https://discord.gg/C9aK28N)

**Comment by yarian** [comment] 2018-03-22 22:57
Quick question as someone who is integrating with this library for the first time specifically for push notifications. If you had to integrate with this library in the next two days, would you do v4 even though it's in alpha or v3 even if though it means rewriting for v4 later?

**Comment by hegelstad** [comment] 2018-03-22 23:20
V3 feels more alpha than V4 😀👍🏼 go for V4

**Comment by chrisbianca** [comment] 2018-03-23 10:19
Any volunteers who'd like to look at adding some typescript definitions for messaging and notifications?

**Comment by matheusmatos** [comment] 2018-03-23 13:34
@chrisbianca I can help with it =)

**Comment by chrisbianca** [comment] 2018-03-23 17:48
Just published a release candidate with a couple of other tasty treats (Firebase Invites, multi-database support and an overhaul of Dynamic Links): https://github.com/invertase/react-native-firebase/releases/tag/v4.0.0-rc.1

**Comment by Salakar** [comment] 2018-03-26 17:42
Going to close this now as we're close to a full release of v4 and there has been plenty of successful early testers on the alpha and RC versions.

Let's move discussions and feedback to the `v4-fcm-notifications` channel on [discord](https://discord.gg/C9aK28N). If you're flagging bugs for v4 please tag your github issue title with `[v4]` to allow us to spot them easier.

Thanks all for the feedback and thanks to all the early adopters/testers ❤️

**Closed by Salakar** 2018-03-26 17:42 UTC
Labels: android, ios, messaging
