### ISSUE TITLE
setUserProperty() sometimes is not working. 

### ISSUE THREAD

**Issue by MichaelSzer** [invertase/react-native-firebase#303] opened 2017-08-02 22:12 UTC
`setUserProperty()` sometimes is not working. For example I have the following code: 

```
async componentDidMount(){

    // Set screen event name.
    this.props.screenProps.firebase.analytics().setCurrentScreen('Grocery Screen.'); // <-- This is updated correctly

    // Log out that the menu wasn't opened to Firebase
    if(!this.categoryMenuWasOpened){
      await this.props.screenProps.firebase.analytics().setUserProperty('Category_Menu_Opened', 'No'); // This is **not** updated correctly
      console.log('Updated category menu "No".');
    }

    // Log out that the search bar isn't being used to Firebase
    if(!this.searchBarUsed){
      await this.props.screenProps.firebase.analytics().setUserProperty('Search_Bar_Used', 'No'); // <-- This is sometimes updated correctly
      console.log('Updated Search Bar "No".'); 
    }
  }
```
(Both console.log() are always triggered.)

Screenshot of Firebase Debug View: 
![firebase_not_updating_properties](https://user-images.githubusercontent.com/25836143/28897211-11ce3178-77b6-11e7-87d2-8b8145abd81c.png)

### Environment

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): Ubuntu 16.04
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Not relevant
4. React Native version (e.g. 0.45.1): 0.46.4
5. RNFirebase Version (e.g. 2.0.2): 2.0.4

**Comment by Ehesp** [comment] 2017-08-07 09:30
@MichaelSzer Assuming your logic is correct, my current thinking is that `setUserProperty` is not a promise, it's a fire and forget. I'm not sure how `async` will compile under the hood, but the fact the JS side doesn't return a promise might be causing an issue here. Try removing the async, or wrap it in a try/catch block to see if it's throwing an error.

**Comment by Chatharaju** [comment] 2017-08-08 16:13
Just wondering if setting user property to null is working?
I have set a user_id property to some number upon login: setUserProperty('user_id', '12345'). This works fine and I can see it on Debug view.
Now, upon logout I want to remove user_id property :  setUserProperty('user_id', null). This seems to be not effecting anything.

**Comment by Ehesp** [comment] 2017-08-09 07:48
@Chatharaju the docs say:

> The value of the user property. Values can be up to 36 characters long. Setting the value to null removes the user property.

I'll check it out, but if a null value is passed over to Java land and it expects a String, I'm not sure how that's handled, as it's not a Nullable value.

**Comment by Ehesp** [comment] 2017-08-09 07:57
Well the value is being sent across to the native side fine....

![image](https://user-images.githubusercontent.com/842078/29111053-c79feed6-7ce0-11e7-869b-0a24bdf38531.png)

![image](https://user-images.githubusercontent.com/842078/29111063-cd29b418-7ce0-11e7-9c8d-1b469fcee26b.png)

**Comment by chrisbianca** [comment] 2017-08-29 08:44
@MichaelSzer @Chatharaju I'm going to close this down as @Ehesp has proven that the code is correctly sending through the values and suggested a way to mitigate the issue by removing the await.

Please feel free to re-open if you're still finding discrepancies.

**Closed by chrisbianca** 2017-08-29 08:44 UTC
Labels: analytics, android, investigate

**Comment by mshibl** [comment] 2018-12-09 04:38
I'm having a similar issue with or without using async/await -- neither `setUserProperty` nor `setUserProperties` seem to work -- even though other methods like `trackEvent` and `setCurrentScreen` work well. 

here's a simple example of my code that's not working:
```
import firebase from "react-native-firebase";
firebase.analytics().setUserProperty('key', 'value' );
```
**Target Platform:** Android
**Development Operating System** MacOS High Seria
**Firebase SDK** Firebase-5.14.0
**React Native** 0.55.4
**react-native-firebase** 5.1.1

**Comment by appli-intramuros** [comment] 2019-01-10 14:19
> I'm having a similar issue with or without using async/await -- neither `setUserProperty` nor `setUserProperties` seem to work -- even though other methods like `trackEvent` and `setCurrentScreen` work well.
> 
> here's a simple example of my code that's not working:
> 
> ```
> import firebase from "react-native-firebase";
> firebase.analytics().setUserProperty('key', 'value' );
> ```
> **Target Platform:** Android
> **Development Operating System** MacOS High Seria
> **Firebase SDK** Firebase-5.14.0
> **React Native** 0.55.4
> **react-native-firebase** 5.1.1

@mshibl  I have exactly the same issue since few weeks. setUserProperty() only works the first time it is called, but when I try to update the value by calling again setUserProperty(), nothing happens, and old value is still there.

Please help us ! :)

**Comment by aashirMIQ** [comment] 2019-10-02 06:48
> I'm having a similar issue with or without using async/await -- neither `setUserProperty` nor `setUserProperties` seem to work -- even though other methods like `trackEvent` and `setCurrentScreen` work well.
> 
> here's a simple example of my code that's not working:
> 
> ```
> import firebase from "react-native-firebase";
> firebase.analytics().setUserProperty('key', 'value' );
> ```
> 
> **Target Platform:** Android
> **Development Operating System** MacOS High Seria
> **Firebase SDK** Firebase-5.14.0
> **React Native** 0.55.4
> **react-native-firebase** 5.1.1

Having the same issue
 "react-native": "0.60.4",
"react-native-firebase": "^5.5.6",

**Comment by mikehardy** [comment] 2021-11-09 15:44
Hi there! Our firebase-ios-sdk dependency is now up to 8.9.1 (!), you should use current versions when testing (13.0.1 here, and it should bring in firebase-ios-sdk 8.9.1 for you

Our e2e tests do test setting the property but it is true they do not assert later via getting the property to prove it is set, nor do they set property/properties then send a null in to clear them and assert it is cleared

https://github.com/invertase/react-native-firebase/blob/3d5d00d6b1ed7cf9e1afbe62f16b1c77e2bf7693/packages/analytics/e2e/analytics.e2e.js#L62-L80

If you'd like to extend the test case or show in some other reproducible way with current versions it is not working, then we can reopen this. Ideally / it would be perfect if the e2e test itself was extended to show the failure if there is one

**Comment by kolboch** [comment] 2021-11-09 16:45
Thanks for your reply @mikehardy and pointing out that our version is out of date :) Will try to update our project asap and get back to this issue if it would be reproducible. So far I can add some input to my previous answer, that after I refreshed my session (not just website) in firebase console the old "should be cleared" param was gone, so I do expect it might me web client issue with clearing params as already mentioned in https://github.com/firebase/firebase-ios-sdk/issues/3230
