### ISSUE TITLE
Connection State return number value, not boolean

### ISSUE THREAD

**Issue by dzuncoi** [invertase/react-native-firebase#55] opened 2017-04-17 05:28 UTC
Hi,

Currently, I'm using `.info/connected` to detect app connection state, as
```javascript
firebase.database().ref('.info/connected').on('value', snapshot => {
    const connectionState = snapshot.val()
})
```
And I expect `connectionState` should return boolean value (`true` of `false`), as [this Firebase doc](https://firebase.google.com/docs/database/web/offline-capabilities).

But it doesn't, my `connectionState` value always return `false` at the first time, then return `1` if app has connection and `0` if not. Is it a correct behavior?

Ps: I'm still fine with those value, just want to confirm this behavior.

**Comment by Salakar** [comment] 2017-04-18 09:02
Seems like incorrect behaviour, can you tell me which platform this issue is on, android or ios?

**Comment by dzuncoi** [comment] 2017-04-18 09:05
@Salakar  
I'm using iOS 10.3, react-native-firebase: 1.0.0-alpha12

**Comment by Ehesp** [comment] 2017-04-20 08:02
@dzuncoi Speaking with @Salakar, on Android SDK it returns as true/false, however on iOS it returns 1/0. The problem is it's part of a Reference, so there'd have to be some custom logic to change this (needs double checking).

**Comment by dzuncoi** [comment] 2017-04-20 08:23
Thanks for investigating this issue. I'm porting my app to Android as well, so I'll check and inform if there is anything should be changed.

**Comment by Salakar** [comment] 2017-04-20 08:40
Might also be an issue with the type conversion in RNFirebase also, @dzuncoi could you try see what setting/reading a boolean value on any ref returns? 

We have tests for this that check all types including Booleans and it's passing, may be some weird edge case in your instance where it isn't.

The iOS SDK docs say it's bool, or at least a boleanValue:
![image](https://cloud.githubusercontent.com/assets/5347038/25221529/56dc06e2-25ad-11e7-8d6c-45400ec22971.png)

**Comment by dzuncoi** [comment] 2017-04-21 07:18
I've tested on Android with the same codes and it return boolean values. And on Android, 

> my connectionState value always return false at the first time

this behavior does not happen as iOS.
It's a little bit weird. I'll test on real device soon.

**Comment by SamMatthewsIsACommonName** [comment] 2017-04-28 18:31
This has been the case for a while but I just deal with it by testing for either 1 or true.
Maybe it's not so elegant but it works haha

**Comment by basequatro** [comment] 2017-04-30 23:12
Use == instead of ===

**Comment by Salakar** [comment] 2017-08-14 12:36
Closing this as there's not much I can do about it, native SDK's return the value like this, but android returns an actual boolean value.

**Closed by Salakar** 2017-08-14 12:36 UTC
Labels: bug, database, investigate, ios
