### ISSUE TITLE
Unable to fetch data from firebase but can save data to firebase

### ISSUE THREAD

**Issue by Oshianor** [invertase/react-native-firebase#1407] opened 2018-08-15 22:39 UTC
### Environment

1. Application Target Platform:

both

2. Development Operating System:

windows 10

3. Build Tools:

Android Studio

4. `React Native` version:

0.55

5. `React Native Firebase` Version:

4.3.8

6. `Firebase` Module:

database, auth, core

7. Are you using `typescript`?

no
---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Oshianor** [comment] 2018-08-15 22:48
Whenever i run this code i get no response unless am just starting the android dev server .  Even when i reload my app it still doesnt work.
`firebase.database().ref('post').once('value').then(res => console.log(res))`

![screenshot 27](https://user-images.githubusercontent.com/26805274/44177403-b2a65400-a0e5-11e8-90dd-4239be619f36.png)
![screenshot 28](https://user-images.githubusercontent.com/26805274/44177404-b2a65400-a0e5-11e8-9f0a-57f23f5d9256.png)
![screenshot 29](https://user-images.githubusercontent.com/26805274/44177405-b33eea80-a0e5-11e8-955e-8c1f5962b467.png)
![screenshot 30](https://user-images.githubusercontent.com/26805274/44177406-b33eea80-a0e5-11e8-9029-8b04a124dfd0.png)

**Comment by Ehesp** [comment] 2018-08-17 08:45
Where is your code usage? Those screenshots don't really help sorry!

**Comment by Oshianor** [comment] 2018-08-17 23:04
My database rules are well setup. After much testing i think i understand what the problem is but i have no ideal how to fix it. Whenever i start up my react native android server when my screens are loaded some times they fetch the data while others they don't and that point i have to manually close the app and open it again. NOTE : The android server keeps running while i close the app.

**Comment by armanatz** [comment] 2018-09-27 19:29
@Ehesp I seem to also be running into the same issue. I am trying to run the same code as @Oshianor but unless I close the application on my emulator and open it again, the code only executes once and never executes again upon subsequent refreshes.

I am running on `react-native@0.57.0` and `react-native-firebase@5.0.0`

Any ideas?

**Comment by KennethSJiang** [comment] 2018-09-29 14:02
having the same issue here. Didn't have this problem when using web based firebase npm

**Comment by csgonutty** [comment] 2018-10-03 10:03
Same issue here, I have to restart the app and emulator in order for the .on() listener to fire.

Im running `react-native@0.57.1` and `react-native-firebase@5.0.0`

**Comment by dantman** [comment] 2018-10-10 21:11
I was going to report the same issue. React Native Firebase works, but then on Android after a few JS reloads it stops working.

I'm using react-redux-firebase, however I did include this code in my app to verify that this issue is actually in react-native-firebase and not in react-redux-firebase:
```js
firebase.firestore().collection('practice').get()
	.then(data => console.log(data.docs[0].data()))
	.catch(console.error);
```

Of particular note. I notice that when it's working I get data; when it fails I get no response at all. i.e. It does not fail with an error, it simply never resolves the promise.

**Comment by ruvice117** [comment] 2018-10-22 16:17
The same issue here. Database works on the first load but stops working after dev app refreshes. I observed this issue  after updating to RNFIrebase v5.0.0

**Comment by gitsad** [comment] 2018-10-23 13:45
I have got the same problem. I need to reload whole app to receive the data on componentDidMount

**Comment by Salakar** [comment] 2018-10-27 04:39
Hey all, this should be fixed as part of https://github.com/invertase/react-native-firebase/pull/1619 - you can give it a go on `react-native-firebase@5.1.0-rc2` - see the rc1 release notes on GH for the correct Native SDK versions.

For firestore could you please raise a seperate issue so I can track it and work on it there.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Closed by Salakar** 2018-10-27 04:39 UTC
Labels: RN-0.57.x, database, ios, rn-reload, 👉 await-user-feedback, 🤖 android

**Comment by losheredos** [comment] 2018-11-18 09:01
Same here still..

**Comment by joey3060** [comment] 2019-03-11 08:34
same here still

**Comment by silvafacundo** [comment] 2019-03-27 00:02
I'am having the same problem. I was using the latest react-native-firebase version but then i read that downgrading to 5.2.0 solves the problem. It Solves it until syntax error, once i fix my bundling problem firebase database stops working...
I'm using react-native 0.59.2
On windows 10 and developing for android

**Comment by anastely** [comment] 2019-03-28 17:39
@silvafacundo I have the same problem but with  "react-native-firebase": "4.3.8",
and I think the syntax is true,
```
displayCategories = () => {
    const refData = firebase.database().ref("categories");
    var items = [];
    refData.once("value", snapshot => {
      console.log(snapshot.val());
      snapshot.forEach((childSnapshot) => {
        items.push({
          id: childSnapshot.val().id,
          name: childSnapshot.val().name,
        });
      });
      this.setState({ categories: items })
    });
  }
```
if you solve the problem please tell me!

**Comment by silvafacundo** [comment] 2019-03-28 17:47
> @silvafacundo I have the same problem but with "react-native-firebase": "4.3.8",
> and I think the syntax is true,
> 
> ```
> displayCategories = () => {
>     const refData = firebase.database().ref("categories");
>     var items = [];
>     refData.once("value", snapshot => {
>       console.log(snapshot.val());
>       snapshot.forEach((childSnapshot) => {
>         items.push({
>           id: childSnapshot.val().id,
>           name: childSnapshot.val().name,
>         });
>       });
>       this.setState({ categories: items })
>     });
>   }
> ```
> if you solve the problem please tell me!

@anastely  I think that the problem is coming from Debuggin JS Remotely. I've managed to get it working by not using that option. Debbugin is pretty tedious, but that was the only solution I've could find

**Comment by anastely** [comment] 2019-03-28 17:59
@silvafacundo uh oh, it's work after uninstalling the app and stoped Debugging JS Remotely,
but now it's not real-time after delete or insert data I don't see any update on my app and change the `.once` into `.on` , any idea?

**Comment by silvafacundo** [comment] 2019-03-28 18:36
Uhmmm... for me it's working fine, make sure that you are updating the correct path, and that is updating at console.firebase.google.com.
If it isn't updating, catch for errors of all your firebase database references and check your database rules.
If you want attach your files and database structure and rules so I can have a better idea

**Comment by silvafacundo** [comment] 2019-03-28 18:37
@anastely  Uhmmm... for me it's working fine, make sure that you are updating the correct path, and that is updating at console.firebase.google.com.
If it isn't updating, catch for errors of all your firebase database references and check your database rules.
If you want attach your files and database structure and rules so I can have a better idea
