### ISSUE TITLE
Build fails. Dex issue

### ISSUE THREAD

**Issue by RevanScript** [invertase/react-native-firebase#752] opened 2018-01-14 14:45 UTC
Build fails with the following log:

```
...
:react-native-firebase:compileDebugAndroidTestShaders UP-TO-DATE
:react-native-firebase:generateDebugAndroidTestAssets UP-TO-DATE
:react-native-firebase:mergeDebugAndroidTestAssets UP-TO-DATE
:react-native-firebase:transformClassesWithDexForDebugAndroidTest
Installing APK 'react-native-background-geolocation-debug-androidTest.apk' on 'phone(AVD) - 5.1.1' for react-native-background-geolocation:debugAndroidTest
:react-native-firebase:transformClassesWithDexForDebugAndroidTest FAILED
Installed on 1 device.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase:transformClassesWithDexForDebugAndroidTest'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
```

Any idea? It usually happens when `multiDexEnabled true` is not set, but i have it in my `build.gradle`

**Comment by RevanScript** [comment] 2018-01-14 15:01
It compiled successfully when i uncommented `multiDexEnabled true` in `node_modules/react-native-firebase/android/build.gradle` lol

**Comment by Ehesp** [comment] 2018-01-14 16:55
Hello, please see https://rnfirebase.io/docs/v3.2.x/faqs#[Android]-Duplicate-Dex-Files-error-(build-time-error)

**Comment by igorsantos07** [comment] 2018-03-26 19:40
Even after ejecting this error still shows up. As mentioned by OP, uncommenting the internal `build.gradle` file works. Everything mentioned in the [official docs on MultiDex](https://developer.android.com/studio/build/multidex.html) is also correct for my app (default settings after ejecting were enough).

Is there a better way to debug and fix this issue?

**Comment by igorsantos07** [comment] 2018-03-26 23:39
More info:
I created a new project from scratch, and following these steps, the error could be reproduced:
1. `create-react-native-app xyz`
2. eject from it, maintaining Expo
3. `npm install react-native-firebase`
4. `react-native link react-native-firebase`
5. `react-native run-android`

Before executing the `link`, `run-android` would fail, complaining of a missing task `installDebug`. Thus I discovered the alternative `react-native run-android --variant DevDebug` and started using it until I noticed I had forgotten to link. After linking, I noticed the bare `run-android` fails with the reported error, while the `DevDebug` variant works normally (actually, it complains of permission denial for starting intent, but seems to be another thing?)

**Comment by Salakar** [comment] 2018-03-27 06:57
@chrisbianca I do wonder if we should just have that multidex line just commented in by default as per 2nd comment. I added that line in v2 I think but left it out as I thought people should be going through the process of forcing versions etc but I think the new gradles are smart enough to just go with multidex without too much effect on bundle sizes.

**Comment by chrisbianca** [comment] 2018-03-28 09:10
Have added the multidex line in by default for upcoming v4. Closing.

**Closed by chrisbianca** 2018-03-28 09:10 UTC

**Comment by LeoUrushi** [comment] 2019-04-01 02:12
I still have the same problem.

**Comment by NomanGul** [comment] 2019-04-05 16:03
Same problem here! Plz Help us :disappointed:

**Comment by mikehardy** [comment] 2019-04-05 18:09
I have successfully used the firebase starter app, with multidex enabled on API16 and up emulators. If you try the firebase start it will likely work, which proves it is possible and thus likely an integration (your app's gradle files) issue. That is a mixed blessing as it means it is something specific to your app that no one can really help with, but should provide the motivation to get all your versions updated and try again exactly like the firebase app.

Worth noting I did have to make some changes in the firebase start to have it go past RN0.58, but you can see them all here if interested. It integrates the MLKit and RN0.59 and MultiDex and worked for me in debug and release mode, no problems.

https://github.com/mikehardy/react-native-firebase-starter/commits/camera-test

**Comment by NomanGul** [comment] 2019-04-05 18:43
@mikehardy Actually Everything (Crashlytics, Analytics, etc) working fine but This issue happens when I'm trying to implement Performance Monitoring SDK :disappointed:

**Comment by mikehardy** [comment] 2019-04-05 19:22
Strange, I actually had that one integrated I thought, in the demonstrator I linked. I definitely have that one integrated in my day-job app and it's working fine.
