### ISSUE TITLE
[🐛] Not working on Windows 10 (build failed - Plugin [id: 'io.invertase.gradle.build', version: '1.4'] was not found...)

### ISSUE THREAD

**Issue by rchowdhe** [invertase/react-native-firebase#4444] opened 2020-10-23 13:17 UTC
## Issue
Hey,

I tried to setup completely new demo app using shell script [https://github.com/mikehardy/rnfbdemo](https://github.com/mikehardy/rnfbdemo) provided by @mikehardy but it seems not working on Windows platform.

Script executed successfully and created the `rnfbdemo` app, Now once I tried to run command` react-native run-android` it throws error :
```
> rnfbdemo@0.0.1 android C:\DEVELOPMENT\OCR\rnfbdemo-master\rnfbdemo
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 991 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\DEVELOPMENT\OCR\rnfbdemo-master\rnfbdemo\node_modules\@react-native-firebase\app\android\build.gradle' line: 20

* What went wrong:
Plugin [id: 'io.invertase.gradle.build', version: '1.4'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.invertase.gradle.build:io.invertase.gradle.build.gradle.plugin:1.4')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rnfbdemo@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rnfbdemo@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
I am not sure what is wrong on `windows`, as everybody suggested its working very much fine for other platform like : (`Linux, macOs`)

If Someone have idea to make it working on windows then, Can you please suggest what's wrong I am doing, Or do I need to apply some tweaks to make it working, I am hopeful for the solution. Actually I don't want to say but I am really struggling with this from last 2 weeks 😞

What I have already tried:

- Created new app using init command (`react-native init OCRFirebaseApp`) and integrate firebase plugin using command (`npm install --save @react-native-firebase/app`) - Same Issue as above
- Create new app using template https://github.com/invertase/react-native-firebase/tree/master/packages/template `npx @react-native-community/cli@next init --template=@react-native-firebase/template@alpha <myProjectName>` But its also not working - Some different issue (If required I can post the error)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "rnfbdemo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-firebase/app": "^8.4.6",
    "react": "16.13.1",
    "react-native": "0.63.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/runtime": "^7.12.1",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.1",
    "eslint": "^7.11.0",
    "jest": "^26.6.1",
    "metro-react-native-babel-preset": "^0.63.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 1.04 GB / 7.38 GB
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 24, 25, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6821437
    Visual Studio: 15.9.28307.1259 (Visual Studio Professional 2017), 16.7.30413.136 (Visual Studio Professional 2019)
  Languages:
    Java: 1.8.0_181
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by amit13091992** [comment] 2020-11-09 04:58
any solutions for this BUG?

Environment  used:
```
    "react": "16.11.0",
    "react-native": "0.62.2",
```

**Comment by hrishiakhade** [comment] 2020-11-09 13:36
Same issue on 

 "react": "16.13.1",
    "react-native": "0.63.3",
"@react-native-firebase/app": "^8.4.7

**Comment by mikehardy** [comment] 2020-11-09 14:03
@amit13091992 so far no, no solution for the BUG that we know of, do you have a TEST or a PR for it? We would happily merge one, but it hasn't been a priority to fix it yet, as react-native development implies building for iOS which assumes a macOS machine somewhere in the mix? We want it to work on windows - no doubt - but in the meantime you might try WSL, Ubuntu flavor to get the builds working? It's free and should work on any windows 10 machine as a (not great, but functional) workaround

**Comment by amit13091992** [comment] 2020-11-09 14:53
> Same issue on
> 
> "react": "16.13.1",
> "react-native": "0.63.3",
> "@react-native-firebase/app": "^8.4.7

@hrishiakhade @mikehardy 
Will you once try downgrading your Gradle version from **gradle.properties** file? I tried downgrading and it worked.

**Comment by mikehardy** [comment] 2020-11-09 15:01
Very interesting! That is new knowledge, thank you. I am mostly up to 6.7 gradle everywhere so had not contemplated downgrading. This gives us something to look at - something about gradle must have changed with the way it handles things on windows between 5.5 and 6.0.1 - a scan of their release notes may show the problem https://gradle.org/releases/

A look there says they have these versions
6.0.1
6.0
5.6.4
5.6.3
5.6.2
5.6.1
5.6
5.5.1
5.5

If you could test it - I think the odds are high that it was the breaking change release from 5.6.4 to 6.0, trying 5.6.4 would limit the changes to examine to a small number. If you can still reproduce it on 5.6.4 then I would bisect and try 5.6 then above and below etc

**Comment by sahilbathla** [comment] 2020-11-09 15:27
> > Same issue on
> > "react": "16.13.1",
> > "react-native": "0.63.3",
> > "@react-native-firebase/app": "^8.4.7
> 
> @hrishiakhade @mikehardy
> Will you once try downgrading your Gradle version from **gradle-wrapper.properties** file? I tried downgrading and it worked.
> My working file, previously its version was 6.0.1 in place of 5.5:
> 
> ```
> distributionBase=GRADLE_USER_HOME
> distributionPath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-5.5-all.zip
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists
> ```

Facing same issue, ^ this did not work. Anyone had luck?

**Comment by hrishiakhade** [comment] 2020-11-09 15:43
I downgraded from Gradle from 6.2 to 6.0.1. It worked !!

**Comment by mikehardy** [comment] 2020-11-09 15:49
isn't this strange though @hrishiakhade ? There is a report above from @amit13091992 that he started (with problems) at 6.0.1 and went to 5.5 and it worked. And @sahilbathla indicates that 5.5 is not working. So, I have reports of success and failure with the same version, and a failure report on downgrade separately. What am I to make of that, as a test result 🤔 

I think there may be something going on with gradle caching, more than anything. When you use a new version of gradle you get a new associated cache, and that's the only thing that seems consistent with the results. If you remove the gradle cache (should be a `.gradle` directory in your home directory?) and kill the gradle daemon and then retry a version that failed before, I wonder if it will work.

**Comment by sahilbathla** [comment] 2020-11-09 15:53
> isn't this strange though @hrishiakhade ? There is a report above from @amit13091992 that he started (with problems) at 6.0.1 and went to 5.5 and it worked. And @sahilbathla indicates that 5.5 is not working. So, I have reports of success and failure with the same version, and a failure report on downgrade separately. What am I to make of that, as a test result 🤔
> 
> I think there may be something going on with gradle caching, more than anything. When you use a new version of gradle you get a new associated cache, and that's the only thing that seems consistent with the results. If you remove the gradle cache (should be a `.gradle` directory in your home directory?) and kill the gradle daemon and then retry a version that failed before, I wonder if it will work.

Might not be true too, as it failed both on 6.0.1 and 5.5 for me. Also, I am using MacOs and not Windows.

**Comment by mikehardy** [comment] 2020-11-09 15:57
@sahilbathla I will hide your comments and request you not post on this issue then please. This is not for macOS. You are not consistent with the bug title

**Comment by rchowdhe** [comment] 2020-11-10 08:19
Don't Know what is still wrong with my environment 😞,  I tried with **6.0.1, 5.5, 5.6** and nothing worked for me.

**Comment by mikehardy** [comment] 2020-11-10 11:39
Perhaps it never worked on windows, or perhaps you have a specific local network issue. I still haven't tried to reproduce it myself, I've been focused elsewhere sorry

**Comment by mikehardy** [comment] 2020-11-10 11:46
You all may be interested in the related issue: https://github.com/invertase/react-native-gradle-plugin/issues/4

In https://github.com/invertase/react-native-gradle-plugin/issues/4#issuecomment-724458535 @rt9092 indicates:

> @mikehardy Clearing all cache worked for me. Thanks

**Comment by rchowdhe** [comment] 2020-11-12 13:07
@mikehardy I know you are busy! That's Ok, Problem is I have no Other environment except Windows to continue with Firebase integration, So do you have any suggestion what could be worst approach anyway to continue with `react-native+Firebase`  I mean, I just want to continue for now in anyway and I not so much involved with mobility topics to solve this topic alone 😞

**Comment by mikehardy** [comment] 2020-11-12 13:25
If I were a developer forced to use nothing but a Windows 10 platform, I would install the Ubuntu 20LTS flavor of the Windows Subsystem for Linux just as a matter of course, because it's a powerful system.

If I had that installed, and I was having a possibly-windows-specific build problem, I would try to build it under Ubuntu then, and I *think* it might work?

Installing Ubuntu under linux sounds like a pretty big detour however - having just installed Ubuntu 20LTS under WSL on Windows 10 myself, I know the process is very painless (almost no effort required, just some disk space and network transfer). So it might actually be easy to try? And it might work?

**Comment by mikehardy** [comment] 2020-11-13 02:24
I just took a moment to make sure this works on windows, and this module works fine on windows. I can't reproduce this so I will close it.

For what it's worth, here is the commit with the changes required to get it verified and working:

https://github.com/mikehardy/rnfbdemo/commit/49b71c29e4b7259415c52761c793b99f47f0a810

You'll notice (if you try it) that I do use Windows Subsystem for Linux in order to create the actual install, but that's just because I'm not going to maintain that port the script (with all it's bash and sed stuff) to non-Unix variants.

The actual final run though is just using PowerShell to do an `npm i` and then a `npx react-native run-android` which then does the full gradle compile and everything and shows that the error in this issue doesn't happen on a clean project.

I suspect something strange about the local network environment (DNS or something) or on-disk gradle caching.

**Closed by mikehardy** 2020-11-13 02:24 UTC
Labels: Help: Needs Triage, Impact: Bug, Workflow: Needs Review

**Comment by hrishiakhade** [comment] 2020-11-14 19:39
> I downgraded Gradle from 6.2 to 6.0.1. It worked !!

I again upgraded it back to 6.2 . This time it worked . Not sure what was the problem earlier. I had tried clearing gradle cache earlier , but I didn't work that time

**Comment by YajanaRao** [comment] 2024-07-12 14:27
For me it is not working on github actions, ubuntu and mac as well. I just upgraded my react native project from 0.69 to 0.74.3

![image](https://github.com/user-attachments/assets/3a57bc98-e938-4eeb-bf17-53151daac96e)

I don't know what I missed. 😞 

github actions: https://github.com/YajanaRao/Serenity/actions/runs/9894288396/job/27332003781
github code: https://github.com/YajanaRao/Serenity/tree/develop/apps/mobile
