### ISSUE TITLE
iOS stops receiving messages if the application is in the background 

### ISSUE THREAD

**Issue by bmp123** [invertase/react-native-firebase#3724] opened 2020-06-01 06:43 UTC
## Issue
iOS stops receiving messages if the application is in the background for more than 15 minutes. Perhaps this is due to the fact that the js thread is paused? How can I receive silent push notifications in background always?
### firebase request body :
```js
{
"to" : ...,
"content_available": true,
"priority": "high",
"apns":{
"headers":{
"apns-priority":"5",
"apns-push-type":"background"
},
"payload":{
"aps":{
"content-available":1
}
}
},
"data" : {
"type":"call"
}
}
```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "....",
  "version": "1.2.148",
  "versionCode": 258,
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "android": "react-native run-android",
    "release": "react-native run-android --variant=release",
    "logs": "adb logcat *:S ReactNative:V ReactNativeJS:V",
    "test": "jest",
    "release:android": "bash createVersion.sh && cd android && ./gradlew bundleRelease",
    "release:android:apk": "bash createVersion.sh && cd android && ./gradlew assembleRelease",
    "postinstall": "npx jetify"
  },
  "dependencies": {
    "@miblanchard/react-native-slider": "^1.2.2",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.1",
    "@react-native-firebase/analytics": "^7.1.0",
    "@react-native-firebase/app": "^7.1.0",
    "@react-native-firebase/crashlytics": "^7.1.0",
    "@react-native-firebase/iid": "^7.1.0",
    "@react-native-firebase/messaging": "^7.1.0",
    "@voximplant/react-native-foreground-service": "2.0.0",
    "libphonenumber-js": "^1.7.52",
    "moment": "^2.26.0",
    "moment-duration-format": "2.3.2",
    "native-base": "^2.13.12",
    "ramda": "0.27.0",
    "react": "^16.13.1",
    "react-native": "^0.62.2",
    "react-native-background-timer": "^2.2.0",
    "react-native-callkeep": "^3.0.13",
    "react-native-check-version": "^1.0.5",
    "react-native-contacts": "^5.2.0",
    "react-native-device-info": "^5.6.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-get-random-values": "^1.4.0",
    "react-native-incall-manager": "3.2.7",
    "react-native-iphone-x-helper": "1.2.1",
    "react-native-largelist-v3": "3.0.15",
    "react-native-launch-application": "1.0.1",
    "react-native-modal": "^11.5.6",
    "react-native-notifications": "^3.2.2",
    "react-native-permissions": "^2.1.5",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^2.0.2",
    "react-native-screens": "^2.8.0",
    "react-native-sound": "0.11.0",
    "react-native-splash-screen": "3.2.0",
    "react-native-spring-scrollview": "2.0.23",
    "react-native-svg": "^12.1.0",
    "react-native-switch-toggle": "1.1.4",
    "react-native-verto": "0.1.3",
    "react-native-voip-push-notification": "^2.1.0",
    "react-native-webrtc": "1.75.3",
    "react-navigation": "^4.3.9",
    "react-navigation-stack": "^2.5.1",
    "react-navigation-tabs": "^2.8.13",
    "react-redux": "7.2.0",
    "redux": "4.0.5",
    "redux-logger": "3.0.6",
    "redux-persist": "6.0.0",
    "redux-thunk": "2.3.0",
    "socket.io-client": "2.3.0",
    "uuid": "^8.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.6",
    "@babel/runtime": "^7.9.6",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^26.0.1",
    "eslint": "^7.1.0",
    "jest": "^26.0.1",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "^16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'onlinepbx' do
  # Pods for ..
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  # pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  #Custom libs
  pod 'ReactNativeIncallManager', :path => '../node_modules/react-native-incall-manager'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"

  target 'onlinepbxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'onlinepbx-tvOS' do
  # Pods for onlinepbx-tvOS

  target 'onlinepbx-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
#import <Firebase.h>
#import "AppDelegate.h"
#import <PushKit/PushKit.h>  
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNVoipPushNotificationManager.h"
#import "RNCallKeep.h"
#import "RNSplashScreen.h"
#import <React/RCTLog.h>


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
continueUserActivity:(NSUserActivity *)userActivity
  restorationHandler:(void(^)(NSArray * __nullable restorableObjects))restorationHandler
{
    return [RNCallKeep application:application
                         continueUserActivity:userActivity
                          restorationHandler:restorationHandler];
  }

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"onlinepbx"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [FIRApp configure];
  [RNSplashScreen show];
  RCTSetLogThreshold(RCTLogLevelInfo - 1);
  
  return YES;
  
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

</p>
</details>

---\

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 209.23 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /var/folders/y4/31dk_nqd4zqfq0v1wkqwntdm0000gn/T/yarn--1590993614925-0.2235182507770741/node
    Yarn: 1.13.0 - /var/folders/y4/31dk_nqd4zqfq0v1wkqwntdm0000gn/T/yarn--1590993614925-0.2235182507770741/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.3
      System Images: android-21 | Google APIs Intel x86 Atom, android-23 | Android Wear Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 9.60s.

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2020-06-01 17:17
You cannot receive silent push messages in background always in iOS by design.
Apple, and the iOS power miser algorithms, will decide whether they will accept in the cloud, forward to device, accept on the device, wake your app or not etc.

And frequently they will drop your message at any of those steps.

Best bet is to watch the Xcode console logs on a real device while you send.

**Comment by bmp123** [comment] 2020-06-02 06:58
I look at the logs in a real device and after 15 minutes the application does not wake up no matter how many messages I send

**Comment by mikehardy** [comment] 2020-06-02 14:37
@bmp123 study iOS power management, iOS / APNs message throttling etc

**Comment by russellwheatley** [comment] 2020-06-17 12:50
As mentioned by @mikehardy, this isn't an issue with React Native Firebase messaging. Feel free to continue the discussion but I'm going to close this issue.

**Closed by russellwheatley** 2020-06-17 12:50 UTC
