### ISSUE TITLE
 firebase.notifications().getInitialNotification().then((notificationOpen: NotificationOpen) => Not working Always return Null in App.js

### ISSUE THREAD

**Issue by lovekothari123** [invertase/react-native-firebase#2768] opened 2019-10-23 13:34 UTC
## Issue

Describe your issue here

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2019-10-23 14:05
You must follow the template or we close the issue

As a hunch maybe make sure this isn't affecting you if you are on android https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454

**Closed by mikehardy** 2019-10-23 14:05 UTC

**Comment by lovekothari123** [comment] 2019-10-23 14:27
Hello @mikehardy please check above code and comments i have mention all information which is related to firebase 
please review all information.

**Comment by mikehardy** [comment] 2019-10-23 14:34
You have picked and chosen which data to show, I can't spend time troubleshooting that way. You did not address my comment about possible splash-screen interaction and only the whole AndroidManifest.xml would show it.

**Comment by lovekothari123** [comment] 2019-10-23 14:48
thank-you thank-you thank-you thank-you thank-you thank-you thank-you thank-you thank-you thank-you thank-you thank-you thank-you thank-you thank-you sooooo much to share me this link  [ crazycodeboy/react-native-splash-screen#289 (comment) ](url)
@mikehardy  
you are great i have solved my issues thank-you again @mikehardy 👍 👍 👍

**Comment by mikehardy** [comment] 2019-10-23 14:50
By my count you are at least the 12th person just from this repo that has had that issue. :sweat_smile:  glad that worked.

**Comment by minhnguyenwp** [comment] 2019-11-07 07:41
@mikehardy  Sorry, i face this issue, but **android works fine**. **IOS is problem.** 
i can get action when app is background, but app killed ios just opens app not goes to deeplink. 
i have  getInitialNotification() <- not work when app killed, 
onNotificationOpened() <- it's fine,
- "react-native": "0.59.9", 
- "react-native-firebase": "5.5.6",
- "react-native-splash-screen": "3.1.1", 

any idea, Gents!

**Comment by ramonvermeulen** [comment] 2019-11-11 09:26
I'm facing this issue as well. getInitialNotification().then(res => ...); is always returning `null` for me just on iOS. On android everything is working just fine, any solutions? Using react-native-firebase 5.5.6 with react-native 0.59

**Comment by arunanna** [comment] 2019-11-13 00:47
@ramonvermeulen I am also having the same issue, except that my react native version is `0.61.0`

**Comment by Juliocbr** [comment] 2019-11-19 21:18
Did anyone find a solution for this error? I planned to upgrade from version 3.3.1 to 5.5.6 but apparently I will not do so for now.

**Comment by davidwlhlm** [comment] 2019-12-03 16:53
Hi, do you have remote debugging enabled? I had the same issue last week with `react-native 0.60.5` and `react-native-firebase 5.5.6`, but I could resolve the issue after turning "Debug JS Remotely" off.

I came to the solution after encountering a similar behaviour with React Native's Linking module. `Linking.getInitialURL()` (detecting with which link the app was initially opened) always returns null, if remote debugging is on.

**Comment by mikehardy** [comment] 2019-12-03 21:50
@davidwlhlm that seems like such a gotcha - could you propose a PR to the docs with a troubleshooting section or something? I can't imagine the time lost trying to find that, and you've already found it :-). All docs have an edit button top-right

**Comment by minhnguyenwp** [comment] 2019-12-04 02:03
> Debug JS Remotely

i knew this issue, but the problem is i reported on real device with ipa and app from appstore.

**Comment by ghasemikasra39** [comment] 2020-07-17 12:21
Dear @minhnguyenwp 
I am facing exactly the same issue as yours. I created the corresponding issue [here](https://github.com/invertase/react-native-firebase/issues/3964). In the meanwhile, have you found any solution to this?

**Comment by RishavKumar-3796** [comment] 2020-11-16 19:18
Push notification does not give call back if there are multiple notifications in the notification console and when one notification is already clicked then clicking on another notification from the notification tray after closing the app does not call any notification life cycle method.

Let's say there are 5-6 notifications in the console, we click on one of the notification which opens up the app and works as expected and calls the related methods. After that when we close the app and then click on another notification from the notification console then it does not call any notification method.

I am using "react-native": "0.61.4", and "@react-native-firebase/messaging": "^7.4.2",

**Comment by CoconutSiloDev** [comment] 2020-12-02 09:07
I am not sure if it is still related but for those who are using 'react-native-splash-screen', if you can, do not use this package as it has a number of serious unobservable issues.
If you still decide to use it and if you also get null for messaging().getInitialNotificatio().

Make sure your SplashActivity.java is similar to this. I found this after getting null for three hours

-------------------------SplashActivity.java --------------------------------------------------------------------

package com.nameOfYourPackage; 

import android.content.Intent;
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;

public class SplashActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Intent fcmIntent = this.getIntent();
        Bundle bundle = fcmIntent.getExtras();

        Intent intent = new Intent(this, MainActivity.class);
        intent.putExtras(fcmIntent);
        startActivity(intent);
        finish();
    }
}

**Comment by cretumarius** [comment] 2021-03-17 15:26
@CoconutSiloDev 
Thanks man, you're awesome. I've faced the exact same problem and your comment solved my issue.
