### ISSUE TITLE
auth/too-many-requests

### ISSUE THREAD

**Issue by amannarola** [invertase/react-native-firebase#6111] opened 2022-03-06 05:21 UTC
**auth/too-many-requests**
This error is coming during login using firebase auth and i tried to put time out for request but it does not work.
So please give me solution for this

**Comment by mikehardy** [comment] 2022-03-06 13:03
Hi there!
This is a duplicate of many: https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+too-many-requests
In the end it will be a local device or project issue, all the others have been 
Also, you skipped the issue template, and we close issues where the template is not followed. But do make sure you are using up to date versions

**Closed by mikehardy** 2022-03-06 13:03 UTC
Labels: Impact: Bug, Help: Needs Triage
