### ISSUE TITLE
[🐛] analytics().logEvent not working ?

### ISSUE THREAD

**Issue by HeIp** [invertase/react-native-firebase#4879] opened 2021-02-07 18:44 UTC
## Issue
Used the code described in https://rnfirebase.io/analytics/usage#predefined-events.
However no logs of that event seem to show up.
The code in question
```
import react, { useEffect } from 'react';
import { View, Button } from 'react-native';
import analytics from '@react-native-firebase/analytics';

function App() {
  return (
    <View>
      <Button
        title="Press me"
        // Logs in the firebase analytics console as "select_content" event
        // only accepts the two object properties which accept strings.
        onPress={async () =>
          await analytics().logSelectContent({
            content_type: 'clothing',
            item_id: 'abcd',
          })
        }
      />
    </View>
  );
}
```

No logs of events shown. I could be looking in the wrong place.

**Comment by mikehardy** [comment] 2021-02-07 19:00
Best advice is to check the docs thoroughly, I suggest focusing on the android side of things first, and checking the analytics docs for firebase-android-sdk specifically how to turn on debug logging for analytics and then watch `adb logcat` to see the results as you attempt to log things, while watching the debug event stream on the firebase console. Explore logging different type of events to see how it goes, and note that sometimes things just don't work, e.g. https://rnfirebase.io/faqs-and-tips#i-have-a-custom-analytics-parameter-called-items-and-its-not-showing-up-on-the-firebase-console-how-come

**Comment by HeIp** [comment] 2021-02-08 04:01
Got it to work but doesn't show in firebase in real time, seems there's a delay on their platform.

**Comment by mikehardy** [comment] 2021-02-08 04:06
Unfortunately that is the case for some of the items, while that is understandably frustrating I don't think it's actionable here, so I'm going to close this. Good luck with your project!

**Closed by mikehardy** 2021-02-08 04:06 UTC
Labels: Help: Needs Triage, Impact: Bug

**Comment by willks** [comment] 2022-02-16 11:15
> Got it to work but doesn't show in firebase in real time, seems there's a delay on their platform.

Yes there is a delay, and also not real-time accurate. I've been monitoring server events and Firebase events - I don't think it's a library issue. Maybe it's due to Firebase/Google geo-location - refresh the Firebase pages and you get different results some times.

**Comment by mtoninelli** [comment] 2022-02-21 09:35
@willks Yes, same here. I can confirm what you said.

**Comment by wgsquayson** [comment] 2022-08-01 17:58
@HeIp how did you get it to work?

**Comment by Spixz** [comment] 2023-01-05 16:52
Same problem for me on flutter. Apparently the bug come from google since severals years. [Source](https://stackoverflow.com/questions/71251235/items-are-not-showing-in-firebase-analytics#comment125962619_71251235)

**Comment by russelRajitha** [comment] 2023-01-11 05:42
i am also trying to log some events but noting happens
