### ISSUE TITLE
[Android][Database] Reference.on('value') calling success callback twice when arrays or numbers are updated

### ISSUE THREAD

**Issue by greena13** [invertase/react-native-firebase#92] opened 2017-05-06 13:40 UTC
When binding a callback using `Reference.on('value',...)` to a location with an array, the callback is correctly called once with the entire array.

However, when that array is changed (`Reference.set()` is called), the callback is called twice, instead of once, with the new value.

This can be seen in a number of failing tests in the Database test suite on https://github.com/invertase/react-native-firebase/pull/91.

**Comment by chrisbianca** [comment] 2017-05-07 14:56
I noticed this when implementing the database changes.  It seemed to be an issue with the Android Firebase library, not in the RNFirebase library, but I could be wrong - I didn't have a lot of time to debug the issue, but there was only a single listener being added to Firebase, but it was receiving 2 events.

**Comment by greena13** [comment] 2017-05-08 05:16
Strange. Do you know of the best place to raise this issue with the Firebase team?

What's the best way of working around this issue in the meantime? In the Java code, wrap the callback in some of check to prevent the second call? 

What would be the best way of detecting the second call as being a duplicate? Perhaps wrap the callback in a routine that increments a counter every time, and then only calls the JavaScript callback if the counter is odd. 

The first time (with the initial data) the counter would be 1 - odd - and execute the callback. The first time the data is modified, it would be 2 - even - so it wouldn't be called. The second, duplicate time it's called (still for the first time the data is modified) the counter would be 3 - odd - so the JS callback would be called. And so on, until the callback is removed.

Not ideal, but I think it would work.

**Comment by Salakar** [comment] 2017-05-08 13:58
Wasn't this actually as intended - is setPersistence on? With that on firebase does fire events twice, once when it reads from the locally cached data, and the 2nd time once it gets back a response from the server

**Comment by greena13** [comment] 2017-05-08 17:17
I am not sure, to be honest.

**Observations:**

When I comment out `persistence: true` in `src/firebase.js` (and close the app completely and re-open to be sure the change has applied to the underlying `FirebaseDatabase` Java instance), the test for the callback being executed only twice, still fails.

When I switch to using the web instance, the test passes.

When I add `persistence: true` to the web instance configuration in `src/firebase.js` the test still passes - I actually think this isn't a recognised configuration option of the web instance.

**Documentation:**

https://firebase.google.com/docs/reference/js/firebase.database.Reference#on states 

> value event
> This event will trigger once with the initial data stored at this location, and then trigger again each time the data changes. The DataSnapshot passed to the callback will be for the location at which on() was called. **It won't trigger until the entire contents has been synchronized**. If the location has no data, it will be triggered with an empty DataSnapshot ( val() will return null).

https://firebase.google.com/docs/reference/js/firebase.database.Database#goOffline says

> While offline, the client will no longer receive data updates from the Database. However, **all Database operations performed locally will continue to immediately fire events**, allowing your application to continue behaving normally. Additionally, each operation performed locally will automatically be queued and retried upon reconnection to the Database server.

If we want to adhere to the Web API, I think we should probably make it only fire once:

* When persistence is enabled, fire immediately
* When persistence is not enabled, fire when the synchronisation has complete

I'll have a think about the best way of achieving this, but does anyone else have any alternative ideas?

**Comment by Salakar** [comment] 2017-05-08 17:36
This is probably just a bug then in the implementation, is it definitely just array ones that are calling back twice?

RE: the firing twice with persistence, this is intended by google so as to appear responsive - for example if you're offline you'll still get the first event from cache but not the second. This should stay as is really.

**Comment by chrisbianca** [comment] 2017-05-08 20:03
I've just double checked this.  It's definitely the Firebase Android library that's sending the duplicate event and nothing within RNFirebase causing the issue.  RNFirebase correctly adds the listener, and when the array is updated receives two 'value' events from Firebase Android.  

I don't think we should be adding anything into RNFirebase to 'correct' this behaviour as it's rightly or wrongly coming from Firebase Android.  Firebase iOS doesn't have the same behaviour, so it may be a bug in Firebase's Android implementation and worth reporting to them.

Regardless, other than a duplicate event, this shouldn't affect your app at all, as it should be set up to handle multiple 'value' events anyway.

I'd be inclined to treat this as accepted behaviour and 'fix' the test by adding a Platform specific check which looks for the extra event on Android.  At least that way, people aren't going to be concerned at this false positive and if Firebase fix it in the future we'll be aware of the change.

**Comment by Salakar** [comment] 2017-05-08 23:19
I'll make a support request tomorrow with fb if that's the case

**Comment by greena13** [comment] 2017-05-09 06:26
Strangely, my preliminary tests suggest the callback gets executed twice for array and number values, but not for boolean, string and object values. 

I've tested this just by commenting out each value type in `DatabaseContents.js` and running the test `on('value') calls callback with the initial data and then when value changes`.

I thought this may be misleading due to race conditions - for whatever reason array and number call the callback a second time, faster and it gets detected by the test assertion - so I added a 2 second wait between the update and the assertion for all data types and the results remain the same.

The "problem" still occurs for an array with a single element and a single digit number, so it doesn't seem to be tied to the complexity of updating the existing object.

> RE: the firing twice with persistence, this is intended by google so as to appear responsive - for example if you're offline you'll still get the first event from cache but not the second. This should stay as is really.

So, just to clarify, we are in agreeance that the callback should only ever be called once, but you are proposing that when persistence is enabled, that one time should be the initial event and *not* once synchronisation has occurred (as is stated by the Firebase Web API documentation). i.e. We should deviate from the documented behaviour of the Web API in the interest of responsiveness and to honour Google's intentions on the mobile platform?

**Comment by greena13** [comment] 2017-05-09 06:53
I've pushed an update to the tests. I didn't know any other way of linking the commit to this issue, so I marked it as closed.

Reopening now as it requires additional action - raising the issue with Firebase.

**Comment by Salakar** [comment] 2017-05-10 15:41
@puf is this something you may be able to advise on, seems to be a bug with the firebase android sdk, unless this is an intended difference from the other SDK's?

**Comment by Salakar** [comment] 2017-05-10 15:59
Or maybe @samtstern? 🙄

**Comment by NielsLindberg** [comment] 2017-05-16 22:25
Also ran into this issue.

The workaround i ended up with was to do a deep object comparison with lodash between the current and previous snap before continuing with the rest of the redux flow. It cut my processing time down to approx half.

`getState().backend.userRef.child('trips').on('value', (snap) => {
	   		if(typeof getState().trips.userTrips.val === 'function') {
	   				if(!_.isEqual(snap.val(), getState().trips.userTrips.val())) {
	   					dispatch(setUserTrips(snap));
	   				}
	   			} else {
	   				dispatch(setUserTrips(snap));
	   			}
	   		dispatch(setUserTripsFetching(false));
		})`

**Comment by chrisbianca** [comment] 2017-06-16 15:45
This is now fixed in the v2.0 branch.  It seems v11 of Firebase for Android has fixed the problem.

**Closed by chrisbianca** 2017-06-16 15:45 UTC
Labels: android, database, firebase-issue
