### ISSUE TITLE
[npm-issue] packages removed / not available after install

### ISSUE THREAD

**Issue by barjas** [invertase/react-native-firebase#190] opened 2017-06-22 08:10 UTC
after running "npm i react-native-firebase --save" i get the following message:
`**added 31 packages, removed 649 packages and updated 113 packages in 19.899s**`

and when i try to run "**react-native run-ios**", i get "Command `run-ios` unrecognized"

what am doing wrong ?

**Comment by SamMatthewsIsACommonName** [comment] 2017-06-22 14:29
Same here, the install removes all of the react native packages etc for some reason

**Comment by Salakar** [comment] 2017-06-22 15:24
Hmm this is a weird one - what are your npm versions @barjas @SamMatthewsIsACommonName - this may be a npm v5 issue - can you down grade your npm and give it a whirl - see if it's actually that?

**Comment by SamMatthewsIsACommonName** [comment] 2017-06-22 15:30
OK I will do after dinner. My project is now broken again so I need to start a new one. I've been battling cocoapods/ problems with latest react native for last 5 hours straight and about to pull my hair out haha

**Comment by Salakar** [comment] 2017-06-22 15:52
Confirmed other npm 5 users are facing this issue:

https://github.com/npm/npm/issues/17379
https://github.com/npm/npm/issues/17384

Rollback to 4 for now

**Comment by Salakar** [comment] 2017-06-22 16:09
Will leave this open for now until the npm issue is resolved.

**Comment by guhungry** [comment] 2017-06-26 04:29
Sometimes I have to switch to yarn if npm install have problem (with npm 5.0.3 since it comes with node 8.1.2 by default)

**Comment by chrisbianca** [comment] 2017-07-20 07:23
@Salakar according to https://github.com/npm/npm/issues/17384 this was fixed in npm 5.1.0.  I've just updated to npm 5.3.0 and everything seemed to work ok, so will close this issue.

**Closed by chrisbianca** 2017-07-20 07:23 UTC
