### ISSUE TITLE
🔥[React-Native-Messaging] Show Stopper ===> with react-native-messaging 6.4.0, no longer able to show local notifications

### ISSUE THREAD

**Issue by guanhuay** [invertase/react-native-firebase#3393] opened 2020-04-04 18:13 UTC
## Issue

Describe your issue here

I have tried integrate react-native-firebase-messaging v6.4.0 into my project to receive FCM messaging.

However i have tried all three recommend libraries below to show simple local notification:
1. react-native-push-notifications
2. react-native-notifications
3. expo-notifications

None of then worked on IOS even for a simple show local notifications action.

If I delete react-native-firebase-messaging v6.4.0 from my package.json file, notification shows up without any problem. Please see below for simple code to reproduce the bug.

**Note: I already tried most of the previous version, react-native-firebase v6.3.4 is latest version that works.**

---

### Javascript
```
import React, {useEffect, Fragment} from 'react';
import { Button, StatusBar, StyleSheet, View } from 'react-native';
import * as Notifications from "expo-notifications";

Notifications.setNotificationHandler({
  handleNotification: async (notification) => {
    return {
      shouldShowAlert: true,
      shouldPlaySound: true,
      shouldSetBadge: false,
    };
  },
});

const requestNotificationPermissionAsync = async () => {
  return await Notifications.requestPermissionsAsync({
    ios: {
      allowAlert: true,
      allowSound: true,
      allowBadge: false,
      allowAnnouncements: true,
    },
  });
};

export default function App() {
  useEffect(() => {
    requestNotificationPermissionAsync().then(() => {});
  }, []);

  return (
      <View style={styles.container}>
        <Button
            title="Show notif"
            onPress={() => {
              Notifications.scheduleNotificationAsync({
                content: {
                  title: "Look at that notification",
                  body: "I'm so proud of myself!",
                },
                trigger: {
                  seconds: 1,
                },
              });
            }}
        />
      </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```
#### `package.json`:

```
{
  "main": "index.js",
  "scripts": {
    "start": "react-native start",
    "start:clean": "react-native start --reset-cache",
    "android": "npx react-native run-android",
    "android:big": "npx react-native run-android --deviceId emulator-5554 --reset-cache",
    "ios": "npx react-native run-ios --simulator=\"iPhone 11\"",
    "ios:big": "npx react-native run-ios --simulator=\"iPhone 11 Pro\"",
    "link:ios": "cd ios && pod install && cd ..",
    "doctor": "npx react-native doctor",
    "build:apk": "cd android && ./gradlew assembleRelease",
    "android:clean": "watchman watch-del-all && rm -rf /tmp/metro-bundler-cache-* && cd android && ./gradlew clean && cd ..",
    "lint": "eslint",
    "link:fix": "eslint --fix",
    "test": "jest",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "^37.0.4",
    "expo-updates": "^0.1.1",
    "expo-notifications": "^0.1.1",
    "react-native-unimodules": "^0.9.0",
    "react": "16.9.0",
    "react-dom": "^16.9.0",
    "react-native": "0.61.5",
    "react-native-web": "~0.11.7",
    "@react-native-firebase/app": "^6.4.0-rc4",
    "@react-native-firebase/auth": "^6.4.0-rc4",
    "@react-native-firebase/firestore": "^6.4.0-rc4",
    **"@react-native-firebase/messaging": "^6.4.0-rc4",**
  },
  "devDependencies": {
    "@babel/core": "~7.8.6",
    "babel-jest": "~24.9.0",
    "jest": "~24.9.0",
    "metro-react-native-babel-preset": "~0.56.4",
    "react-test-renderer": "~16.9.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'myapp' do
  rnPrefix = "../node_modules/react-native"

  # React Native and its dependencies
  pod 'FBLazyVector', :path => "#{rnPrefix}/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "#{rnPrefix}/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "#{rnPrefix}/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "#{rnPrefix}/Libraries/TypeSafety"
  pod 'React', :path => "#{rnPrefix}/"
  pod 'React-Core', :path => "#{rnPrefix}/"
  pod 'React-CoreModules', :path => "#{rnPrefix}/React/CoreModules"
  pod 'React-RCTActionSheet', :path => "#{rnPrefix}/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{rnPrefix}/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{rnPrefix}/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{rnPrefix}/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{rnPrefix}/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{rnPrefix}/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{rnPrefix}/Libraries/Settings"
  pod 'React-RCTText', :path => "#{rnPrefix}/Libraries/Text"
  pod 'React-RCTVibration', :path => "#{rnPrefix}/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', :path => "#{rnPrefix}/"
  pod 'React-Core/DevSupport', :path => "#{rnPrefix}/"
  pod 'React-cxxreact', :path => "#{rnPrefix}/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{rnPrefix}/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{rnPrefix}/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{rnPrefix}/ReactCommon/jsinspector"
  pod 'ReactCommon/jscallinvoker', :path => "#{rnPrefix}/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "#{rnPrefix}/ReactCommon"
  pod 'Yoga', :path => "#{rnPrefix}/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => "#{rnPrefix}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rnPrefix}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rnPrefix}/third-party-podspecs/Folly.podspec"

  # Other native modules

  # Automatically detect installed unimodules
  use_unimodules!

  # react-native-cli autolinking
  use_native_modules!
end

```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.67 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by ASchwad** [comment] 2020-04-05 11:39
I can confirm this issue with react-native-push-notification.
iOS Notifications work fine (Fore- and Background) in 6.3.4
in 6.4.0 they only work in the background

**Comment by LuongTruong** [comment] 2020-04-06 02:24
Hello @guanhuay , thank you for saving my life. I get stuck in this since Friday until now. I guessed it is happening because of my config, thanks again.

**Comment by Ehesp** [comment] 2020-04-06 07:55
This is being tracked as part of https://github.com/invertase/react-native-firebase/issues/3367

It seems the updates to 6.4.0 with delegate swizzling need to be extended to also swizzle in delegate methods from other libraries which make use of the notification centre delegate handlers.

Will close this - please follow/comment on #3367

**Closed by Ehesp** 2020-04-06 07:55 UTC
