### ISSUE TITLE
[🐛] dynamicLinks().getInitialLink() returning null + dynamicLinks().resolveLink() returning Dynamic link not found + iOS specific

### ISSUE THREAD

**Issue by haxakl** [invertase/react-native-firebase#4527] opened 2020-11-10 13:58 UTC
🔥

## Issue

DynamicLinks.getInitialLink() returning null. I can get the url through Linking.getInitialURL() but when i try to resolve the link with dynamicLinks().resolveLink(), it's returning an exception "Dynamic link not found".

I searched for a day but nothing worked. On Android everything is working well. I don't know how to debug, find the problem and resolved it.

---

## Project Files

<details><summary>Click To Expand</summary>
<p>

### Apple app site association (https://__.page.link/apple-app-site-association)

```json
{"applinks":{"apps":[],"details":[{"appID":"TEAMID.com.___.___","paths":["NOT /_/*","/*"]}]}}
```

### Firebase App & Team ID

![Image of Firebase App ID](https://cdn.discordapp.com/attachments/771737549835993098/775719628692914176/Firebase_team__app_id.jpg)

![Image of Firebase page link](https://cdn.discordapp.com/attachments/771737549835993098/775719631137669141/prefix_on_firebase_dynamic_links.jpg)

### On Xcode

![Image of Bundle ID](https://cdn.discordapp.com/attachments/771737549835993098/775719633692786690/Bundle_ID_xcode.jpg)

![Image of Applinks](https://cdn.discordapp.com/attachments/771737549835993098/775719635395280926/Applinks.jpg)

</p>
</details>

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
    "name": "",
    "version": "1.1.2",
    "private": true,
    "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "start": "react-native start",
        "test": "jest",
        "lint": "eslint .",
        "build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'"
    },
    "dependencies": {
        "@invertase/react-native-apple-authentication": "^2.0.0",
        "@react-native-community/async-storage": "^1.12.1",
        "@react-native-community/geolocation": "^2.0.2",
        "@react-native-community/google-signin": "^5.0.0",
        "@react-native-community/image-editor": "^2.3.0",
        "@react-native-community/masked-view": "^0.1.10",
        "@react-native-firebase/analytics": "^7.6.8",
        "@react-native-firebase/app": "^8.4.6",
        "@react-native-firebase/dynamic-links": "^7.5.10",
        "@react-native-firebase/messaging": "^7.9.1",
        "i18n-js": "github:fnando/i18n-js",
        "moment": "^2.29.1",
        "moment-timezone": "^0.5.31",
        "react": "16.13.1",
        "react-native": "^0.63.3",
        "react-native-app-auth": "^6.0.0",
        "react-native-calendars": "^1.403.0",
        "react-native-camera": "^3.40.0",
        "react-native-countdown-component": "^2.7.1",
        "react-native-drawer-layout": "^2.0.0",
        "react-native-exception-handler": "^2.10.8",
        "react-native-fast-image": "^8.3.2",
        "react-native-fbsdk": "^2.0.0",
        "react-native-gesture-handler": "^1.8.0",
        "react-native-image-picker": "^2.3.4",
        "react-native-linear-gradient": "^2.5.6",
        "react-native-localize": "^1.4.2",
        "react-native-maps": "^0.27.1",
        "react-native-paypal": "^3.1.1",
        "react-native-permissions": "^2.2.2",
        "react-native-picker-select": "^8.0.1",
        "react-native-progress-steps": "^1.3.4",
        "react-native-qrcode-scanner": "^1.4.1",
        "react-native-qrcode-svg": "^6.0.6",
        "react-native-reanimated": "^1.13.1",
        "react-native-render-html": "^4.2.4",
        "react-native-safe-area-context": "^3.1.8",
        "react-native-scalable-image": "^1.0.0",
        "react-native-screens": "^2.11.0",
        "react-native-simple-dialogs": "^1.4.0",
        "react-native-splash-screen": "^3.2.0",
        "react-native-svg": "^12.1.0",
        "react-native-system-setting": "^1.7.6",
        "react-native-twitter-signin": "^1.1.1",
        "react-native-vector-icons": "^7.1.0",
        "react-native-version-check": "^3.4.2",
        "react-native-webview": "^10.9.2",
        "react-navigation": "^4.4.2",
        "react-navigation-stack": "^2.8.4",
        "react-number-format": "^4.4.1",
        "rollbar-react-native": "^0.9.1",
        "socket.io-client": "^2.3.1",
        "underscore": "^1.11.0"
    },
    "devDependencies": {
        "@babel/core": "^7.11.6",
        "@babel/plugin-proposal-decorators": "^7.10.5",
        "@babel/runtime": "^7.11.2",
        "@react-native-community/eslint-config": "^2.0.0",
        "@types/jest": "^24.0.23",
        "@types/moment-timezone": "^0.5.30",
        "@types/react": "^16.9.49",
        "@types/react-native": "^0.63.23",
        "@types/react-native-calendars": "^1.20.10",
        "@types/react-native-drawer-layout": "^1.3.5",
        "@types/react-native-fbsdk": "^1.1.0",
        "@types/react-native-i18n": "^2.0.0",
        "@types/react-native-qrcode": "^0.2.2",
        "@types/react-native-vector-icons": "^6.4.6",
        "@types/react-native-version-check": "^3.4.1",
        "@types/react-test-renderer": "^16.9.3",
        "@types/socket.io-client": "^1.4.34",
        "@types/underscore": "^1.10.24",
        "babel-jest": "^24.9.0",
        "eslint": "^6.7.2",
        "jest": "^24.9.0",
        "metro": "^0.59.0",
        "metro-react-native-babel-preset": "^0.57.0",
        "prettier": "^2.1.2",
        "react-test-renderer": "16.9.0",
        "typescript": "^4.0.3"
    },
    "jest": {
        "preset": "react-native"
    },
    "rnpm": {
        "assets": [
            "./assets/fonts"
        ]
    }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
{
    "react-native": {
        "messaging_android_headless_task_timeout": 30000
    }
}

```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods', :deterministic_uuids => false

platform :ios, '11.0'

target 'test' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'

  use_react_native!(:path => config["reactNativePath"])

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'

  target 'testTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

```ruby
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>--</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>Facebook ID</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>--</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>Twitter ID</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>--</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>Bundle ID</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.__.__</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>Google map ID</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>--</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>FacebookAppID</key>
	<string>--</string>
	<key>FacebookDisplayName</key>
	<string>--</string>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<string>yes</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>--</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>--</string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>--</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>--</string>
	<key>UIAppFonts</key>
	<array>
		<string>AntDesign.ttf</string>
		<string>Entypo.ttf</string>
		<string>EvilIcons.ttf</string>
		<string>Feather.ttf</string>
		<string>FontAwesome.ttf</string>
		<string>FontAwesome5_Brands.ttf</string>
		<string>FontAwesome5_Regular.ttf</string>
		<string>FontAwesome5_Solid.ttf</string>
		<string>Fontisto.ttf</string>
		<string>Foundation.ttf</string>
		<string>Ionicons.ttf</string>
		<string>MaterialCommunityIcons.ttf</string>
		<string>MaterialIcons.ttf</string>
		<string>Octicons.ttf</string>
		<string>SimpleLineIcons.ttf</string>
		<string>Zocial.ttf</string>
		<string>Aclonica.ttf</string>
		<string>BebasNeue-Regular.ttf</string>
		<string>OpenSans-Bold.ttf</string>
		<string>OpenSans-Light.ttf</string>
		<string>OpenSans-Regular.ttf</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UIRequiresFullScreen</key>
	<true/>
	<key>UIStatusBarHidden</key>
	<false/>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import "RNPaypal.h"
#import "RNSplashScreen.h"
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <GoogleMaps/GoogleMaps.h>
#import <TwitterKit/TWTRKit.h>
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"dragonlineplayer"
                                            initialProperties:nil];
  
  [[RNPaypal sharedInstance] configure];
  [[Twitter sharedInstance]startWithConsumerKey:@"test" consumerSecret:@"test"];
  
  [GMSServices provideAPIKey:@"test"];
  
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  [RNSplashScreen show];
  return YES;
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [[Twitter sharedInstance] application: application openURL:url options:options] || [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options] || [[RNPaypal sharedInstance] application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [[RNPaypal sharedInstance] application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 20.54 MB / 8.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: Yarn v0.1.1 2011 Jesper Kjeldgaard - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.3 => 0.63.3 
  npmGlobalPackages:
    react-native: 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - ^8.4.6`
- **`Firebase` module(s) you're using that has the issue:**
  - Dynamic-links
- **Are you using `TypeScript`?**
  - Y & 4.0.3

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2020-11-10 14:00
if it works on android but not ios, I wonder if there is some ios config missing, like settings in the plist for the domains that are links etc? I know I have this working in my app, on ios so it is possible, but I'm not sure what it can be. I recognize this is a very vague response - I am sorry - I won't have time to look deeply into it for a while unfortunately

**Comment by mikehardy** [comment] 2020-11-10 14:04
oh - probably unrelated but there have been reports upstream (firebase-ios-sdk repo) where iOS was not fetching and installing the app association links correctly, and if I remember correctly it was sort of device/network specific and reboots may have fixed it. Apologies again for the vague responses

**Comment by haxakl** [comment] 2020-11-10 14:05
Thank you for these quick answer!

I will change to integrate the plist. I(ll try to restart my iPad and try again

**Comment by janpe** [comment] 2020-11-12 06:50
@haxakl did you get this to work? I'm facing a similar problem on iOS. If the app is not open in the background, then getInitialLink return null. But if the app is open in the background, then it works as intended. No problem on Android.

**Comment by haxakl** [comment] 2020-11-12 12:26
@janpe No. I don't know what to do. The problem is just on iOS so I think the problem is from our config but I don't see what is wrong from all the docs and tutorial I found on the web. Let me try when the app is closed.

**Comment by mikehardy** [comment] 2020-11-12 12:58
@haxakl I can't reproduce that in my app. initial link works even after force closing the app then opening the app via link. perhaps you are calling getInitialLink to soon? If I recall you need to call it after initial root view component mount

**Comment by haxakl** [comment] 2020-11-12 13:27
@mikehardy I do it in the componentDidMount of my App.tsx. And if I do the resolveLink manually from a button it says the same "Dynamic Link not found"
@janpe It's not working for me even the app is closed. Only Linking from react catch the link.

**Comment by mikehardy** [comment] 2020-11-12 13:36
if resolveLink is not working when called directly then there is some deeper underlying problem with either your input not being an actual link (test it by pasting it into a browser with '?d=1' on the end to debug it, e.g. https://appdev.komp.ai/me/qbvQ?d=1) or your config not being correct.

**Comment by haxakl** [comment] 2020-11-12 13:48
@mikehardy oh! ok i have 3 warnings.

```
Android app 'com.__.__' lacks SHA256. AppLinks is not enabled for the app. Learn more.
Android app 'host.exp.exponent' lacks SHA256. AppLinks is not enabled for the app. Learn more.
There is no configuration to prevent phishing on this domain https://dragonline.page.link. Setup URL patterns to whitelist in the Firebase Dynamic Links console.
```
I'm going to resolve it before continue.

**Comment by mikehardy** [comment] 2020-11-12 13:51
Ok - I'm going to resolve this, as it appears to be project-specific, these APIs are working in the module (and I added the resolveLink API here, plus the unit test that runs in CI which passed before I personally performed the last release plus it works in my app - so I have a high amount of confidence)

**Closed by mikehardy** 2020-11-12 13:51 UTC
Labels: Help: Needs Triage, Impact: Bug
