### ISSUE TITLE
[🐛] iOS device fails to connect firebase emulator

### ISSUE THREAD

**Issue by ziyafenn** [invertase/react-native-firebase#4875] opened 2021-02-05 20:48 UTC
## Issue

iOS **device** fails to connect Firebase Emulator (auth, firestore) on localhost. No problem with the simulator.
On Android, everything works perfectly on the device too.

I tried to enable `NSAllowsArbitraryLoads` and `NSAllowsLocalNetworking` in _Info.plist_ without any domain exceptions, no success.

Here is the piece of code to connect RN to emuator: 

```
db.settings({
        host: `192.168.0.13:8080`,
        ssl: false,
        persistence: false,
        cacheSizeBytes: firestore.CACHE_SIZE_UNLIMITED,
      });
```
Here is the piece of log from Xcode: 

```
NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=http://192.168.0.13:8081/status,
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [X ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 10.5.0
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - Y

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2021-02-05 21:00
I'm not sure, but if android device and ios smulator is able to connect to it, that means the emulator is working, and the configuration is working.

The emulator has a UI that runs on port 4000 if I recall correctly. (it says as much in the console when you start the emulator) Are you able to just use a browser on the iOS device and hit the UI? That might help figure out where the problem is

**Comment by ziyafenn** [comment] 2021-02-05 21:03
@mikehardy yes, i can use browser and connect to the emulator (i.e. hosting instance) using same IP address.

**Comment by mikehardy** [comment] 2021-02-05 21:05
Why is the db configured for 8080 but log message is for 8081? 🤔

**Comment by ziyafenn** [comment] 2021-02-05 21:34
No idea, but 8081 is default metro port if i'm not mistaken and i can connect to the development server.

Can you please try and replicate this issue on your end if you happen to have an iOS device?

**Comment by mikehardy** [comment] 2021-02-06 00:52
I can try but I make no guarantee on timing, it might not be until end of next week, I'm set to do some emulator work then and I've already spent a big block of time on react-native-firebase this week so I'm out of time for a while, sorry

**Comment by mikehardy** [comment] 2021-02-06 13:14
I believe @Olivierlesnicki saw similar in #4878 and found an upstream issue related - resolving this as a duplicate as that has an upstream link

**Closed by mikehardy** 2021-02-06 13:14 UTC
Labels: Help: Needs Triage, Impact: Bug, Workflow: Needs Review
