### ISSUE TITLE
[🐛] Bug at React Native 0.69.3

### ISSUE THREAD

**Issue by huoengineer** [invertase/react-native-firebase#6423] opened 2022-07-26 15:29 UTC
Not working react-native-firebase module in react-native 0.69.3

**Comment by jeveloper** [comment] 2022-07-27 20:24
@huoengineer  Huo, Don't leave people guessing. Empathy starts with seeing others' perspectives.

**Comment by huoengineer** [comment] 2022-07-27 20:30
@jeveloper Serge, react-native-firebase, would you tell me the working answer at react-native 0.69.3?

**Comment by MeetSuhagiya** [comment] 2022-07-28 10:01
Hello,
react-native-firebase is not working in IOS as we are unable to do pod install whenever we add this library to the react-native 0.69.3 even if we have disabled flipper and hermes in addition to that we also added use_frameworks! but still no success.
Can you give a proper documentation for that?

**Comment by nighttiger1990** [comment] 2022-07-28 12:13
comment use_frameworks! and add these line in Podfile. I install and build app successfully
```ruby
  # use_frameworks!
  $RNFirebaseAsStaticFramework = true
  config = use_native_modules!

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
```

**Comment by mikehardy** [comment] 2022-07-30 21:31
@nighttiger1990 that is not a supportable solution and you should have no expectation it will work going forward, unfortunately. I understand it's difficult at the moment but the firebase-ios-sdk underlying this module *requires* `use_frameworks!`. Attempting to circumvent that will result in pain either now (if you require storage or functions, which strictly require use_frameworks already) or in future (as more modules start to strictly require it).

Either use react-native-firebase v14, or turn off flipper and hermes and make sure other modules work, and 0.69.3 will work for you, at least as recently as 0.69.1

Here it is working with 0.69.1, all modules: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh - if you read through that, and/or run it locally it should work. I sincerely hope that helps

In the meantime, this is largely duplicate of #6332 and should be tracked there

In future definitely follow this article as a guideline for logging issues: https://stackoverflow.com/help/how-to-ask

**Closed by mikehardy** 2022-07-30 21:31 UTC
Labels: Impact: Bug, Help: Needs Triage
