### ISSUE TITLE
[🐛] Display name is null

### ISSUE THREAD

**Issue by moas** [invertase/react-native-firebase#7621] opened 2024-02-13 00:31 UTC
Hello,
My application doesn't pass Apple's validation because the "displayName" attribute of the returned user is set to null.
Below is the message Apple sent me:

```
Regarding 4.0, concerning the Sign In With Apple Login Issue.

Please find enclosed the step by step screenshots we have after using Sign in with Apple.

To have this issue resolved, the last screenshot “Mon Profil” asking again the Name and Surname of the usera have to be removed because here, the app requires users to provide their name and/or email address after using Sign in with Apple. This information is already provided by the [Authentication Services framework](https://developer.apple.com/documentation/authenticationservices). 

Please revise the Sign in with Apple experience in your app to address the issues we identified above.
```

Below are the versions of the library I use:
```
"@react-native-firebase/app": "^18.3.2",
"@react-native-firebase/auth": "^18.3.2",
"@react-native-firebase/database": "^18.3.2",
"@react-native-firebase/messaging": "^18.3.2"
```

And I specify the scopes well:
```
const appleAuthRequestResponse = await appleAuth.performRequest({
                requestedOperation: appleAuth.Operation.LOGIN,
                requestedScopes: [appleAuth.Scope.FULL_NAME, appleAuth.Scope.EMAIL],
            });

```

**Comment by mikehardy** [comment] 2024-02-14 16:11
Hello 👋 - @moas I believe this is a duplicate of #7603

**Closed by mikehardy** 2024-02-14 16:11 UTC
Labels: Impact: Bug, Help: Needs Triage
