### ISSUE TITLE
onNotificationOpened isn't called when opening remote notification on iOS

### ISSUE THREAD

**Issue by siderakis** [invertase/react-native-firebase#1517] opened 2018-09-22 15:36 UTC
### Issue

The callback is never called when opening remote notifications. Local notifications do fire the callback when opened.
  ```
 firebase
          .notifications()
          .onNotificationOpened((notificationOpen: NotificationOpen) => {
            alert("onNotificationOpened")
          })
```

The same remote notifications will fire getInitialNotification if opened when the app is closed.

### Environment

1. Application Target Platform: iOS
2. Development Operating System: MacOS
3. Build Tools: Xcode
4. `React Native` version:  "react-native": "0.55.4",
5. `React Native Firebase` Version:  "react-native-firebase": "^5.0.0-rc4",
6. `Firebase` Module:

 ```
pod 'Firebase/Core', '~> 5.3.0'
 pod 'Firebase/Messaging', '~> 5.3.0'
 pod 'Firebase/Auth', '~> 5.3.0'
 pod 'Firebase/DynamicLinks', '~> 5.3.0'
 pod 'Firebase/Performance', '~> 5.3.0'

```
7. Are you using `typescript`?: No

**Comment by ThomasAbbink** [comment] 2018-10-09 09:44
Same issue here.

`  pod 'Firebase/Core', '~> 5.3.0'
    pod 'Firebase/Database', '~> 5.3.0'
    pod 'Firebase/Auth', '~> 5.3.0'
    pod 'Firebase/Messaging', '~> 5.3.0'
    pod 'Firebase/Functions', '~> 5.3.0'`

`{
    "react-native": "0.55.2",
   "react-native-firebase": "^4.3.8"
}`

**Comment by Salakar** [comment] 2018-10-23 12:12
Duplicate of #1149 and many others, lets track all `onNotificationOpened` opened issues in one place please (same platform or not please discuss on #1149).

Thanks

**Closed by Salakar** 2018-10-23 12:12 UTC
