### ISSUE TITLE
App Check Replay Protection

### ISSUE THREAD

**Issue by apetta** [invertase/react-native-firebase#7394] opened 2023-10-04 17:25 UTC
Hi!
Would it be possible to use the app-check [replay protection](https://firebase.google.com/docs/app-check/ios/custom-resource#replay-protection) with this library?

**Comment by mikehardy** [comment] 2023-10-20 17:43
Interesting - I haven't contemplated adding support for it, but I would happily merge any reasonable PR that implemented the API and wrapped the underlying native calls

This is the API to model, as we use the firebase-js-sdk API shapes: https://firebase.google.com/docs/app-check/web/custom-resource#replay-protection

**Comment by apetta** [comment] 2023-10-26 21:10
> Interesting - I haven't contemplated adding support for it, but I would happily merge any reasonable PR that implemented the API and wrapped the underlying native calls
> 
> This is the API to model, as we use the firebase-js-sdk API shapes: https://firebase.google.com/docs/app-check/web/custom-resource#replay-protection

Just submitted a PR. Would be great if you could have a look :)

**Comment by mikehardy** [comment] 2023-11-24 02:01
Not stale and neither is the PR - definitely going to happen - sorry for the delay - thank you for your patience

**Comment by JasonPan** [comment] 2023-12-20 16:09
I seem to be getting an issue related to the work on the linked PR, is this feature still a work in progress?

I'm just trying to set up the baseline AppCheck functionality at the moment and came across this error. Led me to this issue / PR

<img width="817" alt="image" src="https://github.com/invertase/react-native-firebase/assets/6129538/ba0fc20e-a8de-4947-9263-a463dc1df184">

**Comment by JasonPan** [comment] 2023-12-20 16:20
(This is on the latest version 18.7.3, 18.6.1 seems to work okay)

**Comment by apetta** [comment] 2023-12-20 16:57
Hmm, I was able to get it up & running on the latest version. 

It might be worth opening a new issue with more details of your setup

**Comment by mikehardy** [comment] 2023-12-20 20:57
@JasonPan You have most likely overridden your firebase-ios-sdk version, which is something we intend to clearly note is *at your own risk* as we will adopt new features that require new versions of the SDK from time to time.

If you override your SDK and are not using the correct minimum version of firebase-ios-sdk as we direct in our app module package.json, you will see compilation errors like this

They are an indicator that you should take your firebase-ios-sdk version override out of your Podfile (preferred) or you must bump your firebase pod versions

**Comment by mikehardy** [comment] 2023-12-20 20:58
The feature has been merged though, and there's no further work planned. It appears to be working as intended.

**Closed by mikehardy** 2023-12-20 20:58 UTC
Labels: Type: Feature Request, Service: AppCheck

**Comment by JasonPan** [comment] 2023-12-22 03:53
Nevermind, thanks! You're right, I did just have to make sure all my RN Firebase dependencies were upgraded to the latest version, working now :)

**Comment by JasonPan** [comment] 2023-12-22 04:19
For my reference, did this issue also tackle implementing replay protection for Firebase Cloud Function calls?

e.g. using `getLimitedUseToken` with `functions().httpsCallable`, I can't seem to find where the token can be set.

**Comment by mikehardy** [comment] 2023-12-22 05:49
@JasonPan it is not easy to use, by my read, and the use case is specific to non-firebase resources yes - I think the firebase docs are pretty reasonable on how to use it though https://firebase.google.com/docs/app-check/web/custom-resource#replay-protection - you don't "set" the token, you send the limited use token to your non-firebase endpoint, and when that code goes to verify that the token is valid, it can also check if it's already been used, to guard against token reuse / replay

If I understand correctly
