### ISSUE TITLE
Execution failed for task ':react-native-firebase:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by buraksak35** [invertase/react-native-firebase#1315] opened 2018-07-18 14:26 UTC
![ekran resmi 2018-07-18 18 05 43](https://user-images.githubusercontent.com/39245976/42890401-6944f640-8ab5-11e8-9890-c1f82d0235db.png)

![ekran resmi 2018-07-18 17 15 41](https://user-images.githubusercontent.com/39245976/42887941-c7c98498-8aaf-11e8-875f-c633f701119e.png)

 React native android firebase install . Execution failed for task ':react-native-firebase:compileDebugJavaWithJavac

### Environment

1. Application Target Platform: 

Android

2. Development Operating System:

Mac OS

3. Build Tools:

buildToolsVersion '27.0.3' (Android)

4. `React Native` version:
0.56

5. `React Native Firebase` Version:

 "react-native-firebase": "^4.3.7",

6. `Firebase` Module:

core

7. Are you using `typescript`? 

no

---
Loving `react-native-firebase`? Please consider supporting them with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Ehesp** [comment] 2018-07-18 15:55
Duplicate of https://github.com/invertase/react-native-firebase/issues/1070

**Closed by Ehesp** 2018-07-18 15:55 UTC
