### ISSUE TITLE
[🐛] libc++abi.dylib: terminating with uncaught exception of type NSException | Terminating app due to uncaught exception 'NSInvalidArgumentException'

### ISSUE THREAD

**Issue by seamive** [invertase/react-native-firebase#4935] opened 2021-02-19 20:58 UTC
## Issue
Using `npx react-native` with all.
**NOTE:** changed my 'real app name' with 'myApp'
Getting this error on iOS 14.4 iPhone 11 Simulator & iPhone 12 Real Device

```
 -[fir_D620517E-4A34-48C6-976A-8A203DA26238_GULNetworkURLSession _flex_swizzle_74b39a6a_URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]: unrecognized selector sent to instance 0x600003e8b4e0

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[fir_D620517E-4A34-48C6-976A-8A203DA26238_GULNetworkURLSession _flex_swizzle_74b39a6a_URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]: unrecognized selector sent to instance


* First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204306f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff20426036 ___forwarding___ + 1489
	4   CoreFoundation                      0x00007fff20428068 _CF_forwarding_prep_0 + 120
	5   myApp                              0x000000010cceb30f __71+[FLEXNetworkObserver injectDownloadTaskDidWriteDataIntoDelegateClass:]_block_invoke.383 + 79
	6   myApp                              0x000000010ccdefbc +[FLEXNetworkObserver sniffWithoutDuplicationForObject:selector:sniffingBlock:originalImplementationBlock:] + 444
	7   myApp                              0x000000010cceb0d6 __71+[FLEXNetworkObserver injectDownloadTaskDidWriteDataIntoDelegateClass:]_block_invoke_2 + 710
	8   CFNetwork                           0x00007fff236cffd5 _CFNetworkHTTPConnectionCacheSetLimit + 160777
	9   libdispatch.dylib                   0x00000001119227ec _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00000001119239c8 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x0000000111931e75 _dispatch_main_queue_callback_4CF + 1152
	12  CoreFoundation                      0x00007fff2038fdbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x00007fff2038a63e __CFRunLoopRun + 2685
	14  CoreFoundation                      0x00007fff203896d6 CFRunLoopRunSpecific + 567
	15  GraphicsServices                    0x00007fff2c257db3 GSEventRunModal + 139
	16  UIKitCore                           0x00007fff24696cf7 -[UIApplication _run] + 912
	17  UIKitCore                           0x00007fff2469bba8 UIApplicationMain + 101
	18  myApp                              0x000000010c652a00 main + 112
	19  libdyld.dylib                       0x00007fff2025a3e9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[fir_D620517E-4A34-48C6-976A-8A203DA26238_GULNetworkURLSession _flex_swizzle_74b39a6a_URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]: unrecognized selector sent to instance 0x600003e8b4e0'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 11 (5C776520-5F33-4F6E-8A1F-8E60C6AC34BF) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 11

```

Describe your issue here

**I'm trying to use Firebase, as soon as I added and load it in AppDelegate.m it crashes.**
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```{
  "name": "myApp",
  "version": "0.0.3-alpha",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.13.4",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.10",
    "@react-native-firebase/admob": "^10.8.0",
    "@react-native-firebase/analytics": "^10.8.0",
    "@react-native-firebase/app": "^10.8.0",
    "@react-native-firebase/crashlytics": "^10.8.0",
    "@react-native-firebase/dynamic-links": "^10.8.0",
    "@react-native-firebase/iid": "^10.8.0",
    "@react-native-firebase/in-app-messaging": "^10.8.0",
    "@react-native-firebase/messaging": "^10.8.0",
    "@react-native-firebase/perf": "^10.8.0",
    "@react-native-firebase/remote-config": "^10.8.0",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/compat": "^5.3.13",
    "@react-navigation/drawer": "^5.12.3",
    "@react-navigation/material-bottom-tabs": "^5.3.13",
    "@react-navigation/material-top-tabs": "^5.3.13",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "apisauce": "^2.0.1",
    "lottie-react-native": "^3.5.0",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-device-info": "^8.0.1",
    "react-native-fbads": "^7.0.3",
    "react-native-fbsdk": "^3.0.0",
    "react-native-gesture-handler": "^1.10.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-paper": "^4.7.1",
    "react-native-permissions": "^3.0.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1",
    "react-native-shimmer-placeholder": "^2.0.6",
    "react-native-slider-intro": "^1.0.17",
    "react-native-vector-icons": "^8.0.0",
    "react-native-video": "^5.1.1",
    "tipsi-stripe": "^8.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/runtime": "^7.12.13",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.19.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.65.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "admob_android_app_id": "ca-app-pub-XXXXXXXXXXXXXXXX~XXXXXXX000",
    "admob_ios_app_id": "ca-app-pub-XXXXXXXXXXXXXXXX~XXXXXXX000"
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm using Pods and my Podfile looks like this:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
target 'myApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Pods for myApp

  #OpenSSL
  pod 'OpenSSL-Universal'
  #pod 'Stripe'
  pod 'Stripe', '~> 19.4.0'
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Firebase/AppDistribution'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"


  target 'myAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  use_flipper!({ 'Flipper' => '0.75.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'myApp-tvOS' do
  # Pods for myApp-tvOS

  target 'myApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

```

#### `AppDelegate.m`:

```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#if RCT_DEV
#import <React/RCTDevLoadingView.h>
#endif

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@import Firebase;
@import GoogleMobileAds;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  [[GADMobileAds sharedInstance] startWithCompletionHandler:nil];
  
  #ifdef FB_SONARKIT_ENABLED
    InitializeFlipper(application);
  #endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  #if RCT_DEV //Custom
    [bridge moduleForClass:[RCTDevLoadingView class]];
  #endif
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"myApp"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 407.67 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.1
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: 22.0.7026061
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/local/opt/openjdk/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: ^0.63.16 => 0.63.16
  npmGlobalPackages:
    *react-native*: Not Found

```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:** 
  - `10.8.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Admob`
  - `Analytics`
  - `App`
  - `Crashlytics`
  - `Dynamic Links`
  - `IID`
  - `In App Messaging`
  - `Messaging`
  - `Perf`
  - `Remote Config`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2021-02-19 23:28
Out of curiosity, what is this about in the Podfile?

```ruby

  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Firebase/AppDistribution'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'
```

Is this a mixed-mode app, like you are calling the firebase-ios-sdk APIs natively with custom objective-c (or swift I guess) code? If you are not, if you are only using react-native-firebase APIs then those lines should not be there as auto-linking will bring in the react-native-firebase podspecs and those will transitively bring in the dependencies they need

I don't think that is the source of the problem though. 

The source of your problem is whatever this FLEXNetworkObserver thing is

```
5   myApp                              0x000000010cceb30f __71+[FLEXNetworkObserver injectDownloadTaskDidWriteDataIntoDelegateClass:]_block_invoke.383 + 79
	6   myApp                              0x000000010ccdefbc +[FLEXNetworkObserver sniffWithoutDuplicationForObject:selector:sniffingBlock:originalImplementationBlock:] + 444
	7   myApp                              0x000000010cceb0d6 __71+[FLEXNetworkObserver injectDownloadTaskDidWriteDataIntoDelegateClass:]_block_invoke_2 + 710
	
```

That is not react-native-firebase code. I'm going to close this unless you can show how react-native-firebase is responsible, preferably with an App.js that is self-contained and may be placed into the result of a clean project (like that created from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh)

**Comment by oxyii** [comment] 2021-02-19 23:43
Same here.
@mikehardy reproduced on `react-native@0.64.0-rc.3` only if `"@react-native-firebase/analytics": "^10.8.0"` installed. Also installed:
```json
    "@react-native-firebase/app": "^10.8.0",
    "@react-native-firebase/crashlytics": "^10.8.0",
    "@react-native-firebase/dynamic-links": "^10.8.0",
    "@react-native-firebase/firestore": "^10.8.0",
    "@react-native-firebase/messaging": "^10.8.0",
    "@react-native-firebase/perf": "^10.8.0",
    "@react-native-firebase/storage": "^10.8.0",
```

Without analytics all works fine

**Comment by mikehardy** [comment] 2021-02-19 23:51
@oxyii is that with a clean nothing-else-installed setup e.g. from the make-demo script? All that needs to happen to trigger it is to run that script and it's fine (with react-native 0.63.4) but if you alter the react-native template used to 0.64.0-rc.3 it fails on startup? If so that would be pretty easy to reproduce but very surprising of course.

Please let me know - I will not chase down potentially project-specific items with the limited time I've got but if it can be triggered on a fresh app I definitely want to try it

**Comment by oxyii** [comment] 2021-02-20 01:24
ref??? https://github.com/facebook/flipper/issues/1940

**Comment by oxyii** [comment] 2021-02-20 02:27
@mikehardy i think you can close this issue now

**Comment by mikehardy** [comment] 2021-02-20 03:05
Good sleuthing though! For this reason I must admit I just disabled flipper. Seems like it's always something, either an OpenSSL thing or this or who knows. Tough enough to get this stuff all working!

**Closed** 2021-02-20 03:06 UTC
Labels: Help: Needs Triage, Impact: Bug

**Comment by seamive** [comment] 2021-02-20 08:42
> Out of curiosity, what is this about in the Podfile?
> 
> ```ruby
>   # Add the Firebase pod for Google Analytics
>   pod 'Firebase/Analytics'
>   pod 'Google-Mobile-Ads-SDK'
>   pod 'Firebase/AppDistribution'
>   pod 'Firebase/Messaging'
>   pod 'Firebase/Crashlytics'
>   pod 'Firebase/DynamicLinks'
>   pod 'Firebase/InAppMessaging'
>   pod 'Firebase/Performance'
>   pod 'Firebase/RemoteConfig'
> ```
> 
> Is this a mixed-mode app, like you are calling the firebase-ios-sdk APIs natively with custom objective-c (or swift I guess) code? If you are not, if you are only using react-native-firebase APIs then those lines should not be there as auto-linking will bring in the react-native-firebase podspecs and those will transitively bring in the dependencies they need
> 
> I don't think that is the source of the problem though.
> 
> The source of your problem is whatever this FLEXNetworkObserver thing is
> 
> ```
> 5   myApp                              0x000000010cceb30f __71+[FLEXNetworkObserver injectDownloadTaskDidWriteDataIntoDelegateClass:]_block_invoke.383 + 79
> 	6   myApp                              0x000000010ccdefbc +[FLEXNetworkObserver sniffWithoutDuplicationForObject:selector:sniffingBlock:originalImplementationBlock:] + 444
> 	7   myApp                              0x000000010cceb0d6 __71+[FLEXNetworkObserver injectDownloadTaskDidWriteDataIntoDelegateClass:]_block_invoke_2 + 710
> 	
> ```
> 
> That is not react-native-firebase code. I'm going to close this unless you can show how react-native-firebase is responsible, preferably with an App.js that is self-contained and may be placed into the result of a clean project (like that created from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh)

So you're saying, we should remove those from POD File and let rnfirebase handle to bring the Pod specs with auto-linking? @mikehardy

**Comment by oxyii** [comment] 2021-02-20 08:54
@seamive Exactly! look
Flipper >= 0.69 will NOT work with analytics (i don't know why and i think nobody know it :) ). So you must downgrade Flipper to 0.54 (yeah, it's by default). But you can see error `event2/event.h file not found` while app building. Then you need to upgrade `Flipper-Folly` to 2.3.0

**Comment by seamive** [comment] 2021-02-20 08:54
> @seamive
> 
> > use_flipper!({ 'Flipper' => '0.75.1' })
> 
> your Flipper force upgrading in `Podfile` is bad idea because of [this](https://github.com/facebook/flipper/issues/1940).
> 
> Please use
> 
> `use_flipper!({ 'Flipper-Folly' => '2.3.0' })`
> 
> instead in Podfile [facebook/react-native#30836 (comment)](https://github.com/facebook/react-native/issues/30836#issuecomment-772830882)
> 
> @mikehardy I hope [this PR](https://github.com/facebook/flipper/pull/1810) will be released before RN-0.64 stable release )))

Thank you this was the issue I guess!

**Comment by seamive** [comment] 2021-02-20 08:56
@mikehardy: We saw that we might need to include the POD separately but now I get that it will automatically include the required packages with auto-linking, thank you so much for the help, we can close this now! :)

**Comment by tgensol** [comment] 2021-03-25 17:40
Hi there !

I am using latest versions of RNFirebase, It was working very well. Since I upgraded to RN 0.64, I have some crashs with that trace : 

`021-03-25 18:35:13.153708+0100 Choose Dev[20410:141316] -[fir_D994CC17-019D-4E3E-B16D-40DB53FF1026_GULNetworkURLSession _flex_swizzle_5d79e5c1_URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]: unrecognized selector sent to instance 0x600002d80f60
2021-03-25 18:35:13.164455+0100 Choose Dev[20410:141316] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[fir_D994CC17-019D-4E3E-B16D-40DB53FF1026_GULNetworkURLSession _flex_swizzle_5d79e5c1_URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]: unrecognized selector sent to instance 0x600002d80f60'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001161a6af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x0000000115b10e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001161b56f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00000001161ab036 ___forwarding___ + 1489
	4   CoreFoundation                      0x00000001161ad068 _CF_forwarding_prep_0 + 120
	5   Choose Dev                          0x000000010a79dd0f __71+[FLEXNetworkObserver injectDownloadTaskDidWriteDataIntoDelegateClass:]_block_invoke.383 + 79
	6   Choose Dev                          0x000000010a7919bc +[FLEXNetworkObserver sniffWithoutDuplicationForObject:selector:sniffingBlock:originalImplementationBlock:] + 444
	7   Choose Dev                          0x000000010a79dad6 __71+[FLEXNetworkObserver injectDownloadTaskDidWriteDataIntoDelegateClass:]_block_invoke_2 + 710
	8   CFNetwork                           0x000000010f8e8fd5 _CFNetworkHTTPConnectionCacheSetLimit + 160777
	9   libdispatch.dylib                   0x000000011caf37ec _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000011caf49c8 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000011cb02e75 _dispatch_main_queue_callback_4CF + 1152
	12  CoreFoundation                      0x0000000116114dbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x000000011610f63e __CFRunLoopRun + 2685
	14  CoreFoundation                      0x000000011610e6d6 CFRunLoopRunSpecific + 567
	15  GraphicsServices                    0x000000011e0efdb3 GSEventRunModal + 139
	16  UIKitCore                           0x000000012631fcf7 -[UIApplication _run] + 912
	17  UIKitCore                           0x0000000126324ba8 UIApplicationMain + 101
	18  Choose Dev                          0x0000000109ec0a20 main + 112
	19  libdyld.dylib                       0x000000011cb833e9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[fir_D994CC17-019D-4E3E-B16D-40DB53FF1026_GULNetworkURLSession _flex_swizzle_5d79e5c1_URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]: unrecognized selector sent to instance 0x600002d80f60'
terminating with uncaught exception of type NSException`

But I am using :
`use_flipper!()`

Wich is 2.5.1. If I removed Flipper, my app works well. Is it the same "issue" ?  

Thanks !
