### ISSUE TITLE
[🐛] auth() crashes on Android 8

### ISSUE THREAD

**Issue by Sydney-o9** [invertase/react-native-firebase#6338] opened 2022-06-26 04:57 UTC
This bug only happens on Android 8 `ONLY`. Works perfectly on all other Android and iOS OSes.

It seems to be due to this [line](https://github.com/invertase/react-native-firebase/blob/main/packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java#L145) in `ReactNativeFirebaseAuthModule.java `

```
    "@react-native-firebase/app": "^15.0.0",
    "@react-native-firebase/app-types": "^6.7.2",
    "@react-native-firebase/auth": "^15.0.0",
```

```
dependencies {
       // ...
        classpath 'com.google.gms:google-services:4.3.12'
}
```

Reproducible with minimum effort:
```
import auth from '@react-native-firebase/auth';

const App = () => {
  console.log(auth()); <---- This crashes

  return (
     // ...
  );
};

export default App;
```

```
Stack trace

java.lang.IncompatibleClassChangeError: The method 'java.lang.String java.lang.Object.toString()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'io.invertase.firebase.auth.ReactNativeFirebaseAuthModule' appears in /data/app/app.myapp-9E_F0pbVq5Y6y6PIQwPmwQ==/base.apk:classes2.dex)

FATAL EXCEPTION: main
Process: app.myapp, PID: 4781
java.lang.IncompatibleClassChangeError: The method 'java.lang.String java.lang.Object.toString()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'io.invertase.firebase.auth.ReactNativeFirebaseAuthModule' appears in /data/app/app.myapp-9E_F0pbVq5Y6y6PIQwPmwQ==/base.apk:classes2.dex)
	at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule.lambda$addAuthStateListener$0$io-invertase-firebase-auth-ReactNativeFirebaseAuthModule(ReactNativeFirebaseAuthModule.java:145)
	at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule$$ExternalSyntheticLambda25.onAuthStateChanged(Unknown Source:4)
	at com.google.firebase.auth.zzl.run(com.google.firebase:firebase-auth@@21.0.5:1)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by mikehardy** [comment] 2022-06-26 13:51
Hi there! 

1) [You skipped our template](https://stackoverflow.com/help/how-to-ask)

it has some information that would be useful here, specifically your react-native version and JDK in use

The internet (that is: [stackoverflow et al when I search for your error message](https://stackoverflow.com/questions/1980452/what-causes-java-lang-incompatibleclasschangeerror)) seems to think you've got some JDK oddity going on. Normally it would be a binary-incompatible library publish but react-native is built from source, so that means a local compile issue most likely.

I suggest using JDK11 to compile the app (and triple-check you are *actually* using it to compile the app).
I suggest you `\rm -fr android/app/build` (or perhaps `npx react-native-clean-project`) to clean out old artifacts.

2) I cannot reproduce

This is what makes me think it will be a local problem with your project, since I start an API26 (that is: Android 8) emulator and run this https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh and it works fine with JDK11 and this diff which was your reproduction:

```diff
mike@bistromath:~/work/Invertase/rnfbdemo (main *) % git diff
diff --git a/App.js b/App.js
index 8b91e33..c145285 100644
--- a/App.js
+++ b/App.js
@@ -34,6 +34,7 @@ const instructions = Platform.select({
 
 export default class App extends Component {
   render() {
+    console.log(auth());
     return (
       <View style={styles.container}>
         <Text style={styles.welcome}>React Native Firebase Build Demo</Text>
```

3) Imprecise version spec on description -

Note that this statement: "Works perfectly on all other Android " cannot be correct. For instance it will not work on Android 4, so certainly there is a lower bound to perfect functioning? Did you try Android 6 and 7 and 7.1?

Either way, I ran it against emulators with API21 (our minSdkVersion), API26 (your reproduction) and API31 (my current testing upper bound) and it all worked.

4) You should remove an include

I'm not sure what this import is and why you include it? It's not something we use anywhere internally anymore - it hasn't been published in 2 years and [just contains some flow typings if I understand correctly](https://npm.runkit.com/@react-native-firebase/app-types?t=1656250422036)

>     "@react-native-firebase/app-types": "^6.7.2",


Hopefully something in here gets you going - [my reproduction is fully scripted so it should be authoritative](https://stackoverflow.com/help/mcve) and that means this likely won't be actionable so I'm going to close it. If you can specify some alteration to the script that can reproduce this failure we can reopen and figure out what's going on

**Closed by mikehardy** 2022-06-26 13:51 UTC
Labels: Impact: Bug, Help: Needs Triage

**Comment by mrcwerfar** [comment] 2022-06-29 11:08
I still have this problem. I discovered the error via the "before launch"-report when I tried to publish my app on Google Play. The stack-trace marked A (below) is from Google Play.
 
I have tried [mikehardy](https://github.com/mikehardy)'s suggestions without success, i.e. using JDK11, deleted build folder, ./gradle clean, invalidate caches in AS etc.

Testing on Android8 (API26) and Android8.1 (API27) emulators from Android Studio, or command-line, both fails and give a stack trace as shown below (marked as B). On API 28 and above it works. I have not tested lower APIs.

As you can see AndroidStudio reports NoClassDefFoundError on ReactNativeFirebaseAuthPackage while Google Play reports IncompatibleClassChangeError on ReactNativeFirebaseAuthModule. It seems like these are related. 

Maybe the Android stack trace (B) give some more clues to what is the problem?
I have struggled with this for many days now without any progress.

Any suggestion will be appreciated.

**A: Stack-trace from Google Play "before-launch" report:**

```
FATAL EXCEPTION: main
Process: com.my_app_name, PID: 25852
java.lang.IncompatibleClassChangeError: The method 'java.lang.String java.lang.Object.toString()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'io.invertase.firebase.auth.ReactNativeFirebaseAuthModule' appears in /data/app/com.my_app_name-Tm5OR6u-LvUrf07xZDvX8A==/base.apk:classes2.dex)
	at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule.lambda$addAuthStateListener$0$io-invertase-firebase-auth-ReactNativeFirebaseAuthModule(ReactNativeFirebaseAuthModule.java:145)
	at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule$$ExternalSyntheticLambda25.onAuthStateChanged(Unknown Source:4)
	at com.google.firebase.auth.zzl.run(com.google.firebase:firebase-auth@@21.0.5:1)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**B: Stack-trace from AndroidStudio:**

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my_app_name, PID: 4996
    java.lang.NoClassDefFoundError: Failed resolution of: Lio/invertase/firebase/auth/ReactNativeFirebaseAuthPackage;
        at com.facebook.react.PackageList.getPackages(PackageList.java:93)
        at com.my_app_name.MainApplication$1.getPackages(MainApplication.java:30)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:85)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:91)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:86)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46)
        at com.my_app_name.MainActivity.onCreate(MainActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.invertase.firebase.auth.ReactNativeFirebaseAuthPackage" on path: DexPathList[[zip file "/data/app/com.my_app_name-ow2w5F-nRAWZCczjo555CQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.my_app_name-ow2w5F-nRAWZCczjo555CQ==/lib/x86, /data/app/com.my_app_name-ow2w5F-nRAWZCczjo555CQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.react.PackageList.getPackages(PackageList.java:93) 
        at com.my_app_name.MainApplication$1.getPackages(MainApplication.java:30) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:85) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42) 
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104) 
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:91) 
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:86) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46) 
        at com.my_app_name.MainActivity.onCreate(MainActivity.java:21) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**My package.json:**
```
{
  "name": "my_app_name",
  "version": "6.2.0",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "run:android": "react-native run-android",
    "run:ios": "react-native run-ios --simulator=\"iPhone X\"",
    "build:apk": "cd android && ./gradlew assembleRelease",
    "test": "jest",
    "prepare": "patch-package",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^9.0.0",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-firebase/app": "^14.11.1",
    "@react-native-firebase/auth": "^14.11.1",
    "@react-native-firebase/messaging": "^14.11.1",
    "@react-navigation/elements": "^1.3.3",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "axios": "^0.27.2",
    "moment": "^2.29.3",
    "prop-types": "15.8.1",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-device-info": "^9.0.2",
    "react-native-gesture-handler": "^2.4.2",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-picker": "^4.8.4",
    "react-native-localize": "^2.2.2",
    "react-native-pager-view": "^5.4.24",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "^2.8.0",
    "react-native-root-toast": "^3.4.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.13.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^12.3.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-webview": "11.22.2",
    "react-redux": "^8.0.2",
    "redux": "^4.2.0",
    "redux-thunk": "^2.4.1",
    "styled-components": "^5.3.5",
    "styled-system": "^5.1.5"
  },
  "devDependencies": {
    "@babel/core": "^7.18.5",
    "@babel/runtime": "^7.18.3",
    "@react-native-community/eslint-config": "^3.0.2",
    "babel-jest": "^28.1.1",
    "eslint": "^8.18.0",
    "jest": "^28.1.1",
    "metro-react-native-babel-preset": "^0.71.1",
    "patch-package": "^6.4.7",
    "react-native-clean-project": "^4.0.1",
    "react-native-codegen": "^0.69.1",
    "react-test-renderer": "18.2.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**My Android project build.gradle:**
```
buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.3'
        classpath 'com.google.gms:google-services:4.3.10'
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:4.1.2")
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}
```

**My app build.gradle (leaving out all comments and unreleated stuff):**
```
apply plugin: "com.android.application"
apply plugin: 'com.google.gms.google-services'

import com.android.build.OutputFile
import org.apache.tools.ant.taskdefs.condition.Os
project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]
apply from: "../../node_modules/react-native/react.gradle"
def enableSeparateBuildPerCPUArchitecture = false
def enableProguardInReleaseBuilds = false
def jscFlavor = 'org.webkit:android-jsc:+'
def enableHermes = project.ext.react.get("enableHermes", false);
def reactNativeArchitectures() {
    def value = project.getProperties().get("reactNativeArchitectures")
    return value ? value.split(",") : ["armeabi-v7a", "x86", "x86_64", "arm64-v8a"]
}
. . . etc.

android {
    ndkVersion rootProject.ext.ndkVersion
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
       applicationId "com.my_app_name"
       minSdkVersion rootProject.ext.minSdkVersion
       targetSdkVersion rootProject.ext.targetSdkVersion
       . . . etc.
       buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()
       if (isNewArchitectureEnabled()) {
          . . . etc.
       }
    }
    . . . etc.
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    . . . etc.
}

dependencies {
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-vector-icons')
    . . . etc.
    implementation project(path: ":@react-native-firebase_messaging")
    implementation project(path: ":@react-native-firebase_auth")
    . . . etc.
}
. . . etc.
```

**Comment by mikehardy** [comment] 2022-06-29 12:20
I don't doubt you have a problem, there is something going on.

However I can't reproduce it. I just tuned my demo / repro script to try to match your conditions

https://github.com/mikehardy/rnfbdemo/tree/rnfb-issue6338-repro

The modules you include (app / auth / messages) worked in release mode and debug mode

Execution environment:
- API26 / API27 emulators (x86_64 / play store flavor, fully up to date in play store / manage apps etc)
- `yarn react-native info`:

```
mike@bistromath:~/work/Invertase/rnfbdemo/rnfbdemo (rnfb-issue6338-repro) % yarn react-native info
yarn run v1.22.18
$ /home/mike/work/Invertase/rnfbdemo/rnfbdemo/node_modules/.bin/react-native info
info Fetching system and libraries information...
System:
    OS: Linux 5.18 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
    Memory: 13.85 GB / 62.68 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.2 - /tmp/yarn--1656505198284-0.25927441650254424/node
    Yarn: 1.22.18 - /tmp/yarn--1656505198284-0.25927441650254424/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32
      Build Tools: 23.0.1, 24.0.0, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 26.0.0, 26.0.3, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, chromeos-67 | Chrome OS 67
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
  npmGlobalPackages:
    *react-native*: Not Found
Done in 3.45s.
mike@bistromath:~/work/Invertase/rnfbdemo/rnfbdemo (rnfb-issue6338-repro) % 
```


If you can modify those somehow so that they fail, or determine the environment difference that makes them fail, maybe we can proceed further?

![image](https://user-images.githubusercontent.com/782704/176434157-01fd9ed4-2995-4e6f-8e87-3ee019f04e3e.png)

**Comment by mrcwerfar** [comment] 2022-06-30 12:43
ok, I fixed the path variable and now it seems to work if the app is started from the command line using "react-native run-android" (or react-native run-android --variant = release), and run in emulator (API26 or 27). If it is run directly from AndroidStudio, the same error still occurs, occasionally... Maybe AndroidStudio uses a different JDK? I do not know. Anyway, I have now generated an apk which is uploaded to Google Play and which passed (automatic) testing. For now, I consider the problem solved. Thank you so much for your help.

**Comment by mikehardy** [comment] 2022-06-30 12:45
> Maybe AndroidStudio uses a different JDK?

AndroidStudio definitely has it's own JDK configuration, stackoverflow is stuffed full of Q&A on that one because the way to change it varies by AndroidStudio version...

The react-native website PR is going to merge also, with a prescriptive comment to use JDK11 or be open to incompatibilities at your risk basically :-)

Glad you are moving forward! Good luck with your project

**Comment by mikehardy** [comment] 2022-06-30 16:02
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
}
```

This has nothing to do with your JDK in use, it simply has no bearing. It is related to what level bytecode the JDK will *produce* but nothing else. So you can forget it for these purposes.

It is out of scope here to troubleshoot tools setup in IDEs, but it does seem like you have set the JDK correctly in android studio. You can always print the JDK in use like I do in a different project (that we have tested and know works with 11/14/16, `android/build.gradle`

```groovy
// at the top
import org.gradle.internal.jvm.Jvm

// somewhere later
    jvmVersion = Jvm.current().javaVersion.majorVersion
    if (jvmVersion != "11" && jvmVersion != "14" && jvmVersion != "16") {
        println "\n\n\n"
        println "**************************************************************************************************************"
        println "\n\n\n"
        println "ERROR: AnkiDroid builds with JVM version 11, 14, or 16."
        println "  Incompatible major version detected: '" + jvmVersion + "'"
        println "\n\n\n"
        println "**************************************************************************************************************"
        println "\n\n\n"
        System.exit(1)
    }
```
