### ISSUE TITLE
App crash after getting new notification when app close in IOS 13

### ISSUE THREAD

**Issue by barak109** [invertase/react-native-firebase#3165] opened 2020-02-02 17:23 UTC
## Issue

Describe your issue here

Everything works fine besides -
1. when i close the app (kill) 
2.get new notification
3.open the notification by tapping on her or clicking on the app icon
4. my app is crashing.

**What i tried**

1. In first i started to work with react-native-firebase version 5.5 all the things works besides what i mention above.

2. after that i was trying to  work with version  5.6 and the problem continuum(i tried this with fresh react native project- the current version).

3.now i'm trying to do that with react-native-firebase  V6 and the problem continuum.
-was trying to do that with fresh react native project without success
- after that i was trying to do that with my project that contains react native 0.59.8
-and because i need notification i added react-native-push-notification.

 I read that people mentioned that firebase ios sdk is the problem but i did all the things that suggests without any success.

I'm really appreciate with any help because i spent 3 days on it, thank you!

---

## Project Files

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/push-notification-ios": "^1.0.5",
    "@react-native-firebase/app": "^6.2.0",
    "@react-native-firebase/messaging": "^6.2.0",
    "@types/react-native-push-notification": "^3.0.7",
    "@types/react-native-vector-icons": "^6.4.4",
    "@types/react-redux": "^7.1.5",
    "@types/socket.io-client": "^1.4.32",
    "add": "^2.0.6",
    "axios": "^0.19.0",
    "jetifier": "^1.6.4",
    "prettier": "^1.16.4",
    "react": "^16.8.6",
    "react-native": "^0.59.8",
    "react-native-android-location-enabler": "^1.2.0",
    "react-native-android-open-settings": "^1.3.0",
    "react-native-autocomplete-input": "^4.1.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-deck-swiper": "1.5.25",
    "react-native-dotenv": "^0.2.0",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-gifted-chat": "^0.13.0",
    "react-native-image-picker": "^1.1.0",
    "react-native-image-resizer": "^1.1.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-keychain": "3.0.0",
    "react-native-modal-selector": "^1.1.2",
    "react-native-push-notification": "^3.1.9",
    "react-native-sortable-grid": "https://github.com/ollija/react-native-sortable-grid",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.8.1",
    "react-redux": "^7.1.3",
    "realm": "3.0",
    "redux": "^4.0.4",
    "redux-immutable-state-invariant": "^2.1.0",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.3.0",
    "tslint": "^5.15.0",
    "tslint-config-prettier": "^1.18.0",
    "tslint-eslint-rules": "^5.4.0",
    "tslint-react": "^4.0.0",
    "typescript": "^3.4.3",
    "yarn": "^1.21.1"
  },
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'

target 'AwesomeProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Firebase/Messaging', '~> 6.13.0'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app' 
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  pod 'Folly', :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec"

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end

```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <RNCPushNotificationIOS.h>

#import <Firebase.h>
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
     [FIRApp configure];
   }
  
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"AwesomeProject"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
  [RNCPushNotificationIOS didRegisterUserNotificationSettings:notificationSettings];
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [RNCPushNotificationIOS didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
  [RNCPushNotificationIOS didFailToRegisterForRemoteNotificationsWithError:error];
}

- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
  [RNCPushNotificationIOS didReceiveLocalNotification:notification];
}


@end

```

</p>
</details>

## my IOS version
  13.3

## The Crash

![IMG_0012](https://user-images.githubusercontent.com/50053032/73612482-db314f00-45f4-11ea-8b43-6bc70838f0f1.PNG)

**Comment by mikehardy** [comment] 2020-02-02 17:53
Hi there

On iOS you should do all messaging / notification work on a real device not a simulator

You can still launch the app on a connected real device though, and watch in Xcode. The crash trace will be important. It looks to me like your crash has nothing to do with react-native-firebase, it looks like your app is waking up and just failing to load the bundle from your dev server somehow.

**Comment by barak109** [comment] 2020-02-02 18:12
1. I'm using real - device new Iphone 11
2. All fine if i close my app and open regularly i do that all the time, but when i get remote notification and open it - it's crash
3.i don't know a lot about xcode - how can i show you the error becasue when i close the app the connection between xcdoe and my device is disconnect( i still can open and close my device and all good beside when i get notification when close)
* if you know how to do that i will check
thank you for the response

**Comment by mikehardy** [comment] 2020-02-02 18:21
This has nothing to do with react-native-firebase.

Build it for release mode and it will work because the bundle is in your app.

The problem is loading the bundle when the notification opens the app vs when you launch it somehow. Why? No idea. But I'll be surprised if it has anything to do with react-native-firebase. I think it has more to do with metro (the react-native bundler) + Xcode + your device.

Maybe use the command line instead (`react-native run-ios`) and see how it goes. Either way, you'll need to demonstrate a stack trace or error message that has react-native-firebase in it before it's a problem here.

I'm going to close this preliminarily pending demonstration this is a react-native-firebase issue.

**Closed by mikehardy** 2020-02-02 18:21 UTC
