### ISSUE TITLE
[🐛] Bug Report Title - Set user property null does not work

### ISSUE THREAD

**Issue by tdekoning** [invertase/react-native-firebase#4916] opened 2021-02-16 11:05 UTC
## Issue

Passing `null` to `setUserProperty` doesn't show up in Firebase analytics and screen-views afterwards still include the user property with the old value. 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/analytics": "^10.5.1",
    "@react-native-firebase/app": "^10.5.0",
    "@react-native-firebase/crashlytics": "^10.5.1",
```

#### `analytics.js`
```js
await analytics().setUserProperty('my_property', null)
```

</details>

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Analytics`
- **Are you using `TypeScript`?**
  - `Y` & `4.1.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2021-02-16 22:13
- we're on 10.8.x can you still reproduce it?
- show us code, give us an App.js self-contained that you can drop in a clean project (like https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh) to reproduce it
- what happens if you send an empty string?
- what happens if you reach into the javascript in node_modules and log parameters prior to the native call to whatever platform you experience this on (you did not specify since you skipped the template)? What happens when you log the native calls in node_modules here before it calls into the firebase SDK?
- can you reproduce with https://github.com/firebase/quickstart-ios/tree/master/analytics or https://github.com/firebase/quickstart-android/tree/master/analytics ?

We close issues when users don't respect the template, as it does not respect maintainer time, so I am going to close this, but with the pointers above you should be able to either resolve this directly or know exactly what the resolution should be and if we need a PR here you can open a new issue with actual details and we can collaborate

**Closed by mikehardy** 2021-02-16 22:13 UTC
Labels: Help: Needs Triage, Impact: Bug
