### ISSUE TITLE
 Can not specify local notification sound.

### ISSUE THREAD

**Issue by salomaosnff** [invertase/react-native-firebase#1234] opened 2018-06-20 20:04 UTC
### Issue
I need to set a custom sound for local notification.
I tried with `notification.setSound ('notification')` and putting the file inside `android/app/src/main/res/raw/notification.mp3`

### Environment

1. Application Target Platform: Android

2. Development Operating System: Windows 10

3. Build Tools: 27.0.3

4. React Native version: 0.55.4

5. RNFirebase Version: 4.2.0

6. Firebase Module: notifications

**Comment by Salakar** [comment] 2018-06-26 16:41
Duplicate of #1176

**Closed by Salakar** 2018-06-26 16:41 UTC
