### ISSUE TITLE
After pushing data to firebase database I get null instead of snapshot in then()

### ISSUE THREAD

**Issue by berpcor** [invertase/react-native-firebase#1572] opened 2018-10-06 21:09 UTC
One of my actions:

```
export const startAction = (item) => {


    return (dispatch) => {

        firebase.database().ref(`/users/${firebase.auth().currentUser.uid}/some/`)
            .push(item).then((snapshot) => {
                console.log('Added to firebase', snapshot,  snapshot.key);

            }).catch((err) => { console.log('errooooor', err) });
    }


}
```
My code is above. This code works with firebase directly, without RNFB, but in RNFB it doesn't work for some reasons. Error text: _Cannot read property 'key' of null_. Is it normal behavior?

**Comment by shiftrtech** [comment] 2018-10-07 02:43
Maybe related to #1498

**Comment by Salakar** [comment] 2018-10-07 02:49
Duplicate of https://github.com/invertase/react-native-firebase/issues/893

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Closed by Salakar** 2018-10-07 02:49 UTC

**Comment by Salakar** [comment] 2018-10-27 00:52
Have just pushed a re-write of the `push()` logic to match the Web SDK. 

Have added test cases from this issue and others which can be seen working here: https://github.com/invertase/react-native-firebase/blob/database-fixes/tests/e2e/database/ref/push.js#L73

This will land in v5.1.0, apologies for the delay on this one.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
