### ISSUE TITLE
Error when get document by firestore

### ISSUE THREAD

**Issue by arvitaly** [invertase/react-native-firebase#533] opened 2017-10-20 11:13 UTC
### Issue

App crashed

```typescript
import firebase from "react-native-firebase";
firebase.firestore().collection("test").doc("124").get().then((ref)=>{ console.log(ref) });
```

```
java.lang.ExceptionInInitializerError
 at io.invertase.firebase.firestore.RNFirebaseFirestoreDocumentReference$2.onComplete(RNFirebaseFirestoreDocumentReference.java:64)
```

### Environment

1. Application Target Platform: Android

2. Development Operating System: Window Server 2016

3. Build Tools: react-native run-android

4. React Native version: "react-native": "0.49.3",

5. RNFirebase Version: "react-native-firebase": "^3.0.4",

6. Firebase Module: firestore

**Comment by chrisbianca** [comment] 2017-10-20 14:58
@arvitaly Can you send us the entire stack trace, not just the first couple of lines?

**Comment by arvitaly** [comment] 2017-10-20 16:14
Yes, of course
```
 java.lang.ExceptionInInitializerError
       at io.invertase.firebase.firestore.RNFirebaseFirestoreDocumentReference$2.onComplete(RNFirebaseFirestoreDocumentReference.java:65)
       at com.google.android.gms.tasks.zzf.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5451)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'X'
       at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
       at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
       at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
       at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:258)
       at io.invertase.firebase.firestore.FirestoreSerialize.<clinit>(FirestoreSerialize.java:33)
```

**Comment by Ehesp** [comment] 2017-10-20 18:48
@chrisbianca seems to be related to the issue you mentioned on Discord "Unknown pattern character 'X'"

**Comment by urajat** [comment] 2017-10-23 06:41
@chrisbianca In commit fc3fc6d , the `Z` which I had introduced as a fix for #505 has been replaced with `X`. Not sure if this was deliberate. This is actually a bug - the single character X discards the minutes in the timezone and hence instead of `2017-10-18T01:12:43.274+0530` for IST, I see `2017-10-18T01:12:43.274+05` which is wrong! In `console.log` for these values, I am getting `Invalid Date` errors. `new Date().toISOString()` in Chrome console returns a value with Z in it. This issue and the timezone one likely have the same root cause - happening because of the same change. I can open a separate bug for this if you want.

**Comment by chrisbianca** [comment] 2017-10-23 06:45
@urajat Yes, I introduced this to fix a failing test in our test suite.  However it seems that this failing test is caused by the fact that the Android emulator uses a different version of Java to an actual device!! In Java SDK 7+ (which I hadn't realised was only used in the emulator), `X` is the correct way of dealing with an ISO timezone, but it seems this does not work on an actual device.  I'm just debugging at the moment to confirm that everything is correct and will push up a fix followed by a new release shortly.

**Comment by urajat** [comment] 2017-10-23 06:59
@chrisbianca Checked https://developer.android.com/reference/java/text/SimpleDateFormat.html#iso8601timezone In this case, using XX should help. I am testing on the emulator where the single X works, but discards the timezone minutes. With XX or XXX, the values are interpreted correctly. XX appears to be the direct equivalent of Z.

**Comment by chrisbianca** [comment] 2017-10-23 07:04
@urajat Thanks for this. Can you do me a favour and see what happens when you run with XX on a device? According to this open bug, even though it states that X is supported, it doesn't actually work on most versions of Android: https://issuetracker.google.com/issues/65350732. Instead you get the error that's cited above

**Comment by urajat** [comment] 2017-10-23 07:30
@chrisbianca I just checked with a Moto X Play device with Android 6.0.1. No combination of X works - X, XX, XXX - throws the `Unknown pattern character 'X'` exception. The Z option works correctly on the device too. According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString, the `toISOString` method returns Z too - so the test case that you have should ideally pass even while using Z?

**Comment by chrisbianca** [comment] 2017-10-23 07:58
@urajat The Z option seems to work correctly when sending dates from Native to JS, but when reading dates that are sent from JS to Native I get a `ParseException: Unparseable date` error. 

The test case we have that is failing sets a date from the JS side into Firestore, then reads it back out to check they're the same.  It looks like Javascript `toISOString()` always sends the date as UTC time which is why the `'Z'` parameter with apostrophes worked for parsing the dates.  It looks like we might need to use different date formats for reading (JS to Native) compared to writing (Native to JS).  I'm just struggling to figure out what they should be!

**Comment by chrisbianca** [comment] 2017-10-23 08:17
@urajat Ok, I think I have figured it out, though because I'm in the GMT/BST timezone, it's always an easier one to account for!  Are you able to try out this commit and see whether it works for you:

https://github.com/invertase/react-native-firebase/commit/2c7c768522683927c17687d5632212f485be863f

You should be able to install directly by doing the following:

`npm install --save https://github.com/invertase/react-native-firebase#v3.0.x`

**Comment by chrisbianca** [comment] 2017-10-23 16:25
This has now been released as part of version 3.0.5

**Closed by chrisbianca** 2017-10-23 16:25 UTC

**Comment by urajat** [comment] 2017-10-23 19:36
@chrisbianca Just got around to testing this. 3.0.5 works on the emulator (tested on Android 7.1.1). But on the device with 7.1.1, this doesn't work - I get an `Invalid Date` value for the dates which are being read even though they work perfectly on the emulator and are correct on Firestore too. I added debugging statements in `buildTypeMap` to compare the values on device vs emulator - there is no change and the parsing is working as expected. I even tried going back to 3.0.4 and manually making the 'X' to 'Z' change to see if that helps, but nope - same Invalid Date issue on device. In the morning, I was testing with a 6.0.1 device where the Z option worked. Not sure if there's some other place where there is some date interpretation happening.

**Comment by chrisbianca** [comment] 2017-10-23 20:05
I'm moving this over to a new issue: https://github.com/invertase/react-native-firebase/issues/545 as the initial bug is fixed.
