### ISSUE TITLE
[🐛] Bug Report Title - Property 'utmParametersDictionary' not found on object of type 'FIRDynamicLink

### ISSUE THREAD

**Issue by nwpnkmngm** [invertase/react-native-firebase#6153] opened 2022-03-24 07:17 UTC
![image](https://user-images.githubusercontent.com/48342930/159862820-19c161f8-e183-4060-936c-73d372e8ec33.png)

**Comment by mikehardy** [comment] 2022-03-24 11:58
When logging issues, you must search the issues list first - this is a duplicate of a couple exact same messages and has solutions (e.g., upgrade correctly to current version) https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+utmparametersdictionary+FIRDynamiclink

**Closed by mikehardy** 2022-03-24 11:58 UTC
Labels: Impact: Bug, Help: Needs Triage
