### ISSUE TITLE
Differing behavior between this and Google's SDKs for ref.on() and ref.off() 

### ISSUE THREAD

**Issue by jsm** [invertase/react-native-firebase#160] opened 2017-06-12 18:56 UTC
Version: 1.1.0

## Example

```
await database.ref('meow').on('value', callback)
await database.ref('meow').off('value', callback)
```

## Expected behavior (firebase-web)

The listener is removed. Callback no longer executes on update to the `meow` ref

## Actual Behavior (react-native-firebase)

The listener is not removed. Updates to `meow` ref trigger the callback.

## Explanation
When calling database.ref(), although the ref is a new instance, it uses the same firebase 'Repo' object.
https://github.com/firebase/firebase-js-sdk/blob/master/src/database/js-client/api/Firebase.js#L99

The 'repo' object is an extension of their core `SyncTree` which stores and retrieves event subscriptions in this shared object.
https://github.com/firebase/firebase-js-sdk/blob/master/src/database/js-client/core/SyncTree.js#L328

Thus calling `on` or `off` on the same ref path, even if they're different ref instances, will work.

The iOS SDK has the same behavior.
https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Database/Core/FSyncTree.m#L472

In `react-native-firebase`, the ref has it's own `listeners` instance variable that stores instances separately. Thus, this does not work.
https://github.com/invertase/react-native-firebase/blob/master/lib/modules/database/reference.js#L345

## Consequences
Replacing the firebase-web SDK with this SDK mostly works. And it SEEMS to work pretty well, except that since we had the above code pattern in our codebase, there were things that broke pretty mysteriously and sometimes unnoticeably until we realized what was going on.

## Solution
I'm not sure what the best way to tackle this is. To do it similarly to how firebase is doing it would require a substantial change in the codebase.

What I did for us to get around this for now was the following. If it makes sense to you I can go ahead and make a PR, but I wanted to hear everyone's thoughts first.
https://github.com/jsm/react-native-firebase/commit/b93b6b9743bee7137596c24040465312a5885dda
Essentially, it's having `database.ref` save ref instances, and returning the existing instance if it's called with the same path.

**Comment by Salakar** [comment] 2017-06-13 01:24
@jsm thanks again for another well written issue 🎉 

Interesting one which we must of missed, was certainly a lot harder to see intended behaviour when the SDK's were closed source - much easier now though thankfully.

We'll look into this for v2 (#130) and back port if necessary.

**Comment by JonathanAJ** [comment] 2017-06-14 01:52
@jsm Your code work for me too, thanks!!

**Comment by mikelambert** [comment] 2017-06-19 11:44
Thanks for the diagnosis and fix, this would have bitten me when migrating from `react-native-firestack`.

I'm curious if it's intentionally in the [v2.x list](https://github.com/invertase/react-native-firebase/milestone/1) versus the [v2 list](https://github.com/invertase/react-native-firebase/milestone/2), given that there's a [working PR](https://github.com/jsm/react-native-firebase/commit/b93b6b9743bee7137596c24040465312a5885dda) linked above.

FWIW I believe the above approach is basically what `react-native-firestack` is doing [here](https://github.com/fullstackreact/react-native-firestack/blob/master/lib/modules/database.js#L380). (Though it seems they also do more with `this.refs` too.)

**Comment by chrisbianca** [comment] 2017-06-19 12:03
@mikelambert this is actually much more complicated than this PR implies - whilst the PR does work in the simplest of cases, it does not cover query modifiers (limit, sort, equals) and opens up the app to memory leaks as the refs are never cleared down.

It also has the potential to reintroduce bugs like this: https://github.com/invertase/react-native-firebase/issues/25.

We need to properly evaluate the issue as this goes against how we'd interpreted the web SDK spec, hence why it has been bumped to v2.x rather than v2.

**Comment by mikelambert** [comment] 2017-06-19 12:20
Ahhh ok thanks, appreciate the clarification.

I'm looking to migrate off `react-native-firestack` and `react-native-firebase3` (my old library), but it's not urgent, so I'll wait until there's time to do the time to work through the proper fix here. (I was depending on this feature to detect if a listener was already installed.)

**Comment by chrisbianca** [comment] 2017-06-19 12:27
@mikelambert the easiest way to "work around" this issue is to make use of the React component lifecycle methods:

```
componentDidMount() {
  this.ref = firebase.database().ref('meow').on('value', callback);
}

componentWillUnmount() {
  this.ref.off('value', callback);
}
```

This is how we'd recommend working with the database refs.

**Comment by mikelambert** [comment] 2017-06-19 14:25
Ahh, I'm doing something different from the original poster.

I have multiple components that wanted to listen to the same db path, each being stuffed into a StackNavigator (ie, a navigation UI with panels pushed onto the stack). I was trying to coordinate them so only the first-push component listened to the db path, and the others were silent (instead pulling from a shared redux store).

It's possible this was a limitation of `react-native-firestack`, if it didn't allow me to have multiple listeners on the same path without conflicting? Do you know if this would work seamlessly in `react-native-firebase`? And possibly because of this constraint, I was storing it in a shared redux state that all components could then pull from, checking the number of listeners on the reference to identify if someone had already "taken responsibility" for the cache.

**Comment by chrisbianca** [comment] 2017-06-19 15:06
@mikelambert This has definitely been resolved in `react-native-firebase` so you can add multiple listeners to the same path without there being any conflicts.  I was previously using redux for the same reasons, but have now changed so each component listens to firebase directly and removed the dependency on redux for any of my firebase data.

**Comment by alxvallejo** [comment] 2017-07-22 22:20
@chrisbianca Your recommended approach is not working for me. I can see my .off() hitting here:

```
  componentWillUnmount() {
    if (this.state.messagesPath) {
      // this IS hitting
      firebase.database().ref(this.state.messagesPath).off();
    }
  }
```

But my listener still fires when i'm on a different screen. Should I open a new ticket or am i missing something?

**Comment by Ehesp** [comment] 2017-07-24 07:57
@alxvallejo You need to use the same ref instance, like so:

```js
constructor() {
  super();
  this.onUpdate = this.onUpdate.bind(this);
  this.ref = firebase.database().ref(messagesPath);
}

componentDidMount() {
  this.ref.on('value', this.onUpdate);
}

componentWillUnmount() {
  this.ref.off('value', this.onUpdate);
}

onUpdate(snapshot) {

}
```

**Closed** 2017-08-09 08:06 UTC
Labels: bug, database, js

**Comment by jsm** [comment] 2017-08-09 18:22
Is this fixed in some version?

**Comment by Salakar** [comment] 2017-08-09 18:48
@jsm upcoming V3 version, see releases

**Comment by Salakar** [comment] 2017-08-15 20:31
For those interested: https://github.com/invertase/react-native-firebase/blob/v3/lib/utils/SyncTree.js - most of the logic is now in that, new implementation.
