### ISSUE TITLE
v6 Android gradle sync fails

### ISSUE THREAD

**Issue by guveniscan** [invertase/react-native-firebase#2386] opened 2019-07-21 22:03 UTC
Hey,

I have a completely fresh project created with `npx @react-native-community/cli@next init --template=@react-native-firebase/template` and iOS project is running all fine. On Android gradle sync fails and I'm not able to run with the below error.  Upgraded gradle to 5.2.1 to see if it will help but didn't. I'm running react-native-cli: 2.0.1 and react-native: 0.59.8. I've tried upgrading react-native to 0.60 via react-native upgrade but that fails as well. Any help will be greatly appreciated.

`react-native run-android` log:
```
info JS server already running.
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...

FAILURE: Build failed with an exception.

* Where:
Script '/Users/[user-name]/Developer/[project-name]/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 190

* What went wrong:
A problem occurred evaluating settings '[project-name]'.
> Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run "react-native --help" to see a list of all available commands.
  ^
```

package.json:
```
{
  "name": [project-name],
  "version": "0.0.26",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "run:android": "react-native run-android",
    "run:ios": "react-native run-ios --simulator=\"iPhone X\"",
    "build:apk": "cd android && ./gradlew assembleRelease",
    "test": "jest",
    "prepare": "patch-package"
  },
  "dependencies": {
    "@react-native-firebase/app": "^0.0.26",
    "react": "16.8.1",
    "react-native": "0.59.8"
  },
  "devDependencies": {
    "@babel/core": "^7.3.3",
    "@babel/runtime": "^7.3.1",
    "@react-native-community/cli": "2.0.0-alpha.23",
    "@react-native-community/eslint-config": "^0.0.3",
    "babel-jest": "^24.1.0",
    "jest": "^24.1.0",
    "metro-react-native-babel-preset": "^0.51.1",
    "patch-package": "^6.1.0",
    "react-test-renderer": "16.8.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

build.gradle:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath 'com.google.gms:google-services:4.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        jcenter()
    }
}

```

settings.gradle:
```
rootProject.name = [project-name]
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

**Comment by prasadkesarkar** [comment] 2019-07-23 11:55
Getting Same Issue. Any help.

**Comment by ShashankMalviya1994** [comment] 2019-07-24 04:03
+1

**Comment by ShashankMalviya1994** [comment] 2019-07-24 04:04
I am also getting same issue. Please help !

**Comment by Highspeed7** [comment] 2019-07-24 05:32
I too am getting this error... the only thing that has helped me in the past is to restart my machine. It sounds over the top, but when all else fails...

**Comment by jayampathiadhikari** [comment] 2019-07-24 06:01
same here :(

**Comment by Highspeed7** [comment] 2019-07-24 06:39
So here's what I did to get around this... I have no idea what the problem is.

Copy all relevant files you've created... components, etc. I copied everything you see below into a backup folder...

![image](https://user-images.githubusercontent.com/9501337/61770752-dddbfd80-ada2-11e9-9c46-a6c1b37963af.png)

Then delete your entire directory and run react-native init all over again naming the same folder. After that copy everything back that you backed up. This worked for me.

I have constantly gotten this error after sometime of development and have had to do this like 6 times in the last week now. Very annoying.

**Comment by jayampathiadhikari** [comment] 2019-07-24 06:56
My error is similar to yours  but not the same.
Try deleting app\build\intermediates\signing_config\debug\out\signing-config.json
this worked for me.
(also ran as admin)

**Comment by Highspeed7** [comment] 2019-07-24 07:16
> My error is similar to yours but not the same.
> Try deleting **app\build\intermediates\signing_config\debug\out\signing-config.json**
> this worked for me.
> (also ran as admin)

Lifesaver... this worked for me. Thanks!

**Comment by mikehardy** [comment] 2019-07-24 13:01
If deleting that file saves you, it's the same as doing `cd android && ./gradlew clean`

To me this seems like an odd set of dependencies. I'd go with a regular init (not off cli@next) to get RN60, then use the RNFB6 template (which is in the command line you are init'ing already), and I'd use the AndroidX dependencies from firebase SDK (you don't mention those, but it's play services 17+ and all the newest android firebase SDK versions). Basically, full-current. Otherwise you'll figure out how to get this working but it will be obsolete knowledge immediately, with no good upgrade path

**Comment by Highspeed7** [comment] 2019-07-24 18:26
@mikehardy Clearly not as I have on several occasions done gradlew clean to no affect.

**Comment by tomasro27** [comment] 2019-08-03 21:25
`cd android && ./gradlew clean` also didn't work for me, but removing the file manually did

**Comment by shubhamdeol** [comment] 2019-09-04 09:40
@mikehardy 
what do you mean by regular init?
Do you mean that we should not use this dependency at all.
also, If I will use rnFirebase version 6. I won't face this issue?

**Comment by mikehardy** [comment] 2019-09-04 18:05
- regular init: `react-native init rn60rnfbexample` or similar. No extra arguments.
- I don't know what "this dependency" you are referring to
- this issue is about v6 android gradle sync failing. So "if I will use rnFirebase version 6. I won't face this issue?" makes no sense

I'm still on v5 so I'm not sure about v6 but this is their recommendation: https://invertase.io/oss/react-native-firebase/quick-start/new-project

and my recommendation is always follow the docs in general...

**Comment by DavidRafanan** [comment] 2019-09-24 20:15
I have the same error, but app\build\intermediates\signing_config\debug\out\signing-config.json does NOT exist in my directory. Any updates on what should be done if this is the case?

**Comment by MXLI88** [comment] 2019-10-03 08:43
> My error is similar to yours but not the same.
> Try deleting **app\build\intermediates\signing_config\debug\out\signing-config.json**
> this worked for me.
> (also ran as admin)

Thx mate :), this solved my problem

**Comment by Salakar** [comment] 2019-10-07 05:55
Given that this error is coming from `@react-native-community/cli-platform-android/native_modules.gradle' line: 190` (the auto-linking script in the CLI) I'm going to close this issue - but feel free to continue the conversation 👍

**Closed by Salakar** 2019-10-07 05:55 UTC

**Comment by Isaius** [comment] 2019-10-12 14:55
> I have the same error, but app\build\intermediates\signing_config\debug\out\signing-config.json does NOT exist in my directory. Any updates on what should be done if this is the case?

Same Here. Tried `cd android && ./gradlew clean` and didn't work for me. I tried run in another project (Hello World initial) and run without error

**Comment by bkleef** [comment] 2019-10-12 16:19
In my case `bash` was not installed in the Docker container.

**Comment by jungRoit** [comment] 2019-10-16 13:20
I am facing the same issue. I tried to remove react-native-firebase package. and I have been getting this issue since

**Comment by MalinduPabasara** [comment] 2022-08-30 15:43
try this -> cd android && .\gradlew clean
