### ISSUE TITLE
Read values from default files, in case of no internet.

### ISSUE THREAD

**Issue by christopher-18** [invertase/react-native-firebase#6555] opened 2022-09-20 04:24 UTC
I need to read the default values , from remote_default_config.json file, when there is no network, but i am unable to do so and in those cases, values are being read from in code default values.
Following is the detailed description -

https://stackoverflow.com/questions/73773478/read-default-values-from-firebase-remote-config-in-js

**Comment by mikehardy** [comment] 2022-09-20 12:36
Hi there - it seems to me, based on the stackoverflow question this is not a react-native-firebase or firebase issue.
This is a "I'm having difficulty loading a JSON file" issue. I've answered you there: https://stackoverflow.com/a/73786807/9910298

It's not a bug in this library though and will not result in a change to this library so it is not really an issue, and I'll close it

**Closed by mikehardy** 2022-09-20 12:36 UTC
Labels: Impact: Bug, Help: Needs Triage

**Comment by christopher-18** [comment] 2022-09-21 03:18
@mikehardy   i followed following documentation , it is saying resource not found. Therefore wanted to know where exactly do i need to store the .json file. 
 This is what the function says.
 /**
     * Sets the default values from a resource file.
     * On iOS this is a plist file and on Android this is an XML defaultsMap file.
     *
     * ```js
     * // put in either your iOS or Android directory without the file extension included (.plist or .xml)
     *  await firebase.remoteConfig().setDefaultsFromResource('config_resource');
     *
     * // resource values will now be loaded in with your other config values
     * const config = firebase.remoteConfig().getAll();
     * ```
     *
     * @param resourceName The plist/xml file name with no extension.
     */
    setDefaultsFromResource(resourceName: string): Promise<null>;

**Comment by mikehardy** [comment] 2022-09-21 12:21
> documentation

You are attempting to follow the firebase-js-sdk documentation, while we attempt to follow their *apis*, we are not the firebase-js-sdk, we use the firebase-ios-sdk and firebase-android-sdks under the covers, and are a react-native module.

You need an object, to set in to here: https://rnfirebase.io/reference/remote-config/configdefaults

Not a resource name, we do not have that API because it is a react-native module not a JS module, so you must follow rnfirebase.io documentation

Given that - my statements above are still valid: you need to load the JSON file in whatever way is appropriate for you within the constraints of a react-native project, you need to parse it into a javascript object, then call the API I linked in this comment.

That should work...
