### ISSUE TITLE
iOS: FirebaseCore/FIRLogger.h cannot be found

### ISSUE THREAD

**Issue by vongohren** [invertase/react-native-firebase#2193] opened 2019-06-03 10:04 UTC
## Issue

My projected worked one week ago, but today it started failing on 
```
❌  /Users/snorre/code/diwala/cert-platform/packages/mobile/ios/Pods/FirebaseAuth/Firebase/Auth/Source/FIRUser.m:19:9: 'FirebaseCore/FIRLogger.h' file not found

#import <FirebaseCore/FIRLogger.h>
```

No idea why, I have not upgraded anything, except Xcode

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DiwalaMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  node_modules_path = '../node_modules'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  
  # React Native paths, needed for better integration
  # React native path for easier change between monorepo and not
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly  
  rn_path = "#{node_modules_path}/react-native" 
  
  pod 'React', :path => rn_path, :subspecs => [
    'CxxBridge', # Include this for RN >= 0.47
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => "#{rn_path}/ReactCommon/yoga"
  
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # Pods for DiwalaMobile
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'GoogleAppMeasurement', '5.8.0'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  
  # Intercom SDK
  pod 'Intercom'

  # Other injections of react native libraries


  target 'DiwalaMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end
   # this is needed to avoid including multiple references to react.
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end

```

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
      Memory: 36.66 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.10.0 - ~/.nvm/versions/node/v9.10.0/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.4.0 - ~/.nvm/versions/node/v9.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react-native: 0.57.5 => 0.57.5
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Android
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `Core & Auth`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2019-06-03 14:26
Install react-native-clean-project, on macOS run `react-native clean-project-auto && cd ios && pod update` then try again

**Comment by mikehardy** [comment] 2019-06-03 19:47
I'm going to resolve this as duplicate of #2163 - there are some path issues but the workaround there works, just a matter of fixing it for real but no one should be blocked anymore

**Closed by mikehardy** 2019-06-03 19:47 UTC

**Comment by vongohren** [comment] 2019-06-05 13:52
Thanks, it helped
