### ISSUE TITLE
ClassNotFoundException:    at dalvik.system.BaseDexClassLoader.findClass

### ISSUE THREAD

**Issue by riadhriadh** [invertase/react-native-firebase#5464] opened 2021-06-30 08:55 UTC
my google console dashboard shows a blocked app install because of 
java.lang.ClassNotFoundException
dalvik.system.BaseDexClassLoader.findClass

`java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4410)
  at android.app.ActivityThread.access$1600 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2159)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8506)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:207)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
  at android.app.AppComponentFactory.instantiateReceiver (AppComponentFactory.java:110)
  at androidx.core.app.CoreComponentFactory.instantiateReceiver (CoreComponentFactory.java:1)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4403)`

<img width="1268" alt="Capture d’écran 2021-06-30 à 09 49 26" src="https://user-images.githubusercontent.com/13996941/123931487-76fcf100-d988-11eb-822e-3ec4adfa0802.png">

<img width="318" alt="Capture d’écran 2021-06-30 à 09 49 47" src="https://user-images.githubusercontent.com/13996941/123931542-82e8b300-d988-11eb-9fc1-40783d86c68a.png">

I installed multidex:2.0.1

`
       compile 'androidx.multidex:multidex:2.0.1'

`
`project.ext {
  set('react-native', [
    versions: [
      // Overriding Build/Android SDK Versions
      android : [
        minSdk    : 16,
        targetSdk : 30,
        compileSdk: 30,
        buildTools: "30.0.2"
      ]
    ],
  ])
}`
This is my package information:
  "@react-native-firebase/analytics": "^11.5.0",
  "@react-native-firebase/app": "^11.5.0",
  "react": "17.0.1",
   "react-native": "^0.63.4",

**Comment by mikehardy** [comment] 2021-06-30 13:04
Hi there! This is not a problem with this module, so I will close this. No resolution here will result in a change in this module.

You have deleted the parts of the template which would allow troubleshooting, specifically MainApplication needs to extend MultiDexApplication.

This version of my demo script will demonstrate exactly how to do multidex, you may compare your project with the script and it's output to resolve your issue

https://github.com/mikehardy/rnfbdemo/blob/e015afec6d4242d3d180af57a447b593e969a464/make-demo.sh

Although it appears that with Android 11 and Android 10 you should not have problems with multidex, so you may have some other problem

**Closed by mikehardy** 2021-06-30 13:04 UTC
Labels: Help: Needs Triage, Impact: Bug

**Comment by riadhriadh** [comment] 2021-07-05 07:44
@mikehardy  the problem also with some android 9 devices
but there are devices that indicate in play store a crash but when download the app it is installed well and it works

**Comment by mikehardy** [comment] 2021-07-05 14:56
> You have deleted the parts of the template which would allow troubleshooting

**Comment by riadhriadh** [comment] 2021-07-05 17:43
@mikehardy  so how can I find out exactly where the problem exists

**Comment by mikehardy** [comment] 2021-07-05 17:50
By doing the work to find it. It is maybe not easy but no one is going to do your work for you, you have to dig in and reproduce the problem, then if it turns out that it's in some software component you are using (maybe this one, though doubtful, no one else has this problem, so maybe focus attention elsewhere to start?) you post an example using their issue tracker *and posting all the information they request* and they (or we) pick it uphttps://stackoverflow.com/help/minimal-reproducible-example

**Comment by mikehardy** [comment] 2021-07-05 17:52
To be most clear: there is *NO* indication react-native-firebase is involved in your stack trace at all. This is not a problem in this module near as I can tell.
