### ISSUE TITLE
[🐛] Bug Report Title - App crashed on first time launch with latest version [v10.8.1]

### ISSUE THREAD

**Issue by JiboStore** [invertase/react-native-firebase#4979] opened 2021-03-03 08:50 UTC
## Issue

Upon upgrading to latest version (v10.8.1), first install and run of the app causes crash / hang (if debug version)

```
import firebase from '@react-native-firebase/app';
firebase.initializeApp({appId: 'com.testrefresh'}); // this line causes the problem
```

This issue only happens on Android 11 devices (API Level 30)
-. start a new emulator with API Level 30 and run it there to see the first time launch crash:
emulator @Nexus_6_API_30 -wipe-data

-. It does not happen on lower Android versions
-. It does not happen on second and subsequent launches
-. there's no log at all other than WIN DEATH and process killed
-. the difference between working and non-working is just the react-native-firebase package version

The same code was fine before upgrading (prior version was v8.4.0)

I have created 2 branches (1 good case, and 1 bad case) based on the initial `react-native init` blank project setup, with just `react-native-firebase` dependencies being added together with the `initializeApp` code

Prior to upgrade (working code):
https://github.com/JiboStore/rnfirebase-firstcrash-repro-210303/tree/rnfirebase/repro-good

After upgrade (crashing)
https://github.com/JiboStore/rnfirebase-firstcrash-repro-210303/tree/rnfirebase/repro-bad

The difference between ok and crashing code:
https://github.com/JiboStore/rnfirebase-firstcrash-repro-210303/compare/rnfirebase/repro-good?expand=1

# Update:
Re-run again and get this suspicious callstack in logcat.
Could this be the cause?
https://github.com/JiboStore/rnfirebase-firstcrash-repro-210303/blob/rnfirebase/repro-bad-logcat/logcat.txt#L311

There are no changes at all, just the `react-native-firebase` versions

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [X] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2021-03-03 12:56
Could you please provide a crash stack trace?

**Comment by JiboStore** [comment] 2021-03-04 02:53
Sorry, previous run do not have any suspicious crash stack except win death
But I tried re-run again and get something suspicious

https://github.com/JiboStore/rnfirebase-firstcrash-repro-210303/blob/rnfirebase/repro-bad-logcat/logcat.txt#L311

**Comment by mikehardy** [comment] 2021-03-04 03:03
Very strange! Is it possible to reproduce this startup crash initializing a second app with a clean known-good project from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh ?

**Comment by JiboStore** [comment] 2021-03-04 03:50
@mikehardy thanks for the help~

I run your make-demo.sh and the generated project does not have the issue, however I noticed that there is no `firebase.initializeApp()` function call anywhere, so I added it in App.js like this:

https://github.com/JiboStore/rnfirebase-firstcrash-repro-210303/commit/4edb2aaf6ccf14df2d155e7714128efb6232abd8

then the issue happens

The same suspected trace is logged in 2 trial runs (across 2 separate installs, since issue only happens on first run of new installation):

https://github.com/JiboStore/rnfirebase-firstcrash-repro-210303/blob/rnfbdemo/master/logcat.txt#L4604
https://github.com/JiboStore/rnfirebase-firstcrash-repro-210303/blob/rnfbdemo/master/logcat-2.txt#L314

**Comment by mikehardy** [comment] 2021-03-04 13:14
Thanks - I really appreciate the logcats, and knowing you can reproduce it with the make-demo script is great, I've always got that script set up on my machine for troubleshooting problems in this repo. I can check it out this morning

**Comment by mikehardy** [comment] 2021-03-04 15:14
Okay, I reproduce the crash (on iOS as well!) when I use initializeApp that way.

My question is, why would you attempt to use the API that way? It does not seem to conform to the method signature at all?

https://rnfirebase.io/reference/app#initializeApp

You want to send in an argument with a different shape, specifically I think you want `{ name: 'your name here' }` ?

I have successful tests when I use it like that, e.g., these work for me:

https://github.com/invertase/react-native-firebase/blob/05067030c61fdf854ba19903db5b739736e68d1a/packages/app/e2e/app.e2e.js#L40-L49


(some side notes as a maintainer, I will fix all of these: 1) the type docs indicate return value of `FirebaseApp` for the `initializeApp` API call, but it should be `Promise<FirebaseApp>`, 2) the e2e tests here were disabled and not structured well, I have them patched up and working locally 3) the module of course should not crash with unexpected input - it works with correct input! - but I will patch up error handling)

**Comment by mikehardy** [comment] 2021-03-04 17:00
Okay 
- I was not able to reliably reproduce the crash so I can't make any changes to the native modules
- The javascript lib does an incredible amount of validation but the argument order is very important, you were attempting to provide a config value (which should be the second argument) as the first argument (which should be an options value, followed by your config). If the arguments are not in the order or shape expected, the javascript initializeApp code makes some assumptions and tries to initialize the default app

My proposed fix for you was to use name object property vs appId, but what you really want if you want to initialize appId is to pass options as well as a name as the second argument:

https://github.com/invertase/react-native-firebase/pull/4986/files#diff-ba4ac6d78adbedb6c794417f7f99411bf18deab1aa254662d8e778eacb49e55aR67

At which point you will receive an error because you need to send in the rest of the properties as well (apiKey etc etc): https://github.com/invertase/react-native-firebase/pull/4986/files#diff-ba4ac6d78adbedb6c794417f7f99411bf18deab1aa254662d8e778eacb49e55aR70

Also as mentioned you will want to await the call since initializeApp should return a Promise (which I have fixed in the typings)

Since this was an API usage issue, not really a bug, and I can't make it crash in testing when used correctly or incorrectly, I don't think there is anything else actionable here.

**Comment by JiboStore** [comment] 2021-03-05 04:21
Hi, sorry to bring this up again,

From your comments, here are further things I realised and some clarifications I'd like to make:
-. From the documentation, both Signature 1 and Signature 2 of `initializeApp` indicates that the 2nd param are optional, initially I was skipping them and only provide the `FirebaseAppOptions` as the first param:
`initializeApp(options: FirebaseAppOptions, config?: FirebaseAppConfig): FirebaseApp;`
`initializeApp(options: FirebaseAppOptions, name?: undefined | string): FirebaseApp;`
However, I tried filling in 2nd params accordingly (tried with Signature 1 and Signature 2) but the problem persist

-. I realised that I was missing another required properties of `FirebaseAppOptions`, that is `projectId`, so I modified the initializeApp calls to this:
`firebase.initializeApp({appId: 'com.testrefresh', projectId: 'project-id-from-firebase-console'});`
This also doesn't solve the problem

-. I only have the 1 app and just realised that I can forego calling that method entirely, accessing `firebase.firestore()` still let me access firestore services in old version (v8.4.1) after omitting the `initializeApp` calls and app name is initialized as `'[DEFAULT]'`

-. In v10.8.1, omitting the `initializeApp` call also result in the issue, running the second time, I am able to access firestore services without crash

Digging into the source-code and diff-ing v.8.4.1 and v10.8.1, I found this change:
-. https://github.com/invertase/react-native-firebase/blob/master/packages/app/android/src/reactnative/java/io/invertase/firebase/utils/ReactNativeFirebaseUtilsModule.java#L164
-. https://github.com/invertase/react-native-firebase/blob/%40react-native-firebase/app%408.4.1/packages/app/android/src/reactnative/java/io/invertase/firebase/utils/ReactNativeFirebaseUtilsModule.java#L164

Further digging into `context.getExternalFilesDir(null)` I found that it may indeed return null, and when it does so, the app will crash with the stated logcat
-. https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir(java.lang.String)

After I added the null check, it works fine!

**Comment by mikehardy** [comment] 2021-03-05 04:24
Ah ha! You appear to have found the native crash I couldn't trigger - since you already have the change, would you mind posting a PR for it? I could get it merged in and released quickly

And no - if you just have one app, there is no need to formally initialize it - the "default" app will always be initialized for you with no effort on your part, from the google-services.json (or plist, for iOS) files

**Comment by JiboStore** [comment] 2021-03-05 04:35
Thanks! I've cleaned up my code and created a PR for it

**Closed** 2021-03-05 12:51 UTC
Labels: Help: Needs Triage, Impact: Bug, Impact: Crash, Workflow: Waiting for User Response
