### ISSUE TITLE
Failed for task :app:processDebugGoogleServices

### ISSUE THREAD

**Issue by comycos** [invertase/react-native-firebase#398] opened 2017-09-08 14:52 UTC
### Issue

I'm pretty sure that this issue has been resolved before but I didn't find it.

I get this error while compiling: Failed for task :app:processDebugGoogleServices
Image: [https://imgur.com/a/VW56f](https://imgur.com/a/VW56f)

Sorry if I asked for something answered before and thanks!

### Environment

1. Application Target Platform: Android

2. Development Operating System:  Windows 10

3. Build Tools: Android Studio

4. React Native version: 0.48.2

5. RNFirebase Version: 2.2.0

6. Firebase Module: N/A

**Comment by Salakar** [comment] 2017-09-08 17:47
Most likely you have included 2 versions of google play services in your gradle files, check for any duplicates and remove the older version.

Also, you can use WIN + SHIFT + S - to screen capture on windows without needing to upload anywhere (goes direct to clipboard), saved me hours ha.

**Comment by comycos** [comment] 2017-09-08 18:21
Thank for the tip 😄 

I'm sure that I haven't any duplicate of google play services in my gradle files, but I tried to recompile and now I get another error.
![image](https://user-images.githubusercontent.com/7388957/30225614-6536174c-94d3-11e7-89c7-66e641f1039c.png)

That has any sense?

**Comment by Salakar** [comment] 2017-09-08 18:41
Can you paste both of your gradle files so I can take a look

**Comment by comycos** [comment] 2017-09-08 19:03
[build.gradle](https://gist.github.com/comycos/1d07e9ff5c8a4ab5cd27ca1eb286ab83)
[in app folder build.gradle](https://gist.github.com/comycos/8e4cc23a78a50684a601912ea94c7d51)

**Comment by ynsgnr** [comment] 2017-09-09 01:47
This issue about file acces. Deleting android/app/build folder usually solves it for me. Windows and its shenanigans :(

**Comment by comycos** [comment] 2017-09-09 11:26
Ok, I tried to delete the android/app/build folder and all seems to work fine but only the first time. When I recompile (without deleting the folder) I get:
![image](https://user-images.githubusercontent.com/7388957/30239671-1ef14268-9562-11e7-9a9b-acb553ca19a4.png)
as the first time.

I need to delete the build folder every time before run the project?

**Comment by ynsgnr** [comment] 2017-09-09 11:28
I guess yes, or try to find the process that locking that folder, its probably java gradle or npm then restart it

**Comment by comycos** [comment] 2017-09-09 12:35
I prefer to do a script that deletes that folder 😆 
but this error shouldn't happen at least in react native 0.47.2 doesn't happen.

**Comment by ynsgnr** [comment] 2017-09-09 12:39
Even that script might fail due to admin rights issue. Its about windows OS it has very stupid way to manage user rights on folders

**Comment by comycos** [comment] 2017-09-10 16:38
I do not know if it has to do with the previous errors but when I try to create an account with email it throws me this:
![image](https://user-images.githubusercontent.com/7388957/30250826-752dae0c-9655-11e7-8a92-10a80433fd30.png)

I have a file to initialize firebase
`import RNFirebase from 'react-native-firebase'`
`const configurationOptions = { debug: true};`
`const firebase = RNFirebase.initializeApp(configurationOptions);`
`export default firebase;`

Then I import that
`import firebase from '../../services/firebase'`

And yes my firebase project has allowed the email/password authentication method.

Why I can't use the auth module?

**Comment by ynsgnr** [comment] 2017-09-10 17:55
At this point you should ask on stackoverflow because its not a bug
Anyway, you probably didnt implement google-services.json try to look at https://developers.google.com/android/guides/google-services-plugin

**Comment by chrisbianca** [comment] 2017-09-18 08:01
Looks like the original issue has been resolved, so I'm closing this issue.  Please shout if this isn't the case.

**Closed by chrisbianca** 2017-09-18 08:01 UTC

**Comment by xanderberkein** [comment] 2018-05-17 13:31
@comycos Did you ever resolve this issue without having to delete the build folder every time? I got the same problem here.

**Comment by comycos** [comment] 2018-05-17 17:37
@xanderberkein Yes, I just update react-native and move the whole project to another directory to avoid problems with directory length.

**Comment by NiCRoZi** [comment] 2018-07-19 01:56
Should change your windows property settings of the files in the folder.
![capture](https://user-images.githubusercontent.com/26320678/42916877-fac6d494-8b0f-11e8-8531-61a00830912d.PNG)

*Ensure the Read-only check-box in unchecked. then click apply.

**Comment by Apak00** [comment] 2018-07-25 07:39
@NiCRoZi but you have to do this everytime, am I right? if so there is no perminent solution to this issue yet, is there?

**Comment by NiCRoZi** [comment] 2018-07-25 07:42
@Apak00  yes. I havent found any solution this far. I do gradlew clean everytime in android before i run react-native run-android

**Comment by Apak00** [comment] 2018-07-25 08:15
@NickyMwangi  I might have found a solution, I'm not sure  but try adding your buildToolsVersion back. Like so, I added `buildToolsVersion "26.0.0"` to my app level `build.gradle` file.

**Comment by digrase008** [comment] 2018-08-10 08:08
@Apak00 thanks your solution work for me . yes this is the issue with **buitdToolsVersion** try to track back on it. For me it's working properly on _**buildToolsVersion "25.0.3"**_ on **buildToolsVersion "26.0.0"** it is still creating issue some time

**Comment by abrarum** [comment] 2018-11-29 06:48
I had my terminal opened with packager already running (npm start). I terminated the packager and run from the android studio and I didn't get that error then.

**Comment by Joaaofiilho** [comment] 2019-03-30 20:39
This is about Windows file access. **Try restarting the computer**, it always worked for me. For some reason, windows blocks these file access.

**Comment by Javi** [comment] 2019-05-22 19:45
I still encounter this issue regularly on Windows. I always have to do `run-android` twice so things shake out in the right order and it's very frustrating.

**Comment by georgecirilo** [comment] 2019-06-02 13:12
Hello, is it possible that this error occurs whenever you're experiencing **internet** connection issues? 
I reckon that this configuratin in the buid.gradle has something to do:

    implementation 'com.google.android.gms:play-services-base:+'
    implementation 'com.google.android.gms:play-services-maps:+'

**Comment by Javi** [comment] 2019-06-04 00:26
Certainly not, it happens every single time. I'm pretty sure there's some kind of race condition in Windows environments where a file is written to and deleted at the same time before it's released.

**Comment by LuckyShine001** [comment] 2019-11-28 11:44
https://github.com/invertase/react-native-firebase/issues/1413#issuecomment-559461920

**Comment by alex-Z-** [comment] 2019-12-04 10:24
For me, the issue caused by the Linux Subsystem (I have run some jobs for this project from the subsystem and some from Windows). As a result, I had to run chmod from the subsystem (Ubuntu app in my case ), and it did the trick for me. Hope it helps.

**Comment by afx31** [comment] 2020-02-20 23:40
This issue constantly happens to me. I can close my project at the end of the day working, open it the following morning and it'll crash with the `Execution failed for task ':app:processDebugGoogleServices'` error straight away. Seems like a poor flaw with so many issues over the internet of it, with the only 'solution' being to either restarting windows, keep rebuilding the project with hope, or run the usual `cd android && ./gradlew clean`

**Comment by kavinraju** [comment] 2020-02-27 00:34
@JavierYepez Did you create a new project and added the google-json.services of another project and added the SHA1 of the new project in that another project's Firebase console?

**Comment by sugih28** [comment] 2020-03-09 09:03
run as Administrator in CMD & run the project, it's gonna be Ok for me.

**Comment by datdang2311** [comment] 2020-05-11 07:52
> run as Administrator in CMD & run the project, it's gonna be Ok for me.

it's work for me :D

**Comment by harisrozajac** [comment] 2020-12-23 18:47
> Ok, I tried to delete the android/app/build folder and all seems to work fine but only the first time. When I recompile (without deleting the folder) I get:
> ![image](https://user-images.githubusercontent.com/7388957/30239671-1ef14268-9562-11e7-9a9b-acb553ca19a4.png)
> as the first time.
> 
> I need to delete the build folder every time before run the project?

I just manually created a debug directory in google-services and it solved the issue for me

**Comment by subhash-kumar** [comment] 2023-10-30 06:30
I am facing this error plz solution permanent.

1.: I tried to delete the android/app/build folder and all seems to work fine but only the first time. When I recompile (without deleting the folder) I get:

2.)  I need to delete the build folder every time before run the project?

![image](https://github.com/invertase/react-native-firebase/assets/25743407/8bd6d56a-514b-4653-a939-471467bd99ff)
