### ISSUE TITLE
[🔥] Phone authentication fails in Play Store - Phone authentication works in apk and stopped working in play store

### ISSUE THREAD

**Issue by steniobarroso** [invertase/react-native-firebase#5463] opened 2021-06-29 20:59 UTC
## Issue

<-->

Remembering that installing the generated apk the application sends the SMS without problems

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x ] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ x] my application is an AndroidX application?
- [ x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2021-06-29 21:20
This is almost always the wrong SHA in the firebase web console. Especially if you use App Bundles, Google generates an APK for you and signs it themselves. You must get *that* SHA and make it known to google firebase in the config in the web console.

There are plenty of other issues in this repo with the similar issue and successful project-specific resolution if you search, I believe

This is not a bug in the module and will not result in a change to the module so I will close the issue.

**Closed by mikehardy** 2021-06-29 21:20 UTC
Labels: Help: Needs Triage, Impact: Bug
