### ISSUE TITLE
[🐛] Apple Store review fails - Cannot contact reCAPTCHA. Check your connection and try again

### ISSUE THREAD

**Issue by AmmarArnt** [invertase/react-native-firebase#6485] opened 2022-08-23 14:18 UTC
## Issue

During the Apple review process they are rejecting the app for the following reason:

> Cannot contact reCAPTCHA. Check your connection and try again

Please note that I do not get this behavior on any real device, or on iOS simulators. This does not occur on Android.

![screenshot](https://iosapps-ssl.itunes.apple.com/itunes-assets/Purple122/v4/c6/a3/9c/c6a39cba-f9ee-cdb6-421a-9f9c5a4bc50d/Screenshot-0822-115708.png?accessKey=1661521230_3391344357850569374_6QNa7RvS5C8CqmPlsTvTbfobEOP67S5Rz3Z2lPDG0rBLV%2FKPyBteSMtB2Ac5WiJTlVhyOCWs%2Fv%2FcNqqQwqrBg9uwyWz7%2FKnreoikZvOBEARK0a%2BFSwALHxdcNNdcOAszVikyp%2FsEedaKh9Kb1HWhtG%2BQ%2F%2B%2BhOMy%2FbcyWgNjJqXf7s2wWELjg1W5TN8vP%2Bc3i)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "14.8.0"
    "@react-native-firebase/auth": "14.8.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.0'
def shared_pods
  config = use_native_modules!
  inhibit_all_warnings!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  $RNFirebaseAnalyticsWithoutAdIdSupport=true
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2022-08-23 17:11
Sorry - I just saw this issue, but I saw the comment first, here: https://github.com/invertase/react-native-firebase/issues/5882#issuecomment-1224351857

I'm going to say this is in fact a duplicate of #5882, based on my reasoning from the comment:

----

Best guess here is intermittent network connection issue on the reviewers side. It was resolved by another affected party by essentially re-reviewing until they had a device that worked:

https://github.com/firebase/firebase-ios-sdk/issues?q=cannot+contact+recaptcha+check+your+connection+and+try+again

Unfortunately, this isn't actionable here as it doesn't reproduce for me and does not happen normally. But! Networks do have intermittent failures all the time, it appears that it is just really unfortunate this happened to the reviewer during the review process :weary:

**Closed by mikehardy** 2022-08-23 17:11 UTC
Labels: Impact: Bug, Help: Needs Triage
