### ISSUE TITLE
[docs] Setup with staging / production project configurations

### ISSUE THREAD

**Issue by JesperLekland** [invertase/react-native-firebase#452] opened 2017-09-28 08:31 UTC
### Issue

Hi! I was wondering how one would go about settings this up with different GoogleService-info.plist files? I have two configurations (Staging & Production), and for these I want the different plist files. 

According to [this](https://firebase.google.com/docs/configure/) it's absolutely possible but I don't know how to do this with your wrapper.

Thanks in advance

### Environment

1. Application Target Platform: iOS 

2. Development Operating System: macOS  

3. Build Tools: Xcode

4. React Native version: not relevant

5. RNFirebase Version: 2.2.1

6. Firebase Module: notifications

**Comment by akshetpandey** [comment] 2017-09-28 18:17
The may I do it is create multiple schemes and buildTypes on ios/Android. Then as a build step copy over the right GoogleService-info.plist  file.

Each scheme has a custom property that specifies the filename

<img width="511" alt="screen shot 2017-09-28 at 11 15 14 am" src="https://user-images.githubusercontent.com/1213060/30983117-58daefe8-a43e-11e7-9d9b-55f51090606b.png">

Build Phases then has a script to copy the right one over

<img width="300" alt="screen shot 2017-09-28 at 11 16 30 am" src="https://user-images.githubusercontent.com/1213060/30983181-842e7e3a-a43e-11e7-913b-97e8ed0a296a.png">

Here is the code for the build script:
```sh
cp -r "${PROJECT_DIR}/thriller/SupportingFiles/${FIREBASE_CONFIG_FILE_PREFIX}-GoogleService-Info.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
echo "${FIREBASE_CONFIG_FILE_PREFIX} Firebase plist copied"
```

**Comment by chrisbianca** [comment] 2017-09-29 07:39
This is the approach we use too.  I'll leave this issue open so we can add some information to the docs.

**Comment by Ehesp** [comment] 2017-10-21 08:31
New docs are at https://github.com/invertase/react-native-firebase-docs - will need adding there, not sure under what section yet though.

**Comment by egunsoma** [comment] 2017-12-21 13:45
Could you guys please create a step-by-step setup guide for this in the docs? It would be really helpful for most of us, since I haven't found any guide like this online. Thank you!

**Comment by egunsoma** [comment] 2018-01-09 00:46
I created a solution that works with App Center:
https://medium.com/@egunsoma/firebase-environments-with-react-native-dev-staging-prod-3832d7d22a80

**Comment by pmarconi** [comment] 2018-04-16 18:28
Hi guys, thanks for the help on this... I have doubts about how to do this correctly.
But why not use different targets as specified in the firebase documentation? Where in each of the targets you can associate a  different `GoogleService-Info.plist` file

**Comment by Salakar** [comment] 2018-07-01 17:19
Thanks all for the solutions on this and the write-ups. Lets move this discussion over to https://github.com/invertase/react-native-firebase-docs/issues/76 which is a duplicate of this.

**Closed by Salakar** 2018-07-01 17:19 UTC
Labels: docs, help wanted

**Comment by krewllobster** [comment] 2019-01-03 22:21
Any chance of reviving as issue #76 is a broken link?

**Comment by Salakar** [comment] 2019-01-03 23:48
@krewllobster link is fine now, sorry about that. On a side note this functionality will be coming in a CLI later in the year.

**Comment by fhuel** [comment] 2020-02-06 16:04
Hey there, 
I'm really struggling to setup dev and prod environments, and build the app accordingly,
any news about this?

**Comment by mikehardy** [comment] 2020-02-06 18:14
@fhuel there are lots of ways to do it. Depends on your desires. Here is a big copy/splat from the Discord where I answered this recently.

>I am unsure. I personally wanted fewer steps, and I felt having a sort of "render" phase prior to the real build (the file copy style) was another moving part and some script to maintain, while Xcode provided me the way to configure and declare the targets and plist files etc, so I chose that. But I'll be the first to rant about how terrible Xcode's configuration system is - almost bad enough to make me want to do a pre-render (which isn't too hard to reason about) vs have it in Xcode. In the end I did it in Xcode and it's worked well so I just keep using it. :slight_smile:
> GazzaHazzaLast Tuesday at 10:17 AM
> Thanks for letting me know! if you have any good material on this subject that helped you could you pass it my way? :thumbsup: Thanks again
> MikeHardyLast Tuesday at 10:24 AM
> then on the android side I use flavors - I followed a tutorial that I have since forgotten unfortunately
> here is an example of the "pre-render" style https://medium.com/@egunsoma/firebase-environments-with-react-native-dev-staging-prod-3832d7d22a80
here's one that does pre-render but as a build phase https://medium.com/bam-tech/setup-firebase-on-ios-android-with-multiple-environments-ad4e7ef35607
here's the different targets style https://gist.github.com/jacks205/45b2721bf2a2b912b1c130aef2572820 - mine works a bit like this
> MikeHardyLast Tuesday at 10:30 AM
> I misspoke - they are not targets, they are schemes - this example is from flutter but maps very closely to how I did it on both sides https://medium.com/@matt.goodson.business/separating-build-environment-configurations-in-flutter-with-firebase-doing-it-the-right-way-c72c3ad3621f
then I just choose which scheme to build. lots of ways to do it as you can see :-). good luck
```

**Comment by fhuel** [comment] 2020-02-07 10:25
Hey @mikehardy , thank you!

**Comment by github4es** [comment] 2020-04-07 23:13
Per the CodePush multi-deployment docs, the multi-deployment is only available for React. any ideas how others do it for Angular 8 and iOS ?

**Comment by KrisLau** [comment] 2024-05-31 09:14
@mikehardy or anyone else that might've done this, sorry I know it's an old issue but I'm trying to setup a prod environment but I'm running into an issue with the android part of the [setup](https://rnfirebase.io/#generating-android-credentials) where when I'm adding the sha to to prod project I get this error. How did you guys set this up for multiple environments? Did you guys just use the release variant of the sha?
![image](https://github.com/invertase/react-native-firebase/assets/46275463/263257ec-d953-43da-b9ee-218dad781a7c)

**Comment by mikehardy** [comment] 2024-06-07 23:16
my multi-backend builds use android package suffix, so the shas and package names are different, it avoids this problem

e.g., com.kullki.kscore.dev com.kullki.kscore.staging and then just com.kullki.kscore for prod

**Comment by mikehardy** [comment] 2024-06-07 23:16
@KrisLau should have tagged you - replied above ☝️
