### ISSUE TITLE
Firebase Dynamic Link on getInitialLink is null

### ISSUE THREAD

**Issue by glyhakan** [invertase/react-native-firebase#6707] opened 2022-11-17 10:55 UTC
**Issue**

Problem is Firebase Dynamic Link on getInitialLink is null when app opened with deeplink. IOS and Android same.  Deeplink is working well when app is on background.

  ```
  dynamicLinks()
      .getInitialLink()
      .then((link) => {
       window.console.log(link) -----> always null
      });
```

**Dependencies**

 "@react-native-firebase/app": "8.2.0",
  "@react-native-firebase/dynamic-links": "7.3.2",
  rn version: 0.70.6

what can i handle this situation ?

**Comment by mikehardy** [comment] 2022-11-17 12:36
These versions are frighteningly old!

```
"@react-native-firebase/app": "8.2.0",
"@react-native-firebase/dynamic-links": "7.3.2"
```

--> we are on v16+ here now - https://invertase.io/blog/react-native-firebase-versioning will explain our versioning and give you the tools you need to get current

*only once you are current and you still reproduce this is it worth looking at*

That said, if you notice this on iOS you may need this workaround: https://github.com/invertase/react-native-firebase/issues/4548#issuecomment-1252028059

Since that issue is tracking dynamic link behavior (with the given workaround) and everyone reports it working as long as the workaround is in place, I'm going to close this for now as duplicate / versions out of support

**Closed by mikehardy** 2022-11-17 12:36 UTC
Labels: Impact: Bug, Help: Needs Triage
