### ISSUE TITLE
[🐛] Bug when trying to upgrade my firebase libraries

### ISSUE THREAD

**Issue by laurpantelimon** [invertase/react-native-firebase#5447] opened 2021-06-22 09:30 UTC
## Issue

So I upgraded all my firebase libraries as follows:

"@react-native-firebase/admob": "^10.1.1" -> "^11.5.0",
    "@react-native-firebase/analytics": "^7.6.1"  ->  "^12.1.0",
    "@react-native-firebase/app": "^8.4.1"  ->  "^12.1.0",
    "@react-native-firebase/auth": "^9.1.2"  ->  "^12.1.0",
    "@react-native-firebase/firestore": "^7.6.2"  -> "^12.1.0",
    "@react-native-firebase/functions": "^7.4.2"  ->  "^12.1.0",
    "@react-native-firebase/messaging": "^7.8.4"  -> "^12.1.0",

But when I run pod install (or pod install --repo-update) I get the following error: 
 ---
[!] CocoaPods could not find compatible versions for pod "Firebase/AdMob":
  In Podfile:
    RNFBAdMob (from `../node_modules/@react-native-firebase/admob`) was resolved to 11.5.0, which depends on
      Firebase/AdMob (= 8.1.1)

None of your spec sources contain a spec satisfying the dependency: `Firebase/AdMob (= 8.1.1)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

[!] NPM package '@react-native-firebase/admob' depends on '@react-native-firebase/app' v11.5.0 but found v12.1.0, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/admob' depends on '@react-native-firebase/app' v11.5.0 but found v12.1.0, this might cause build issues or runtime crashes.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2021-06-22 13:28
You cannot mix and match the versions here

https://invertase.io/blog/react-native-firebase-versioning

You cannot use admob with v12 https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#breaking-changes

> AdMob: Removed from upstream SDKs. Stay on v11.5.0 for now if you need AdMob. @invertase/react-native-admob package planned with v11.5.0 code

So you cannot upgrade your libraries past v11.5.0 while still using admob

There are still plans to release a separate admob but it's a human process (time available) and professional thing (admob is *not* in firebase anymore so it is prioritized behind firebase-specifc items important to the firebase ecosystem)#2355 

In essence this is a duplicate of #5329 then and discussion / status is there

I appreciate the understanding while handling all the breaking changes and getting it done

**Closed by mikehardy** 2021-06-22 13:28 UTC
Labels: Help: Needs Triage, Impact: Bug
