### ISSUE TITLE
Archive Firebasecore/FirebaseAppinternal.h file not found 

### ISSUE THREAD

**Issue by getinfyKiranreddy** [invertase/react-native-firebase#2177] opened 2019-05-29 08:04 UTC
xcode . 10.2.1
React-native0.57.8
ReactJs 16
react-native-firebase  5.2. 
i am archiving my ios project in xcode i got Firebasecore/firebaseAppinternal.h file not found error. can any one help me out

**Comment by mikehardy** [comment] 2019-05-29 18:34
Sorry - as far as I know most folks have moved to current (0.59.8 react-native, 5.4.1+ react-native-firebase etc). I'm not sure what's going on with the older versions but I there are a lot of bugfixes I don't want to hit that have personally affected me so I'm not that motivated to go back.

If you can reproduce this on current versions I can look. If it's just archiving then I would pay very careful attention to any header search path differences in XCode between debug and release

There is a separate iOS issue I'm currently working through on current versions #2163  that has a partial workaround you can apply in a podfile. Maybe it will help or maybe it just makes things worse, unknown for older versions

**Comment by getinfyKiranreddy** [comment] 2019-05-30 04:15
my project was started 6 months back, so we uses 0.57. now we can't move to new versions why because all version needs to changed in package.json file so I am using RNFirebase version 5.2.5. If I use latest version then i got some error even my project is not supporting so that's way I used older version 

when I run IOS build then it works fine everything but when I run archive then It gives an error like FirebaseCore/FirebaseAppInternal.h file not found.

I have tried to solve different ways but It could not solved. It's been 3 days I am working on it 

Can you help out ? what should I do ?

**Comment by mikehardy** [comment] 2019-05-30 12:00
Needing to change many versions in package.json is not a great reason, I still won't invest time supporting old versions, sorry, it's more painful than the necessary work to move forward. Would have taken less than 3 days! You definitely have something wrong in your search paths. There's something different between debug and release mode paths. Examine your project file (like, the actual text file) to find those differences.

**Comment by getinfyKiranreddy** [comment] 2019-05-31 08:22
Yeah thanks for supporting 
react-native : 0.59.8
react:16.8.6
React-native-firebase: 5.4.2
I have updated my package.json file everything is fine now
But when I archive my project again I got above error only
I have checked all paths but still same error I am getting 
can you help me out ?
Thanks

**Comment by mikehardy** [comment] 2019-05-31 14:38
Okay, so the react-native-firebase-starter project works - you can clone that, and prove it works for you. That serves two purposes, makes sure your local environment works, and also gives you an XCode project file with correct paths. I'd carefully compare the paths and use the same ones. Past that, I dunno - XCode is terrible and these problems should embarrass the creators - I feel your pain but don't know what else to do other than careful comparison from working projects.

**Comment by getinfyKiranreddy** [comment] 2019-06-03 05:46
Which project I have to clone it ?
I have checked all paths those are all correct. Even I got same issue FirebaseCore/FirenbaseAppInternal.h file not found 
Everything is fine when I build an app it's working super good.But issue is when I archive an app then only I got an issue.
I was got irritated by that issues I was trying to solve that issues but I could not 
Please help me out.

Thanks

**Comment by mikehardy** [comment] 2019-06-03 18:29
@getinfyKiranreddy 
> Which project I have to clone it ?
react-native-firebase-starter - the one I mentioned, it's the first result? https://duckduckgo.com/?q=react-native-firebase-starter

Also you might like https://github.com/mikehardy/rnfbdemo - it starts from scratch (`react-native init`) links in react-native-firebase and by the time it's done it archives fine. I just tested it.

There is a workaround in the Podfile there, related to #2163 - maybe it would help you.

**Comment by mikehardy** [comment] 2019-06-03 19:44
I'm going to resolve this as duplicate of #2163 - the workaround there works, just a matter of fixing it for real but no one should be blocked anymore

**Closed by mikehardy** 2019-06-03 19:44 UTC
