### ISSUE TITLE
iOS app crashes after upgrading to v5.1.0

### ISSUE THREAD

**Issue by KazuyaHara** [invertase/react-native-firebase#1761] opened 2018-12-14 11:26 UTC
## Issue

iOS app crashes and can't open after upgrading to v5.1.0. App works with v5.0.0 correctly. And to make matter worse, there is no error message without this.

```
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
``` 

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '10.0'

target 'XXX' do
  # use_frameworks!

  # Pods for XXX
  rn_path = '../node_modules/react-native'

  pod 'BVLinearGradient', path: '../node_modules/react-native-linear-gradient'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'Fabric', '~> 1.7.13'
  pod 'Firebase/Auth', '~> 5.10.0'
  pod 'Firebase/Core', '~> 5.10.0'
  pod 'Firebase/Firestore', '~> 5.10.0'
  pod 'Firebase/Functions', '~> 5.10.0'
  pod 'Firebase/Storage', '~> 5.10.0'
  pod 'Folly', podspec: "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'React', path: rn_path, subspecs: %w[
    Core
    CxxBridge
    DevSupport
    RCTActionSheet
    RCTAnimation
    RCTGeolocation
    RCTImage
    RCTLinkingIOS
    RCTNetwork
    RCTSettings
    RCTText
    RCTVibration
    RCTWebSocket
  ]
  pod 'react-native-fast-image', path: '../node_modules/react-native-fast-image'
  pod 'react-native-splash-screen', path: '../node_modules/react-native-splash-screen'
  pod 'react-native-version-check', path: '../node_modules/react-native-version-check'
  pod 'RNImageCropPicker', path: '../node_modules/react-native-image-crop-picker'
  pod 'RNSVG', path: '../node_modules/react-native-svg'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"

  target 'XXXTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'XXX-tvOS' do
  # use_frameworks!

  # Pods for XXX-tvOS

  target 'XXX-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.remove_from_project if target.name == 'React'
  end
end

```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <Firebase.h>

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNSplashScreen.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];

  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"XXX"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [RNSplashScreen show];
  
  return YES;
}

@end
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - iOS 12.1
- **Operating System:**
  - [X] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - Xcode 10
- **`React Native` version:**
  - v0.57
- **`React Native Firebase` library version:**
  - v5.1.0
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [X] Authentication
  - [ ] Analytics
  - [X] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [X] Crashlytics
  - [ ] Dynamic **Links**
  - [X] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [X] Storage
- **Are you using `TypeScript`?**
  - [X] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by oOMoeOo** [comment] 2018-12-14 17:21
I'm experiencing exactly the same issue!

**Comment by partriv** [comment] 2018-12-15 05:51
I had this exact issue. Had to drop my version to 5.0.0 of RNFirebase.

**Comment by oOMoeOo** [comment] 2018-12-15 08:36
It seems to be a problem with the native firebase sdk 5.10.0 and 5.11.0. After upgrading to 5.14.0 everything works fine.

**Comment by artechventure** [comment] 2018-12-16 14:49
I solved this issue by upgrading native firebase sdk to 5.14.0 too.

**Comment by NativLouie** [comment] 2018-12-18 15:14
still having the same issue even after upgrading to 5.14.0. any suggestions?

**Comment by Salakar** [comment] 2018-12-18 15:21
Hey, this is a duplicate of https://github.com/invertase/react-native-firebase/issues/313 - please collate / collab over there. Thanks.

**Closed by Salakar** 2018-12-18 15:21 UTC
