### ISSUE TITLE
[📚] Documentation Issue Title -  Firebase Installation for Latest React Native Version 0.71.8 for ios

### ISSUE THREAD

**Issue by HassaanShahzad98** [invertase/react-native-firebase#7158] opened 2023-06-04 16:10 UTC
## cannot build the application for ios side in react-native version 0.71.8

Hello, firebase community, I am reaching out to seek guidance to install Firebase in my react-native app version 0.71.8

I have tried it for a couple of days and I find the documentation to be not very clear or helpful for the ios side, I have successfully done it for my Android side, but unable to build the application for ios.

it would be very helpful if someone could provide me steps of installation w.r.t react-native version 0.71.8

thank you in advance

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2023-06-06 00:05
Here is a fully reproducible scripted build demonstration that I just updated to / tested with 0.71.8

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

It works fine, and as that is a complete reproduction that proves it works I'm going to have to close this as cannot reproduce - but I sincerely hope reading that script (it is thoroughly commented and starts from scratch!) will get you moving

**Closed by mikehardy** 2023-06-06 00:05 UTC
Labels: Type: Docs, Help: Good First Issue
