### ISSUE TITLE
[Android][Notification] getInitialNotification cant get notification data

### ISSUE THREAD

**Issue by jindada** [invertase/react-native-firebase#1190] opened 2018-06-08 07:56 UTC
### Issue
application is closed, click the notification, app run and call getInitialNotification 
only can get notificationId
![image](https://user-images.githubusercontent.com/16317349/41145471-c0419360-6b32-11e8-9189-b670d063bc63.png)
but when  application is running, get  data success from onNotificationOpened

### Environment
1. Application Target Platform: Android
2. Development Operating System: macOS Sierra
3. Build Tools: Android Studio 3
4. React Native version: 0.55.3
5. RNFirebase Version: 4.1.0
6. Firebase Module: FCM notification

**Comment by chrisbianca** [comment] 2018-06-18 15:34
What is the content of the notification that you're sending?

**Comment by jindada** [comment] 2018-06-19 01:06
I send a data message ( high-level ) through firebase console
I didn't configure the `RNFirebaseBackgroundMessage` function and I received the background message, after the configuration `RNFirebaseBackgroundMessage` function,  there is no change
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.soufeel.soufeel"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:launchMode="singleTop">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

      <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />

      <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>
      
      <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
        <intent-filter>
          <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
        </intent-filter>
      </service>


      <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>
      
      <receiver android:enabled="true" android:exported="true"  android:name="io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED"/>
              <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
              <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
              <category android:name="android.intent.category.DEFAULT" />
          </intent-filter>
      </receiver>

      <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_launcher" />

      <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:value="#000" />

      <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="default-channel"/>

      <receiver android:name="io.invertase.firebase.notifications.RNFirebaseBackgroundNotificationActionReceiver" android:exported="true">
        <intent-filter>
          <action android:name="io.invertase.firebase.notifications.BackgroundAction"/>
        </intent-filter>
      </receiver>
      <service android:name="io.invertase.firebase.notifications.RNFirebaseBackgroundNotificationActionsService"/>

    </application>

</manifest>
```

```
componentDidMount() {
    this.notificationListener = firebase.notifications().onNotification(e => {
      const notification = new firebase.notifications.Notification()
        .setNotificationId(e._notificationId)
        .setTitle(e._title)
        .setBody(e._body)
        .setSound('default')
        .android.setChannelId('default-channel')
        .android.setSmallIcon('ic_launcher')
        .android.setPriority(firebase.notifications.Android.Priority.High)      
        .setData(e._data);
      
      firebase.notifications().displayNotification(notification)
    });



    firebase.notifications().onNotificationOpened((notificationOpen) => {
      console.log(notificationOpen)
      firebase.notifications().removeDeliveredNotification(notificationOpen.notification._notificationId)
    });


    firebase.notifications().getInitialNotification()
      .then((notificationOpen) => {
        console.log(notificationOpen)
      });
  }
```

**Comment by Salakar** [comment] 2018-06-26 17:00
@jindada can you show the content of your notification from the firebase console

**Comment by Nitingadhiya** [comment] 2018-08-01 11:57
same issue in android device, 
when click to notification window that time 
getinitial method call but we have getting null response. 
when we click to notification.
react-native V : 0.56.0
react: 16.4.1

**Comment by AlanRedvike** [comment] 2018-08-03 06:47
any one with a solution ? i can't get this to work ;s

**Comment by RobertFOConnor** [comment] 2018-08-03 13:39
seem to be getting a similar issue :/ works for ios tho

**Comment by rheng001** [comment] 2018-08-13 23:49
Same issue here for Android. When app is opened foreground/background I get notifications just fine. When I close the app and use

```
async componentDidMount() {
  const notificationOpen: NotificationOpen = await firebase.notifications().getInitialNotification();
  if (notificationOpen) {
      alert("Opened from closed app");
  }
  else{
    alert("Not opened from closed app")
  }
} 
```
It always goes into the else statement

**Comment by vhuerta** [comment] 2018-09-03 16:53
Im getting the same problem, when i open the notification on android device onNotificationOpened is called but the notification has an empty body and also and empty title and data, this is the same when the app is completely closed getInitialNotification returns empty values too.

**Comment by vhuerta** [comment] 2018-09-17 15:56
Any update on this?

**Comment by CoderHuzaifa** [comment] 2018-09-19 08:50
+1 Need solution for this..

**Comment by CoderHuzaifa** [comment] 2018-09-19 08:50
If you console.log(NotificationOpen) it just shows undefined

**Comment by babara2** [comment] 2018-09-28 16:56
Same issue here. 

getInitialNotification() is not working as expected for android.

**Comment by sibelius** [comment] 2018-10-02 21:03
When the notification is received the `data` value contains that notification data

However, when I click in the notification, the data is empty

**Comment by MattElias** [comment] 2018-11-04 00:53
I got stuck in this issue for the last 4 hours.

It turns out that you've got to send the message with the data object outside the notification object, as exemplified below:

```
const MESSAGE_CONFIG = {
  to: FCM_TOPIC,
  content_available: true,
}

export interface IMessage {
  to: string,
  content_available: boolean,
  data: IData,
  notification: INotification
}

export interface IData {
  url: string,
}

export interface INotification {
  title: string,
  body: string,
}

async function sendNotification(notification: INotification, data?: IData) {
  const message = { ...MESSAGE_CONFIG, notification, data } as IMessage
  await fcm.send(message)
}
```

After this change, the data started to show upon opening the notification with the app closed.

**Comment by karlmarxlopez** [comment] 2018-11-06 13:00
I'm expieriencing this also. The payload is null when I tap on a notification, but when I close then open the app. I get the payload of the previously opened notification

**Comment by jankrah12** [comment] 2018-11-15 23:46
Any solution? Many have asked the question but there does not seem to be a solution in any of the threads. getInitialNotification() is still null on android

**Comment by luisfuertes** [comment] 2018-11-16 12:43
+1 with "react-native-firebase": "4.3.8", "react-native": "0.54.0"

**Comment by Huzaifaak** [comment] 2019-01-12 14:08
For those who can't access body, title of notifcation when app is background or closed: 

> On Android, unfortunately there is no way to access the title and body of an opened remote notification. You can use the data part of the remote notification to supply this information if it's required.

**Comment by introin** [comment] 2019-03-08 16:51
For android — Use data part to send title and body and then handle while showing message
Ex
` const { data } = notificationOpen.notification;
            this.showAlert(data.title,data.body);`

**Comment by MrEdinLaw** [comment] 2019-06-12 13:09
Bump? Still not working...

**Comment by mikehardy** [comment] 2019-06-12 15:43
Show a clean reproduction, or make a PR and we can try to reproduce or we'll have a fix...

**Comment by MrEdinLaw** [comment] 2019-06-13 10:46
@mikehardy i have fixed it by running the `firebase.auth` after the `getInitialNotification`

**Comment by luisfuertes** [comment] 2019-06-13 10:48
Buy my app dont user firebase login. How can if ix?

**Comment by mikehardy** [comment] 2019-06-15 23:24
If anyone has combined react-native-splash-screen with react-native-firebase, and they implemented the splash screen with a separate launch activity, this will happen. There are workarounds but you should use splash-screen with a single Activity and it just works. Code here: https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454

**Comment by mikehardy** [comment] 2019-06-16 15:50
This is an unfocused discussion now, and after confirming that react-native-splash-screen (which is very common) can interfere with this and testing a workaround for it (linked above) I'm going to close this. If people still have problem please follow the issue template completely and (ideally!) post a reproduction repo on github

**Closed by mikehardy** 2019-06-16 15:50 UTC
Labels: API: Notifications, Blocked: Needs Review, Help: General, Platform: Android

**Comment by SathishSaminathan** [comment] 2019-11-16 02:29
https://github.com/invertase/react-native-firebase/issues/1108#issuecomment-427006332 Try this..

**Comment by inceabdullah** [comment] 2019-12-15 20:26
> 
> 
> Same issue here for Android. When app is opened foreground/background I get notifications just fine with if (notificationOpen). When the app is closed and I reopen it and use getInitialNotification
> 
> ```js
> async componentDidMount() {
>   const notificationOpen: NotificationOpen = await firebase.notifications().getInitialNotification();
>   if (notificationOpen) {
>       alert("Opened from closed app");
>   }
>   else{
>     alert("Not opened from closed app")
>   }
> } 
> ```
> 
> It always goes into the else statement

Shoud be `Opened from closed app.`

**Comment by sadikyalcin** [comment] 2020-04-23 19:42
2 years on and I'm facing the same issue. There are multiple issues regarding this and I've yet to find a solution. It works fine for iOS.

I am now not even getting the notifications when the app is dead and getting the `No task registered for key ReactNativeFirebaseMessagingHeadlessTask` warning.

    constructor(props, context) {
        super(props, context);
        this.state = {
            store: authStore.getState(),
        };

        messaging().onMessage(async remoteMessage => {
            if (remoteMessage) {
                console.log('@onMessage()');
                this.showAlert(remoteMessage);
            }
        });

        messaging().setBackgroundMessageHandler(async remoteMessage => {
            console.log('Message handled in the background!');
            //console.log(remoteMessage);
        });

        messaging().onNotificationOpenedApp(remoteMessage => {
            // not firing
            console.log('@onNotificationOpenedApp(): ', remoteMessage);
            if (remoteMessage) {
                console.log('@onNotificationOpenedApp()');
                this.showAlert(remoteMessage);
            }
        });

        messaging()
            .getInitialNotification()
            .then(remoteMessage => {
                console.log('@getInitialNotification(): ', remoteMessage); // null
                if (remoteMessage) {
                    console.log('@getInitialNotification()');
                    this.showAlert(remoteMessage);
                }
        });
    }

**Comment by marcoburrometo** [comment] 2020-05-18 13:57
> @jankrah12 the referred solution worked with me perfectly as it was the splash screen which was the issue and as you referred to the solution adding
> 
> ```js
>         // NOTE: This is necessary to forward the original intent on to the main activity.
>         // This makes firebase.notifications().getInitialNotification() work.
>         intent.putExtras(this.getIntent());
> ```
> 
> inside the **SplashActivity.java** it worked !
> 
> Big Thank You

Thank you, saved my life :)

**Comment by MahmonirB** [comment] 2020-08-24 18:28
I have this issue in Android.
react-native: "0.62.2"
react-native-firebase: "~5.6.0"

**Comment by mikehardy** [comment] 2020-08-24 18:36
@MahmonirB RNFBv5 is definitely no longer seeing support, if it is still reproduced on current versions of messaging and/or full featured local device notification packages, we can look into it. It seems to be working for me in my work project, in combo with react-native-boot-splash

**Comment by yashnerkar** [comment] 2024-01-27 21:27
> > @jankrah12 the referred solution worked with me perfectly as it was the splash screen which was the issue and as you referred to the solution adding
> > ```js
> >         // NOTE: This is necessary to forward the original intent on to the main activity.
> >         // This makes firebase.notifications().getInitialNotification() work.
> >         intent.putExtras(this.getIntent());
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > inside the **SplashActivity.java** it worked !
> > Big Thank You
> 
> Thank you, saved my life :)



> @jankrah12 the referred solution worked with me perfectly as it was the splash screen which was the issue and as you referred to the solution adding
> 
> ```js
>         // NOTE: This is necessary to forward the original intent on to the main activity.
>         // This makes firebase.notifications().getInitialNotification() work.
>         intent.putExtras(this.getIntent());
> ```
> 
> inside the **SplashActivity.java** it worked !
> 
> Big Thank You

Man, you saved my life 🫡. I was banging my head from last 2 days. Thank you!
