### ISSUE TITLE
[🐛] Unhandled promise rejection [Error: [firestore/unavailable]

### ISSUE THREAD

**Issue by bytewiz** [invertase/react-native-firebase#4923] opened 2021-02-17 12:33 UTC
## Issue

Trying to connect to the emulator from my app and keep getting the following issue:

OS: Mac OSX Big Sur
Simulator: iPhone 11
Xcode: 12.4

Unhandled promise rejection [Error: [firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.]

---

### Javascript
```javscript
 firestore.settings({
        host: FIRESTORE_HOST, // this is "localhost:8080"
        ssl: false,
        persistence: false,
        cacheSizeBytes: firebaseFirestore.CACHE_SIZE_UNLIMITED,
    });
```
#### `package.json`:

```json
    "@react-native-firebase/analytics": "10.5.1",
    "@react-native-firebase/app": "10.5.0",
    "@react-native-firebase/auth": "10.5.1",
    "@react-native-firebase/crashlytics": "10.5.1",
    "@react-native-firebase/firestore": "10.5.1",
    "@react-native-firebase/messaging": "10.5.1",
    "@react-native-firebase/storage": "10.5.1",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2021-02-17 18:28
Definitely use the latest version, I put in some specific code that will give you an indication of exactly what's happening during emulator connections (this is important because on android at least we do a little IP re-mapping for android+localhost combos) but may not matter in your case

If you are having trouble using the emulator and If you are using up to date code I'm not sure exactly what to tell you, as our CI E2E tests which must pass before I merge changes, and then run after any changes are merged, are all emulator based and they all work on iOS and Android.

So you should consult our .github/actions + .github/actions/scripts directories as well as our tests/ directory here. They show exactly how to use the emulator, and it works.

**Comment by bytewiz** [comment] 2021-02-18 09:22
@mikehardy thanks for checking in here! I had a look at the setup and everything seems correct according to your guide. 

When I visit the `localhost:8080` where firestore emulator runs in the browser I get the usual correct `OK` but the iOS simulator can't connect.. Have you heard of any port/network issues with this before for Big Sur OSX? or similar?

**Comment by mikehardy** [comment] 2021-02-18 14:32
The simulator prints out a few other ports. I think 4000 is the UI. Should be accessible. Only other thing I can think of of is to check the plist of our test app, note you must allow insecure network connections

**Comment by mikehardy** [comment] 2021-04-05 22:15
Our E2E tests definitely have a simulator connect to the firestore emulator so I don't know how to move this forward and I'm going to close it. We do some host re-mapping that used to be subtle but now we print something very specific to the javascript console when we do it, so that should be a help at least. If we can get a reproduction we can reopen and try to fix it

**Closed by mikehardy** 2021-04-05 22:15 UTC
Labels: Help: Needs Triage, Impact: Bug

**Comment by adamonkey** [comment] 2021-04-06 15:52
There are a lot of issues with this error in the repo. It's a super tricky error that's a problem with Firebase itself. I followed this blog and it fixed it: https://medium.com/@chonnaronghanyawongse/coding-diary-why-my-firestore-doesnt-work-2db41fb82121

**Comment by mikehardy** [comment] 2021-04-06 16:00
Fascinating @adamonkey !

It's quite the article, here's the important bit people can check - it appears one cause can be that firestore detects an expired token, attempts to refresh, token refresh is denied because of a missing permission on a Google API (link below), and thus cannot fetch documents.

Fix the token refresh service, then firestore can refresh tokens when they hit their 1-hour expiration, and things keep working. Nifty

```
Token Service API has not been used in project xxxyyyzzz before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/securetoken.googleapis.com/overview?project=xxxyyyzzz then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```
