### ISSUE TITLE
TypeError: expected dynamic type `double', but had type `null' - FirestoreSerialize.java:254

### ISSUE THREAD

**Issue by 3210jr** [invertase/react-native-firebase#880] opened 2018-03-13 14:55 UTC
### Issue

Hey, 

I have a recurring error on my firebase crash reporting logs. Its really strange as it literally only happens in production and on about 70% of my users!
I have tried and failed to replicate the issue.

Below is my stack trace:

```

Exception com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `double', but had type `null'
com.facebook.react.bridge.ReadableNativeMap.getDouble (ReadableNativeMap.java)
io.invertase.firebase.firestore.FirestoreSerialize.parseTypeMap (FirestoreSerialize.java:254)
io.invertase.firebase.firestore.FirestoreSerialize.parseReadableMap (FirestoreSerialize.java:233)
io.invertase.firebase.firestore.FirestoreSerialize.parseTypeMap (FirestoreSerialize.java:262)
io.invertase.firebase.firestore.FirestoreSerialize.parseReadableMap (FirestoreSerialize.java:233)
io.invertase.firebase.firestore.RNFirebaseFirestoreDocumentReference.set (RNFirebaseFirestoreDocumentReference.java:107)
io.invertase.firebase.firestore.RNFirebaseFirestore.documentSet (RNFirebaseFirestore.java:154)
java.lang.reflect.Method.invoke (Method.java)
com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:374)
com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:162)
com.facebook.react.bridge.queue.NativeRunnable.run (NativeRunnable.java)
android.os.Handler.handleCallback (Handler.java:836)
android.os.Handler.dispatchMessage (Handler.java:103)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:31)
android.os.Looper.loop (Looper.java:203)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:194)
java.lang.Thread.run (Thread.java:761)
```

Any help appreciated!

### Environment

1. Application Target Platform: Android

2. Development Operating System: MacOS Sierra

3. Build Tools: Andrdoid Studio

4. React Native version: 0.51.0

5. RNFirebase Version: 3.2.0

6. Firebase Module: Firestore

**Comment by chrisbianca** [comment] 2018-03-18 10:51
@3210jr this is really strange as it's implying that the JS thinks the value being supplied is a number, but has a value of `null`.  This _shouldn't_ be possible as when we serialize the data being sent to the native side, the first thing we do is check if the value being sent is `null` and set the type to null: https://github.com/invertase/react-native-firebase/blob/master/lib/modules/firestore/utils/serialize.js#L52

On the Android side we then use the type dictated by the JS to deserialize it: https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/firestore/FirestoreSerialize.java#L249

It would be really helpful if you were able to reproduce this somehow, or figure out the sequence of steps that your users are going through to get to this point?

**Comment by 3210jr** [comment] 2018-03-18 11:04
Sorry, I have tried to replicate it several times but I only get this error out in the wild... I can go for a couple of days without the error and al of a sudden I it occurs on 5  users, then 5 more the next day, and so on...

Almost out of nowhere

**Comment by chrisbianca** [comment] 2018-03-18 11:07
Can you think of any flow which might result in null values being set in your data?

**Comment by 3210jr** [comment] 2018-03-18 12:14
I really can't...
I updated one of my apps from `RNFirebase Version: 3.2.0` to `RNFirebase Version: 3.2.5` and this app hasn't reported the error over the past couple of days.

What I have done now is update this current app to `RNFirebase Version: 3.3.1` and its been one day without this error. 
So, fingers crossed that it wont resurface.

**Comment by chrisbianca** [comment] 2018-03-18 14:09
Ok, please let us know how it goes!

**Comment by arash8m** [comment] 2018-03-24 20:12
@3210jr I just encountered exact same error as you and was able to resolve it. In my case I was not passing any null values. For one of the fields in firestore that was a timestamp, instead of giving it a "Date" object, I was passing it an instance of "moment". Not sure if this helps, but verify the type of data you're passing.

**Comment by chrisbianca** [comment] 2018-03-27 15:52
@3210jr any update on this? Are you still seeing the problem?

**Comment by 3210jr** [comment] 2018-03-27 16:17
@arash8m hey, after updating to the latest rnfirebase version. The error has disappeared.

Along with react native firebase I also updated react native as well. So it's possible both updates were required to fix.

**Comment by chrisbianca** [comment] 2018-03-27 16:23
Ok, I'm going to close this for now. If you feel it needs to be re-opened in the future, please just go ahead and re-open it.

**Closed by chrisbianca** 2018-03-27 16:23 UTC
Labels: awaiting-user-feedback, firestore

**Comment by JaxGit** [comment] 2018-05-06 09:25
@3210jr @chrisbianca @arash8m I encounter the same error with firebase-js-sdk v4.2.0, RN 0.51.0 on Android: 

After exiting the app using `BackHandler.exitApp()` when pressing hardware back button at the ground level of navigation, then re-open the app, all components start to re-mount, and I was getting another native error `Firebase App named '[DEFAULT]' already exists (app/duplicate-app)` due to duplicated initialisation. 

However after I deleted the existing firebase app instance by `firebase.app().delete()` whenever the provider will unmount due to hardware back button press, I will get this `type `null' ` error when re-opening app.

**Comment by brenohq** [comment] 2019-06-17 18:54
same error here on React Native 0.57.7 and React Native Firebase 5.2.5
