### ISSUE TITLE
 auth/missing-client-identifier 

### ISSUE THREAD

**Issue by Osamasomy** [invertase/react-native-firebase#4505] opened 2020-11-05 10:53 UTC
## Issue

I follow the docs download google-service.json and also add SH1 key in firebase console and then copy the example code and try to run it but i saw the below issue.Help Needed. Thanks.

This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.

### Javascript
```
import React, { useState } from 'react';
import { Button, TextInput, View } from 'react-native';
import auth from '@react-native-firebase/auth';
 

const PhoneSignIn = ()=>{
  // If null, no SMS has been sent
  const [confirm, setConfirm] = useState(null);
  const [number, setNumber] = useState(false)
  const [code, setCode] = useState('');

  // Handle the button press
  const _signInWithPhoneNumber = async()=>{
    if(!number) return
    alert(number)
    const confirmation = await auth().signInWithPhoneNumber(number)
    console.log(confirmation)
    setConfirm(confirmation);
  }

  const confirmCode= async()=>{
    try {
      await confirm.confirm(code).then(res => {
        alert(`Verified! ${res.user.uid}`)
      })
    } catch (error) {
      console.log('Invalid code.');
    }
  }

  if (!confirm) {
    return (
      <View style= {{flex: 1}}>
        <TextInput style={{ width: '100%'}} placeholder= "enter number +923075018584" onChangeText={text => setNumber(text)}/>
        <Button
          title="Phone Number Sign In"
          onPress={() => _signInWithPhoneNumber()}
        />
      </View>
    );
  }

  return (
    <>
      <TextInput value={code} placeholder="Code" onChangeText={text => setCode(text)} />
      <Button title="Confirm Code" onPress={() => confirmCode()} />
    </>
  );
}

export default PhoneSignIn
```
#### `package.json`:

```
"@react-native-firebase/app": "^8.4.7",
"@react-native-firebase/auth": "^9.3.2",
"react-native": "^0.63.2",
```

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

**Comment by Osamasomy** [comment] 2020-11-05 11:49
@andymatuschak need help

**Comment by dileepkantapop** [comment] 2020-11-06 05:17
I am also getting the same error. Help me in fixing this @Osamasomy if you found a solution.

**Comment by Osamasomy** [comment] 2020-11-06 10:41
@dileepkantapop  still no luck brother.

**Comment by Osamasomy** [comment] 2020-11-06 10:41
@mlc @andymatuschak @felixclack  any help on this problem?

**Comment by dileepkantapop** [comment] 2020-11-06 10:46
It's related to SHA1 and SHA256 keys, in console.cloud.google.com for your project enable "Android Device Verification", 
keep sha1 and sha256 keys 256 keys updated in firebase console for your app. That solved my error.

Read this: https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification

**Comment by Osamasomy** [comment] 2020-11-09 10:52
still face the same problem i added sh1 and sh256 key in firebase console.

**Comment by KristjanRetter** [comment] 2020-11-16 17:44
@Osamasomy Did you download the new and replace the old google-services.json after adding sha1 in firebase console?

**Comment by KristjanRetter** [comment] 2020-11-16 17:46
@Osamasomy Also you need to add test phone numbers in the firebase console, then you can test your phone auth.

**Comment by Eiby10** [comment] 2020-11-18 00:50
@Osamasomy bro do u already have the solution? please im facing the same issue in my android app

**Comment by sajidjutt7** [comment] 2020-11-23 20:21
You have to authenticate your app via SHA-1 and SHA-256.
if not resolve -> Check -> you have to declare Firebase auth in you class and use that auth instance to login with credentials you get from firebase.
if not resolve -> Check -> Proper dependencies you are adding - Versions??
if not resolve -> You also have to add Captche reading facility for mobile to access browser. For this add dependency ->  com.android.support:customtabs

**Comment by bunbalhara** [comment] 2020-12-02 13:06
I have some issues

**Comment by mikehardy** [comment] 2020-12-02 13:10
@bunbalhara that is no way to get help, sorry :-). What would you do if a co-worker came up to you and said that? It's not actionable at all. You'd say either "then you should seek help", or "what's the problem". But there is no expectation you could solve the problem.

**Comment by mfaisalabbasi** [comment] 2020-12-02 13:26
Same issue,

**Comment by mikehardy** [comment] 2020-12-02 13:28
@mfaisalabbasi that is also not actionable.

**Comment by mikehardy** [comment] 2020-12-02 13:29
If no one posts details, and verifies their SHA1 and SHA256 is up to date per the comment above, while running on current versions (v10.1.0 of react-native-firebase) I will close and lock this issue as it is not useful and is attracting low quality comments.

**Comment by mfaisalabbasi** [comment] 2020-12-02 13:34
@mikehardy  SHA1 and SHA256 are up date,
And this is my pakage.json pkg details.
"@react-native-firebase/app": "^10.1.0",
 "@react-native-firebase/auth": "^10.1.0",

**Comment by mfaisalabbasi** [comment] 2020-12-02 13:37
And It's working when I used to Enter number that is already in firebase  testing purpose, but when I use Random number it causing error.
simply testing number working.

**Comment by mikehardy** [comment] 2020-12-02 13:38
@mfaisalabbasi please attest you have enabled verification https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification
please verify you are testing a real device plugged in to your computer
Please follow `adb logcat` for the device and see if anything interesting pops out for your app

**Comment by mfaisalabbasi** [comment] 2020-12-02 13:41
Yup i enabled android device verification and i am using real devices
connected through usb
And let me check adb logcat

**Comment by mfaisalabbasi** [comment] 2020-12-02 13:42
yup Enabled android Device Verification and I am using Real Device Connected through Usb

**Comment by Avhishek05** [comment] 2020-12-02 18:34
Getting same issue followed all the steps 
1. Added sha-1 , sha-256 and enabled device check also

**Comment by mikehardy** [comment] 2020-12-02 18:49
@Avhishek05 so catching up to the state of the issue: how did it go when you looked at adb logcat? We're looking for new information at the moment, "me toos" do not advance the discussion. Not to be harsh but we all have limited time, yes? Advance things or just watch + listen

**Comment by Avhishek05** [comment] 2020-12-07 17:08
@mikehardy I have posted adb logcat in my last comment.

**Comment by mikehardy** [comment] 2020-12-07 17:21
@Avhishek05 you posted some sort of truncated image thing? Posting logcat is like:

```
here are a bunch of logcat lines
```

Or attaching logcat.txt ...

**Comment by shahjahanpak** [comment] 2020-12-09 08:30
I had the issue; The SHA-1 and SHA-256 fingerprints I provided at Firebase Console were not _correct_ somehow. 
Executed this command in Project's root directory `keytool -list -v -keystore ./android/app/debug.keystore -alias androiddebugkey -storepass android -keypass android` to get SHA-1 and SHA-256 fingerprints.
Updating Firebase console with newly acquired values **resolved** the issue for me.

**Comment by mikehardy** [comment] 2020-12-09 17:30
I think this will resolve to a project setup issue every time. I'm going to close it as unactionable - the react-native-firebase is known to work

**Closed by mikehardy** 2020-12-09 17:30 UTC
Labels: Help: Needs Triage, Impact: Bug

**Comment by Eiby10** [comment] 2020-12-10 06:38
Im still having the same issue despite of all the information you guys have provided this is frustrating please need help

**Comment by Eiby10** [comment] 2020-12-10 06:39
@mikehardy can you help me

**Comment by mikehardy** [comment] 2020-12-10 11:29
No I can't. You have a project-specific setup issue. Frustrating I am sure, but the information above about carefully getting the SHA hashes of the actual keystores used to sign the app for delivery etc etc and configuring everything is it.

**Comment by aminehtb** [comment] 2021-01-12 21:52
1. Go to firebase console
2. open your project
3. open project settings
4. if you have an application in "**Your apps**" section just add the **sha-1** and **sha-256** keys
5. if not add your application package, name, and the two keys
6. download the google-services.json file and add it to your application

**Comment by linhlie** [comment] 2021-01-25 04:14
+1

**Comment by linhlie** [comment] 2021-01-25 07:04
+1

**Comment by sylvesterasiedu** [comment] 2021-02-01 17:56
You might need to enable the Google Device Verification in your Google cloud console.

**Comment by nixolas1** [comment] 2021-02-04 10:59
For anyone still having problems with this (But only in production), our problem was that Google Play signed the bundle after upload with their own certificate, which wasn't automatically added to the firebase project. So adding the fingerprint from your own key dosn't do anything.

So: Go to your app's google play console -> Setup -> App signing, and add the SHA1 and SHA256 keys to your firebase project, and download a new google-services.json

**Comment by mikehardy** [comment] 2021-02-04 15:01
Oh! @nixolas1 that is a gotcha we had not documented. I assume you are using the 'Android Bundle' style where you upload the build but Google Play is managing the keys etc? Could you please :pray: :pray: add a quick note saying exactly what you said here in the Android Setup area for auth? This could get a lot of people, this style is ...relatively new still but Google pushes it very hard now so it will likely get more and more people

**Comment by nixolas1** [comment] 2021-02-04 16:05
Yeah, kinda facepalmed when I realised. But I'm not completely sure this is the issue. It worked before, without adding the Google Play App Signing fingerprints, and adding them didn't help in this instance, so I'm at a loss again.
But if I figure out what is causing the error I'll get back :)

**Comment by nileshinkane** [comment] 2021-02-05 05:55
I used the command given by @shahjahanpak , Added only the SHA1 to the firebase console, replaced the google-services file and then added this line `implementation "androidx.browser:browser:1.2.0"`  into dependencies section of `app/build.gradle`.
After this everything was working fine.

**Comment by Aditya-Ojha** [comment] 2021-03-22 16:55
I was facing same problem. What I did -> put SHA-1 and SHA-256 both. Then enable API in Google cloud platform[](https://firebase.google.com/docs/auth/android/phone-auth). Most important is update your Android Studio to latest stable version!!

**Comment by ibrofro** [comment] 2021-04-07 04:13
> I had the same issue; The SHA-1 and SHA-256 fingerprints I provided at Firebase Console were not _correct_ somehow.
> Executed this command in Project's root directory `keytool -list -v -keystore ./android/app/debug.keystore -alias androiddebugkey -storepass android -keypass android` to get SHA-1 and SHA-256 fingerprints.
> Updating Firebase console with newly acquired values **resolved** the issue for me.

The good solution

**Comment by Sugamsm** [comment] 2021-06-14 05:54
Hello, not sure if the issue is still valid. But, wanted to mention if it helps anyone. In my case I was working directly on Native Android Java code, I had the `FirebaseAuth.getInstance().getFirebaseAuthSettings()
                .setAppVerificationDisabledForTesting(true);` which wasn't allowing any Original numbers verification. This was the only step missing apart from all the SHA-1 SHA-256 additions and Enabling Android Device Verification API + Safety Net implementation. Removing the above lines worked for me.

**Comment by 969rishi** [comment] 2021-06-16 19:31
![image](https://user-images.githubusercontent.com/32278183/122281009-6cae1200-cf07-11eb-9d81-d5ed56fffd16.png)
**Check this Out & thanks me later**
Here you have to update your SHA256 generated from keytool and its ready to go.

**Comment by oguzhnatly** [comment] 2021-08-05 11:10
> * Go to firebase console
> * open your project
> * open project settings
> * if you have an application in "**Your apps**" section just add the **sha-1** and **sha-256** keys
> * if not add your application package, name, and the two keys
> * download the google-services.json file and add it to your application

Thank you @aminehtb. The most important attention here is that both sha256 and sha1 keys need to be added to my apps in the project settings and also just sha256 key to the AppCheck section of the firebase console. This solved my error for android.

**Comment by oguzhnatly** [comment] 2021-08-05 11:11
> * Go to firebase console
> * open your project
> * open project settings
> * if you have an application in "**Your apps**" section just add the **sha-1** and **sha-256** keys
> * if not add your application package, name, and the two keys
> * download the google-services.json file and add it to your application

Thank you @aminehtb. The most important attention here is that both sha256 and sha1 keys need to be added to my apps in the project settings and also just sha256 key to the AppCheck section of the firebase console. This solved my error for android.

**Comment by oguzhnatly** [comment] 2021-08-05 11:14
> * Go to firebase console
> * open your project
> * open project settings
> * if you have an application in "**Your apps**" section just add the **sha-1** and **sha-256** keys
> * if not add your application package, name, and the two keys
> * download the google-services.json file and add it to your application

Thank you @aminehtb. The most important attention here is that both SHA256 and SHA1 keys need to be added to my apps in the project settings and also only SHA256 key to the AppCheck in the firebase console. This solved my error for android.

**Comment by AbhiShrek** [comment] 2021-09-19 11:09
I tried with the keytool cmd mentioned above, but those SHA fingerprints were already there in my project. Then I tried the following cmd, which gave me the SHA  fingerprints of release build too. I added those FP to my project, downloaded the google-services.json again, and it started working fine.
```
cd android
./gradlew signingReport
```

PS: I haven't yet enabled the Safety-Net for my App, but the authentication is now working fine.

**Comment by mikehardy** [comment] 2021-09-19 14:39
Safety Net will help by avoiding recaptcha for phone Auth, or enabling app check module but may be considered optional if my understanding is correct

**Comment by Ilhamsafeek** [comment] 2021-10-17 04:49
This solved in my case:

https://stackoverflow.com/a/69601358/3962688

**Comment by Ilhamsafeek** [comment] 2021-10-17 04:49
Check my answer

This solved in my case:

https://stackoverflow.com/a/69601358/3962688

**Comment by MuhammadHamza12** [comment] 2023-02-26 14:12
> I had the same issue; The SHA-1 and SHA-256 fingerprints I provided at Firebase Console were not _correct_ somehow. Executed this command in Project's root directory `keytool -list -v -keystore ./android/app/debug.keystore -alias androiddebugkey -storepass android -keypass android` to get SHA-1 and SHA-256 fingerprints. Updating Firebase console with newly acquired values **resolved** the issue for me.

This resolve my issue thank you so much... save my day.

**Comment by Cleversou1983** [comment] 2023-08-30 19:58
Error: [auth/missing-client-identifier] This request is missing a valid app identifier, meaning that Play Integrity checks, and геСАРТСНА checks were unsuccessful.
Please try again, or check the logcat for more details.

I've checked both SHA-1 and SHA-256 on my project and downloaded the new google-services.json... That's so annoying, I will trying to convince the customer to drop this crappy phone authentication service.

**Comment by simiel** [comment] 2024-03-03 02:19
If you are using Expo, follow all the above listed steps and run a dev build on eas servers. If you choose to do it locally, you may not get the signing credentials right.

**Comment by naticio** [comment] 2024-04-25 05:52
> Error: [auth/missing-client-identifier] This request is missing a valid app identifier, meaning that Play Integrity checks, and геСАРТСНА checks were unsuccessful. Please try again, or check the logcat for more details.
> 
> I've checked both SHA-1 and SHA-256 on my project and downloaded the new google-services.json... That's so annoying, I will try to convince our customer to drop this crappy phone authentication service from firebase.

crappy indeed, any other alternatives? twilio?
