### ISSUE TITLE
How to handle BigPicture when app is in backgroud or killed state

### ISSUE THREAD

**Issue by venkat-waran** [invertase/react-native-firebase#2211] opened 2019-06-07 06:54 UTC
## Issue

This is my payload I handled bigpicture in onNotification function but its only working when the app is in background. How I have to handle bigPicture when the app is in background or killed state.
` message = {
              data: {
                bigPicture: req.body.big_picture
              },
              notification: {
                title: req.body.title,
                body: req.body.body,
              },
              android: {
                priority: 'high',
                notification: {
                  icon: "@mipmap/ic_launcher",
                }
              },
              topic: "****"
            }`

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        // classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.android.tools.build:gradle:3.1.3' // <--- update this
        classpath 'com.google.gms:google-services:4.0.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {url "https://maven.google.com"}
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 26
                buildToolsVersion '26.0.3'
                googlePlayServicesVersion = "15.0.1"
            }
        }
    }
}
ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
    googlePlayServicesVersion = "15.0.1"
}

```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"

import com.android.build.OutputFile


project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"


def enableSeparateBuildPerCPUArchitecture = false


def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.samplex"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.3"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    buildToolsVersion '26.0.3'
}

dependencies {
    compile project(':react-native-firebase')
    implementation project(':react-native-firebase')
   
     // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.firebase:firebase-core:16.0.1"
    implementation "com.google.firebase:firebase-messaging:17.1.0"
    implementation "com.google.firebase:firebase-database:16.0.1"
    
}
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply plugin: 'com.google.gms.google-services'
```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'SampleX'
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
include ':app'
```

#### `MainApplication.java`:

```java
package com.Sample;

import android.app.Application;

import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.analytics.RNFirebaseAnalyticsPackage;
import io.invertase.firebase.database.RNFirebaseDatabasePackage;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

        @Override
        protected String getJSBundleFile() {
        return CodePush.getJSBundleFile();
        }
    
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new RNFirebaseAnalyticsPackage(),
          new RNFirebaseDatabasePackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.samplex" xmlns:tools="http://schemas.android.com/tools"
    android:versionCode="1"
    android:versionName="1.3">

   
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      
      
        <!--add CustomTabActivity-->
       
        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
            <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />
        <!--reference your fb_app_id-->
        <meta-data
                android:name="com.facebook.sdk.ApplicationId"
                tools:replace="android:value"
                android:value="@string/fb_app_id"/>
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id"/>
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@mipmap/notif_icon" />
        <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>
        <receiver android:enabled="true" android:exported="true"  android:name="io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver">
            <intent-filter>
            <action android:name="android.intent.action.BOOT_COMPLETED"/>
            <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
            <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </receiver>
    </application>

</manifest>

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
No result  or Output
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2019-06-07 19:08
I could be wrong, but I think if your app is killed, you may only receive data payloads *or* show simple notifications in the status bar, and if you want a custom notification you have to receive the data payload then create a custom notification in your headless task, that you display yourself

**Comment by venkat-waran** [comment] 2019-06-10 07:29
Hi Thanks for the reply, I have a headless task
my headless task:
` 
export default async message => {
   console.log(message);   

  const notification = new firebase.notifications.Notification({
      sound: "default",
      show_in_foreground: true
    })
      .setNotificationId("notificationId")
      .setTitle(message.data.title)
      .setBody(message.data.body)
      .setSubtitle(message.data.subtitle);

  notification.android
        .setChannelId("***")
        .android.setSmallIcon("@mipmap/notif_icon")
        .android.setLargeIcon("@mipmap/ic_launcher")
        .android.setPriority(firebase.notifications.Android.Priority.High);
    if (message && message.data && message.data.bigPicture) {
      notification.android.setBigPicture(message.data.bigPicture);
    }
    firebase.notifications().displayNotification(notification);
}
  return Promise.resolve();
} 
`
But bigPicture is not working in when the app is killed state or background. Let me know if i want to change something. Even console is not working in killed and background state.

**Comment by mikehardy** [comment] 2019-06-10 14:28
If the headless task is actually working, console works as well. When my headless task is started (after the app is killed) I get all sorts of console messages. So that seems suspicious and I'd do the most basic app you could until you're sure headless tasks are working for you. You could maybe build off https://github.com/mikehardy/rnfbdemo - it goes from nothing to a working app pretty quickly

**Comment by mikehardy** [comment] 2019-06-10 14:28
Or react-native-firebase-starter of course, it's also pretty much ready to go for tests like this

**Comment by venkat-waran** [comment] 2019-06-11 08:36
Thanks for the reply,
This is my payload which im sending from backend.
`message = 
{
              data: {
                bigPicture: req.body.big_picture
              },
              notification: {
                title: req.body.title,
                body: req.body.body,
              },
              android: {
                priority: 'high',
                notification: {
                  icon: "@mipmap/ic_launcher",
                }
              },
              topic: "*******"
            }`

Console works fine when im sending only data messages but when im sending with both notificatin and data messages console is not working fine.

**Comment by mikehardy** [comment] 2019-06-11 12:47
If you're in the background, I believe you need to do silent push, construct a notification, and post the notification.

**Comment by venkat-waran** [comment] 2019-06-11 12:55
Im not getting you clearly, can you explain it more

**Comment by mikehardy** [comment] 2019-06-11 13:07
Make sure silent push to a headless task works. In the silent push include data that instructs your headless task clearly what you want. In the headless task, create a local notification in the style you want

**Comment by venkat-waran** [comment] 2019-06-12 06:28
Hi silent push to a headless task works fine, but I'm not able to get the data properly and display the bigPicture.
What im doing is correct? or i have to modify something.
`
export default async message => {
console.log(message);

const notification = new firebase.notifications.Notification({
sound: "default",
show_in_foreground: true
})
.setNotificationId("notificationId")
.setTitle(message.data.title)
.setBody(message.data.body)
.setSubtitle(message.data.subtitle);

notification.android
.setChannelId("***")
.android.setSmallIcon("@mipmap/notif_icon")
.android.setLargeIcon("@mipmap/ic_launcher")
.android.setPriority(firebase.notifications.Android.Priority.High);
if (message && message.data && message.data.bigPicture) {
notification.android.setBigPicture(message.data.bigPicture);
}
firebase.notifications().displayNotification(notification);
}
return Promise.resolve();
}
`

**Comment by mikehardy** [comment] 2019-06-12 15:30
I saw in a related issue that you must set a sound as well? Might try it - looks like you're close to having it working

**Comment by venkat-waran** [comment] 2019-06-13 12:08
Hi I saw in your documentation that **Android allows you to act on data-only messages when your application is closed or running in the background. This is particularly useful if you'd like to be able to show heads-up notifications to your user.** But im sending both notification + data message payload from backend, Then I cant customize in headless task right?

**Comment by mikehardy** [comment] 2019-06-13 12:26
Have you tried it?

**Comment by venkat-waran** [comment] 2019-06-13 12:34
Thanks for the reply, I'm not sure what do you mean by silent push. But im handling all the things in headless task and creating custom local notification. I have also shared the code of headless task in the previous thread. Help me with this one, im trying from long back.

**Comment by venkat-waran** [comment] 2019-06-14 13:08
Hi can i get any solution?

**Comment by mikehardy** [comment] 2019-06-14 20:08
Sorry @venkat-waran - your project isn't my project. We hear success reports so I don't think the react-native-firebase module has a problem. I am not working on this specifically right now. If had a github URL I could clone and run immediately (with my firebase json file) that showed the problem I could maybe reproduce, other than that I am not sure what else I can do

**Comment by venkat-waran** [comment] 2019-06-15 15:14
OK thanks can you elaborate about sending silent push so that I can test

**Comment by mikehardy** [comment] 2019-06-15 15:20
No, sorry - this is a big subject. You have learning to do, and it won't happen in short form comment boxes. The firebase blog is a great resource. As are any articles that talk about the interaction between FCM and APNs. The react-native-firebase documentation itself links to a great article on how to troubleshoot messages. Here's some maybe:

https://firebase.googleblog.com/2019/02/life-of-a-message.html
https://firebase.googleblog.com/2018/09/handle-fcm-messages-on-android.html

**Comment by mikehardy** [comment] 2019-06-15 15:49
without a reproduction, I'm closing this. I've provided the help I can. Others can discuss if it helps but it's not an issue with the module

**Closed by mikehardy** 2019-06-15 15:49 UTC
Labels: API: Notifications, Platform: Android, Service: Messaging, Type: Question

**Comment by littlehome-eugene** [comment] 2019-12-01 04:39
I'm having similar issue..

background push notification works 

But as soon as I add `android.setBigPicture` , it stops working with v5


```
  let notification = new firebase.notifications.Notification()
    .setNotificationId(message.data.id)
    .setTitle(message.data.message)
    .setSound("default")
    .android.setChannelId("noti") // e.g. the id you chose above
    .android.setSmallIcon("ic_small_tab")
    .setData(message.data)
    .android.setPriority(firebase.notifications.Android.Priority.Max);

  // if I comment out the following, everything works fine
  if (message.data.image_url) {
    if (Platform.OS == "android") {
      notification.android.setBigPicture(message.data.image_url);
    }
  }
```
