### ISSUE TITLE
[🐛] property with 'retain ' attribute must be of object type

### ISSUE THREAD

**Issue by theartificialguy** [invertase/react-native-firebase#6628] opened 2022-10-25 09:40 UTC
## Issue

After configuring react-native-firebase, when I build the app, I get the following build error for `@react-native-firebase/messaging` & `@react-native-firebase/storage`:- `property with 'retain ' attribute must be of object type`

Whole trace:-
```
Compiling @react-native-firebase/storage Pods/RNFBStorage » RNFBStorageModule.m

❌  (ios/Pods/FirebaseFirestore/Firestore/Source/Public/FirebaseFirestore/FIRFirestoreSettings.h:46:1)

  44 |  * the main queue is used.
  45 |  */
> 46 | @property(nonatomic, strong) dispatch_queue_t dispatchQueue;
     | ^ property with 'retain ' attribute must be of object type
  47 | 
  48 | /** Set to false to disable local persistent storage. */
  49 | @property(nonatomic, getter=isPersistenceEnabled) BOOL persistenceEnabled;


❌  (ios/Pods/Headers/Public/Firebase/Firebase.h:50:13)

  48 | 
  49 |   #if __has_include(<FirebaseFirestore/FirebaseFirestore.h>)
> 50 |     #import <FirebaseFirestore/FirebaseFirestore.h>
     |             ^ could not build module 'FirebaseFirestore'
  51 |   #endif
  52 | 
  53 |   #if __has_include("FirebaseFunctions-umbrella.h")


❌  (/Users/macbookair/Library/Developer/Xcode/DerivedData/justChat-gvlyyuoxvfahekfvnoiuaatjtplq/Build/Products/Debug-iphonesimulator/FirebaseStorage/FirebaseStorage.framework/Headers/FirebaseStorage-Swift.h:277:1)

  275 | @property (nonatomic) NSTimeInterval maxOperationRetryTime;
  276 | /// A <code>DispatchQueue</code> that all developer callbacks are fired on. Defaults to the main queue.
> 277 | @property (nonatomic, strong) dispatch_queue_t _Nonnull callbackQueue;
      | ^ property with 'retain ' attribute must be of object type
  278 | /// Creates a <code>StorageReference</code> initialized at the root Firebase Storage location.
  279 | ///
  280 | /// returns:


❌  (node_modules/react-native/React/Base/RCTBridgeModule.h:182:1)

  180 |  * when it initializes the module.
  181 |  */
> 182 | @property (nonatomic, strong, readonly) dispatch_queue_t methodQueue;
      | ^ property with 'retain ' attribute must be of object type
  183 | 
  184 | /**
  185 |  * Wrap the parameter line of your method implementation with this macro to


❌  (node_modules/react-native/React/Base/RCTModuleData.h:101:1)

   99 |  * queue and the module itself if they have not already been created.
  100 |  */
> 101 | @property (nonatomic, strong, readonly) dispatch_queue_t methodQueue;
      | ^ property with 'retain ' attribute must be of object type
  102 | 
  103 | /**
  104 |  * Whether the receiver has a valid `instance` which implements -batchDidComplete.


❌  (node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.h:33:1)

  31 | - (instancetype)initWithURL:(NSURL *)url __deprecated_msg("Use initWithURL:queue: instead");
  32 | /** @brief Must be set before -start to have effect */
> 33 | @property (nonatomic, strong) dispatch_queue_t delegateDispatchQueue __deprecated_msg("Use initWithURL:queue: instead");
     | ^ property with 'retain ' attribute must be of object type
  34 | 
  35 | @end
  36 | 

› Compiling @react-native-firebase/storage Pods/RNFBStorage » RNFBStorageCommon.m

❌  (ios/Pods/FirebaseFirestore/Firestore/Source/Public/FirebaseFirestore/FIRFirestoreSettings.h:46:1)

  44 |  * the main queue is used.
  45 |  */
> 46 | @property(nonatomic, strong) dispatch_queue_t dispatchQueue;
     | ^ property with 'retain ' attribute must be of object type
  47 | 
  48 | /** Set to false to disable local persistent storage. */
  49 | @property(nonatomic, getter=isPersistenceEnabled) BOOL persistenceEnabled;


❌  (ios/Pods/Headers/Public/Firebase/Firebase.h:50:13)

  48 | 
  49 |   #if __has_include(<FirebaseFirestore/FirebaseFirestore.h>)
> 50 |     #import <FirebaseFirestore/FirebaseFirestore.h>
     |             ^ could not build module 'FirebaseFirestore'
  51 |   #endif
  52 | 
  53 |   #if __has_include("FirebaseFunctions-umbrella.h")


❌  (/Users/macbookair/Library/Developer/Xcode/DerivedData/justChat-gvlyyuoxvfahekfvnoiuaatjtplq/Build/Products/Debug-iphonesimulator/FirebaseStorage/FirebaseStorage.framework/Headers/FirebaseStorage-Swift.h:277:1)

  275 | @property (nonatomic) NSTimeInterval maxOperationRetryTime;
  276 | /// A <code>DispatchQueue</code> that all developer callbacks are fired on. Defaults to the main queue.
> 277 | @property (nonatomic, strong) dispatch_queue_t _Nonnull callbackQueue;
      | ^ property with 'retain ' attribute must be of object type
  278 | /// Creates a <code>StorageReference</code> initialized at the root Firebase Storage location.
  279 | ///
  280 | /// returns:


❌  (node_modules/react-native/React/Base/RCTBridgeModule.h:182:1)

  180 |  * when it initializes the module.
  181 |  */
> 182 | @property (nonatomic, strong, readonly) dispatch_queue_t methodQueue;
      | ^ property with 'retain ' attribute must be of object type
  183 | 
  184 | /**
  185 |  * Wrap the parameter line of your method implementation with this macro to


❌  (node_modules/react-native/React/Base/RCTModuleData.h:101:1)

   99 |  * queue and the module itself if they have not already been created.
  100 |  */
> 101 | @property (nonatomic, strong, readonly) dispatch_queue_t methodQueue;
      | ^ property with 'retain ' attribute must be of object type
  102 | 
  103 | /**
  104 |  * Whether the receiver has a valid `instance` which implements -batchDidComplete.


❌  (node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.h:33:1)

  31 | - (instancetype)initWithURL:(NSURL *)url __deprecated_msg("Use initWithURL:queue: instead");
  32 | /** @brief Must be set before -start to have effect */
> 33 | @property (nonatomic, strong) dispatch_queue_t delegateDispatchQueue __deprecated_msg("Use initWithURL:queue: instead");
     | ^ property with 'retain ' attribute must be of object type
  34 | 
  35 | @end
  36 | 


❌  (/Users/macbookair/Desktop/justChat/node_modules/@react-native-firebase/app/ios/RNFBApp/RCTConvert+FIRApp.h:19:9)

  17 | 
  18 | #import <FirebaseCore/FirebaseCore.h>
> 19 | #import <React/RCTConvert.h>
     |         ^ could not build module 'React'
  20 | 
  21 | @interface RCTConvert (FIRApp)
  22 | + (FIRApp *)firAppFromString:(NSString *)appName;

› Compiling @react-native-firebase/messaging Pods/RNFBMessaging » RNFBMessagingSerializer.m

❌  (ios/Pods/FirebaseFirestore/Firestore/Source/Public/FirebaseFirestore/FIRFirestoreSettings.h:46:1)

  44 |  * the main queue is used.
  45 |  */
> 46 | @property(nonatomic, strong) dispatch_queue_t dispatchQueue;
     | ^ property with 'retain ' attribute must be of object type
  47 | 
  48 | /** Set to false to disable local persistent storage. */
  49 | @property(nonatomic, getter=isPersistenceEnabled) BOOL persistenceEnabled;


❌  (ios/Pods/Headers/Public/Firebase/Firebase.h:50:13)

  48 | 
  49 |   #if __has_include(<FirebaseFirestore/FirebaseFirestore.h>)
> 50 |     #import <FirebaseFirestore/FirebaseFirestore.h>
     |             ^ could not build module 'FirebaseFirestore'
  51 |   #endif
  52 | 
  53 |   #if __has_include("FirebaseFunctions-umbrella.h")


❌  (/Users/macbookair/Library/Developer/Xcode/DerivedData/justChat-gvlyyuoxvfahekfvnoiuaatjtplq/Build/Products/Debug-iphonesimulator/FirebaseStorage/FirebaseStorage.framework/Headers/FirebaseStorage-Swift.h:277:1)

  275 | @property (nonatomic) NSTimeInterval maxOperationRetryTime;
  276 | /// A <code>DispatchQueue</code> that all developer callbacks are fired on. Defaults to the main queue.
> 277 | @property (nonatomic, strong) dispatch_queue_t _Nonnull callbackQueue;
      | ^ property with 'retain ' attribute must be of object type
  278 | /// Creates a <code>StorageReference</code> initialized at the root Firebase Storage location.
  279 | ///
  280 | /// returns:


❌  (node_modules/react-native/React/Base/RCTBridgeModule.h:182:1)

  180 |  * when it initializes the module.
  181 |  */
> 182 | @property (nonatomic, strong, readonly) dispatch_queue_t methodQueue;
      | ^ property with 'retain ' attribute must be of object type
  183 | 
  184 | /**
  185 |  * Wrap the parameter line of your method implementation with this macro to


❌  (node_modules/react-native/React/Base/RCTModuleData.h:101:1)

   99 |  * queue and the module itself if they have not already been created.
  100 |  */
> 101 | @property (nonatomic, strong, readonly) dispatch_queue_t methodQueue;
      | ^ property with 'retain ' attribute must be of object type
  102 | 
  103 | /**
  104 |  * Whether the receiver has a valid `instance` which implements -batchDidComplete.


❌  (node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.h:33:1)

  31 | - (instancetype)initWithURL:(NSURL *)url __deprecated_msg("Use initWithURL:queue: instead");
  32 | /** @brief Must be set before -start to have effect */
> 33 | @property (nonatomic, strong) dispatch_queue_t delegateDispatchQueue __deprecated_msg("Use initWithURL:queue: instead");
     | ^ property with 'retain ' attribute must be of object type
  34 | 
  35 | @end
  36 | 


› 19 error(s), and 0 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.
```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-firebase/app": "~15.4.0",
    "@react-native-firebase/auth": "^15.4.0",
    "@react-native-firebase/firestore": "^15.4.0",
    "@react-native-firebase/messaging": "^15.4.0",
    "@react-native-firebase/storage": "^15.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@reduxjs/toolkit": "^1.8.6",
    "expo": "^46.0.0",
    "react": "18.0.0",
    "react-hook-form": "^7.38.0",
    "react-native": "0.69.6",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-redux": "^8.0.4"
  }
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$RNFirebaseAsStaticFramework = true

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

# pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false

target 'justChat' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!
  use_frameworks! :linkage => :static

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'justChatTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"
#import <Firebase.h>
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <React/RCTAppSetupUtils.h>

#if RCT_NEW_ARCH_ENABLED
#import <React/CoreModulesPlugins.h>
#import <React/RCTCxxBridgeDelegate.h>
#import <React/RCTFabricSurfaceHostingProxyRootView.h>
#import <React/RCTSurfacePresenter.h>
#import <React/RCTSurfacePresenterBridgeAdapter.h>
#import <ReactCommon/RCTTurboModuleManager.h>

#import <react/config/ReactNativeConfig.h>

static NSString *const kRNConcurrentRoot = @"concurrentRoot";

@interface AppDelegate () <RCTCxxBridgeDelegate, RCTTurboModuleManagerDelegate> {
  RCTTurboModuleManager *_turboModuleManager;
  RCTSurfacePresenterBridgeAdapter *_bridgeAdapter;
  std::shared_ptr<const facebook::react::ReactNativeConfig> _reactNativeConfig;
  facebook::react::ContextContainer::Shared _contextContainer;
}
@end
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  RCTAppSetupPrepareApp(application);

  RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];

#if RCT_NEW_ARCH_ENABLED
  _contextContainer = std::make_shared<facebook::react::ContextContainer const>();
  _reactNativeConfig = std::make_shared<facebook::react::EmptyReactNativeConfig const>();
  _contextContainer->insert("ReactNativeConfig", _reactNativeConfig);
  _bridgeAdapter = [[RCTSurfacePresenterBridgeAdapter alloc] initWithBridge:bridge contextContainer:_contextContainer];
  bridge.surfacePresenter = _bridgeAdapter.surfacePresenter;
#endif

  NSDictionary *initProps = [self prepareInitialProps];
  UIView *rootView = [self.reactDelegate createRootViewWithBridge:bridge moduleName:@"justChat" initialProperties:initProps];

  if (@available(iOS 13.0, *)) {
    rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
    rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [self.reactDelegate createRootViewController];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [super application:application didFinishLaunchingWithOptions:launchOptions];
  return YES;
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feture is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  // Switch this bool to turn on and off the concurrent root
  return true;
}

- (NSDictionary *)prepareInitialProps
{
  NSMutableDictionary *initProps = [NSMutableDictionary new];

#ifdef RCT_NEW_ARCH_ENABLED
  initProps[kRNConcurrentRoot] = @([self concurrentRootEnabled]);
#endif

  return initProps;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

#if RCT_NEW_ARCH_ENABLED

#pragma mark - RCTCxxBridgeDelegate

- (std::unique_ptr<facebook::react::JSExecutorFactory>)jsExecutorFactoryForBridge:(RCTBridge *)bridge
{
  _turboModuleManager = [[RCTTurboModuleManager alloc] initWithBridge:bridge
                                                             delegate:self
                                                            jsInvoker:bridge.jsCallInvoker];
  return RCTAppSetupDefaultJsExecutorFactory(bridge, _turboModuleManager);
}

#pragma mark RCTTurboModuleManagerDelegate

- (Class)getModuleClassFromName:(const char *)name
{
  return RCTCoreModulesClassProvider(name);
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                      jsInvoker:(std::shared_ptr<facebook::react::CallInvoker>)jsInvoker
{
  return nullptr;
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                     initParams:
                                                         (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return nullptr;
}

- (id<RCTTurboModule>)getModuleInstanceFromClass:(Class)moduleClass
{
  return RCTAppSetupDefaultModuleFromClass(moduleClass);
}

#endif

@end
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 148.73 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      Android NDK: 24.0.8215888
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Yes` & `"typescript": "^4.8.3"`

</p>
</details>

#### What I've tried so far:-
1) cd ios/ && pod disintegrate && pod install && cd .. (Didn't work)
2) https://stackoverflow.com/a/44486792/11685381 (Didn't work)
3) https://stackoverflow.com/a/41713575/11685381 (Didn't work)

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2022-10-25 13:21
Hmm - everything seems okay on a first glance :thinking: 

Can you try this in your environment: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

That's a scripted integration / build demonstration rig, it works where I run it normally, it should work in your environment, thhen the difference between what it creates and what's in your project will be the thing. If it doesn't work, that will be very curious

**Comment by piedrahitapablo** [comment] 2022-10-25 20:42
Hi, I'm seeing this same error on an expo development build. I created this minimal repo to reproduce the issue:

https://github.com/piedrahitapablo/rn-firebase-error

Steps to see the error:
1. `yarn install`
2. Copy a `GoogleService-Info.plist` file to the root of the repo
3. `yarn ios`

The error I get is this one:

```
❌  (node_modules/react-native/React/Base/RCTBridgeModule.h:182:1)

  180 |  * when it initializes the module.
  181 |  */
> 182 | @property (nonatomic, strong, readonly) dispatch_queue_t methodQueue;
      | ^ property with 'retain ' attribute must be of object type
  183 |
  184 | /**
  185 |  * Wrap the parameter line of your method implementation with this macro to


❌  (node_modules/react-native/React/Base/RCTModuleData.h:101:1)

   99 |  * queue and the module itself if they have not already been created.
  100 |  */
> 101 | @property (nonatomic, strong, readonly) dispatch_queue_t methodQueue;
      | ^ property with 'retain ' attribute must be of object type
  102 |
  103 | /**
  104 |  * Whether the receiver has a valid `instance` which implements -batchDidComplete.


❌  (node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.h:33:1)

  31 | - (instancetype)initWithURL:(NSURL *)url __deprecated_msg("Use initWithURL:queue: instead");
  32 | /** @brief Must be set before -start to have effect */
> 33 | @property (nonatomic, strong) dispatch_queue_t delegateDispatchQueue __deprecated_msg("Use initWithURL:queue: instead");
     | ^ property with 'retain ' attribute must be of object type
  34 |
  35 | @end
  36 |


❌  (node_modules/@react-native-firebase/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.h:20:9)

  18 | #import <Firebase/Firebase.h>
  19 | #import <Foundation/Foundation.h>
> 20 | #import <React/RCTBridgeModule.h>
     |         ^ could not build module 'React'
  21 |
  22 | @interface RNFBMessagingSerializer : NSObject
  23 |
```

**Comment by piedrahitapablo** [comment] 2022-10-25 22:34
I found the issue, turns out I was using the `expo-cli` to install the packages and it was using these versions:

```
"@react-native-firebase/app": "~15.4.0",
"@react-native-firebase/messaging": "^16.2.0",
```

after changing the version of messaging to `~15.4.0`, the error disappeared.

**Comment by mikehardy** [comment] 2022-10-26 00:09
That's the wrong direction, not sure why you'd downgrade on purpose? The most important thing is to have all one version:

https://invertase.io/blog/react-native-firebase-versioning

I don't use Expo personally so I don't do more than basic triage on the issues, but I'm happy to merge any reasonable PRs (that is, perhaps to the documentation...) as needed from Expo users for Expo users. Just hit the edit button at top right of any page on rnfirebase.io

This appears to have no further actions other than an optional doc followup if needed from you all, so I'll close this out after editing the title a bit to help others

**Closed by mikehardy** 2022-10-26 00:09 UTC
Labels: Impact: Bug, Help: Needs Triage
