### ISSUE TITLE
Notifications not working with IOS Simulator after Upgrade 14.8.0

### ISSUE THREAD

**Issue by ims7inc** [invertase/react-native-firebase#6365] opened 2022-07-04 11:29 UTC
## Issue
Notifications not working in IOS Simulator after upgrade from 7.0.1 to 14.8.0. it was worked Earlier with 7.0.1

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.8.0`
- **Are you using `TypeScript`?**
  - `Y`

**Comment by mikehardy** [comment] 2022-07-04 17:34
Hi there! Unfortunately you've not included any information needed to reproduce this, additionally, no one else has reported notifications not working and that is one of the most important + most heavily used parts of the library + I use it personally and I know it works. I'm going to have to close this as no template / no reproduction / can't reproduce. We can reopen if you reproduce based on a known-good integration (like https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh)

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/mcve

**Closed by mikehardy** 2022-07-04 17:34 UTC
Labels: Impact: Bug, Help: Needs Triage

**Comment by ims7inc** [comment] 2022-07-06 06:27
@mikehardy I could able to get Notifications in IOS Real devices with 14.8.0 but Notifications not received on IOS Simulator. If i downgraded to 7.0.1 then i could able to get Notifications on both Real devices & Simulator
