### ISSUE TITLE
Receive data messages when app is closed

### ISSUE THREAD

**Issue by barbaragomes** [invertase/react-native-firebase#1005] opened 2018-04-20 23:37 UTC
### Issue

Hi there,

I'm using Cloud Message with data messages only. I get the data messages from the server when the app is in the background and in the foreground, but if I kill the app, when I open it again, I do not get the messages it was sent during the period the app was closed.

As per documentation: When the app is closed the messages will be received when app is next opened

Does it mean that the onMessage method should be called for each message that was received when the app was closed? If so, that is not happening and what can I do to fix it?

### Environment

iOS

1. Application Target Platform: macOS High Sierra

2. Development Operating System: Xcode Version 9.3 (9E145)

4. React Native version: 0.53.3

5. RNFirebase Version: 4.0.4

6. Firebase Module: Data Message

**Comment by judemanutd** [comment] 2018-04-21 06:26
Are you testing on a simulator or a physical device ?

**Comment by judemanutd** [comment] 2018-04-23 02:45
Are you testing it with a preloaded bundle or is the bundle being loaded from the computer? I suspect that might be an issue, try it with a preloaded bundle, such as a release build.

**Comment by barbaragomes** [comment] 2018-04-23 17:06
I have tested that with a pre loaded bundle in release build. I will try releasing it to testflight and see if it works

**Comment by barbaragomes** [comment] 2018-04-23 19:36
@judemanutd I'm having another problem now. In order to submit my app to testflight, Apple requires the "aps-environment" in the entitlement, which gets added by enabling Push Notifications in my project Capabilities file.

Now, when I enable Push Notifications on my project, I stop getting the data messages in the device, but I get the data messages when running in the Simulator. 

Any idea of what am I missing?

**Comment by judemanutd** [comment] 2018-04-23 19:40
In Xcode under capabilities make sure background and remote notifications are enabled

**Comment by barbaragomes** [comment] 2018-04-23 22:35
@judemanutd I have added all the configurations and I have no success when app is running on device when I have Push Notification capability enabled. ANy other suggestion?

**Comment by barbaragomes** [comment] 2018-04-23 23:43
**UPDATE**: I'm able to receive the messages on the device, foreground and background. Turns out even if I'm using only Data Messages, I still have to configure all the notification code as well. 

I'm still not getting the messages while the app is closed. I'm not looking for Push notifications, I'm using only data messages, and I just need the messages that was sent while the app was closed to be replayed once the app starts

**Comment by judemanutd** [comment] 2018-04-24 03:03
How exactly are you sending notifications to the device? If its a topic then make sure you've implemented the `onTokenRefresh` method and within that method subscribe to a topic.

Make sure your time to live for the fcm is long enough, also that you're sending  `out `content_available:true` in your fcm request.

**Comment by barbaragomes** [comment] 2018-04-24 22:38
We using device groups. When the user logs in, we register the token to the user and we have messages that are destined to a group of users.

We publish a data message to the group, and all messages have `content_available:true`

Is a data message supposed to be delivered to the app if it was published and the app was closed?

**Comment by judemanutd** [comment] 2018-04-25 03:08
It should be delivered when the app opens next according to the documentation but I can guarantee that notification only fcms get delivered even if the app is completely closed.
At this point I'm not really sure why you aren't receiving the messages.

**Comment by chrisbianca** [comment] 2018-05-16 16:54
The first part of this which will capture any messages that arrive whilst the app is initialising has been done as part of: https://github.com/invertase/react-native-firebase/commit/dc793696fe3115b80fef0c141154f91b8488a0b2

The second part will be addressed as part of the work: https://github.com/invertase/react-native-firebase/issues/971

I'm going to close this as the remainder is a duplicate of #971.  Please follow there for full support.

**Closed by chrisbianca** 2018-05-16 16:54 UTC
Labels: awaiting-user-feedback, ios, messaging
