### ISSUE TITLE
Collection Query using where new Date() works but new Date() where you set 0 on hh:mm:sss doesn't

### ISSUE THREAD

**Issue by jojonarte** [invertase/react-native-firebase#1439] opened 2018-08-29 07:09 UTC
### Issue
I have this code below, what I was trying to accomplish was query all documents of the collection using the `dateTime` key which is a Firestore.timestamp.  

Each document on that collection looks like below:
```
reservationDocument: {
   dateTime: TimeStamp,
   deleted: boolean,
   duration: number,
}
```

This query returns data:
```
firebase.firestore().collection('reservations').where('dateTime', '>=', new Date()).get()

```

While this returns empty:
```
const today = new Date();
today.setHours(0);
today.setMinutes(0);
today.setMilliseconds(0);
today.setSeconds(0);

firebase.firestore().collection('reservations').where('dateTime', '>=', today).get()

```

### Environment

1. Application Target Platform:

Both

2. Development Operating System:
OS: macOS High Sierra 10.13.5

3. Build Tools:
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4819257

  Node: 8.11.2
  Yarn: 1.7.0
  npm: 6.2.0
  Watchman: 4.9.0
4. `React Native` version:
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
5. `React Native Firebase` Version:
    "react-native-firebase": "^4.3.8",
6. `Firebase` Module:
firestore,

7. Are you using `typescript`?
no

**Comment by Ehesp** [comment] 2018-08-30 18:35
@jojonarte Could you show us a screenshot of what exactly is on the Firebase console under the `dateTime` field please?

**Comment by jojonarte** [comment] 2018-08-31 10:41
@Ehesp  
![screen shot 2018-08-31 at 6 40 12 pm](https://user-images.githubusercontent.com/11880365/44908270-6eee5400-ad4d-11e8-9b96-599e5fb4b370.png)

**Comment by YGKtech** [comment] 2018-10-16 22:34
So, query's using inequality operators on date/timestamp fields are just broken, have been broken for over a month, and it's not being fixed?  Am I understanding that correctly?  Seems like something that ought to be prioritized...

**Comment by jojonarte** [comment] 2018-10-17 01:55
After few minutes it actually worked, I still haven't figured out why.

**Comment by YGKtech** [comment] 2018-10-17 17:16
@Salakar : I'll admit my comments on this thread and on #735 are a bit snarky, I had just spent all day troubleshooting the problem and was rather frustrated when I found out that it was a known issue that wasn't documented and had gone unfixed for so long.

Frustration aside, I don't think the issues identified in #735 are a strict sub-set of the issues being discussed in this thread, and merging them may impair efforts to fix the separate issues.

This thread identifies issues with using `where` to construct a query with `Date` objects, which I believe is probably related to some of the problems found in 735.  But some users in the discussion around 735 converted their date/timestamp fields to numbers using equivalent unix timestamps, and still found the `.startAfter` operator didn't function correctly in iOS builds, but seemingly does work correctly in android.

It is entirely possible that the maintainers know more about the issues and are confident both conversations relate to the same root causes, but it's not outwardly apparent to me that this is the case.

@jojonarte : is it now functioning consistently for you?  I've been struggling with the `.startAfter` operator not handling Date objects well, but if you're able to get `.where` working, albeit with some issues along the way, that may be a viable alternative.

**Comment by Salakar** [comment] 2018-10-17 17:40
@YGKtech only a tad snarky for what is a free open source product that I slave away on in my own time for everyone, not to mention the other contributors 🙃 

Anyway, I get the frustration, so apologies for the delay; there have been a number of bigger issues (RN changes & Firebase SDK changes) that completely break the build as opposed to 1 small part (albeit critical for pagination) that needed focusing on hence why this got delayed - If I can't build it then I can't fix the smaller issues 😅 

What would help hugely to speed it along is a sample dataset(s) and a sample code snippet(s) that demonstrates the incorrect behaviours, I can then use this as part of the e2e tests to ensure the behaviour is fixed/help debug the issue quicker. If you can get something to me like this I'll be super grateful and will get a fix out overnight ☕️

**Comment by YGKtech** [comment] 2018-10-17 18:50
@Salakar : I'll work on generalizing some of my test code to make a functioning example script, though my work is more directly related to issue #735.  It looks like another maintainer had done some work on that thread a while back and determined that it was going to be a difficult fix, you may want to check in with them to about it.
I suspect this issue might relate to firestore migrating to the Timestamp class for datetime values, I've had a lot of issues working with it server-side (the constructor is very picky and errors out when it doesn't like your params.  Could be why behavior differs for `Date` instances with zero'd out time components, if it's being converted to a Timestamp instance at some point).

I do value the work that's done on this repo, but your docs set an expectation about what can be done with this library, and when the code doesn't deliver on those expectations it can cause problems.

If there were a note in the README or in your documentation, or better yet a runtime warning, I could have spent my time on an alternative solution, like setting up an API layer so I could query firestore using official SDK's on the server side, instead of trying to make it work with a module that doesn't provide the feature I need.

**Comment by Salakar** [comment] 2018-10-17 18:54
@YGKtech that's fair, let's focus on your issue first, #735 and then we can go from there for the other issues. 

Thanks for looking into an example script. Also for reference what version RNFB are you on?

**Comment by YGKtech** [comment] 2018-10-19 18:06
@Salakar : sorry for the delay, I was going to get you that test code but I got pulled onto another project and haven't had time.  I'll try to get you something next week.

**Comment by Salakar** [comment] 2019-01-04 22:13
All, I've gone through every Date based querying scenario I could think of plus the ones linked in the other issues and I've been unable to reproduce any errors on either platform;

You can view all the tests I added for this here: https://github.com/invertase/react-native-firebase/commit/6bc668c8ab9e1e3cf3a990348a9ac9f4596f6bd8

This may have been an issue with the Native SDKs or an earlier release but everything appears to be fine now.

I'll go ahead and close this issue now. I'd suggest if anyone has an issue like this again submit a PR with a test that fails - the ground work for this has been done in that commit.

(I'll re-open the `startAfter` one @YGKtech linked and look at that seperately tomorrow)

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by nous-** [comment] 2019-01-12 14:42
react-native-firebase 5.2.0/iOS:  The document cursor passed to startAfter [document snapshot query cursor](https://firebase.google.com/docs/firestore/query-data/query-cursors#use_a_document_snapshot_to_define_the_query_cursor) is included in the resulting collection

Running the same code with firebase js library ("firebase": "^5.7.2", "firebase-admin": "^6.4.0") works correctly.

Quick code for repo:
```
// Grab latest 5 entries
firebase.firestore().collection('examplecollection').orderBy('time', 'desc').limit(5).onSnapshot(docs => {
  console.log(docs.docs.map(doc => ({id:doc.id, time:doc.data().time})));

  // Use last entry as cursor
  const cursor = docs.docs[docs.docs.length - 1]; // assumed not empty

  // Same query starting after cursor (last doc)
  firebase.firestore().collection('examplecollection').orderBy('time', 'desc').startAfter(cursor.id).limit(5).onSnapshot(docs => {

    // docs.docs includes cursor
    console.log(docs.docs.map(doc => ({id:doc.id, time:doc.data().time})));
  });
})
```
where there are 11 documents under /examplecollection with required property time as Timestamp

**Comment by jojonarte** [comment] 2019-02-02 14:32
@YGKtech it's actually functioning well for me. Sorry for getting back later.

**Comment by tkow** [comment] 2019-03-27 07:38
Same [this](https://github.com/invertase/react-native-firebase/issues/1439#issuecomment-453752782) occurs for me, too.
I did remedy to paginate end for this.
```
if (nextCursorSnapShot.id === results.docs[results.docs.length-1].id) // cursor end break;
if ( results.docs[0].id === nextCursorSnapShot.id) results.docs.shift()
```
this patch will stop when reaching the end of query documents and exclude cursor from results.

**Comment by Salakar** [comment] 2019-07-31 12:38
Hey all 👋 	

A fix for snapshot cursors and other things is live on the preview release of v6; [[changelog]](https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#cloud-firestore-firestore)

See [this comment](https://github.com/invertase/react-native-firebase/issues/2025#issuecomment-516310002) for release details.

Please give it a go and if you have any issues please create a new issue with `[v6]` in the title.

Thanks

**Closed by Salakar** 2019-07-31 12:38 UTC
Labels: Blocked: Needs Review, Help: Needs Tests, Impact: Bug, Platform: Android, Platform: iOS, Service: Firestore, 📌 pin

**Comment by Daniel0liver** [comment] 2021-08-13 14:39
if you use date-fns, this is working for me:

```import { format } from 'date-fns';

const startAt = (date: Date) => {
  const parsed = format(date, 'yyyy-MM-dd 00:00:00.000');
  return new Date(parsed);
};

const endAt = (date: Date) => {
  const parsed = format(date, 'yyyy-MM-dd 23:59:00.000');
  return new Date(parsed);
};

const startDate = startAt(new Date())
const endDate = endAt(new Date())

firebase.firestore().collection('reservations')
  .where('dateField', '>=', startDate)
  .where('dateField', '<=', endDate).get()
```
