### ISSUE TITLE
Doesn't work in rare cases

### ISSUE THREAD

**Issue by markhalonen** [invertase/react-native-firebase#322] opened 2017-08-10 04:18 UTC
### Environment

1. Target Platform: Android
2. Development Operating System: macOS
3. Build tools Android Studio 2.3.1
4. React Native version: 0.43.3
5. RNFirebase Version: 2.0.4

Hello, this may be long winded and may never get an answer, but I don't know what to try next. 
I have an app with 12k users, with _everything_ on Firebase. At first, I used the js Firebase library, with none of these crashes, and then I switched to this one.

The issue: I'm getting quite random reports that the app simply doesn't work. I've never been able to replicate on my own device. This is a list of the reviews reporting it doesn't work:

Crashes when pressing register:
![image](https://user-images.githubusercontent.com/7853605/29154166-856e5144-7d60-11e7-978d-70753b861e64.png)

Will not open:
![image](https://user-images.githubusercontent.com/7853605/29154176-9159152a-7d60-11e7-9d1f-bff3d3d2b0ee.png)

Will not open:
![image](https://user-images.githubusercontent.com/7853605/29154187-a249ed00-7d60-11e7-9e91-6b04760eabd1.png)

Will not open:
![image](https://user-images.githubusercontent.com/7853605/29154191-adaff07c-7d60-11e7-94f5-a732bc1ab0ba.png)

Crashes when pressing register:
![image](https://user-images.githubusercontent.com/7853605/29154202-be37b8bc-7d60-11e7-8c85-fff7cc62169b.png)

I have an affected user who I'm emailing who is willing to try anything to make it work, but I don't even know what to tell her! Any suggestions? I thought it was something with Google Play Services, but it doesn't seem to be the case.

**Comment by chrisbianca** [comment] 2017-08-10 08:19
@markhalonen Do you have the associated stack dump to go with these crashes? Without these, we're completely blind so won't be able to offer any real assistance.

**Comment by Ehesp** [comment] 2017-08-10 10:52
Have you got any options set in the initialiser? These: http://invertase.io/react-native-firebase/#/usage?id=configuration-options

**Comment by markhalonen** [comment] 2017-08-10 14:37
@chrisbianca Here's some stack dumps. 
![image](https://user-images.githubusercontent.com/7853605/29175700-bc82cc8a-7db7-11e7-946d-2021e705412a.png)


The person with the S7 (heroqltevzw) is the one willing to help, so I'll post those ones:
![image](https://user-images.githubusercontent.com/7853605/29175522-44071220-7db7-11e7-8c93-79d328e50208.png)

This one looks like it could my error (I recognize the code):
![image](https://user-images.githubusercontent.com/7853605/29175600-7708f724-7db7-11e7-93fa-9816ec5b6c9c.png)

Really if any kind of hack works, I'd be happy. I just want stuff to try.

**Comment by markhalonen** [comment] 2017-08-10 14:43
@Ehesp No, I don't have any options. I never realized those were available. The one I'm interested in is database persistence. A big reason for my move to this library was to improve offline performance, so thanks for pointing this out! I hadn't noticed any improvement, but I'll test this out!

**Comment by Ehesp** [comment] 2017-08-10 14:48
You'll mainly notice improvements with animations and touch events. If you enable crash reporting you'll also get these crashes going into your firebase console.

Although from that stack trace, the crashes look to have no relation to this lib. The JavaScriptException is being thrown as you're trying to access a deep nested prop object which is undefined. The ViewGroup errors are being thrown because there's an issue with your component rendering I'd imagine.

**Comment by markhalonen** [comment] 2017-08-10 14:54
I'm getting the crashes in the firebase console, which is cool. 
The person with the S7 left the review on August 9th, 9:30pm. The two stack traces are on August 6th and July 30th. Perhaps she went back 3+ days later to leave a review, or perhaps the crash is not getting reported?

**Comment by Ehesp** [comment] 2017-08-11 19:35
It does look like a user/code error, especially will be prone if you're dynamically accessing deep nested objects. I'd try and do some debugging around that `props[idx]` area.

**Comment by markhalonen** [comment] 2017-08-12 02:23
The person with the S7 reported that yesterday morning it worked! And then this morning, it did not work. Baffling. Just crashes on launch.

**Comment by chrisbianca** [comment] 2017-08-13 09:34
@markhalonen it sounds like it might be a path in your code that's causing the error.  None of the stack traces indicate that it's RNFirebase causing the issue.  Do you log any events to Firebase Analytics?  If so, then with the stack trace you should also be able to see the events that have been logged before the error happens.  That might give you some steps to reproduce...

**Comment by markhalonen** [comment] 2017-08-16 03:47
@chrisbianca I don't log any events to Firebase Analytics. That seems like the next logical thing to do, log every step of the way in the very first parts of the code to see exactly where it's getting stuck.

I will probably just bite the bullet on the affected users and stick to this library, as the Analytics and offline support outweigh these errors.

**Comment by chrisbianca** [comment] 2017-08-18 08:07
@markhalonen Given the rare nature of this issue and the fact that you're unable to reproduce it, what makes you think that it's related to RNFirebase, rather than an edge case that hadn't previously been reached in your code?

The only reason I ask, is that there's nothing in any of the stack traces that you've included which links back to an error within RNFirebase so it's difficult to see how this could be the case.

**Comment by chrisbianca** [comment] 2017-08-29 08:11
I'm going to close this, please feel free to re-open if you find something that relates the errors back to `react-native-firebase`

**Closed by chrisbianca** 2017-08-29 08:11 UTC
Labels: awaiting-user-feedback
