### ISSUE TITLE
React 0.56 support

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#1283] opened 2018-07-07 12:06 UTC
### Issue

Updating to react native v0.56.0 requires flow bin update to ^0.75.0 which results in following errors
```
Error ┈┈┈┈┈ node_modules/react-native-firebase/dist/modules/firestore/Query.js.flow:417:20

Property fieldpath is missing in NativeFieldPath [1].

 [1]  46│   fieldPath: NativeFieldPath,
        :
     414│           fieldOrder.fieldPath.string
     415│         ) {
     416│           values.push(docSnapshot.get(fieldOrder.fieldPath.string));
     417│         } else if (fieldOrder.fieldPath.fieldpath) {
     418│           const fieldPath = new FieldPath(...fieldOrder.fieldPath.fieldpath);
     419│           values.push(docSnapshot.get(fieldPath));
     420│         }


Error ┈┈┈┈ node_modules/react-native-firebase/dist/modules/storage/reference.js.flow:77:12

Cannot return new StorageTask(...) because StorageTask [1] is incompatible with
Promise [2].

     74│    * @return {Promise}
     75│    */
 [2] 76│   downloadFile(filePath: string): Promise<Object> {
 [1] 77│     return new StorageTask(
     78│       DOWNLOAD_TASK,
     79│       getNativeModule(this._storage).downloadFile(this.path, filePath),
     80│       this
     81│     );
     82│   }
     83│
     84│   /**


Error ┈┈┈ node_modules/react-native-firebase/dist/modules/storage/reference.js.flow:100:12

Cannot return new StorageTask(...) because StorageTask [1] is incompatible with
Promise [2].

      97│    */
 [2]  98│   putFile(filePath: Object, metadata: Object = {}): Promise<Object> {
      99│     const _filePath = filePath.replace('file://', '');
 [1] 100│     return new StorageTask(
     101│       UPLOAD_TASK,
     102│       getNativeModule(this._storage).putFile(this.path, _filePath, metadata),
     103│       this
     104│     );
     105│   }
     106│ }
     107│

```

### Environment

1. Application Target Platform: iOS

2. Development Operating System: macOS High Sierra

3. Build Tools: Not needed

4. `React Native` version: 0.56.0

5. `React Native Firebase` Version: 4.2.0

6. `Firebase` Module: firestore, storage

7. Are you using `typescript`? no

---
Loving `react-native-firebase`? Please consider supporting them with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Salakar** [comment] 2018-07-07 13:42
@IljaDaderko rn 56 has backwards compatible breaking changes so support for it will only land in v5.0.0, we have started work on it in this branch already: https://github.com/invertase/react-native-firebase/tree/react-native-56

Thanks for the heads up!

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by leethree** [comment] 2018-07-23 08:10
We already upgraded our project to React Native v0.56. Should I use the current version (v4.3.6) or wait for v5? Is there anything known to break in v4 other than flow errors (which we can ignore)?

**Comment by Salakar** [comment] 2018-07-23 09:32
@leethree there's this issues and all the ones linked above your comment e.g. there are issues with importing and using `react-native-firebase` in JS land due to breaking changes in the way the module is compiled with Babel; as it has been upgraded to v7:

![image](https://user-images.githubusercontent.com/5347038/43068837-6f1fb24c-8e63-11e8-8931-2e59661f045e.png)

Support will land in v5 in the next week or two hopefully.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by leethree** [comment] 2018-07-23 09:45
@Salakar got it! we'll probably wait for v5 if it's coming soon.

**Comment by smkhalsa** [comment] 2018-07-28 06:22
@Salakar any idea when v5 will land?

**Comment by Salakar** [comment] 2018-07-29 20:57
@smkhalsa hey; we're aiming for a release on the 7th. Thanks

**Comment by Salakar** [comment] 2018-08-05 02:35
@IljaDaderko @leethree @smkhalsa and anyone else - React Native ^0.56.0 support is on master for anyone feeling daring.

Would be helpful if anyone could try it - 0.56 broke our testing infra so it's going to take me a couple of days to re-write it all again 😭 - I have manually tested builds etc and all seems fine - including the flow issues above posted by @IljaDaderko 

If you're on v4.3.x currently then your only update step (for now - v5 stil WIP) is updating to RN 0.56.0 and all your babel versions as described in the RN 56 release notes.

See https://github.com/invertase/react-native-firebase/blob/master/bridge/package.json for an example app running the latest versions.

**Comment by Salakar** [comment] 2018-08-08 13:38
@timwangdev as requested;

![image](https://user-images.githubusercontent.com/5347038/43840377-7443a10e-9b18-11e8-9293-ac18731916b2.png)


```sh
npm i react-native-firebase@next
```

As always please report any issues you find, additionally can you tag them `[next]` on your GitHub issue titles so I can pick them up easier.

**Comment by alexichristakis** [comment] 2018-08-08 18:58
I just tried upgrading my project to the RC and im stuck getting the error: 

```
unable to resolve module '../crash' from `/Users/alexic/react-native/sesh/node_modules/react-native-firebase/dist/modules/core/firebase.js`: The module `../crash` could not be found from `/Users/alexic/react-native/sesh/node_modules/react-native-firebase/dist/modules/core/firebase.js`. Indeed, none of these files exist:
```

but it looks like firebase.js isn't requiring such a module. I tried reinstalling the package with no luck.

**Comment by Salakar** [comment] 2018-08-08 19:19
@alexichristakis can you try reset your rn packager cache, start it with `--reset-cache`

**Comment by alexichristakis** [comment] 2018-08-08 19:21
@Salakar still no luck

**Comment by Salakar** [comment] 2018-08-08 19:33
Can you try `npm i react-native-firebase@5.0.0-rc0` - specifying the version specifically?

**Comment by alexichristakis** [comment] 2018-08-08 19:40
rolling back to an old branch and reinstalling now. maybe something got messed up the first time...

**Comment by Salakar** [comment] 2018-08-08 19:41
Ok, am on discord as well if you still continue to have issues ping me on there and I can take a look

**Comment by Salakar** [comment] 2018-08-14 00:41
Confirmed working on `npm i react-native-firebase@5.0.0-rc0`. Closing this issue pending the full release of v5.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Closed by Salakar** 2018-08-14 00:41 UTC
Labels: await-user-feedback, build, fixed-pending-release, help-wanted, react-native

**Comment by gianpaj** [comment] 2018-09-15 12:48
If I have a RN v0.56 app and currently using RNFilrebase v4.2.0, should I upgrade the latest v4.3.x or wait until the v5.0 is released?

**Comment by timwangdev** [comment] 2018-09-16 13:28
@gianpaj You could use `@next` release. It works fine on our project.
@Salakar It's better to see 5.0.0 release coming soon, of cause.

**Comment by IljaDaderko** [comment] 2018-09-21 14:11
@Salakar I will be playing with my side project this weekend can try out latest v5 rc, should it be compatible, is it by any chance compatible with rn 0.57.x, so I can try both? Also which versions of firebase ios sdk should be used?

**Comment by Salakar** [comment] 2018-09-21 14:30
@IljaDaderko it is fully compatible with 0.56 & 0.57 now - our tests app runs on 0.57, see [react-native-firebase/tests](https://github.com/invertase/react-native-firebase/tree/master/tests) if you'd like - as a reference to which versions of RN/React/Firebase etc to use 👍

I'll be about most of the weekend on Discord so feel free to drop me a DM if you have any issues or need an assist.

See the pinned messages on Discord in the #pre-releases channel for RC release notes - latest is RC4 from yesterday.

**Comment by quachsimon** [comment] 2019-01-04 22:16
We are going to be updating our project from 0.55.4 -> 0.57 in the coming weeks. We are currently on RNFirebase v4.3.8, the latest one is v5.1.x. 

Should we update from v4.3.8 -> v5.0.0 then from v5.0.0 -> v5.1.0? or can we just make the jump from v4.3.8 -> v5.1.0?

I looked at the docs and wasn't sure if that's possible.

https://rnfirebase.io/docs/v5.x.x/release-notes#Upgrade-from-v5.1.0
