### ISSUE TITLE
Crash when trying signInWithEmailAndPassword with empty string

### ISSUE THREAD

**Issue by ohtangza** [invertase/react-native-firebase#127] opened 2017-05-26 13:10 UTC
In Firebase Web SDK, it provides error response instead of an exception.
(We encountered this error after migrating from Web SDK to this `react-native-firebase`.)

I think it is better it works same as the official SDK. Any thoughts?

**Comment by Salakar** [comment] 2017-05-26 13:34
Thanks for the report,

 - Can you explain what you mean by empty string, empty email, empty password? 
 - What's the behaviour of the web sdk specifically that is not happening with RNFirebase?
 - Can you provide screenshots/code examples please of expected behaviour vs what's not expected?

**Comment by ohtangza** [comment] 2017-05-26 13:49
Oh, further investigate this issue, and this issue is specific to Android. iOS works as the web SDK by outputting a message ".The email address is badly formatted."

- empty string/email/password is just empty string `''`.
- The following is the stack trace from calling `firebase.auth().signInWithEmailAndPassword('', 'test')` on Android.
```
java.lang.IllegalArgumentException Given String is empty or null 
    Unknown:-1 com.google.android.gms.common.internal.zzac.zzdr
    Unknown:-1 com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword
    RNFirebaseAuth.java:177 io.invertase.firebase.auth.RNFirebaseAuth.signInWithEmailAndPassword
    Method.java:-2 java.lang.reflect.Method.invoke
    BaseJavaModule.java:345 com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke
    JavaModuleWrapper.java:141 com.facebook.react.cxxbridge.JavaModuleWrapper.invoke
    NativeRunnable.java:-2 com.facebook.react.bridge.queue.NativeRunnable.run
    Handler.java:751 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    MessageQueueThreadHandler.java:31 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    Looper.java:154 android.os.Looper.loop
    MessageQueueThreadImpl.java:196 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:761 java.lang.Thread.run
```

**Comment by Salakar** [comment] 2017-05-26 14:26
Ok I see what you mean, looks like this is an inconsistency between the official firebase iOS and Android SDK's.

As you can see from the below screenshots - ios when the email is empty correctly goes into the completion block. Android however throws an exception without event getting into the `OnFailureListener` - it errors on the line `mAuth.signInWithEmailAndPassword(email, password)` when it should instead complete as a failure without throwing an exception.

I'd suggest raising a support request with firebase and raise this inconsistency issue please - I'm sure they've had enough of me raising the issues =] You can use this issue and this comment in it as a reference. By the looks of it it's not just limited to this method on android either - I'd imagine methods such as `createUserWithEmailAndPassword` would be affected also.

### iOS
![image](https://cloud.githubusercontent.com/assets/5347038/26498067/a355d0c2-4225-11e7-8b99-b201cc3f4eb0.png)

### Android
![image](https://cloud.githubusercontent.com/assets/5347038/26498331/9b3f77f2-4226-11e7-8e75-4b7af68082a4.png)

Let me know how the support request goes and if they plan on resolving this. 

Thanks

**Comment by ohtangza** [comment] 2017-05-26 23:02
@Salakar I reported this issue with a detailed message to Firebase support team through "Bug Report or Feature Request" channel. Keep you updated if there is a response! Thanks for your quick response.

**Comment by ohtangza** [comment] 2017-05-31 16:24
I am sharing here the response from Firebase team. In short, it was correct that the SDK was designed inconsistently. I will keep updating if there is any other news.

------------------------------

Hi Jeungmin,

My apologies for not getting back to you sooner.

I tried to replicate the issue on our Firebase Android SDK, and I did encountered the same error. I have informed our engineers regarding this one and I'll update you once I have more information to share.

Sincerely,
Hazel

**Comment by ohtangza** [comment] 2017-06-02 16:35
I finally got the decision, which turned out that this issue should be handled RN wrapper level for the time being. Given that the motto of this wrapper is to mimic the behavior of the official web SDK, I think Android should prevent from crashing by this library. Any thoughts on this?

-----------------------------
"I have talked to our engineers. Here's our perspective regarding this one, the behavior that you're seeing was an explicit design choice made by the FirebaseAuth team. In general, these types of errors are ones that the developer such as yourself should be explicitly handling in all cases, so we fail proactively to let you know during development. As you mentioned, it's possible for you to resolve this at the RN wrapper level."

**Comment by chrisbianca** [comment] 2017-06-02 16:50
@ohtangza If it was an explicit design choice made by the FirebaseAuth team, then why does the behaviour differ between iOS and Android?  That's not aimed at you, but at them!

I'm loathe to introduce platform specific handling because the SDKs throw an internal error rather than deal with the behaviour correctly.

Can I suggest that you add some protection in your app to prevent a user being able to submit an empty username or password?  This is a pretty standard user experience for any app that I've ever used, and certainly is what I'm doing with my apps...

**Comment by Salakar** [comment] 2017-06-02 17:05
I'm with @chrisbianca, if it's a 'design choice' why is iOS different, sounds like another standard response.

**Comment by Sparragus** [comment] 2017-06-02 17:14
Ugh. So sad that was FirebaseAuth's response.

@ohtangza Check out [validator](https://github.com/chriso/validator.js). It has a ton of validation functions you can use, including `validator.isEmail` and `validator.isEmpty`.

**Closed** 2017-06-05 06:33 UTC
Labels: firebase-issue

**Comment by edlovejoy** [comment] 2018-01-16 14:06
i had same issue and i did a temp fix where i went to the activity_login and add
android:text="email" plus the hint too. so the user have to delete this email before they put 
in the new one..so if the login without any input then they will get the regular login error instead of 
a crash..  because the text is not making the it empty any more.. but i will look into it further with a proper way to validate .

**Comment by ChkBuk** [comment] 2021-04-05 21:57
> I finally got the decision, which turned out that this issue should be handled RN wrapper level for the time being. Given that the motto of this wrapper is to mimic the behavior of the official web SDK, I think Android should prevent from crashing by this library. Any thoughts on this?
> 
> "I have talked to our engineers. Here's our perspective regarding this one, the behavior that you're seeing was an explicit design choice made by the FirebaseAuth team. In general, these types of errors are ones that the developer such as yourself should be explicitly handling in all cases, so we fail proactively to let you know during development. As you mentioned, it's possible for you to resolve this at the RN wrapper level."

Hi @ohtangza,
Have you got any feedback from firebase?

**Comment by mikehardy** [comment] 2021-04-06 16:23
@ChkBuk this issue has been closed for almost **4 years** and the feedback was in there.
I'm not sure we still crash on this at all actually, but if we do, a PR would be okay to prevent the crash.
There will be no more activity on this closed issue though :-)

**Comment by catcatwithcat** [comment] 2021-04-07 18:22
> > I finally got the decision, which turned out that this issue should be handled RN wrapper level for the time being. Given that the motto of this wrapper is to mimic the behavior of the official web SDK, I think Android should prevent from crashing by this library. Any thoughts on this?
> > "I have talked to our engineers. Here's our perspective regarding this one, the behavior that you're seeing was an explicit design choice made by the FirebaseAuth team. In general, these types of errors are ones that the developer such as yourself should be explicitly handling in all cases, so we fail proactively to let you know during development. As you mentioned, it's possible for you to resolve this at the RN wrapper level."
> 
> Hi @ohtangza,
> Have you got any feedback from firebase?
