### ISSUE TITLE
no payload in getInitialNotification

### ISSUE THREAD

**Issue by AlanRedvike** [invertase/react-native-firebase#1361] opened 2018-08-02 12:03 UTC
### Issue

Hi there, im implementing notifications in my app and came across this problem:
When i send a message from firebase console it is properly received in the emulator and i get the event in app. 
If the app is in foreground mode i receive a proper payload in the onMessage handler (with notification's body text etc..)
However, if the app is in background mode and i try to get something through getInitialNotification handler i receive : 

```json
{
  "opened_from_tray": true,
  "fcm": {
    "action": null
  }
}
```

It happens everytime when i open the app from notification. I need to get the body from the payload.
btw. im using old versions of react-native and react-native-firebase and i can't update it to the newest versions.

### My `AndroidManifest.xml`

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="xxx"
    android:versionCode="6"
    android:versionName="1.1">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <permission
        android:name="com.chitownapp.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <uses-permission android:name="xxx.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="26" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize"
        android:launchMode="singleTop"
        android:exported="true">
      </activity>
      <activity
            android:name=".SplashActivity"
            android:theme="@style/SplashTheme"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <service
        android:name="io.invertase.firebase.messaging.MessagingService"
        android:enabled="true"
        android:exported="true">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>
      <service android:name="io.invertase.firebase.messaging.InstanceIdService" android:exported="false">
        <intent-filter>
          <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
        </intent-filter>
      </service>
    </application>

</manifest>
```

### My `MainApplication.java`

```java
package com.xxx;

import android.app.Application;

import android.content.Intent; 
import android.os.Bundle;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.horcrux.svg.SvgPackage;
import com.BV.LinearGradient.LinearGradientPackage;

import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.facebook.appevents.AppEventsLogger;

import com.gettipsi.stripe.StripeReactPackage;

import java.util.Arrays;
import java.util.List;

import org.devio.rn.splashscreen.SplashScreenReactPackage;

import io.sentry.RNSentryPackage;

import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;

public class MainApplication extends Application implements ReactApplication {

  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();

  protected static CallbackManager getCallbackManager() {
    return mCallbackManager;
  }

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new SvgPackage(),
          new LinearGradientPackage(),
          new FBSDKPackage(mCallbackManager),
          new StripeReactPackage(),
          new SplashScreenReactPackage(),
          new RNFirebasePackage(),
          new RNFirebaseMessagingPackage(),
          new RNSentryPackage(MainApplication.this)
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    FacebookSdk.sdkInitialize(getApplicationContext());
    AppEventsLogger.activateApp(this);
  }
}
```

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

macOS Sierra

3. Build Tools:

Android Studio 3

4. `React Native` version:

0.47.0

5. `React Native Firebase` Version:

3.3.0

6. `Firebase` Module:

messaging

7. Are you using `typescript`?

no

**Comment by Salakar** [comment] 2018-08-02 13:01
@AlanRedvike thanks submitting and all the detail.

This is a duplicate of https://github.com/invertase/react-native-firebase/issues/1190 so will close this one and we can continue the conversation over there.

**Closed by Salakar** 2018-08-02 13:01 UTC
