### ISSUE TITLE
[🐛] Bug Report Title - build.gradle crashes after recent PR: Cannot get property 'android' on null object

### ISSUE THREAD

**Issue by JiboStore** [invertase/react-native-firebase#4153] opened 2020-08-27 06:59 UTC
## Issue

https://github.com/invertase/react-native-firebase/pull/4122

Your changes from:
`def firebaseBomVersion = appPackageJson['sdkVersions'] ? appPackageJson['sdkVersions']['android']['firebase'] : "25.5.0"`

To:
`def firebaseBomVersion = appPackageJson['sdkVersions']['android']['firebase']`

causes crash while building:
```
* What went wrong:
A problem occurred evaluating project ':react-native-firebase_perf'.
> Cannot get property 'android' on null object
```

Is there any reason for removing the checks?

Describe your issue here

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2020-08-27 14:49
@JiboStore I'm going to mark this as a duplicate of #4154 - we can focus effort there, but as mentioned there in the expected react-native-firebase installation the directories of app and all other packages are next to each other, so it should work. We'll figure out (over there) why that is not the case, but I do not want to revert to having version numbers all over the place so I want to keep the centralization change

**Closed by mikehardy** 2020-08-27 14:49 UTC
Labels: Help: Needs Triage, Impact:  Build Error, Impact: Bug, Platform: Android
