### ISSUE TITLE
🔥 [🐛] Secondary app problem with Storage module starting from 15.7.1

### ISSUE THREAD

**Issue by brianGammon** [invertase/react-native-firebase#6671] opened 2022-11-06 03:54 UTC
## Issue

I upgraded my project from 14.12.0 to 16.4.1 this week and found that my secondary Firebase app is causing problems with the storage module on iOS. 

The scenario is this: if I call a method on the primary app storage first, when I later try to use the secondary app (with storage(secondaryApp)), the promise will never resolve. Vice verse, if I use the secondary storage first, any attempt to use the primary will hang. So basically whichever one is used first works, the other is hosed.

To troubleshoot, I created a fresh/empty RN project started experimenting with different configurations. As soon as I downgraded to 15.7.0, it started working. So my guess is something in 15.7.1 seems to have changed how secondary apps work. I only use the secondary app for storage, so I am not sure if it is isolated to storage or potentially an issue in the core app package. It works fine on Android all the way up to 16.4.2.

**EDIT**: I added some code in my sandbox app to toggle between reading from RTDB on primary and secondary and that seems to be working with no issue. There are some [changes in the iOS storage module in 15.7.1](https://github.com/invertase/react-native-firebase/compare/v15.7.0...v15.7.1) related to iOS SDK 10.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "temp_rnfb",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@react-native-firebase/app": "15.7.1",
    "@react-native-firebase/auth": "15.7.1",
    "@react-native-firebase/database": "15.7.1",
    "@react-native-firebase/storage": "15.7.1",
    "react": "18.1.0",
    "react-native": "0.70.4",
    "react-native-blob-util": "^0.16.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^26.0.23",
    "@types/react": "^18.0.21",
    "@types/react-native": "^0.70.6",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.37.0",
    "@typescript-eslint/parser": "^5.37.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0",
    "typescript": "^4.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "database": {
    "rules": "database.rules.json"
  },
  "storage": {
    "rules": "storage.rules"
  },
  "emulators": {
    "auth": {
      "port": 9099
    },
    "firestore": {
      "port": 8080
    },
    "database": {
      "port": 9000
    },
    "storage": {
      "port": 9199
    },
    "ui": {
      "enabled": true
    },
    "singleProjectMode": true
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
$RNFirebaseAsStaticFramework = true

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'temp_rnfb' do
  use_frameworks!
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => false,
    :fabric_enabled => false,
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'temp_rnfbTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

#### `AppDelegate.m`:

```objc
#import <Firebase.h>
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <React/RCTAppSetupUtils.h>

#if RCT_NEW_ARCH_ENABLED
#import <React/CoreModulesPlugins.h>
#import <React/RCTCxxBridgeDelegate.h>
#import <React/RCTFabricSurfaceHostingProxyRootView.h>
#import <React/RCTSurfacePresenter.h>
#import <React/RCTSurfacePresenterBridgeAdapter.h>
#import <ReactCommon/RCTTurboModuleManager.h>

#import <react/config/ReactNativeConfig.h>

static NSString *const kRNConcurrentRoot = @"concurrentRoot";

@interface AppDelegate () <RCTCxxBridgeDelegate, RCTTurboModuleManagerDelegate> {
  RCTTurboModuleManager *_turboModuleManager;
  RCTSurfacePresenterBridgeAdapter *_bridgeAdapter;
  std::shared_ptr<const facebook::react::ReactNativeConfig> _reactNativeConfig;
  facebook::react::ContextContainer::Shared _contextContainer;
}
@end
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  RCTAppSetupPrepareApp(application);

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];

#if RCT_NEW_ARCH_ENABLED
  _contextContainer = std::make_shared<facebook::react::ContextContainer const>();
  _reactNativeConfig = std::make_shared<facebook::react::EmptyReactNativeConfig const>();
  _contextContainer->insert("ReactNativeConfig", _reactNativeConfig);
  _bridgeAdapter = [[RCTSurfacePresenterBridgeAdapter alloc] initWithBridge:bridge contextContainer:_contextContainer];
  bridge.surfacePresenter = _bridgeAdapter.surfacePresenter;
#endif

  NSDictionary *initProps = [self prepareInitialProps];
  UIView *rootView = RCTAppSetupDefaultRootView(bridge, @"temp_rnfb", initProps);

  if (@available(iOS 13.0, *)) {
    rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
    rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feture is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  // Switch this bool to turn on and off the concurrent root
  return true;
}

- (NSDictionary *)prepareInitialProps
{
  NSMutableDictionary *initProps = [NSMutableDictionary new];

#ifdef RCT_NEW_ARCH_ENABLED
  initProps[kRNConcurrentRoot] = @([self concurrentRootEnabled]);
#endif

  return initProps;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

#if RCT_NEW_ARCH_ENABLED

#pragma mark - RCTCxxBridgeDelegate

- (std::unique_ptr<facebook::react::JSExecutorFactory>)jsExecutorFactoryForBridge:(RCTBridge *)bridge
{
  _turboModuleManager = [[RCTTurboModuleManager alloc] initWithBridge:bridge
                                                             delegate:self
                                                            jsInvoker:bridge.jsCallInvoker];
  return RCTAppSetupDefaultJsExecutorFactory(bridge, _turboModuleManager);
}

#pragma mark RCTTurboModuleManagerDelegate

- (Class)getModuleClassFromName:(const char *)name
{
  return RCTCoreModulesClassProvider(name);
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                      jsInvoker:(std::shared_ptr<facebook::react::CallInvoker>)jsInvoker
{
  return nullptr;
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                     initParams:
                                                         (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return nullptr;
}

- (id<RCTTurboModule>)getModuleInstanceFromClass:(Class)moduleClass
{
  return RCTAppSetupDefaultModuleFromClass(moduleClass);
}

#endif

@end
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.53 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-28 | Google APIs ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 15.7.1
- **`Firebase` module(s) you're using that has the issue:**
  - Storage
- **Are you using `TypeScript`?**
  - Y

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2022-11-06 14:55
Mmm 🤔 this bodes ill - 15.7.1 was actually a release system misfire - it should *not* have gone out but for reproducible build / immutability reasons I don't retract it. 15.7.1 was re-released as 16.0.0 with only release system fixes (for breaking change recognition in semver conventional commits)

So what we're really talking about here is the major changes from v15.final to v16:

https://github.com/invertase/react-native-firebase/compare/v15.7.0...v16.0.0

And what happened there was firebase-ios-sdk v10.0.0 was adopted (given this is an iOS issue for you). This was the final bits in the native SDK to move their implementation to Swift and had a number of issues related to it that were actual native issues.

I took a quick scan of upstream and I see no related issues, so my working assumption is that this will be a problem in this module, but I won't discount upstream https://github.com/firebase/firebase-ios-sdk/issues?q=is%3Aissue+label%3A%22api%3A+storage%22+sort%3Aupdated-desc

Can I ask if you are reproducing this against the firebase emulator, or the real/live cloud storage APIs, or both?

> To troubleshoot, I created a fresh/empty RN project started experimenting with different configurations

Good step - I have seen quite a few promise-resolution failures related to redux / redux-thunk etc that do not reproduce on clean projects.

We do exercise secondary apps in storage in our e2e testing but only in the most perfunctory method possible, making sure you may init / reference one, not actually use it: https://github.com/invertase/react-native-firebase/blob/fe9e40480d70b0eb6b2a9d4c2c117688c9abcafd/packages/storage/e2e/storage.e2e.js#L28-L36

Adding some more secondary-app testing in there would (I assume) surface the issue - probably need to parameterize the helpers (https://github.com/invertase/react-native-firebase/blob/main/packages/storage/e2e/helpers.js) to take optionally take name of app so they may seed + configure rules for secondary app then seed it, then exercise it. And probably just attempting to seed it will fail if we reproduce easily, as it seems to for you

**Comment by brianGammon** [comment] 2022-11-06 15:06
> Mmm 🤔 this bodes ill - 15.7.1 was actually a release system misfire - it should _not_ have gone out but for reproducible build / immutability reasons I don't retract it. 15.7.1 was re-released as 16.0.0 with only release system fixes (for breaking change recognition in semver conventional commits)
I did notice the note in the change log about 15.7.1, but wanted to just report the details from my experimenting which involved degrading one release at a time until it worked. Make sense what you're saying about 15.final to 16.
 
> Can I ask if you are reproducing this against the firebase emulator, or the real/live cloud storage APIs, or both?
I can reproduce it with both. It's a pain to set up since it needs 2 firebase projects, but overall relatively easy to reproduce in a fresh project. I'm my case it's definitely not a thunk or redux issue. I will post the code from the sandbox app I've been using to troubleshoot if you want me to.

**Comment by mikehardy** [comment] 2022-11-06 16:03
If it is as easy to reproduce as you say (and I have no reason to doubt that...) then it should be pretty easy to trigger in our e2e test. I've touched almost all parts of the storage code at this point (not something I can say about all the modules) so I have pretty high confidence I can bend e2e to expose it and then drive this to a root cause

**Comment by mikehardy** [comment] 2022-11-06 18:54
I believe I have this reproduced and I *think* (uncomfirmed) it is an upstream issue, I am going to collaborate with firebase-ios-sdk to see what turns up

**Comment by brianGammon** [comment] 2022-11-06 22:26
So glad you were able to reproduce it. Once this is fixed all my tests will pass and I'll move forward to 16, for now I'll stay put on 14.12.0. Thanks for your efforts!

**Comment by mikehardy** [comment] 2022-11-09 15:34
Fixed upstream, fix will release with firebase-ios-sdk 10.2.0 until then I'll leave this open, however there will be no more activity here other than a close when the new upstream SDK releases and I release the version here (along with the new e2e test that probes this case...)

**Comment by alexanderwassbjer** [comment] 2022-11-16 08:43
firebase-ios-sdk 10.2.0 is now released. When will this repo be updated with the newest release of firebase sdk?

**Comment by mikehardy** [comment] 2022-11-16 14:12
@alexanderwassbjer shortly, but why wait? Get it now: https://rnfirebase.io/#ios

**Closed** 2022-11-16 21:07 UTC
Labels: Impact: Bug, Platform: iOS, Type: Firebase, Service: Storage, Blocked: Firebase SDK, Type: In Progress
