### ISSUE TITLE
[🐛] How to remove Personalized Ad Consent SDK in react-native-firebase/Admod

### ISSUE THREAD

**Issue by nguyenthixanh18011988** [invertase/react-native-firebase#5395] opened 2021-06-07 04:25 UTC
I get message from google: 

About the Families policy We have detected that your app includes the deprecated Personalized Ad Consent SDK, which is not approved for use in child-directed services. The SDK has been deprecated in favor of the User Messaging Platform SDK and must be updated. Apps in the Designed for Families program must only use ad SDKs that have certified their compliance with the Families Ads Program.

so How to remove Personalized Ad Consent SDK in react-native-firebase/Admod?

**Comment by mikehardy** [comment] 2021-06-08 04:12
Duplicate of this discussion here I think: https://github.com/invertase/react-native-firebase/discussions/5384 - plus you provided none of the information we request in the issue template which means we have nothing to base any reasoning on. We close issues like that immediately, sorry

**Closed by mikehardy** 2021-06-08 04:12 UTC
Labels: Help: Needs Triage, Impact: Bug
