### ISSUE TITLE
Unable to Receive Silent Push Notifications on iOS

### ISSUE THREAD

**Issue by Anum-Amin** [invertase/react-native-firebase#1278] opened 2018-07-05 13:23 UTC
I am unable to receive Silent Push Notification on iOS though I have followed all the steps provided in documentation from [messaging](https://github.com/invertase/react-native-firebase-docs/blob/master/docs/messaging/receiving-messages.md) and [notifications](https://github.com/invertase/react-native-firebase-docs/blob/master/docs/notifications/receiving-notifications.md). Same code is working fine on Android. By silent push notifications, I mean notifications with data payload only so that it can be solely handled by app.

Payload used:

```
{
	"content_available": true,
	"priority":"high",
	"to" : "<FCM Token>",
	"collapse_key" : "type_a",
	"data" : {
         // ...... my data
	}
}
```

### AppDelegate.m

```
#import <Firebase.h>
#import "RNFirebaseNotifications.h"
#import "RNFirebaseMessaging.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  [RNFirebaseNotifications configure];

 // .... template initialization code
  return YES;
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo
fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler{
  [[RNFirebaseNotifications instance] didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [[RNFirebaseMessaging instance] didRegisterUserNotificationSettings:notificationSettings];
}

-(void) userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {
 
  [[RNFirebaseMessaging instance] didReceiveRemoteNotification:response.notification.request.content.userInfo];
  completionHandler();
}

@end
```

### BackgroundMessage.js

```
import firebase from 'react-native-firebase';

export default async (message) => {
    if (message) {
        const {
            topic, title, body
        } = message.data;
        const notification = new firebase.notifications.Notification()
            .setNotificationId(getRandomNotificationId())
            .setTitle(title)
            .setBody(body)
            .setData(message.data);
        notification
            .android.setChannelId('my.channel')
            .android.setSmallIcon('ic_stat_ic_notification');
        firebase.notifications().displayNotification(notification);
    }
    Promise.resolve();
};
```
### index.js

```
AppRegistry.registerComponent('myApp', () => App);
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => BackgroundMessage);
```

### App.js (Main Component)

```
class App extends Component {
    async componentDidMount() {
        notificationService.checkPermission();
        this.attachNotificationListeners();
    }

    componentWillUnmount() {
        this.messageListener();
        this.notificationListener();
        this.notificationOpenedListener();
    }

    async attachNotificationListeners() {
        this.messageListener = firebase.messaging().onMessage((message) => {
            // perform action
            }
        });

        this.notificationListener = firebase.notifications().onNotification((notification) => {
             // perform action
        });

        this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
           // perform action
        });

        const notificationOpen = await firebase.notifications().getInitialNotification();
       // perform action
    }

    render() {
        return (
            <Provider store={store}>
                <MainStackRoute />
            </Provider>
        );
    }
```  

### Environment

1. Application Target Platform:  `iOS and Android both`

2. Development Operating System: `Mac OSX Sierra (10.12.6 )`

3. Build Tools: `Xcode, Android Studio, Web Storm`

4. `React Native` version: `0.55.4`

5. `React Native Firebase` Version: `4.2.0`

6. `Firebase` Module: `notifications, messaging`

7. Are you using `typescript`? `No`

**Comment by tsaicharit** [comment] 2018-09-06 08:36
i was seeing this issue in both android and iOS, any solution for this?

**Comment by shrivastavaanurag** [comment] 2018-09-20 10:14
any solutions?? i am not getting the notifications when app is closed, but it works in samsung device.

**Comment by Kerrick** [comment] 2018-09-28 19:09
I ran into this issue too; is there a known work-around?

**Comment by addmaths07** [comment] 2018-10-02 06:54
we faced exact same issue aswell when we tried to upgrade to 4.x. Had to revert back to 3.x to make it work.

**Comment by Samykills** [comment] 2018-10-04 15:01
the OnMessage func receives the notification on Android, but on IOS it doesnt work...has any one found a workaround for the IOS ???
I want the App to run a func when it receives a data-message as notification, but cant do as it does not work when the app is in background :(

**Comment by Kerrick** [comment] 2018-11-04 07:30
This issue still requires attention. @stale[bot]

**Comment by Samykills** [comment] 2018-11-04 15:07
Found a workaround for this problem...now using VOIP for silent notifications and using react-native-voip-notifications plugin to read the same, this adds a listener to the notification event emitted by the native code, which even works on the background.

**Comment by Gys** [comment] 2018-11-18 15:07
In my experience iOS does not always process silent notifications immediately. Apple probably does not want apps in the background (or foreground but with screen off) to draw much power. Because in theory its possible to keep an app running by sending it a silent notification every 30 seconds. 

So I wonder: did anyone every see if the silent notification is processed at the moment the app became active again ? Because that is what I see happen in my case.

I currently use OneSignal for sending notifications, but that does not work well. Notifications (silent or normal) often arrive late or not at all. So I am looking into an alternative, like Firebase.

**Comment by crushy26** [comment] 2018-11-20 07:01
Hi, I am able to receive a notification message sent from firebase console that means the library is integrated properly.

The issue is same as described above by author, I am unable to receive data-only messages sent from my node server.

**Comment by zaharidichev** [comment] 2019-01-21 15:13
Will there be any progress on that or its deep in the backlog now? I mean supporting silent notifications on Ios seems like something that can be useful in quite a few scenarios...

**Comment by danmdinu** [comment] 2019-03-07 22:34
Hi, any progress with this? thanks

**Comment by jayzyaj** [comment] 2019-04-05 03:37
Hi there, any updates on this issue? Thanks

**Comment by ManigandanRaamanathan** [comment] 2019-04-14 12:33
@Anum-Amin any update on this issue?

**Comment by Anum-Amin** [comment] 2019-04-15 05:01
@ManigandanRaamanathan Sorry didn't get a chance to look into it

**Comment by Anum-Amin** [comment] 2019-05-13 10:10
Hey @chrisbianca / @Salakar any chance this issue will be looked into?

**Comment by ThomasLarge** [comment] 2019-05-30 11:10
@Salakar @invertase any update on this?

**Comment by mikehardy** [comment] 2019-05-30 12:08
I receive silent push notifications on ios 9 through 12 following the instructions, but it's incredibly intermittent. Which is basically what Apple says it will be in their APIs, nothing is guaranteed, seemingly. If you're on a real device, you're using 'content_available' (not underscore) and you've definitely requested permission in the code, you're probably just at the mercy of APNs delivering or not, and/or the phone letting your code run or not. My most successful test was on a device where I had interacted with the app a lot, "educating" the power miser algorithms that I cared and wanted the app to run.

**Comment by nes123** [comment] 2019-10-09 17:40
Is there alternative to implementing notification tray inside the app without using silent push notifications? many of the notifications are being sent to users that are listening on topics so registering every notification in the database is not an option.

**Comment by NicholasIoanJones** [comment] 2019-11-04 18:37
Just to keep the @Stale bot at bay - This would be really useful and it's pretty surprising that it is not already there. I need to send time sensitive alerts and I need them to be heard even in silent mode. Kind of like setting off a persistent annoying alarm clock, but event driven not pre-determined.

**Comment by mikehardy** [comment] 2019-11-04 19:23
I'm honestly not sure there is a lot to be done. You can examine this PR - targeted at handling actions in the background - as an example of how to get your hooks in to the response handlers at the native level. If you were to apply something similar but just logging that a message was received (so you could see it on xcode or something) my hypothesis is that you just wouldn't receive anything. At the native level. How can react-native-firebase help that? My best guess is that if the battery is at 100% and it's plugged in, and the screen is on and you just installed the app then exercised it a bit (read as: plenty of power, expressed interest in the app) you'll get the pushes. If you don't do that, you may not. That's Apple.

**Comment by nes123** [comment] 2019-11-04 19:29
Why the notifications cannot be catched when the app is coming back to life, according to the docs this is what should happen but notifications are just getting lost - they dont wake up the app and they are not being catched at opening

**Comment by NicholasIoanJones** [comment] 2019-11-04 19:37
@mikehardy I understand Apple are ... well Apple. But just for clarity, are you saying that the behavior seen is best summarized by "but the system doesn’t guarantee their delivery" phrase in the link below? https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app 
Most importantly: is delivery less guaranteed (if that makes sense) than a normal push-notification to the notification center

**Comment by mikehardy** [comment] 2019-11-04 20:38
@NicholasIoanJones In my experience yes, "the system doesn't guarantee their delivery" is how things have gone for me so far. I receive messages sometimes under some conditions (listed above if you want to try them). I have a hunch a non-silent notification is delivered at a higher rate, but the results for me are vague enough I couldn't say for sure

**Comment by elyalvarado** [comment] 2019-11-04 20:49
@mikehardy 

>  I have a hunch a non-silent notification is delivered at a higher rate, but the results for me are vague enough I couldn't say for sure

This is indeed so. [According to apple](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns) silent notifications have a priority of 5 by default, which means:

> Notifications with this priority might be grouped and delivered in bursts to the user’s device. They may also be throttled, and in some cases not delivered.

Also:

>  A value of 10 is appropriate for notifications that trigger an alert, play a sound, or badge the app’s icon. Specifying this priority for a notification that has a payload containing the content-available key causes an error.

Apple has also been getting more strict with remote notifications lately, and supposedly in iOS 13 at some point they required the `apns-push-type` header field otherwise they'll drop the notification, at some point this was in the docs, but they removed that and now only mention that is required for watchOS 6 and later.

**Comment by mthuong** [comment] 2019-11-22 06:49
The library worked perfectly on background + foreground with silent push.
You can receive silent push notifications on iOS by subscribe `firebase.messaging().onMessage` 

FYI
You can checkout RNFirebaseNotifications.m 
`- (void)didReceiveRemoteNotification:(NSDictionary *)userInfo
              fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler`

This will call `[[RNFirebaseMessaging instance] didReceiveRemoteNotification:userInfo];`

**Comment by nes123** [comment] 2019-11-22 07:45
@mthuong it works well when the app is in foreground + background but it does not work when the app is closed.

**Comment by kirushi** [comment] 2019-12-10 00:34
> The library worked perfectly on background + foreground with silent push.
> You can receive silent push notifications on iOS by subscribe `firebase.messaging().onMessage`
> 
> FYI
> You can checkout RNFirebaseNotifications.m
> `- (void)didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler`
> 
> This will call `[[RNFirebaseMessaging instance] didReceiveRemoteNotification:userInfo];`

This helped me a tonne, I found that there is a condition in didReceiveRemoteNotification under RNFirebaseNotifications.m that will only pass the message through to the RNFirebaseMessaging if there is only and exactly one field in the aps object i.e. content-available. After I removed my topic messages started coming through :)

e.g. condition seen below:
`if (userInfo[@"aps"] && ((NSDictionary*)userInfo[@"aps"]).count == 1 && userInfo[@"aps"][@"content-available"])`

react-native-firebase: 5.5.6
react-native: 0.59.3

**Comment by gersonmontenegro** [comment] 2020-03-23 16:24
I could solve this issue implementing onMessage to get data notifications on JS
```
    firebase.messaging().onMessage(message => {
      console.log(message);
    });

```
In postman, I made this body:
```
{
    "to": "__FirebaseToken",
     "data": {
     	"code": 99,
     	"title": "New item"
     },
     "priority": "high",
     "content_available": true
}
```
The key part for me was **"content_available": true**, and it surprised me that priority didn't matter.

**Comment by Ehesp** [comment] 2020-03-23 16:55
Hey all 👋 There's a draft PR available which fixes this issue and others, please check it out: https://github.com/invertase/react-native-firebase/pull/3339

We'll be doing a RC release once a few more things are implemented.

**Closed** 2020-03-27 00:06 UTC
Labels: API: Notifications, Blocked: Needs Review, Help: General, Help: Needs Triage, Help: iOS, Platform: iOS, 📌 pin
