### ISSUE TITLE
ECOMMERCE_PURCHASE event is deprecated in favor of PURCHASE event

### ISSUE THREAD

**Issue by bmamone** [invertase/react-native-firebase#3682] opened 2020-05-23 19:28 UTC
## Issue

According to [Firebase docs](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event#ECOMMERCE_PURCHASE), `ECOMMERCE_PURCHASE` event is deprecated and `PURCHASE` should be used instead, but it's not implemented in the analytics library.

This enables the user to log relevant parameters like `items` and should be updated before deprecation.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 7.0.1
- **`Firebase` module(s) you're using that has the issue:**
  - Analytics
- **Are you using `TypeScript`?**
  - No

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by Salakar** [comment] 2020-05-24 13:10
PR is in progress: https://github.com/invertase/react-native-firebase/pull/3385

This is also a duplicate of #3512 - closing as we're  tracking there, thanks.

**Closed by Salakar** 2020-05-24 13:10 UTC
