### ISSUE TITLE
Unable to manually initialize Crashlytics

### ISSUE THREAD

**Issue by vivek-gunasekaran** [invertase/react-native-firebase#2191] opened 2019-06-03 05:57 UTC
I'm trying to do a manual initialization of Crashlytics using the JS API firebase.crashlytics().enableCrashlyticsCollection() but, it doesn't initialize Crashlytics.

Upon inspecting the RNFirebaseCrashlytics.m, I see that Fabric.h is not recognized by the project. I have used cocoapods for Crashlytics and Fabric installation,
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'
and react-native link react-native-firebase for linking RNFirebase.

## Environment
Cocoapods: 1.6.1
RNFirebase: 5.3.1

If I tweak the framework and header search path of RNFirebase to pick up the correct path of Fabric and crashlytics, I'm able to successfully initialize Crashlytics from the JS API but, that is not the desired fix.
Is this because of the pod structure or anything incorrect on my side? Any idea of how to fix this in the environment?

**Comment by mikehardy** [comment] 2019-06-03 14:34
This may be related to #2163 - I can reproducibly demonstrate that the header search paths are incorrect following existing v5 install docs and there is an issue and demo for it. There's also a partial solution on there you can try applying in your Podfile. As a solution it isn't great but I lean towards Podfile / gradle / patch-package solutions at least since they reapply across project teams and still allow you to track upstream versions

**Comment by vivek-gunasekaran** [comment] 2019-06-03 22:39
@mikehardy thanks for the pointing towards the other issue. Your suggested solution to Podfile works for me.

post_install do |installer|
  system("mkdir -p Pods/Headers/Public/Fabric && cp Pods/Fabric/iOS/Fabric.framework/Headers/* Pods/Headers/Public/Fabric/")
end

**Comment by mikehardy** [comment] 2019-06-03 23:02
Okay - very happy to hear that works for you. Obviously there is something to fix, but a Podfile workaround is pretty low-impact. I'm going to close this then as #2163 exists, do follow that one and you'll see when there is a real fix. Cheers

**Closed by mikehardy** 2019-06-03 23:02 UTC
