### ISSUE TITLE
fetchAssetsWithALAssetURLs:options: deprecation warning

### ISSUE THREAD

**Issue by codecog** [invertase/react-native-firebase#3109] opened 2020-01-17 19:30 UTC
## Issue
Forcing pods to use iOS 11 as the deployment target brings out a deprecation warning in RNFBUtilsModule.m

`'fetchAssetsWithALAssetURLs:options:' is deprecated: first deprecated in iOS 11 - Will be removed in a future release [-Wdeprecated-declarations]`

---

## Project Files
- iOS @react-native-firebase/app/ios/RNFBApp/RNFBUtilsModule.m:60:25:

### Javascript
N/A

#### `package.json`:
N/A

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:
- [x] I'm using Pods and my Podfile looks like:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2020-01-17 20:09
not a bug I don't think - it's possible there are assets stored that way and per the docs this is how you fetch them, the module appears to do the correct lookup to see which API to use, and the non-deprecated API is in use when needed, by my read:

https://github.com/invertase/react-native-firebase/blob/760b8f25a22ea13149edc37fd908dd81f0c5688f/packages/app/ios/RNFBApp/RNFBUtilsModule.m#L57-L64

**Comment by codecog** [comment] 2020-01-17 20:14
I don't think it's a bug either, just noticed this in the console when building a fresh application.

**Comment by mikehardy** [comment] 2020-01-17 21:05
okay - closing for now

**Closed by mikehardy** 2020-01-17 21:05 UTC

**Comment by pie6k** [comment] 2020-03-31 17:02
It's became issue again as it's not possible to build on Mac because of that: 

```
'fetchAssetsWithALAssetURLs:options:' is unavailable: not available on macCatalyst
```
