### ISSUE TITLE
[🐛] No crash logs appearing in Crashlytics dashboard of the Firebase 

### ISSUE THREAD

**Issue by hariom20p95** [invertase/react-native-firebase#7431] opened 2023-11-02 07:11 UTC
## Issue

No crash logs appear in the Crashlytics dashboard of the Firebase but getting mail for crashes. (Have attached images for reference). 
<img src="https://github.com/invertase/react-native-firebase/assets/132051307/5d49b129-febb-4d1a-82b6-2e27cb62f2e8" width="600" height="500">

<img height="600" width="1637" alt="firebase_Dashboard" src="https://github.com/invertase/react-native-firebase/assets/132051307/b42e45e4-49ec-421c-a9cc-176f19c88602">

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "humbee",
  "version": "30.3.9",
  "private": true,
  "scripts": {
    "android": "react-native run-android ",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "setup-ios-permissions": "npx react-native setup-ios-permissions"
  },
  "dependencies": {
    "@ant-design/icons-react-native": "^2.3.2",
    "@babel/plugin-proposal-numeric-separator": "^7.16.7",
    "@react-native-async-storage/async-storage": "^1.17.5",
    "@react-native-clipboard/clipboard": "^1.10.0",
    "@react-native-community/datetimepicker": "^6.7.5",
    "@react-native-community/push-notification-ios": "^1.11.0",
    "@react-native-firebase/analytics": "^15.7.0",
    "@react-native-firebase/app": "^15.7.0",
    "@react-native-firebase/crashlytics": "^15.7.0",
    "@react-native-firebase/messaging": "^15.3.0",
    "@react-native-picker/picker": "^2.4.8",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "accordion-collapse-react-native": "^1.1.0",
    "axios": "^0.27.2",
    "i18n-js": "^3.9.2",
    "i18next": "^21.8.3",
    "lodash": "^4.17.21",
    "lottie-ios": "^3.4.0",
    "lottie-react-native": "^5.1.4",
    "moment": "^2.29.3",
    "papaparse": "^5.3.2",
    "react": "17.0.2",
    "react-i18next": "^11.16.9",
    "react-native": "0.68.2",
    "react-native-autocomplete-dropdown": "^2.1.1",
    "react-native-autocomplete-input": "^5.1.0",
    "react-native-calendars": "^1.1295.0",
    "react-native-collapsible": "^1.6.1",
    "react-native-countdown-component": "^2.7.1",
    "react-native-csv": "^0.2.0",
    "react-native-date-picker": "4.2.2",
    "react-native-easebuzz-kit": "file:react-native-easebuzz-kit-1.0.0.tgz",
    "react-native-element-dropdown": "^2.0.0",
    "react-native-flash-message": "^0.2.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "2.6.0",
    "react-native-image-picker": "^4.8.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-otp-inputs": "^7.1.1",
    "react-native-progress-circle": "^2.1.0",
    "react-native-push-notification": "^8.1.1",
    "react-native-reanimated": "^2.9.0",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-style-tachyons": "^4.2.2",
    "react-native-svg": "^12.3.0",
    "react-native-tip": "^0.0.18",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-vector-icons": "9.1.0",
    "react-native-webview": "^13.6.0",
    "react-native-wheel-pick": "1.2.0",
    "react-redux": "^8.0.1",
    "redux": "^4.2.0",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1",
    "rn-fetch-blob": "^0.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-native-version": "^4.0.0",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "crashlytics_debug_enabled": true,
    "crashlytics_disable_auto_disabler": true,
    "crashlytics_auto_collection_enabled": true,
    "crashlytics_is_error_generation_on_js_crash_enabled": true,
    "crashlytics_javascript_exception_handler_chaining_enabled": true,
    "analytics_auto_collection_enabled": true
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
buildscript {
  repositories {
        google()
        mavenCentral()
    }
dependencies {
        classpath("com.android.tools.build:gradle:7.1.3")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:4.1.2")
        classpath 'com.google.gms:google-services:4.3.13'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

dependencies {

    // Firebase
    implementation platform('com.google.firebase:firebase-bom:32.5.0')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'

    }

//With other configuration lines.

    
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 System:
    OS: macOS 14.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 47.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /usr/local/opt/node@18/bin/node
    Yarn: Not Found
    npm: 9.8.1 - /usr/local/opt/node@18/bin/npm
    Watchman: 2023.10.23.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10811636
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.21 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `15.7.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Crashlytics`
- **Are you using `TypeScript`?**
  - `NO`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2023-11-02 11:36
Hi there!
These are very old versions - we are on 18.6.1 now - and they are mismatched versions of react-native-firebase components which is unsupported --> https://invertase.io/blog/react-native-firebase-versioning

Those are both items you should change and re-test, however I believe what is happening is that you probably have a filter of some sort (either the wrong app selected, not selecting "non-fatal crashes" to show, or the issue is closed and you are set to only show open - this is the most common thing.

If you are getting the emails it sounds like the SDK is doing it's job and this is a reporting issue that we won't be able to have any effect on, but which you may ask on stackoverflow

If you want to see how to test the integration more thoroughly you may like this post: https://invertase.io/blog/react-native-firebase-crashlytics-configuration#android-installation-verification

It shows you how to verify *on device* that crashlytics is working. Everything past that point is up in the cloud and if there are issues I believe the support channel is stackoverflow with appropriate firebase tags, but the SDK will be proven to work correctly.

I'm going to close this since I think the code here is working based on evidence presented

**Closed by mikehardy** 2023-11-02 11:36 UTC
Labels: Impact: Bug, Help: Needs Triage
